#!/bin/bash
# Write a meson cross file for $PORT_TRIPLE from the toolchain env.sh exports;
# build-atlas.sh generates one under $PORT_OUT for a cross build. Rewritten on
# every run, so a toolchain change can never leave a stale file behind.
#
# Usage: linux-port/native/write-meson-cross.sh PATH
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/env.sh"

out="${1:?usage: write-meson-cross.sh PATH}"
[ "$PORT_CROSS" = 1 ] ||
	{ echo "PORT_ARCH=$PORT_ARCH is native here; no cross file needed" >&2; exit 1; }

case "$PORT_ARCH" in
arm64) cpu_family=aarch64; cpu=aarch64 ;;
*) echo "no meson cpu_family mapping for PORT_ARCH=$PORT_ARCH" >&2; exit 1 ;;
esac

# In a cross build meson ignores CFLAGS/LDFLAGS and LIBRARY_PATH for the host
# machine — the cross file is the only way in. $PORT_CROSS_LIB_DIRS and
# $PORT_CROSS_INCLUDE_DIRS (space-separated) are how a caller adds its own
# staged prefix, which cc.find_library() then finds too.
lib_args=""
for d in ${PORT_CROSS_LIB_DIRS:-}; do lib_args="$lib_args'-L$d', "; done
inc_args=""
for d in ${PORT_CROSS_INCLUDE_DIRS:-}; do inc_args="$inc_args'-I$d', "; done

mkdir -p "$(dirname "$out")"
cat >"$out" <<EOF
# Generated by linux-port/native/write-meson-cross.sh — do not edit.

[binaries]
c = '$PORT_CC'
cpp = '$PORT_CXX'
ar = '$PORT_AR'
strip = '$PORT_STRIP'
pkg-config = '$PORT_PKG_CONFIG'
# The Java compiler stays a host tool whatever the target is: bytecode is
# bytecode. meson's binary key for it is 'java', and it wants javac, not java —
# a 'javac' key is silently ignored and the build then fails with
# "Unknown compiler: .../bin/java".
java = '$JAVA_HOME/bin/javac'

[properties]
# What meson's 'jni' dependency resolves jni.h and libjvm.so from. It must be
# the *target* JDK, or the launcher would link against the host's libjvm.
java_home = '$PORT_TARGET_JAVA_HOME'

[built-in options]
c_args = [$inc_args]
cpp_args = [$inc_args]
c_link_args = [$lib_args]
cpp_link_args = [$lib_args]

[host_machine]
system = 'linux'
cpu_family = '$cpu_family'
cpu = '$cpu'
endian = 'little'
EOF

echo "wrote $out ($PORT_TRIPLE)"
