#!/usr/bin/env python3
"""Generate com.particlesdevs.photoncamera.R from app/src/main/res.

Android's aapt2 assigns each resource an int id; nothing here depends on the
real values, only on ids being distinct and stable across runs, so they are
allocated in sorted order per type, 0x7f<type><index>.  Strings, bools, integers
and arrays also get a value table so Resources can answer without parsing XML.

  kn/gen-r.py   ->  kn/src/commonMain/kotlin/com/particlesdevs/photoncamera/R.kt
"""
import os, re, sys, xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "app", "src", "main", "res")
OUT = os.path.join(HERE, "src", "commonMain", "kotlin", "com", "particlesdevs",
                   "photoncamera", "R.kt")

# <type> -> {name: value or None}.  Values are only kept where Resources needs them.
VALUE_TAGS = {"string": "string", "bool": "bool", "integer": "integer",
              "color": "color", "dimen": "dimen", "string-array": "array",
              "integer-array": "array", "array": "array", "style": "style",
              "item": None, "attr": "attr", "declare-styleable": None}

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("$", "\\$")

def main():
    types = {}          # type -> {name: value}
    def add(t, name, value=None):
        types.setdefault(t, {})
        if name not in types[t] or types[t][name] is None:
            types[t][name] = value

    # Directory-backed types: drawable, raw, layout, anim, font, xml, mipmap, navigation.
    for d in sorted(os.listdir(RES)):
        base = d.split("-")[0]
        full = os.path.join(RES, d)
        if not os.path.isdir(full) or base == "values":
            continue
        for f in sorted(os.listdir(full)):
            add(base, os.path.splitext(f)[0])

    # values*/: every <string>, <bool>, <integer>, <color>, <dimen>, <*-array>, <style>.
    for d in sorted(os.listdir(RES)):
        if not d.startswith("values"):
            continue
        default = (d == "values")
        for f in sorted(os.listdir(os.path.join(RES, d))):
            if not f.endswith(".xml"):
                continue
            try:
                root = ET.parse(os.path.join(RES, d, f)).getroot()
            except ET.ParseError as e:
                print("skip %s/%s: %s" % (d, f, e), file=sys.stderr)
                continue
            for el in root:
                name = el.get("name")
                if not name:
                    continue
                tag = el.tag
                if tag == "item":
                    tag = el.get("type") or "id"
                t = VALUE_TAGS.get(tag, tag)
                if t is None:
                    continue
                if tag in ("string-array", "integer-array", "array"):
                    t = "array"
                    val = [ (i.text or "") for i in el.findall("item") ] if default else None
                elif tag in ("string", "bool", "integer", "color", "dimen"):
                    val = ("".join(el.itertext()) or "") if default else None
                else:
                    val = None
                add(t, name.replace(".", "_"), val)

    order = sorted(types)
    lines = ["// GENERATED by kn/gen-r.py from app/src/main/res -- do not edit by hand.",
             "// Ids are allocated here, not by aapt2: nothing in this binary reads a",
             "// resource id off a packaged APK, only compares and looks up.",
             "@file:Suppress(\"unused\", \"ObjectPropertyName\")", "",
             "package com.particlesdevs.photoncamera", ""]
    lines.append("object R {")
    for ti, t in enumerate(order):
        names = sorted(types[t])
        lines.append("    object %s {" % (t if t.isidentifier() else t.replace("-", "_")))
        for i, n in enumerate(names):
            ident = n if n.isidentifier() else "`%s`" % n
            lines.append("        const val %s: Int = 0x7f%02x%04x" % (ident, ti + 1, i))
        lines.append("    }")
    lines.append("}")
    lines.append("")

    # The value tables Resources reads.
    def table(kind, conv):
        rows = []
        for n, v in sorted(types.get(kind, {}).items()):
            if v is None:
                continue
            rows.append("    R.%s.%s to %s," % (kind, n if n.isidentifier() else "`%s`" % n, conv(v)))
        return rows

    APP = "{http://schemas.android.com/apk/res-auto}"
    strings = types.get("string", {})
    bools = types.get("bool", {})
    integers = types.get("integer", {})
    arrays = types.get("array", {})

    def resolve(raw):
        if raw is None:
            return None
        raw = raw.strip()
        m = re.fullmatch(r"@(string|bool|integer)/(\w+)", raw)
        if not m:
            return raw
        kind, name = m.group(1), m.group(2)
        v = {"string": strings, "bool": bools, "integer": integers}[kind].get(name)
        return None if v is None else v.strip()

    def resolve_array(raw):
        if raw is None:
            return None
        m = re.fullmatch(r"@array/(\w+)", raw.strip())
        if not m:
            return None
        items = arrays.get(m.group(1))
        return None if items is None else [resolve(i) or "" for i in items]

    lines.append("/** id -> value, for android.content.res.Resources. */")
    lines.append("internal val R_STRINGS: Map<Int, String> = mapOf(")
    lines += table("string", lambda v: '"%s"' % esc(v))
    lines.append(")")
    lines.append("")
    lines.append("internal val R_BOOLS: Map<Int, Boolean> = mapOf(")
    lines += table("bool", lambda v: "true" if v.strip() == "true" else "false")
    lines.append(")")
    lines.append("")
    lines.append("internal val R_INTEGERS: Map<Int, Int> = mapOf(")
    lines += table("integer", lambda v: v.strip() if re.fullmatch(r"-?\d+", v.strip()) else "0")
    lines.append(")")
    lines.append("")
    lines.append("internal val R_ARRAYS: Map<Int, Array<String>> = mapOf(")
    lines += table("array",
                   lambda v: "arrayOf(%s)" % ", ".join('"%s"' % esc(resolve(x) or "") for x in v))
    lines.append(")")
    lines.append("")
    # THE PREFERENCE SCREENS' OWN DEFAULTS.  On Android
    # PreferenceManager.setDefaultValues(context, R.xml.preferences, ...) walks
    # this tree and every `android:defaultValue` becomes the key's default; the
    # preference fragments are in drop.txt here, so nothing would register them
    # and every such setting would read back 0 -- CONTROL_AF_MODE among them,
    # which is a viewfinder that never focuses.  The references are resolved
    # against the value tables above, and a boolean is written the way
    # SettingsManager stores one ("1"/"0").
    A = "{http://schemas.android.com/apk/res/android}"
    prefs = {}
    choices = {}
    xmldir = os.path.join(RES, "xml")
    if os.path.isdir(xmldir):
        for f in sorted(os.listdir(xmldir)):
            if not f.endswith(".xml"):
                continue
            try:
                root = ET.parse(os.path.join(xmldir, f)).getroot()
            except ET.ParseError:
                continue
            for el in root.iter():
                key = resolve(el.get(A + "key"))
                default = resolve(el.get(A + "defaultValue"))
                if key is None or default is None:
                    continue
                if default in ("true", "false"):
                    default = "1" if default == "true" else "0"
                prefs.setdefault(key, default)
                values = resolve_array(el.get(A + "entryValues"))
                if values:
                    choices.setdefault(key, values)

    lines.append("/**")
    lines.append(" * The preference screens' `android:defaultValue`s, key -> default, with the")
    lines.append(" * `@string/`/`@bool/` references already resolved and booleans written the")
    lines.append(" * way SettingsManager stores them.  This is what")
    lines.append(" * PreferenceManager.setDefaultValues reads off res/xml on Android.")
    lines.append(" */")
    lines.append("val R_PREFERENCE_DEFAULTS: Map<String, String> = mapOf(")
    for k in sorted(prefs):
        lines.append('    "%s" to "%s",' % (esc(k), esc(prefs[k])))
    lines.append(")")
    lines.append("")
    lines.append("/** The same screens' `android:entryValues`, for the keys that list them. */")
    lines.append("val R_PREFERENCE_VALUES: Map<String, Array<String>> = mapOf(")
    for k in sorted(choices):
        lines.append('    "%s" to arrayOf(%s),'
                     % (esc(k), ", ".join('"%s"' % esc(v) for v in choices[k])))
    lines.append(")")
    lines.append("")

    # THE SAME SCREEN, TYPED AND IN ORDER.  The defaults above are what the app
    # READS; this is what a settings screen has to DRAW, and there is no
    # androidx.preference here to walk.  Element name -> row type, the titles and
    # summaries resolved, the ListPreference entries beside their values, and the
    # seek bars' own app: attributes, nested exactly as the file nests them.
    def node_type(tag):
        t = tag.split(".")[-1]
        if t == "PreferenceCategory":
            return "category"
        if t == "PreferenceScreen":
            return "screen"
        if t.endswith("ListPreference"):
            return "list"
        if t.endswith("SeekBarPreference"):
            return "seek"
        if "Switch" in t or "CheckBox" in t:
            return "switch"
        return "action"

    def attr(el, name):
        # app: and android: both appear in these files, for the same attribute.
        return el.get(APP + name, el.get(A + name))

    def node(el, indent):
        kind = node_type(el.tag)
        args = ['"%s"' % kind, '"%s"' % esc(resolve(attr(el, "key")) or "")]
        title = resolve(attr(el, "title"))
        summary = resolve(attr(el, "summary"))
        if title:
            args.append('title = "%s"' % esc(title))
        if summary:
            args.append('summary = "%s"' % esc(summary))
        default = resolve(el.get(A + "defaultValue"))
        if default is not None:
            if default in ("true", "false"):
                default = "1" if default == "true" else "0"
            args.append('default = "%s"' % esc(default))
        entries = resolve_array(attr(el, "entries"))
        values = resolve_array(attr(el, "entryValues"))
        if entries:
            args.append("entries = arrayOf(%s)" % ", ".join('"%s"' % esc(e) for e in entries))
        if values:
            args.append("values = arrayOf(%s)" % ", ".join('"%s"' % esc(v) for v in values))
        for name, fmt in (("minValue", "min = %sf"), ("maxValue", "max = %sf"),
                          ("stepPerUnit", "step = %sf")):
            raw = attr(el, name)
            if raw is not None:
                args.append(fmt % raw.strip())
        if (attr(el, "isFloat") or "").strip() == "true":
            args.append("isFloat = true")
        if (el.get(A + "enabled") or "").strip() == "false":
            args.append("enabled = false")
        kids = [node(c, indent + 1) for c in el]
        pad = "    " * indent
        if kids:
            args.append("children = arrayOf(\n%s,\n%s)" % (",\n".join(kids), pad + "    "))
        return "%s    RPreferenceNode(%s)" % (pad, ", ".join(args))

    lines.append("/** One row of res/xml/preferences.xml, as the file types and orders it. */")
    lines.append("class RPreferenceNode(")
    lines.append("    /** category | screen | list | seek | switch | action. */")
    lines.append("    val type: String,")
    lines.append("    val key: String,")
    lines.append("    val title: String = \"\",")
    lines.append("    val summary: String = \"\",")
    lines.append("    val default: String? = null,")
    lines.append("    val entries: Array<String> = emptyArray(),")
    lines.append("    val values: Array<String> = emptyArray(),")
    lines.append("    // UniversalSeekBarPreference's own TypedArray defaults.")
    lines.append("    val min: Float = 0f,")
    lines.append("    val max: Float = 100f,")
    lines.append("    val step: Float = 1f,")
    lines.append("    val isFloat: Boolean = false,")
    lines.append("    val enabled: Boolean = true,")
    lines.append("    val children: Array<RPreferenceNode> = emptyArray(),")
    lines.append(")")
    lines.append("")
    lines.append("/** res/xml/preferences.xml, which is the settings screen. */")
    lines.append("val R_PREFERENCE_TREE: Array<RPreferenceNode> = arrayOf(")
    prefs_xml = os.path.join(xmldir, "preferences.xml")
    if os.path.isfile(prefs_xml):
        root = ET.parse(prefs_xml).getroot()
        lines += [node(el, 0) + "," for el in root]
    lines.append(")")
    lines.append("")

    lines.append("/** id -> resource name, for AssetManager/Resources file lookups. */")
    lines.append("internal val R_NAMES: Map<Int, String> = mapOf(")
    for t in order:
        for n in sorted(types[t]):
            ident = n if n.isidentifier() else "`%s`" % n
            lines.append('    R.%s.%s to "%s",' % (t if t.isidentifier() else t.replace("-", "_"), ident, n))
    lines.append(")")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(lines))
    print("R.kt: %d types, %d ids" % (len(order), sum(len(v) for v in types.values())))

main()
