#!/usr/bin/env python3
"""Generate Kotlin/Native stubs for the android.* "content" slice.

Slice: android.content, android.content.res, android.content.pm,
       android.database, android.provider

Signatures below were derived from the GeckoView call sites (every method
called, field read, type extended, constructor invoked, constant compared)
and, where a call site was ambiguous, from ATL's real Java reimplementation
of android.* at $ATL/src/api-impl/android/.

Run:  python3 stubgen/content.py            # emit + report
      python3 stubgen/content.py --check    # report only, no writes
      python3 stubgen/content.py --shims    # also emit /tmp/kn-content-shims.kt
                                            # (cross-slice placeholders, for the
                                            #  standalone syntax check only)

Kotlin allows exactly ONE `package` per file, so the slice is emitted as five
files rooted at stubs/content.kt.  See REPORT in the parent task notes.
"""

import argparse
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
JAVA_SRC = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview/src/main/java"
OUT_DIR = "/home/nekit/UT/firefox-atl/kn-poc/corpus/stubs"

# packages this slice owns
OWNED = ("android.content", "android.content.res", "android.content.pm",
         "android.database", "android.provider")

HEADER = """// GENERATED by kn-run/stubgen/content.py -- DO NOT EDIT BY HAND.
// android.* stub surface, "content" slice, for the Kotlin/Native GeckoView PoC.
// Bodies are TODO(): these types only have to make the transpiled GeckoView
// resolve and type-check.  Nothing here is meant to run.
"""

# --------------------------------------------------------------------------
# scraper: which types of my slice does GeckoView actually touch?
# --------------------------------------------------------------------------

IMPORT_RE = re.compile(r"^\s*import\s+(?:static\s+)?(android\.[A-Za-z0-9_.]+)\s*;", re.M)
FQN_RE = re.compile(r"\b(android\.(?:content(?:\.res|\.pm)?|database|provider)\.[A-Z][A-Za-z0-9_]*)")


def scrape():
    """Return {simple_type_name: set(files)} for types in the owned packages."""
    hits = defaultdict(set)
    for root, _dirs, files in os.walk(JAVA_SRC):
        for fn in files:
            if not fn.endswith(".java"):
                continue
            path = os.path.join(root, fn)
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = fh.read()
            found = set()
            for fqn in IMPORT_RE.findall(text):
                pkg, _, tail = fqn.rpartition(".")
                # nested import: android.content.ClipboardManager.OnPrimaryClipChangedListener
                if pkg not in OWNED:
                    pkg2, _, tail2 = pkg.rpartition(".")
                    if pkg2 in OWNED:
                        found.add(tail2)
                    continue
                found.add(tail)
            for fqn in FQN_RE.findall(text):
                pkg, _, tail = fqn.rpartition(".")
                if pkg in OWNED:
                    found.add(tail)
            for name in found:
                hits[name].add(os.path.relpath(path, JAVA_SRC))
    return hits


# --------------------------------------------------------------------------
# the stubs
# --------------------------------------------------------------------------
# Cross-slice types referenced by name and owned by other groups / the java
# shim lane.  Listed so the report can name them.
FOREIGN = [
    "android.net.Uri", "android.os.Bundle", "android.os.Handler",
    "android.os.IBinder", "android.os.PersistableBundle",
    "android.os.ParcelFileDescriptor", "android.util.DisplayMetrics",
    "android.util.TypedValue", "android.graphics.drawable.Drawable",
    "java.io.File", "java.io.FileDescriptor", "java.io.FileInputStream",
    "java.io.InputStream", "java.io.OutputStream", "java.util.Locale",
    "java.util.concurrent.Executor",
]

CONTENT_KT = r'''package android.content

import android.content.pm.ApplicationInfo
import android.content.pm.PackageManager
import android.content.res.AssetFileDescriptor
import android.content.res.Configuration
import android.content.res.Resources
import android.content.res.TypedArray
import android.database.ContentObserver
import android.database.Cursor
import android.net.Uri
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.ParcelFileDescriptor
import android.os.PersistableBundle

interface ComponentCallbacks {
    fun onConfigurationChanged(newConfig: Configuration)
    fun onLowMemory()
}

interface ComponentCallbacks2 : ComponentCallbacks {
    fun onTrimMemory(level: Int)

    companion object {
        const val TRIM_MEMORY_COMPLETE = 80
        const val TRIM_MEMORY_MODERATE = 60
        const val TRIM_MEMORY_BACKGROUND = 40
        const val TRIM_MEMORY_UI_HIDDEN = 20
        const val TRIM_MEMORY_RUNNING_CRITICAL = 15
        const val TRIM_MEMORY_RUNNING_LOW = 10
        const val TRIM_MEMORY_RUNNING_MODERATE = 5
    }
}

open class ActivityNotFoundException(message: String? = null) : RuntimeException(message)

open class ComponentName {
    constructor(pkg: String?, cls: String?)
    constructor(pkg: Context?, cls: String?)
    // ComponentName(Context, Class<?>): Class has no Kotlin/Native counterpart,
    // so whatever the codemod emits for `Foo.class` lands in Any?.
    constructor(pkg: Context?, cls: Any?)

    open fun getPackageName(): String = TODO()
    open fun getClassName(): String = TODO()
    open fun flattenToString(): String = TODO()
    open fun flattenToShortString(): String = TODO()
}

open class ClipDescription(label: CharSequence?, mimeTypes: Array<String>?) {
    open fun getLabel(): CharSequence = TODO()
    open fun getMimeType(index: Int): String = TODO()
    open fun getMimeTypeCount(): Int = TODO()
    open fun hasMimeType(mimeType: String?): Boolean = TODO()
    open fun getTimestamp(): Long = TODO()
    open fun getExtras(): PersistableBundle = TODO()
    open fun setExtras(extras: PersistableBundle?) { TODO() }

    companion object {
        const val MIMETYPE_TEXT_PLAIN = "text/plain"
        const val MIMETYPE_TEXT_HTML = "text/html"
        const val MIMETYPE_TEXT_INTENT = "text/vnd.android.intent"
        const val MIMETYPE_TEXT_URILIST = "text/uri-list"
        const val EXTRA_IS_SENSITIVE = "android.content.extra.IS_SENSITIVE"
    }
}

open class ClipData {
    constructor(description: ClipDescription?, item: Item?)
    constructor(label: CharSequence?, mimeTypes: Array<String>?, item: Item?)

    open fun getDescription(): ClipDescription = TODO()
    open fun getItemCount(): Int = TODO()
    open fun getItemAt(index: Int): Item = TODO()
    open fun addItem(item: Item?) { TODO() }

    open class Item {
        constructor(text: CharSequence?)
        constructor(text: CharSequence?, htmlText: String?)
        constructor(intent: Intent?)
        constructor(uri: Uri?)

        open fun getText(): CharSequence = TODO()
        open fun getHtmlText(): String = TODO()
        open fun getIntent(): Intent = TODO()
        open fun getUri(): Uri = TODO()
        open fun coerceToText(context: Context?): CharSequence = TODO()
    }

    companion object {
        fun newPlainText(label: CharSequence?, text: CharSequence?): ClipData = TODO()
        fun newHtmlText(label: CharSequence?, text: CharSequence?, htmlText: String?): ClipData = TODO()
        fun newIntent(label: CharSequence?, intent: Intent?): ClipData = TODO()
        fun newUri(resolver: ContentResolver?, label: CharSequence?, uri: Uri?): ClipData = TODO()
    }
}

open class ClipboardManager {
    open fun hasPrimaryClip(): Boolean = TODO()
    open fun getPrimaryClip(): ClipData = TODO()
    open fun getPrimaryClipDescription(): ClipDescription = TODO()
    open fun setPrimaryClip(clip: ClipData) { TODO() }
    open fun clearPrimaryClip() { TODO() }
    open fun addPrimaryClipChangedListener(what: OnPrimaryClipChangedListener?) { TODO() }
    open fun removePrimaryClipChangedListener(what: OnPrimaryClipChangedListener?) { TODO() }

    interface OnPrimaryClipChangedListener {
        fun onPrimaryClipChanged()
    }
}

open class IntentFilter {
    constructor()
    constructor(action: String?)
    constructor(action: String?, dataType: String?)

    open fun addAction(action: String?) { TODO() }
    open fun addCategory(category: String?) { TODO() }
    open fun addDataScheme(scheme: String?) { TODO() }
    open fun addDataType(type: String?) { TODO() }
    open fun countActions(): Int = TODO()
    open fun getAction(index: Int): String = TODO()
    open fun hasAction(action: String?): Boolean = TODO()
}

open class Intent {
    constructor()
    constructor(o: Intent?)
    constructor(action: String?)
    constructor(action: String?, uri: Uri?)
    // Intent(Context, Class<?>) / Intent(String, Uri, Context, Class<?>)
    constructor(packageContext: Context?, cls: Any?)
    constructor(action: String?, uri: Uri?, packageContext: Context?, cls: Any?)

    open fun getAction(): String = TODO()
    open fun setAction(action: String?): Intent = TODO()
    open fun getData(): Uri = TODO()
    open fun setData(data: Uri?): Intent = TODO()
    open fun getScheme(): String = TODO()
    open fun getType(): String = TODO()
    open fun setType(type: String?): Intent = TODO()
    open fun getFlags(): Int = TODO()
    open fun setFlags(flags: Int): Intent = TODO()
    open fun addFlags(flags: Int): Intent = TODO()
    open fun addCategory(category: String?): Intent = TODO()
    open fun getCategories(): MutableSet<String> = TODO()
    open fun setPackage(packageName: String?): Intent = TODO()
    open fun getPackage(): String = TODO()
    open fun setComponent(component: ComponentName?): Intent = TODO()
    open fun getComponent(): ComponentName = TODO()
    open fun setClassName(packageContext: Context?, className: String?): Intent = TODO()
    open fun setClassName(packageName: String?, className: String?): Intent = TODO()
    open fun setSelector(selector: Intent?) { TODO() }
    open fun getSelector(): Intent = TODO()
    open fun getExtras(): Bundle = TODO()
    open fun putExtras(extras: Bundle?): Intent = TODO()
    open fun hasExtra(name: String?): Boolean = TODO()
    open fun putExtra(name: String?, value: String?): Intent = TODO()
    open fun putExtra(name: String?, value: CharSequence?): Intent = TODO()
    open fun putExtra(name: String?, value: Boolean): Intent = TODO()
    open fun putExtra(name: String?, value: Int): Intent = TODO()
    open fun putExtra(name: String?, value: Long): Intent = TODO()
    open fun putExtra(name: String?, value: Float): Intent = TODO()
    open fun putExtra(name: String?, value: Double): Intent = TODO()
    open fun putExtra(name: String?, value: ByteArray?): Intent = TODO()
    open fun putExtra(name: String?, value: Bundle?): Intent = TODO()
    open fun getStringExtra(name: String?): String = TODO()
    open fun getIntExtra(name: String?, defaultValue: Int): Int = TODO()
    open fun getLongExtra(name: String?, defaultValue: Long): Long = TODO()
    open fun getBooleanExtra(name: String?, defaultValue: Boolean): Boolean = TODO()
    open fun getByteArrayExtra(name: String?): ByteArray = TODO()
    open fun getBundleExtra(name: String?): Bundle = TODO()
    open fun toUri(flags: Int): String = TODO()

    companion object {
        fun parseUri(uri: String?, flags: Int): Intent = TODO()

        const val ACTION_MAIN = "android.intent.action.MAIN"
        const val ACTION_VIEW = "android.intent.action.VIEW"
        const val ACTION_PROCESS_TEXT = "android.intent.action.PROCESS_TEXT"
        const val ACTION_BATTERY_CHANGED = "android.intent.action.BATTERY_CHANGED"
        const val ACTION_LOCALE_CHANGED = "android.intent.action.LOCALE_CHANGED"
        const val ACTION_TIMEZONE_CHANGED = "android.intent.action.TIMEZONE_CHANGED"
        const val CATEGORY_DEFAULT = "android.intent.category.DEFAULT"
        const val CATEGORY_BROWSABLE = "android.intent.category.BROWSABLE"
        const val CATEGORY_HOME = "android.intent.category.HOME"
        const val EXTRA_PROCESS_TEXT = "android.intent.extra.PROCESS_TEXT"
        const val EXTRA_PROCESS_TEXT_READONLY = "android.intent.extra.PROCESS_TEXT_READONLY"
        const val FLAG_GRANT_READ_URI_PERMISSION = 1
        const val FLAG_GRANT_WRITE_URI_PERMISSION = 2
        const val FLAG_ACTIVITY_NEW_TASK = 1 shl 28
        const val FLAG_ACTIVITY_CLEAR_TOP = 1 shl 26
        const val URI_INTENT_SCHEME = 1
    }
}

open class BroadcastReceiver {
    open fun onReceive(context: Context?, intent: Intent?) { TODO() }
    open fun goAsync(): PendingResult = TODO()
    open fun peekService(myContext: Context?, service: Intent?): IBinder = TODO()
    open fun abortBroadcast() { TODO() }
    open fun setDebugUnregister(debug: Boolean) { TODO() }

    open class PendingResult {
        open fun finish() { TODO() }
    }
}

interface ServiceConnection {
    fun onServiceConnected(name: ComponentName?, service: IBinder?)
    fun onServiceDisconnected(name: ComponentName?)
    fun onBindingDied(name: ComponentName?) {}
    fun onNullBinding(name: ComponentName?) {}
}

interface SharedPreferences {
    fun getAll(): MutableMap<String, *>
    fun getString(key: String?, defValue: String?): String
    fun getInt(key: String?, defValue: Int): Int
    fun getLong(key: String?, defValue: Long): Long
    fun getFloat(key: String?, defValue: Float): Float
    fun getBoolean(key: String?, defValue: Boolean): Boolean
    fun contains(key: String?): Boolean
    fun edit(): Editor
    fun registerOnSharedPreferenceChangeListener(listener: OnSharedPreferenceChangeListener?)
    fun unregisterOnSharedPreferenceChangeListener(listener: OnSharedPreferenceChangeListener?)

    interface Editor {
        fun putString(key: String?, value: String?): Editor
        fun putInt(key: String?, value: Int): Editor
        fun putLong(key: String?, value: Long): Editor
        fun putFloat(key: String?, value: Float): Editor
        fun putBoolean(key: String?, value: Boolean): Editor
        fun remove(key: String?): Editor
        fun clear(): Editor
        fun commit(): Boolean
        fun apply()
    }

    interface OnSharedPreferenceChangeListener {
        fun onSharedPreferenceChanged(sharedPreferences: SharedPreferences?, key: String?)
    }
}

open class ContentResolver {
    open fun registerContentObserver(uri: Uri?, notifyForDescendants: Boolean, observer: ContentObserver?) { TODO() }
    open fun unregisterContentObserver(observer: ContentObserver?) { TODO() }
    open fun notifyChange(uri: Uri?, observer: ContentObserver?) { TODO() }
    open fun openAssetFileDescriptor(uri: Uri?, mode: String?): AssetFileDescriptor = TODO()
    open fun openFileDescriptor(uri: Uri?, mode: String?): ParcelFileDescriptor = TODO()
    open fun openInputStream(uri: Uri?): java.io.InputStream = TODO()
    open fun openOutputStream(uri: Uri?): java.io.OutputStream = TODO()
    open fun getType(uri: Uri?): String = TODO()
    open fun query(
        uri: Uri?,
        projection: Array<String>?,
        selection: String?,
        selectionArgs: Array<String>?,
        sortOrder: String?
    ): Cursor = TODO()

    companion object {
        const val SCHEME_CONTENT = "content"
        const val SCHEME_FILE = "file"
        const val SCHEME_ANDROID_RESOURCE = "android.resource"
    }
}

open class Context {
    open fun getApplicationContext(): Context = TODO()
    open fun getPackageName(): String = TODO()
    open fun getPackageResourcePath(): String = TODO()
    open fun getPackageCodePath(): String = TODO()
    open fun getPackageManager(): PackageManager = TODO()
    open fun getContentResolver(): ContentResolver = TODO()
    open fun getApplicationInfo(): ApplicationInfo = TODO()
    open fun getResources(): Resources = TODO()
    open fun getTheme(): Resources.Theme = TODO()
    // ClassLoader has no Kotlin/Native counterpart; Any keeps the call site resolving.
    open fun getClassLoader(): Any = TODO()
    open fun getCacheDir(): java.io.File = TODO()
    open fun getFilesDir(): java.io.File = TODO()
    open fun getExternalFilesDir(type: String?): java.io.File = TODO()
    open fun getMainExecutor(): java.util.concurrent.Executor = TODO()
    open fun getSharedPreferences(name: String?, mode: Int): SharedPreferences = TODO()
    open fun getString(resId: Int): String = TODO()
    open fun getString(resId: Int, vararg formatArgs: Any?): String = TODO()

    // getSystemService(String) returns Object in Java: call sites cast the result.
    open fun getSystemService(name: String?): Any = TODO()
    // getSystemService(Class<T>) -- KClass is the closest Kotlin/Native has.
    open fun <T : Any> getSystemService(serviceClass: kotlin.reflect.KClass<T>): T = TODO()

    open fun obtainStyledAttributes(attrs: IntArray?): TypedArray = TODO()
    open fun obtainStyledAttributes(resid: Int, attrs: IntArray?): TypedArray = TODO()

    open fun registerReceiver(receiver: BroadcastReceiver?, filter: IntentFilter?): Intent = TODO()
    open fun registerReceiver(receiver: BroadcastReceiver?, filter: IntentFilter?, flags: Int): Intent = TODO()
    open fun registerReceiver(
        receiver: BroadcastReceiver?,
        filter: IntentFilter?,
        broadcastPermission: String?,
        scheduler: Handler?
    ): Intent = TODO()
    open fun unregisterReceiver(receiver: BroadcastReceiver?) { TODO() }

    open fun registerComponentCallbacks(callback: ComponentCallbacks?) { TODO() }
    open fun unregisterComponentCallbacks(callback: ComponentCallbacks?) { TODO() }

    open fun sendBroadcast(intent: Intent?) { TODO() }
    open fun sendBroadcast(intent: Intent?, receiverPermission: String?) { TODO() }

    open fun startActivity(intent: Intent?) { TODO() }
    open fun startActivity(intent: Intent?, options: Bundle?) { TODO() }
    open fun startService(service: Intent?): ComponentName = TODO()
    open fun startForegroundService(service: Intent?): ComponentName = TODO()

    open fun bindService(service: Intent?, conn: ServiceConnection?, flags: Int): Boolean = TODO()
    open fun bindService(service: Intent?, flags: Int, executor: java.util.concurrent.Executor?, conn: ServiceConnection?): Boolean = TODO()
    open fun bindIsolatedService(
        service: Intent?,
        flags: Int,
        instanceName: String?,
        executor: java.util.concurrent.Executor?,
        conn: ServiceConnection?
    ): Boolean = TODO()
    open fun unbindService(conn: ServiceConnection?) { TODO() }
    open fun updateServiceGroup(conn: ServiceConnection?, group: Int, importance: Int) { TODO() }

    open fun checkUriPermission(uri: Uri?, pid: Int, uid: Int, modeFlags: Int): Int = TODO()
    open fun checkSelfPermission(permission: String?): Int = TODO()

    companion object {
        const val ACCESSIBILITY_SERVICE = "accessibility"
        const val ACTIVITY_SERVICE = "activity"
        const val AUDIO_SERVICE = "audio"
        const val CLIPBOARD_SERVICE = "clipboard"
        const val CONNECTIVITY_SERVICE = "connectivity"
        const val CREDENTIAL_SERVICE = "credential"
        const val DISPLAY_SERVICE = "display"
        const val INPUT_METHOD_SERVICE = "input_method"
        const val INPUT_SERVICE = "input"
        const val LOCATION_SERVICE = "location"
        const val POWER_SERVICE = "power"
        const val PRINT_SERVICE = "print"
        const val SENSOR_SERVICE = "sensor"
        const val UI_MODE_SERVICE = "uimode"
        const val USER_SERVICE = "user"
        const val VIBRATOR_SERVICE = "vibrator"
        const val WIFI_SERVICE = "wifi"
        const val WINDOW_SERVICE = "window"

        const val BIND_AUTO_CREATE = 1
        const val BIND_DEBUG_UNBIND = 2
        const val BIND_NOT_FOREGROUND = 4
        const val BIND_ABOVE_CLIENT = 8
        const val BIND_ALLOW_OOM_MANAGEMENT = 16
        const val BIND_WAIVE_PRIORITY = 32
        const val BIND_IMPORTANT = 64
        const val BIND_ADJUST_WITH_ACTIVITY = 128

        const val MODE_PRIVATE = 0
        const val RECEIVER_EXPORTED = 2
        const val RECEIVER_NOT_EXPORTED = 4
    }
}

open class ContextWrapper(base: Context?) : Context() {
    open fun getBaseContext(): Context = TODO()
    open fun attachBaseContext(base: Context?) { TODO() }
}
'''

RES_KT = r'''package android.content.res

open class Configuration {
    var fontScale: Float = 1.0f
    var densityDpi: Int = 0
    var keyboard: Int = 0
    var orientation: Int = 0
    var screenLayout: Int = 0
    var screenWidthDp: Int = 0
    var screenHeightDp: Int = 0
    var smallestScreenWidthDp: Int = 0
    var uiMode: Int = 0
    var locale: java.util.Locale = TODO()

    constructor()
    constructor(other: Configuration?)

    open fun setTo(other: Configuration?) { TODO() }
    open fun getLocales(): Any = TODO()

    companion object {
        const val ORIENTATION_UNDEFINED = 0
        const val ORIENTATION_PORTRAIT = 1
        const val ORIENTATION_LANDSCAPE = 2

        const val KEYBOARD_UNDEFINED = 0
        const val KEYBOARD_NOKEYS = 1
        const val KEYBOARD_QWERTY = 2
        const val KEYBOARD_12KEY = 3

        const val SCREENLAYOUT_SIZE_MASK = 0x0f
        const val SCREENLAYOUT_SIZE_UNDEFINED = 0x00
        const val SCREENLAYOUT_SIZE_SMALL = 0x01
        const val SCREENLAYOUT_SIZE_NORMAL = 0x02
        const val SCREENLAYOUT_SIZE_LARGE = 0x03
        const val SCREENLAYOUT_SIZE_XLARGE = 0x04

        const val UI_MODE_TYPE_MASK = 0x0f
        const val UI_MODE_TYPE_NORMAL = 0x01
        const val UI_MODE_TYPE_TELEVISION = 0x04
        const val UI_MODE_NIGHT_MASK = 0x30
        const val UI_MODE_NIGHT_UNDEFINED = 0x00
        const val UI_MODE_NIGHT_NO = 0x10
        const val UI_MODE_NIGHT_YES = 0x20

        const val DENSITY_DPI_UNDEFINED = 0
    }
}

open class TypedArray {
    open fun getIndexCount(): Int = TODO()
    open fun getIndex(at: Int): Int = TODO()
    open fun getColor(index: Int, defValue: Int): Int = TODO()
    open fun getBoolean(index: Int, defValue: Boolean): Boolean = TODO()
    open fun getInt(index: Int, defValue: Int): Int = TODO()
    open fun getFloat(index: Int, defValue: Float): Float = TODO()
    open fun getDimension(index: Int, defValue: Float): Float = TODO()
    open fun getDimensionPixelSize(index: Int, defValue: Int): Int = TODO()
    open fun getResourceId(index: Int, defValue: Int): Int = TODO()
    open fun getString(index: Int): String = TODO()
    open fun getDrawable(index: Int): android.graphics.drawable.Drawable = TODO()
    open fun hasValue(index: Int): Boolean = TODO()
    open fun recycle() { TODO() }
}

open class AssetFileDescriptor : AutoCloseable {
    open fun getFileDescriptor(): java.io.FileDescriptor = TODO()
    open fun getParcelFileDescriptor(): android.os.ParcelFileDescriptor = TODO()
    open fun getStartOffset(): Long = TODO()
    open fun getLength(): Long = TODO()
    open fun getDeclaredLength(): Long = TODO()
    open fun createInputStream(): java.io.FileInputStream = TODO()
    open fun createOutputStream(): java.io.OutputStream = TODO()
    override fun close() { TODO() }
}

open class AssetManager : AutoCloseable {
    open fun open(fileName: String?): java.io.InputStream = TODO()
    open fun list(path: String?): Array<String> = TODO()
    override fun close() { TODO() }
}

open class Resources {
    open fun getConfiguration(): Configuration = TODO()
    open fun getDisplayMetrics(): android.util.DisplayMetrics = TODO()
    open fun updateConfiguration(config: Configuration?, metrics: android.util.DisplayMetrics?) { TODO() }
    open fun getAssets(): AssetManager = TODO()
    open fun getIdentifier(name: String?, defType: String?, defPackage: String?): Int = TODO()
    open fun getString(id: Int): String = TODO()
    open fun getString(id: Int, vararg formatArgs: Any?): String = TODO()
    open fun getBoolean(id: Int): Boolean = TODO()
    open fun getInteger(id: Int): Int = TODO()
    open fun getDimensionPixelSize(id: Int): Int = TODO()
    open fun getDrawable(id: Int, theme: Theme?): android.graphics.drawable.Drawable = TODO()
    open fun openRawResource(id: Int): java.io.InputStream = TODO()

    open class Theme {
        open fun resolveAttribute(resid: Int, outValue: android.util.TypedValue?, resolveRefs: Boolean): Boolean = TODO()
        open fun obtainStyledAttributes(attrs: IntArray?): TypedArray = TODO()
        open fun applyStyle(resId: Int, force: Boolean) { TODO() }
    }

    open class NotFoundException(message: String? = null) : RuntimeException(message)

    companion object {
        fun getSystem(): Resources = TODO()
    }
}
'''

PM_KT = r'''package android.content.pm

import android.content.ComponentName
import android.content.Intent
import android.os.Bundle

open class PackageItemInfo {
    var name: String = TODO()
    var packageName: String = TODO()
    var labelRes: Int = 0
    var nonLocalizedLabel: CharSequence = TODO()
    var icon: Int = 0
    var logo: Int = 0
    var metaData: Bundle = TODO()

    open fun loadLabel(pm: PackageManager?): CharSequence = TODO()
    open fun loadIcon(pm: PackageManager?): android.graphics.drawable.Drawable = TODO()
}

open class ApplicationInfo : PackageItemInfo() {
    var dataDir: String = TODO()
    var nativeLibraryDir: String = TODO()
    var sourceDir: String = TODO()
    var publicSourceDir: String = TODO()
    var processName: String = TODO()
    var className: String = TODO()
    var flags: Int = 0
    var uid: Int = 0
    var targetSdkVersion: Int = 0

    companion object {
        const val FLAG_SYSTEM = 1 shl 0
        const val FLAG_DEBUGGABLE = 1 shl 1
        const val FLAG_HAS_CODE = 1 shl 2
    }
}

open class ComponentInfo : PackageItemInfo() {
    var applicationInfo: ApplicationInfo = TODO()
    var processName: String = TODO()
    var exported: Boolean = false
    var enabled: Boolean = true
    var descriptionRes: Int = 0
}

open class ActivityInfo : ComponentInfo() {
    var theme: Int = 0
    var launchMode: Int = 0
    var flags: Int = 0
    var screenOrientation: Int = SCREEN_ORIENTATION_UNSPECIFIED
    var configChanges: Int = 0

    companion object {
        const val SCREEN_ORIENTATION_UNSPECIFIED = -1
        const val SCREEN_ORIENTATION_LANDSCAPE = 0
        const val SCREEN_ORIENTATION_PORTRAIT = 1
        const val SCREEN_ORIENTATION_USER = 2
        const val SCREEN_ORIENTATION_BEHIND = 3
        const val SCREEN_ORIENTATION_SENSOR = 4
        const val SCREEN_ORIENTATION_NOSENSOR = 5
        const val SCREEN_ORIENTATION_SENSOR_LANDSCAPE = 6
        const val SCREEN_ORIENTATION_SENSOR_PORTRAIT = 7
        const val SCREEN_ORIENTATION_REVERSE_LANDSCAPE = 8
        const val SCREEN_ORIENTATION_REVERSE_PORTRAIT = 9
        const val SCREEN_ORIENTATION_FULL_SENSOR = 10
        const val SCREEN_ORIENTATION_LOCKED = 14
    }
}

open class ServiceInfo : ComponentInfo() {
    var permission: String = TODO()
    var flags: Int = 0

    companion object {
        const val FLAG_STOP_WITH_TASK = 0x0001
        const val FLAG_ISOLATED_PROCESS = 0x0002
        const val FLAG_EXTERNAL_SERVICE = 0x0004
        const val FLAG_USE_APP_ZYGOTE = 0x0008
    }
}

open class ProviderInfo : ComponentInfo() {
    var authority: String = TODO()
    var readPermission: String = TODO()
    var writePermission: String = TODO()
    var grantUriPermissions: Boolean = false
}

open class PackageInfo {
    var packageName: String = TODO()
    var versionName: String = TODO()
    var versionCode: Int = 0
    var firstInstallTime: Long = 0
    var lastUpdateTime: Long = 0
    var applicationInfo: ApplicationInfo = TODO()
    var services: Array<ServiceInfo> = TODO()
    var activities: Array<ActivityInfo> = TODO()
    var providers: Array<ProviderInfo> = TODO()
}

open class ResolveInfo {
    var activityInfo: ActivityInfo = TODO()
    var serviceInfo: ServiceInfo = TODO()
    var providerInfo: ProviderInfo = TODO()
    var priority: Int = 0
    var preferredOrder: Int = 0
    var isDefault: Boolean = false

    open fun loadLabel(pm: PackageManager?): CharSequence = TODO()
    open fun loadIcon(pm: PackageManager?): android.graphics.drawable.Drawable = TODO()
}

open class PackageManager {
    open fun getPackageInfo(packageName: String?, flags: Int): PackageInfo = TODO()
    open fun getApplicationInfo(packageName: String?, flags: Int): ApplicationInfo = TODO()
    open fun getServiceInfo(component: ComponentName?, flags: Int): ServiceInfo = TODO()
    open fun getActivityInfo(component: ComponentName?, flags: Int): ActivityInfo = TODO()
    open fun resolveContentProvider(authority: String?, flags: Int): ProviderInfo = TODO()
    open fun resolveActivity(intent: Intent?, flags: Int): ResolveInfo = TODO()
    open fun queryIntentActivities(intent: Intent?, flags: Int): MutableList<ResolveInfo> = TODO()
    open fun queryIntentActivityOptions(
        caller: ComponentName?,
        specifics: Array<Intent>?,
        intent: Intent?,
        flags: Int
    ): MutableList<ResolveInfo> = TODO()
    open fun queryIntentServices(intent: Intent?, flags: Int): MutableList<ResolveInfo> = TODO()
    open fun hasSystemFeature(name: String?): Boolean = TODO()
    open fun checkPermission(permName: String?, pkgName: String?): Int = TODO()
    open fun getLaunchIntentForPackage(packageName: String?): Intent = TODO()

    class NameNotFoundException(message: String? = null) : Exception(message)

    companion object {
        const val PERMISSION_GRANTED = 0
        const val PERMISSION_DENIED = -1

        const val GET_ACTIVITIES = 0x00000001
        const val GET_RECEIVERS = 0x00000002
        const val GET_SERVICES = 0x00000004
        const val GET_PROVIDERS = 0x00000008
        const val GET_META_DATA = 0x00000080
        const val MATCH_DEFAULT_ONLY = 0x00010000

        const val FEATURE_TOUCHSCREEN = "android.hardware.touchscreen"
        const val FEATURE_TOUCHSCREEN_MULTITOUCH = "android.hardware.touchscreen.multitouch"
        const val FEATURE_TOUCHSCREEN_MULTITOUCH_DISTINCT = "android.hardware.touchscreen.multitouch.distinct"
        const val FEATURE_TOUCHSCREEN_MULTITOUCH_JAZZHAND = "android.hardware.touchscreen.multitouch.jazzhand"
        const val FEATURE_CREDENTIALS = "android.software.credentials"
    }
}
'''

DATABASE_KT = r'''package android.database

import android.net.Uri
import android.os.Handler

open class ContentObserver(handler: Handler?) {
    open fun deliverSelfNotifications(): Boolean = TODO()
    open fun onChange(selfChange: Boolean) { TODO() }
    open fun onChange(selfChange: Boolean, uri: Uri?) { TODO() }
    open fun dispatchChange(selfChange: Boolean) { TODO() }
    open fun dispatchChange(selfChange: Boolean, uri: Uri?) { TODO() }
}

interface Cursor : AutoCloseable {
    fun getCount(): Int
    fun getPosition(): Int
    fun getColumnCount(): Int
    fun getColumnIndex(columnName: String?): Int
    fun getColumnIndexOrThrow(columnName: String?): Int
    fun getColumnName(columnIndex: Int): String
    fun getColumnNames(): Array<String>
    fun moveToFirst(): Boolean
    fun moveToLast(): Boolean
    fun moveToNext(): Boolean
    fun moveToPrevious(): Boolean
    fun moveToPosition(position: Int): Boolean
    fun isNull(columnIndex: Int): Boolean
    fun isClosed(): Boolean
    fun getString(columnIndex: Int): String
    fun getShort(columnIndex: Int): Short
    fun getInt(columnIndex: Int): Int
    fun getLong(columnIndex: Int): Long
    fun getFloat(columnIndex: Int): Float
    fun getDouble(columnIndex: Int): Double
    fun getBlob(columnIndex: Int): ByteArray
    fun getType(columnIndex: Int): Int
    override fun close()

    companion object {
        const val FIELD_TYPE_NULL = 0
        const val FIELD_TYPE_INTEGER = 1
        const val FIELD_TYPE_FLOAT = 2
        const val FIELD_TYPE_STRING = 3
        const val FIELD_TYPE_BLOB = 4
    }
}

open class SQLException(message: String? = null) : RuntimeException(message)

open class StaleDataException(message: String? = null) : RuntimeException(message)
'''

PROVIDER_KT = r'''package android.provider

import android.content.ContentResolver
import android.content.Context
import android.net.Uri

open class Settings {
    object System {
        const val FONT_SCALE = "font_scale"
        const val TEXT_SHOW_PASSWORD = "show_password"
        const val ACCELEROMETER_ROTATION = "accelerometer_rotation"

        fun getUriFor(name: String?): Uri = TODO()
        fun getString(cr: ContentResolver?, name: String?): String = TODO()
        fun getInt(cr: ContentResolver?, name: String?): Int = TODO()
        fun getInt(cr: ContentResolver?, name: String?, def: Int): Int = TODO()
        fun getFloat(cr: ContentResolver?, name: String?): Float = TODO()
        fun getFloat(cr: ContentResolver?, name: String?, def: Float): Float = TODO()
        // Java widens the int literal at `getFloat(cr, KEY, 1)`; Kotlin will not.
        fun getFloat(cr: ContentResolver?, name: String?, def: Int): Float = TODO()
        fun putInt(cr: ContentResolver?, name: String?, value: Int): Boolean = TODO()
        fun putString(cr: ContentResolver?, name: String?, value: String?): Boolean = TODO()
    }

    object Secure {
        const val DEFAULT_INPUT_METHOD = "default_input_method"
        const val ACCESSIBILITY_DISPLAY_INVERSION_ENABLED = "accessibility_display_inversion_enabled"
        const val ACCESSIBILITY_HIGH_TEXT_CONTRAST_ENABLED = "high_text_contrast_enabled"
        const val ANDROID_ID = "android_id"

        fun getUriFor(name: String?): Uri = TODO()
        fun getString(cr: ContentResolver?, name: String?): String = TODO()
        fun getInt(cr: ContentResolver?, name: String?): Int = TODO()
        fun getInt(cr: ContentResolver?, name: String?, def: Int): Int = TODO()
        fun getFloat(cr: ContentResolver?, name: String?): Float = TODO()
        fun getFloat(cr: ContentResolver?, name: String?, def: Float): Float = TODO()
        fun getFloat(cr: ContentResolver?, name: String?, def: Int): Float = TODO()
        fun putInt(cr: ContentResolver?, name: String?, value: Int): Boolean = TODO()
    }

    object Global {
        const val ANIMATOR_DURATION_SCALE = "animator_duration_scale"
        const val DEBUG_APP = "debug_app"
        const val TRANSITION_ANIMATION_SCALE = "transition_animation_scale"

        fun getUriFor(name: String?): Uri = TODO()
        fun getString(cr: ContentResolver?, name: String?): String = TODO()
        fun getInt(cr: ContentResolver?, name: String?): Int = TODO()
        fun getInt(cr: ContentResolver?, name: String?, def: Int): Int = TODO()
        fun getFloat(cr: ContentResolver?, name: String?): Float = TODO()
        fun getFloat(cr: ContentResolver?, name: String?, def: Float): Float = TODO()
        fun getFloat(cr: ContentResolver?, name: String?, def: Int): Float = TODO()
        fun putInt(cr: ContentResolver?, name: String?, value: Int): Boolean = TODO()
    }

    companion object {
        const val ACTION_APPLICATION_DETAILS_SETTINGS =
            "android.settings.APPLICATION_DETAILS_SETTINGS"
    }
}

object DocumentsContract {
    fun getDocumentId(documentUri: Uri?): String = TODO()
    fun getTreeDocumentId(documentUri: Uri?): String = TODO()
    fun isDocumentUri(context: Context?, uri: Uri?): Boolean = TODO()
    fun isTreeUri(uri: Uri?): Boolean = TODO()
    fun buildDocumentUriUsingTree(treeUri: Uri?, documentId: String?): Uri = TODO()
    fun buildChildDocumentsUriUsingTree(treeUri: Uri?, parentDocumentId: String?): Uri = TODO()
    fun buildDocumentUri(authority: String?, documentId: String?): Uri = TODO()

    object Document {
        const val COLUMN_DOCUMENT_ID = "document_id"
        const val COLUMN_MIME_TYPE = "mime_type"
        const val COLUMN_DISPLAY_NAME = "_display_name"
        const val COLUMN_SUMMARY = "summary"
        const val COLUMN_LAST_MODIFIED = "last_modified"
        const val COLUMN_ICON = "icon"
        const val COLUMN_FLAGS = "flags"
        const val COLUMN_SIZE = "_size"
        const val MIME_TYPE_DIR = "vnd.android.document/directory"
    }

    object Root {
        const val COLUMN_ROOT_ID = "root_id"
        const val COLUMN_DOCUMENT_ID = "document_id"
        const val COLUMN_TITLE = "title"
    }
}

interface BaseColumns {
    companion object {
        const val _ID = "_id"
        const val _COUNT = "_count"
    }
}
'''

FILES = [
    ("content.kt", CONTENT_KT),
    ("content_res.kt", RES_KT),
    ("content_pm.kt", PM_KT),
    ("database.kt", DATABASE_KT),
    ("provider.kt", PROVIDER_KT),
]

# Cross-slice placeholders, emitted only for the standalone syntax check.
SHIMS_KT = r'''// throwaway placeholders for types owned by other stub slices / the java lane.
package android.net
class Uri { fun getAuthority(): String? = TODO() }

package_marker_unused_0
'''

SHIM_PARTS = {
    "shim_net.kt": "package android.net\nclass Uri\n",
    "shim_os.kt": ("package android.os\n"
                   "class Bundle\nclass Handler\ninterface IBinder\n"
                   "class PersistableBundle\nclass ParcelFileDescriptor\n"),
    "shim_util.kt": "package android.util\nclass DisplayMetrics\nclass TypedValue\n",
    "shim_gfx.kt": "package android.graphics.drawable\nopen class Drawable\n",
    "shim_javaio.kt": ("package java.io\n"
                       "open class File\nopen class FileDescriptor\n"
                       "open class InputStream\nopen class OutputStream\n"
                       "open class FileInputStream : InputStream()\n"),
    "shim_javautil.kt": ("package java.util\nopen class Locale\n"),
    "shim_javaconc.kt": ("package java.util.concurrent\ninterface Executor\n"),
    "shim_lang.kt": ("package kn.shim\n"),
}


def emit(check_only=False):
    written = []
    if not check_only:
        os.makedirs(OUT_DIR, exist_ok=True)
        for name, body in FILES:
            path = os.path.join(OUT_DIR, name)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(HEADER)
                fh.write("\n")
                fh.write(body)
            written.append(path)
    return written


def emit_shims(dest="/tmp/kn-content-shims"):
    os.makedirs(dest, exist_ok=True)
    for name, body in SHIM_PARTS.items():
        with open(os.path.join(dest, name), "w", encoding="utf-8") as fh:
            fh.write(body)
    return dest


DECL_RE = re.compile(r"^(?:open |abstract |final |sealed )*(?:class|interface|object)\s+([A-Za-z0-9_]+)", re.M)


def declared_types():
    names = set()
    for _name, body in FILES:
        for m in DECL_RE.finditer(body):
            names.add(m.group(1))
    return names


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    ap.add_argument("--shims", action="store_true", help="also emit cross-slice placeholders")
    args = ap.parse_args()

    hits = scrape()
    declared = declared_types()

    used = sorted(hits)
    missing = [t for t in used if t not in declared]
    extra = sorted(declared - set(used))

    written = emit(check_only=args.check)
    if args.shims:
        print("shims:", emit_shims())

    print("== android.content / .res / .pm / android.database / android.provider ==")
    print("types referenced by GeckoView Java : %d" % len(used))
    print("types declared by this generator   : %d" % len(declared))
    print("referenced but NOT declared        : %d %s" % (len(missing), missing))
    print("declared as supporting/base types  : %d %s" % (len(extra), extra))
    print()
    for t in used:
        print("  %-28s %2d file(s)" % (t, len(hits[t])))
    print()
    for p in written:
        print("wrote", p)
    print()
    print("cross-slice types referenced (owned by other groups / the java lane):")
    for f in FOREIGN:
        print("  ", f)

    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
