#!/usr/bin/env python3
"""Emit Kotlin/Native stubs for the media-net slice of the android.* surface.

Slice: android.media, android.net, android.app, android.hardware,
       android.location, android.security, android.system,
       android.credentials, android.annotation (and their subpackages).

Signatures were derived from the GeckoView call sites under SRC; where a call
site was ambiguous the true signature was read out of ATL's real Java
reimplementation under ATL_IMPL (see RECOVERED_FROM_ATL below).

Bodies are TODO() on purpose -- nothing here is ever executed, the only goal is
that Kotlin/Native accepts the transpiled GeckoView that resolves against it.

Kotlin allows exactly one `package` header per file, so this emits one file per
package rather than the single media-net.kt the brief asked for.  media-net.kt
is android.media (the anchor / largest package); the siblings are named
media-net-<subpackage>.kt.

Run:  python3 media-net.py            # writes the stubs
      python3 media-net.py --check    # writes them, then reports uncovered members
"""

import collections
import os
import re
import sys

SRC = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview/src/main/java"
OUT = "/home/nekit/UT/firefox-atl/kn-poc/corpus/stubs"
ATL_IMPL = "/home/nekit/UT/atlas/src/api-impl/android"

# Types whose signature was taken (or confirmed) from ATL's real Java impl
# rather than guessed from the GeckoView call site alone.
RECOVERED_FROM_ATL = [
    "MediaCodec", "MediaCodec.BufferInfo", "MediaCodec.CryptoInfo",
    "MediaCodec.CryptoInfo.Pattern", "MediaCodec.Callback",
    "MediaCodec.CodecException", "MediaCodec.CryptoException",
    "MediaCodecInfo", "MediaCodecInfo.CodecCapabilities",
    "MediaCodecInfo.CodecProfileLevel", "MediaCodecInfo.VideoCapabilities",
    "MediaCodecList", "MediaFormat", "MediaCrypto", "MediaCryptoException",
    "MediaDrm", "MediaDrm.KeyRequest", "MediaDrm.KeyStatus",
    "MediaDrm.ProvisionRequest", "MediaDrm.OnEventListener",
    "MediaDrm.OnKeyStatusChangeListener", "MediaDrmException",
    "NotProvisionedException", "DeniedByServerException",
    "ResourceBusyException", "UnsupportedSchemeException", "AudioManager",
    "Uri", "ConnectivityManager", "ConnectivityManager.NetworkCallback",
    "NetworkInfo", "LinkProperties", "ProxyInfo", "Proxy", "DhcpInfo",
    "WifiManager", "Activity", "ActivityManager",
    "ActivityManager.MemoryInfo", "ActivityManager.RunningAppProcessInfo",
    "Application", "PendingIntent", "Service", "UiModeManager",
    "UiModeManager.ContrastChangeListener",
    "ForegroundServiceStartNotAllowedException", "ZygotePreload",
    "Sensor", "SensorEvent", "SensorEventListener", "SensorManager",
    "DisplayManager", "DisplayManager.DisplayListener", "InputManager",
    "InputManager.InputDeviceListener", "Criteria", "Location",
    "LocationListener", "LocationManager", "KeyChain", "KeyChainException",
    "CredentialManager", "CredentialOption", "Credential",
    "CreateCredentialRequest", "CreateCredentialResponse",
    "CreateCredentialException", "GetCredentialRequest",
    "GetCredentialResponse", "GetCredentialException",
    "PrepareGetCredentialResponse",
    "PrepareGetCredentialResponse.PendingGetCredentialHandle",
]

# android.system.* has no ATL counterpart; hand-written from the call sites in
# org/mozilla/gecko/crashhelper/CrashHelper.java plus libc constants.
NOT_IN_ATL = ["Os", "OsConstants", "ErrnoException", "SuppressLint",
              "Notification", "JobScheduler", "Dialog"]

HDR = """// GENERATED by kn-run/stubgen/media-net.py -- do not edit by hand.
// android.* stubs for the media-net slice, consumed by the transpiled GeckoView.
// Bodies are TODO(): Kotlin/Native has no JVM, no JNI and no Android runtime.
@file:Suppress("UNUSED_PARAMETER", "unused")

"""

# --------------------------------------------------------------------------
# android.media
# --------------------------------------------------------------------------
MEDIA = r'''
open class MediaCodec {
    companion object {
        const val BUFFER_FLAG_KEY_FRAME = 1
        const val BUFFER_FLAG_CODEC_CONFIG = 2
        const val BUFFER_FLAG_END_OF_STREAM = 4
        const val BUFFER_FLAG_SYNC_FRAME = 1
        const val CONFIGURE_FLAG_ENCODE = 1
        const val INFO_TRY_AGAIN_LATER = -1
        const val INFO_OUTPUT_FORMAT_CHANGED = -2
        const val INFO_OUTPUT_BUFFERS_CHANGED = -3
        const val PARAMETER_KEY_REQUEST_SYNC_FRAME = "request-sync"
        const val PARAMETER_KEY_VIDEO_BITRATE = "video-bitrate"

        fun createByCodecName(name: String): MediaCodec = TODO()
        fun createDecoderByType(type: String): MediaCodec = TODO()
        fun createEncoderByType(type: String): MediaCodec = TODO()
    }

    class BufferInfo {
        var offset: Int = 0
        var size: Int = 0
        var presentationTimeUs: Long = 0L
        var flags: Int = 0
        fun set(newOffset: Int, newSize: Int, newTimeUs: Long, newFlags: Int) {}
    }

    class CryptoInfo {
        class Pattern(blocksToEncrypt: Int, blocksToSkip: Int) {
            fun set(blocksToEncrypt: Int, blocksToSkip: Int) {}
            fun getEncryptBlocks(): Int = TODO()
            fun getSkipBlocks(): Int = TODO()
        }

        var numSubSamples: Int = 0
        var numBytesOfClearData: IntArray? = null
        var numBytesOfEncryptedData: IntArray? = null
        var key: ByteArray? = null
        var iv: ByteArray? = null
        var mode: Int = 0

        fun set(
            newNumSubSamples: Int,
            newNumBytesOfClearData: IntArray?,
            newNumBytesOfEncryptedData: IntArray?,
            newKey: ByteArray?,
            newIv: ByteArray?,
            newMode: Int
        ) {}
        fun setPattern(pattern: Pattern?) {}
        fun getPattern(): Pattern = TODO()
    }

    open class CodecException : IllegalStateException() {
        fun getErrorCode(): Int = TODO()
        fun getDiagnosticInfo(): String = TODO()
        fun isRecoverable(): Boolean = TODO()
        fun isTransient(): Boolean = TODO()
    }

    open class CryptoException : RuntimeException() {
        fun getErrorCode(): Int = TODO()
    }

    // GeckoView subclasses this (AsyncCodecImpl.CodecCallback), so the
    // parameters are non-null to match the overrides the codemod emits.
    abstract class Callback {
        abstract fun onInputBufferAvailable(codec: MediaCodec, index: Int)
        abstract fun onOutputBufferAvailable(codec: MediaCodec, index: Int, info: BufferInfo)
        abstract fun onError(codec: MediaCodec, e: CodecException)
        abstract fun onOutputFormatChanged(codec: MediaCodec, format: MediaFormat)
    }

    interface OnFrameRenderedListener {
        fun onFrameRendered(codec: MediaCodec, presentationTimeUs: Long, nanoTime: Long)
    }

    fun configure(format: MediaFormat?, surface: Any?, crypto: MediaCrypto?, flags: Int) {}
    fun setCallback(cb: Callback?) {}
    fun setParameters(params: android.os.Bundle?) {}
    fun start() {}
    fun stop() {}
    fun flush() {}
    fun reset() {}
    fun release() {}
    fun getCodecInfo(): MediaCodecInfo = TODO()
    fun getInputFormat(): MediaFormat = TODO()
    fun getOutputFormat(): MediaFormat = TODO()
    fun getInputBuffer(index: Int): java.nio.ByteBuffer = TODO()
    fun getOutputBuffer(index: Int): java.nio.ByteBuffer = TODO()
    fun queueInputBuffer(index: Int, offset: Int, size: Int, presentationTimeUs: Long, flags: Int) {}
    fun queueSecureInputBuffer(
        index: Int, offset: Int, info: CryptoInfo?, presentationTimeUs: Long, flags: Int
    ) {}
    fun releaseOutputBuffer(index: Int, render: Boolean) {}
    fun releaseOutputBuffer(index: Int, renderTimestampNs: Long) {}
    fun dequeueInputBuffer(timeoutUs: Long): Int = TODO()
    fun dequeueOutputBuffer(info: BufferInfo?, timeoutUs: Long): Int = TODO()
}

open class MediaCodecInfo {
    class CodecCapabilities {
        companion object {
            const val COLOR_FormatSurface = 2130708361
            const val COLOR_FormatYUV420Planar = 19
            const val COLOR_FormatYUV420SemiPlanar = 21
            const val COLOR_QCOM_FormatYUV420SemiPlanar = 2141391872
            const val FEATURE_AdaptivePlayback = "adaptive-playback"
            const val FEATURE_TunneledPlayback = "tunneled-playback"
            const val FEATURE_SecurePlayback = "secure-playback"
            const val FEATURE_EncodingStatistics = "encoding-statistics"
        }

        var colorFormats: IntArray = intArrayOf()
        var profileLevels: Array<CodecProfileLevel> = arrayOf()

        fun isFeatureSupported(name: String?): Boolean = TODO()
        fun isFeatureRequired(name: String?): Boolean = TODO()
        fun getVideoCapabilities(): VideoCapabilities = TODO()
        fun getAudioCapabilities(): AudioCapabilities = TODO()
        fun getEncoderCapabilities(): EncoderCapabilities = TODO()
    }

    class CodecProfileLevel {
        companion object {
            const val AVCProfileHigh = 8
            const val AVCProfileHigh10 = 16
            const val AVCLevel3 = 256
            const val VP9Profile2 = 4
            const val VP9Profile3 = 8
            const val VP9Profile2HDR = 4096
            const val VP9Profile3HDR = 8192
            const val VP9Profile2HDR10Plus = 16384
            const val VP9Profile3HDR10Plus = 32768
            const val HEVCProfileMain10 = 2
            const val HEVCProfileMain10HDR10 = 4096
            const val HEVCProfileMain10HDR10Plus = 8192
            const val AV1ProfileMain10 = 2
            const val AV1ProfileMain10HDR10 = 4096
            const val AV1ProfileMain10HDR10Plus = 8192
        }

        var profile: Int = 0
        var level: Int = 0
    }

    class VideoCapabilities {
        fun isSizeSupported(width: Int, height: Int): Boolean = TODO()
        fun getSupportedWidths(): Any = TODO()
        fun getSupportedHeights(): Any = TODO()
    }

    class AudioCapabilities {
        fun isSampleRateSupported(sampleRate: Int): Boolean = TODO()
        fun getMaxInputChannelCount(): Int = TODO()
    }

    class EncoderCapabilities {
        companion object {
            const val BITRATE_MODE_CQ = 0
            const val BITRATE_MODE_VBR = 1
            const val BITRATE_MODE_CBR = 2
        }
    }

    fun getName(): String = TODO()
    fun getCanonicalName(): String = TODO()
    fun isEncoder(): Boolean = TODO()
    fun isHardwareAccelerated(): Boolean = TODO()
    fun isSoftwareOnly(): Boolean = TODO()
    fun getSupportedTypes(): Array<String> = TODO()
    fun getCapabilitiesForType(type: String?): CodecCapabilities = TODO()
}

open class MediaCodecList(kind: Int) {
    companion object {
        const val REGULAR_CODECS = 0
        const val ALL_CODECS = 1

        fun getCodecCount(): Int = TODO()
        fun getCodecInfoAt(index: Int): MediaCodecInfo = TODO()
    }

    fun getCodecInfos(): Array<MediaCodecInfo> = TODO()
    fun findDecoderForFormat(format: MediaFormat?): String = TODO()
    fun findEncoderForFormat(format: MediaFormat?): String = TODO()
}

open class MediaFormat {
    companion object {
        const val KEY_MIME = "mime"
        const val KEY_WIDTH = "width"
        const val KEY_HEIGHT = "height"
        const val KEY_MAX_WIDTH = "max-width"
        const val KEY_MAX_HEIGHT = "max-height"
        const val KEY_CHANNEL_COUNT = "channel-count"
        const val KEY_SAMPLE_RATE = "sample-rate"
        const val KEY_BIT_RATE = "bitrate"
        const val KEY_BITRATE_MODE = "bitrate-mode"
        const val KEY_COLOR_FORMAT = "color-format"
        const val KEY_COLOR_RANGE = "color-range"
        const val KEY_COLOR_STANDARD = "color-standard"
        const val KEY_FRAME_RATE = "frame-rate"
        const val KEY_I_FRAME_INTERVAL = "i-frame-interval"
        const val KEY_STRIDE = "stride"
        const val KEY_SLICE_HEIGHT = "slice-height"
        const val KEY_CROP_LEFT = "crop-left"
        const val KEY_CROP_RIGHT = "crop-right"
        const val KEY_CROP_TOP = "crop-top"
        const val KEY_CROP_BOTTOM = "crop-bottom"

        fun createVideoFormat(mime: String?, width: Int, height: Int): MediaFormat = TODO()
        fun createAudioFormat(mime: String?, sampleRate: Int, channelCount: Int): MediaFormat = TODO()
    }

    fun containsKey(name: String?): Boolean = TODO()
    fun getString(name: String?): String = TODO()
    fun getInteger(name: String?): Int = TODO()
    fun getLong(name: String?): Long = TODO()
    fun getFloat(name: String?): Float = TODO()
    fun getByteBuffer(name: String?): java.nio.ByteBuffer = TODO()
    fun setString(name: String?, value: String?) {}
    fun setInteger(name: String?, value: Int) {}
    fun setLong(name: String?, value: Long) {}
    fun setFloat(name: String?, value: Float) {}
    fun setByteBuffer(name: String?, value: Any?) {}
}

// uuid is java.util.UUID at the call site; typed Any? so this file does not
// depend on whichever group ends up stubbing java.util.
open class MediaCrypto(uuid: Any?, initData: ByteArray?) {
    companion object {
        fun isCryptoSchemeSupported(uuid: Any?): Boolean = TODO()
    }

    fun requiresSecureDecoderComponent(mime: String?): Boolean = TODO()
    fun setMediaDrmSession(sessionId: ByteArray?) {}
    fun release() {}
}

open class MediaDrm(uuid: Any?) {
    companion object {
        const val EVENT_PROVISION_REQUIRED = 1
        const val EVENT_KEY_REQUIRED = 2
        const val EVENT_KEY_EXPIRED = 3
        const val EVENT_VENDOR_DEFINED = 4
        const val EVENT_SESSION_RECLAIMED = 5
        const val KEY_TYPE_STREAMING = 1
        const val KEY_TYPE_OFFLINE = 2
        const val KEY_TYPE_RELEASE = 3
        const val PROPERTY_VENDOR = "vendor"
        const val PROPERTY_VERSION = "version"
        const val PROPERTY_DESCRIPTION = "description"
        const val PROPERTY_ALGORITHMS = "algorithms"
        const val PROPERTY_DEVICE_UNIQUE_ID = "deviceUniqueId"

        fun isCryptoSchemeSupported(uuid: Any?): Boolean = TODO()
        fun isCryptoSchemeSupported(uuid: Any?, mimeType: String?): Boolean = TODO()
    }

    class KeyRequest {
        companion object {
            const val REQUEST_TYPE_INITIAL = 0
            const val REQUEST_TYPE_RENEWAL = 1
            const val REQUEST_TYPE_RELEASE = 2
            const val REQUEST_TYPE_NONE = 3
            const val REQUEST_TYPE_UPDATE = 4
        }

        fun getData(): ByteArray = TODO()
        fun getDefaultUrl(): String = TODO()
        fun getRequestType(): Int = TODO()
    }

    class ProvisionRequest {
        fun getData(): ByteArray = TODO()
        fun getDefaultUrl(): String = TODO()
    }

    class KeyStatus {
        companion object {
            const val KEY_STATUS_USABLE = 0
            const val KEY_STATUS_EXPIRED = 1
            const val KEY_STATUS_OUTPUT_NOT_ALLOWED = 2
            const val KEY_STATUS_PENDING = 3
            const val KEY_STATUS_INTERNAL_ERROR = 4
        }

        fun getKeyId(): ByteArray = TODO()
        fun getStatusCode(): Int = TODO()
    }

    // GeckoMediaDrmBridge implements both of these.
    interface OnEventListener {
        fun onEvent(md: MediaDrm, sessionId: ByteArray, event: Int, extra: Int, data: ByteArray)
    }

    interface OnKeyStatusChangeListener {
        fun onKeyStatusChange(
            md: MediaDrm, sessionId: ByteArray, keyInformation: List<KeyStatus>, hasNewUsableKey: Boolean
        )
    }

    fun openSession(): ByteArray = TODO()
    fun closeSession(sessionId: ByteArray?) {}
    fun getKeyRequest(
        scope: ByteArray?, init: ByteArray?, mimeType: String?, keyType: Int, optionalParameters: Any?
    ): KeyRequest = TODO()
    fun provideKeyResponse(scope: ByteArray?, response: ByteArray?): ByteArray = TODO()
    fun queryKeyStatus(sessionId: ByteArray?): HashMap<String, String> = TODO()
    fun getProvisionRequest(): ProvisionRequest = TODO()
    fun provideProvisionResponse(response: ByteArray?): Any = TODO()
    fun setPropertyString(propertyName: String?, value: String?) {}
    fun setPropertyByteArray(propertyName: String?, value: ByteArray?) {}
    fun getPropertyString(propertyName: String?): String = TODO()
    fun getPropertyByteArray(propertyName: String?): ByteArray = TODO()
    fun setOnEventListener(listener: OnEventListener?) {}
    fun setOnKeyStatusChangeListener(listener: OnKeyStatusChangeListener?, handler: android.os.Handler?) {}
    fun release() {}
}

open class MediaDrmException : Exception()
open class MediaCryptoException : Exception()
open class NotProvisionedException : MediaDrmException()
open class DeniedByServerException : MediaDrmException()
open class ResourceBusyException : MediaDrmException()
open class UnsupportedSchemeException : MediaDrmException()

open class AudioManager {
    companion object {
        const val PROPERTY_OUTPUT_FRAMES_PER_BUFFER = "android.media.property.OUTPUT_FRAMES_PER_BUFFER"
        const val PROPERTY_OUTPUT_SAMPLE_RATE = "android.media.property.OUTPUT_SAMPLE_RATE"
        const val STREAM_VOICE_CALL = 0
        const val STREAM_SYSTEM = 1
        const val STREAM_RING = 2
        const val STREAM_MUSIC = 3
        const val STREAM_ALARM = 4
        const val STREAM_NOTIFICATION = 5
        const val MODE_NORMAL = 0
        const val MODE_RINGTONE = 1
        const val MODE_IN_CALL = 2
        const val MODE_IN_COMMUNICATION = 3
    }

    interface OnAudioFocusChangeListener {
        fun onAudioFocusChange(focusChange: Int)
    }

    fun getProperty(key: String?): String = TODO()
    fun startBluetoothSco() {}
    fun stopBluetoothSco() {}
    fun setBluetoothScoOn(on: Boolean) {}
    fun isBluetoothScoOn(): Boolean = TODO()
    fun setMode(mode: Int) {}
    fun getMode(): Int = TODO()
    fun isMusicActive(): Boolean = TODO()
    fun dispatchMediaKeyEvent(keyEvent: Any?) {}
}
'''

# --------------------------------------------------------------------------
# android.net
# --------------------------------------------------------------------------
NET = r'''
open class Uri {
    companion object {
        val EMPTY: Uri = TODO()
        fun parse(uriString: String?): Uri = TODO()
        fun encode(s: String?): String = TODO()
        fun encode(s: String?, allow: String?): String = TODO()
        fun decode(s: String?): String = TODO()
        fun fromFile(file: Any?): Uri = TODO()
        fun fromParts(scheme: String?, ssp: String?, fragment: String?): Uri = TODO()
        fun withAppendedPath(base: Uri?, pathSegment: String?): Uri = TODO()
    }

    open class Builder {
        fun scheme(scheme: String?): Builder = TODO()
        fun authority(authority: String?): Builder = TODO()
        fun path(path: String?): Builder = TODO()
        fun appendPath(newSegment: String?): Builder = TODO()
        fun query(query: String?): Builder = TODO()
        fun appendQueryParameter(key: String?, value: String?): Builder = TODO()
        fun fragment(fragment: String?): Builder = TODO()
        fun opaquePart(opaquePart: String?): Builder = TODO()
        fun build(): Uri = TODO()
    }

    fun getScheme(): String = TODO()
    fun getSchemeSpecificPart(): String = TODO()
    fun getEncodedSchemeSpecificPart(): String = TODO()
    fun getAuthority(): String = TODO()
    fun getEncodedAuthority(): String = TODO()
    fun getUserInfo(): String = TODO()
    fun getHost(): String = TODO()
    fun getPort(): Int = TODO()
    fun getPath(): String = TODO()
    fun getEncodedPath(): String = TODO()
    fun getQuery(): String = TODO()
    fun getFragment(): String = TODO()
    fun getLastPathSegment(): String = TODO()
    fun getPathSegments(): List<String> = TODO()
    fun getQueryParameter(key: String?): String = TODO()
    fun isHierarchical(): Boolean = TODO()
    fun isOpaque(): Boolean = TODO()
    fun isRelative(): Boolean = TODO()
    fun isAbsolute(): Boolean = TODO()
    fun normalizeScheme(): Uri = TODO()
    fun buildUpon(): Builder = TODO()
}

open class Network

open class LinkProperties {
    fun isPrivateDnsActive(): Boolean = TODO()
    fun getPrivateDnsServerName(): String = TODO()
    fun getDomains(): String = TODO()
    fun getInterfaceName(): String = TODO()
}

open class NetworkInfo {
    enum class State { CONNECTING, CONNECTED, SUSPENDED, DISCONNECTING, DISCONNECTED, UNKNOWN }

    fun isConnected(): Boolean = TODO()
    fun isConnectedOrConnecting(): Boolean = TODO()
    fun isAvailable(): Boolean = TODO()
    fun isRoaming(): Boolean = TODO()
    fun getType(): Int = TODO()
    fun getSubtype(): Int = TODO()
    fun getTypeName(): String = TODO()
    fun getSubtypeName(): String = TODO()
    fun getState(): State = TODO()
    fun getExtraInfo(): String = TODO()
}

open class NetworkCapabilities
open class NetworkRequest

open class ConnectivityManager {
    companion object {
        const val CONNECTIVITY_ACTION = "android.net.conn.CONNECTIVITY_CHANGE"
        const val TYPE_MOBILE = 0
        const val TYPE_WIFI = 1
        const val TYPE_WIMAX = 6
        const val TYPE_BLUETOOTH = 7
        const val TYPE_ETHERNET = 9
        const val RESTRICT_BACKGROUND_STATUS_DISABLED = 1
        const val RESTRICT_BACKGROUND_STATUS_WHITELISTED = 2
        const val RESTRICT_BACKGROUND_STATUS_ENABLED = 3
    }

    // GeckoNetworkManager subclasses this anonymously; keep the members open
    // and the parameters non-null so the codemod's overrides line up.
    open class NetworkCallback {
        open fun onAvailable(network: Network) {}
        open fun onLost(network: Network) {}
        open fun onUnavailable() {}
        open fun onLosing(network: Network, maxMsToLive: Int) {}
        open fun onCapabilitiesChanged(network: Network, caps: NetworkCapabilities) {}
        open fun onLinkPropertiesChanged(network: Network, linkProperties: LinkProperties) {}
        open fun onBlockedStatusChanged(network: Network, blocked: Boolean) {}
    }

    fun getActiveNetworkInfo(): NetworkInfo = TODO()
    fun getNetworkInfo(networkType: Int): NetworkInfo = TODO()
    fun getAllNetworkInfo(): Array<NetworkInfo> = TODO()
    fun getActiveNetwork(): Network = TODO()
    fun getAllNetworks(): Array<Network> = TODO()
    fun getNetworkCapabilities(network: Network?): NetworkCapabilities = TODO()
    fun getLinkProperties(network: Network?): LinkProperties = TODO()
    fun getDefaultProxy(): ProxyInfo = TODO()
    fun isActiveNetworkMetered(): Boolean = TODO()
    fun getRestrictBackgroundStatus(): Int = TODO()
    fun registerDefaultNetworkCallback(cb: NetworkCallback?) {}
    fun registerDefaultNetworkCallback(cb: NetworkCallback?, handler: android.os.Handler?) {}
    fun registerNetworkCallback(request: NetworkRequest?, cb: NetworkCallback?) {}
    fun unregisterNetworkCallback(cb: NetworkCallback?) {}
}

open class Proxy {
    companion object {
        const val PROXY_CHANGE_ACTION = "android.intent.action.PROXY_CHANGE"
        const val EXTRA_PROXY_INFO = "android.intent.extra.PROXY_INFO"
    }
}

open class ProxyInfo {
    fun getHost(): String = TODO()
    fun getPort(): Int = TODO()
    fun getExclusionList(): Array<String> = TODO()
    fun getPacFileUrl(): Uri = TODO()
}

open class DhcpInfo {
    var ipAddress: Int = 0
    var gateway: Int = 0
    var netmask: Int = 0
    var dns1: Int = 0
    var dns2: Int = 0
    var serverAddress: Int = 0
    var leaseDuration: Int = 0
}
'''

NET_WIFI = r'''
open class WifiInfo

open class WifiManager {
    companion object {
        const val WIFI_STATE_DISABLING = 0
        const val WIFI_STATE_DISABLED = 1
        const val WIFI_STATE_ENABLING = 2
        const val WIFI_STATE_ENABLED = 3
        const val WIFI_STATE_UNKNOWN = 4
    }

    open class WifiLock {
        fun acquire() {}
        fun release() {}
        fun isHeld(): Boolean = TODO()
        fun setReferenceCounted(referenceCounted: Boolean) {}
    }

    fun getDhcpInfo(): android.net.DhcpInfo = TODO()
    fun getConnectionInfo(): WifiInfo = TODO()
    fun getWifiState(): Int = TODO()
    fun isWifiEnabled(): Boolean = TODO()
    fun createWifiLock(lockType: Int, tag: String?): WifiLock = TODO()
}
'''

# --------------------------------------------------------------------------
# android.app
# --------------------------------------------------------------------------
APP = r'''
// Activity and Service extend android.content.Context so that GeckoView's
// `context instanceof Activity` / `(Activity) context` keep type-checking.
// This assumes the android.content group emits Context as an open (or
// abstract) class with a no-arg constructor.
open class Activity : android.content.Context() {
    companion object {
        const val RESULT_CANCELED = 0
        const val RESULT_OK = -1
        const val RESULT_FIRST_USER = 1
    }

    fun getWindow(): android.view.Window = TODO()
    fun getIntent(): android.content.Intent = TODO()
    fun getCallingPackage(): String = TODO()
    fun isFinishing(): Boolean = TODO()
    fun isDestroyed(): Boolean = TODO()
    fun isInMultiWindowMode(): Boolean = TODO()
    fun getRequestedOrientation(): Int = TODO()
    fun setRequestedOrientation(orientation: Int) {}
    fun startActionMode(callback: Any?): android.view.ActionMode = TODO()
    fun startActionMode(callback: Any?, type: Int): android.view.ActionMode = TODO()
    fun startActivityForResult(intent: android.content.Intent?, requestCode: Int) {}
    fun runOnUiThread(action: Any?) {}
    fun finish() {}
}

open class Application : android.content.Context() {
    companion object {
        fun getProcessName(): String = TODO()
    }

    interface ActivityLifecycleCallbacks

    open fun onCreate() {}
    open fun onTerminate() {}
    open fun onLowMemory() {}
    open fun onTrimMemory(level: Int) {}
    fun registerActivityLifecycleCallbacks(cb: ActivityLifecycleCallbacks?) {}
    fun unregisterActivityLifecycleCallbacks(cb: ActivityLifecycleCallbacks?) {}
}

// MediaManager, GeckoServiceChildProcess and CrashHelper all extend this.
open class Service : android.content.Context() {
    companion object {
        const val START_STICKY = 1
        const val START_NOT_STICKY = 2
        const val START_REDELIVER_INTENT = 3
        const val STOP_FOREGROUND_REMOVE = 1
    }

    open fun onCreate() {}
    open fun onDestroy() {}
    open fun onBind(intent: android.content.Intent?): android.os.IBinder? = TODO()
    open fun onUnbind(intent: android.content.Intent?): Boolean = TODO()
    open fun onRebind(intent: android.content.Intent?) {}
    open fun onStartCommand(intent: android.content.Intent?, flags: Int, startId: Int): Int = TODO()
    open fun onTaskRemoved(rootIntent: android.content.Intent?) {}
    fun stopSelf() {}
    fun stopSelf(startId: Int) {}
    fun stopSelfResult(startId: Int): Boolean = TODO()
    fun startForeground(id: Int, notification: Notification?) {}
    fun startForeground(id: Int, notification: Notification?, foregroundServiceType: Int) {}
    fun stopForeground(remove: Boolean) {}
}

open class ActivityManager {
    class MemoryInfo {
        var availMem: Long = 0L
        var totalMem: Long = 0L
        var threshold: Long = 0L
        var lowMemory: Boolean = false
    }

    class RunningAppProcessInfo {
        companion object {
            const val IMPORTANCE_FOREGROUND = 100
            const val IMPORTANCE_VISIBLE = 200
            const val IMPORTANCE_SERVICE = 300
            const val IMPORTANCE_CACHED = 400
            const val IMPORTANCE_GONE = 1000
        }

        var pid: Int = 0
        var uid: Int = 0
        var importance: Int = 0
        var processName: String = ""
    }

    fun getMemoryInfo(outInfo: MemoryInfo?) {}
    fun getRunningAppProcesses(): List<RunningAppProcessInfo> = TODO()
    fun isLowRamDevice(): Boolean = TODO()
    fun isBackgroundRestricted(): Boolean = TODO()
    fun getMemoryClass(): Int = TODO()
    fun getLargeMemoryClass(): Int = TODO()
}

open class UiModeManager {
    companion object {
        const val MODE_NIGHT_AUTO = 0
        const val MODE_NIGHT_NO = 1
        const val MODE_NIGHT_YES = 2
    }

    // GeckoSystemStateListener implements this anonymously.
    interface ContrastChangeListener {
        fun onContrastChanged(contrast: Float)
    }

    fun getCurrentModeType(): Int = TODO()
    fun getNightMode(): Int = TODO()
    fun getContrast(): Float = TODO()
    fun addContrastChangeListener(executor: Any?, listener: ContrastChangeListener?) {}
    fun removeContrastChangeListener(listener: ContrastChangeListener?) {}
}

open class PendingIntent {
    companion object {
        const val FLAG_ONE_SHOT = 1073741824
        const val FLAG_NO_CREATE = 536870912
        const val FLAG_CANCEL_CURRENT = 268435456
        const val FLAG_UPDATE_CURRENT = 134217728
        const val FLAG_IMMUTABLE = 67108864
        const val FLAG_MUTABLE = 33554432

        fun getActivity(context: Any?, requestCode: Int, intent: Any?, flags: Int): PendingIntent = TODO()
        fun getBroadcast(context: Any?, requestCode: Int, intent: Any?, flags: Int): PendingIntent = TODO()
        fun getService(context: Any?, requestCode: Int, intent: Any?, flags: Int): PendingIntent = TODO()
        fun getForegroundService(context: Any?, requestCode: Int, intent: Any?, flags: Int): PendingIntent = TODO()
    }

    open class CanceledException : Exception()

    fun send() {}
    fun send(context: Any?, code: Int, intent: Any?) {}
    fun cancel() {}
    fun getIntentSender(): Any = TODO()
    fun getCreatorPackage(): String = TODO()
    fun getCreatorUid(): Int = TODO()
}

open class Notification {
    var actions: Array<Action> = arrayOf()
    var flags: Int = 0

    class Action

    open class Builder(context: Any?, channelId: String?) {
        fun build(): Notification = TODO()
    }
}

open class NotificationChannel(id: String?, name: CharSequence?, importance: Int)

open class NotificationManager {
    fun notify(id: Int, notification: Notification?) {}
    fun cancel(id: Int) {}
    fun createNotificationChannel(channel: NotificationChannel?) {}
}

open class Dialog

open class ServiceStartNotAllowedException : IllegalStateException()

// CrashHandler does `e instanceof ForegroundServiceStartNotAllowedException`
// on an IllegalStateException, so the hierarchy below IllegalStateException
// has to be real.
open class ForegroundServiceStartNotAllowedException : ServiceStartNotAllowedException()

// org.mozilla.gecko.process.ZygotePreload implements this.
interface ZygotePreload {
    fun doPreload(applicationInfo: android.content.pm.ApplicationInfo)
}
'''

APP_JOB = r'''
open class JobInfo {
    open class Builder(jobId: Int, jobService: Any?) {
        fun build(): JobInfo = TODO()
    }
}

open class JobParameters {
    fun getJobId(): Int = TODO()
}

open class JobScheduler {
    fun schedule(job: JobInfo?): Int = TODO()
    fun cancel(jobId: Int) {}
    fun cancelAll() {}
}
'''

# --------------------------------------------------------------------------
# android.hardware
# --------------------------------------------------------------------------
HARDWARE = r'''
open class Sensor {
    companion object {
        const val TYPE_ACCELEROMETER = 1
        const val TYPE_MAGNETIC_FIELD = 2
        const val TYPE_ORIENTATION = 3
        const val TYPE_GYROSCOPE = 4
        const val TYPE_LIGHT = 5
        const val TYPE_PRESSURE = 6
        const val TYPE_TEMPERATURE = 7
        const val TYPE_PROXIMITY = 8
        const val TYPE_GRAVITY = 9
        const val TYPE_LINEAR_ACCELERATION = 10
        const val TYPE_ROTATION_VECTOR = 11
        const val TYPE_RELATIVE_HUMIDITY = 12
        const val TYPE_AMBIENT_TEMPERATURE = 13
        const val TYPE_MAGNETIC_FIELD_UNCALIBRATED = 14
        const val TYPE_GAME_ROTATION_VECTOR = 15
        const val TYPE_GYROSCOPE_UNCALIBRATED = 16
        const val TYPE_SIGNIFICANT_MOTION = 17
        const val TYPE_STEP_DETECTOR = 18
        const val TYPE_STEP_COUNTER = 19
        const val TYPE_GEOMAGNETIC_ROTATION_VECTOR = 20
        const val TYPE_ALL = -1
    }

    fun getType(): Int = TODO()
    fun getName(): String = TODO()
    fun getVendor(): String = TODO()
    fun getVersion(): Int = TODO()
    fun getMaximumRange(): Float = TODO()
    fun getResolution(): Float = TODO()
    fun getPower(): Float = TODO()
    fun getMinDelay(): Int = TODO()
}

open class SensorEvent {
    var values: FloatArray = floatArrayOf()
    var sensor: Sensor = TODO()
    var accuracy: Int = 0
    var timestamp: Long = 0L
}

// GeckoSensor.SensorListeners implements this.
interface SensorEventListener {
    fun onSensorChanged(event: SensorEvent)
    fun onAccuracyChanged(sensor: Sensor, accuracy: Int)
}

open class SensorManager {
    companion object {
        const val SENSOR_DELAY_FASTEST = 0
        const val SENSOR_DELAY_GAME = 1
        const val SENSOR_DELAY_UI = 2
        const val SENSOR_DELAY_NORMAL = 3
        const val GRAVITY_EARTH = 9.80665f
    }

    fun getDefaultSensor(type: Int): Sensor = TODO()
    fun getSensorList(type: Int): List<Sensor> = TODO()
    fun registerListener(listener: SensorEventListener?, sensor: Sensor?, samplingPeriodUs: Int): Boolean = TODO()
    fun registerListener(
        listener: SensorEventListener?, sensor: Sensor?, samplingPeriodUs: Int, handler: android.os.Handler?
    ): Boolean = TODO()
    fun unregisterListener(listener: SensorEventListener?) {}
    fun unregisterListener(listener: SensorEventListener?, sensor: Sensor?) {}
}
'''

HARDWARE_DISPLAY = r'''
open class DisplayManager {
    companion object {
        const val VIRTUAL_DISPLAY_FLAG_PUBLIC = 1
        const val VIRTUAL_DISPLAY_FLAG_PRESENTATION = 2
        const val DISPLAY_CATEGORY_PRESENTATION = "android.hardware.display.category.PRESENTATION"
    }

    // GeckoScreenChangeListener implements this.
    interface DisplayListener {
        fun onDisplayAdded(displayId: Int)
        fun onDisplayRemoved(displayId: Int)
        fun onDisplayChanged(displayId: Int)
    }

    fun getDisplay(displayId: Int): android.view.Display = TODO()
    fun getDisplays(): Array<android.view.Display> = TODO()
    fun getDisplays(category: String?): Array<android.view.Display> = TODO()
    fun registerDisplayListener(listener: DisplayListener?, handler: android.os.Handler?) {}
    fun unregisterDisplayListener(listener: DisplayListener?) {}
}
'''

HARDWARE_INPUT = r'''
open class InputManager {
    // AndroidGamepadManager and GeckoSystemStateListener implement this.
    interface InputDeviceListener {
        fun onInputDeviceAdded(deviceId: Int)
        fun onInputDeviceRemoved(deviceId: Int)
        fun onInputDeviceChanged(deviceId: Int)
    }

    fun getInputDeviceIds(): IntArray = TODO()
    fun getInputDevice(id: Int): Any = TODO()
    fun registerInputDeviceListener(listener: InputDeviceListener?, handler: android.os.Handler?) {}
    fun unregisterInputDeviceListener(listener: InputDeviceListener?) {}
}
'''

# --------------------------------------------------------------------------
# android.location
# --------------------------------------------------------------------------
LOCATION = r'''
open class Criteria {
    companion object {
        const val NO_REQUIREMENT = 0
        const val ACCURACY_FINE = 1
        const val ACCURACY_COARSE = 2
        const val ACCURACY_LOW = 1
        const val ACCURACY_MEDIUM = 2
        const val ACCURACY_HIGH = 3
        const val POWER_LOW = 1
        const val POWER_MEDIUM = 2
        const val POWER_HIGH = 3
    }

    fun setAccuracy(accuracy: Int) {}
    fun setAltitudeRequired(required: Boolean) {}
    fun setBearingRequired(required: Boolean) {}
    fun setSpeedRequired(required: Boolean) {}
    fun setCostAllowed(allowed: Boolean) {}
    fun setPowerRequirement(level: Int) {}
}

open class Location {
    fun getLatitude(): Double = TODO()
    fun getLongitude(): Double = TODO()
    fun getAltitude(): Double = TODO()
    fun getAccuracy(): Float = TODO()
    fun getVerticalAccuracyMeters(): Float = TODO()
    fun getSpeed(): Float = TODO()
    fun getBearing(): Float = TODO()
    fun getTime(): Long = TODO()
    fun getElapsedRealtimeNanos(): Long = TODO()
    fun getProvider(): String = TODO()
    fun hasAltitude(): Boolean = TODO()
    fun hasAccuracy(): Boolean = TODO()
    fun hasVerticalAccuracy(): Boolean = TODO()
    fun hasSpeed(): Boolean = TODO()
    fun hasBearing(): Boolean = TODO()
}

// GeckoAppShell.AndroidListeners implements this.
interface LocationListener {
    fun onLocationChanged(location: Location)
    fun onProviderDisabled(provider: String)
    fun onProviderEnabled(provider: String)
    fun onStatusChanged(provider: String, status: Int, extras: android.os.Bundle)
}

open class LocationManager {
    companion object {
        const val GPS_PROVIDER = "gps"
        const val NETWORK_PROVIDER = "network"
        const val PASSIVE_PROVIDER = "passive"
        const val FUSED_PROVIDER = "fused"
    }

    fun getAllProviders(): List<String> = TODO()
    fun getProviders(enabledOnly: Boolean): List<String> = TODO()
    fun getBestProvider(criteria: Criteria?, enabledOnly: Boolean): String = TODO()
    fun getLastKnownLocation(provider: String?): Location = TODO()
    fun isProviderEnabled(provider: String?): Boolean = TODO()
    fun requestLocationUpdates(
        provider: String?, minTimeMs: Long, minDistanceM: Float, listener: LocationListener?
    ) {}
    fun requestLocationUpdates(
        provider: String?, minTimeMs: Long, minDistanceM: Float,
        listener: LocationListener?, looper: android.os.Looper?
    ) {}
    fun removeUpdates(listener: LocationListener?) {}
}
'''

# --------------------------------------------------------------------------
# android.security
# --------------------------------------------------------------------------
SECURITY = r'''
open class KeyChainException : Exception {
    constructor() : super()
    constructor(message: String?) : super(message)
    constructor(message: String?, cause: Throwable?) : super(message, cause)
    constructor(cause: Throwable?) : super(cause)
}

open class KeyChain {
    companion object {
        const val ACTION_KEYCHAIN_CHANGED = "android.security.action.KEYCHAIN_CHANGED"
        const val ACTION_KEY_ACCESS_CHANGED = "android.security.action.KEY_ACCESS_CHANGED"
        const val ACTION_STORAGE_CHANGED = "android.security.STORAGE_CHANGED"
        const val ACTION_TRUST_STORE_CHANGED = "android.security.action.TRUST_STORE_CHANGED"
        const val EXTRA_CERTIFICATE = "CERT"
        const val EXTRA_KEY_ALIAS = "android.security.extra.KEY_ALIAS"
        const val EXTRA_NAME = "name"
        const val EXTRA_PKCS12 = "PKCS12"

        // Return types stay the real java.security ones: ClientAuthCertificateManager
        // assigns them to X509Certificate[] / PrivateKey.
        fun getCertificateChain(context: Any?, alias: String?): Array<java.security.cert.X509Certificate> = TODO()
        fun getPrivateKey(context: Any?, alias: String?): java.security.PrivateKey = TODO()
        fun choosePrivateKeyAlias(
            activity: Any?, response: Any?, keyTypes: Array<String>?, issuers: Any?,
            uri: Any?, alias: String?
        ) {}
    }
}
'''

# --------------------------------------------------------------------------
# android.system  (no ATL counterpart -- hand-written from CrashHelper.java)
# --------------------------------------------------------------------------
SYSTEM = r'''
open class ErrnoException : Exception {
    var errno: Int = 0
    constructor() : super()
    constructor(functionName: String?, errno: Int) : super(functionName)
}

// Constants are the Linux/bionic values; nothing here is executed.
object OsConstants {
    const val AF_UNIX = 1
    const val AF_INET = 2
    const val AF_INET6 = 10
    const val SOCK_STREAM = 1
    const val SOCK_DGRAM = 2
    const val SOCK_SEQPACKET = 5
    const val SOL_SOCKET = 1
    const val SO_PASSCRED = 16
    const val SO_REUSEADDR = 2
    const val SO_SNDBUF = 7
    const val SO_RCVBUF = 8
    const val O_RDONLY = 0
    const val O_WRONLY = 1
    const val O_RDWR = 2
    const val O_CREAT = 64
    const val EINTR = 4
    const val EAGAIN = 11
    const val EBADF = 9
    const val EPIPE = 32
}

object Os {
    fun socketpair(domain: Int, type: Int, protocol: Int, fd1: Any?, fd2: Any?) {}
    fun setsockoptInt(fd: Any?, level: Int, option: Int, value: Int) {}
    fun getsockoptInt(fd: Any?, level: Int, option: Int): Int = TODO()
    fun close(fd: Any?) {}
    fun dup(fd: Any?): Any = TODO()
    fun pipe(): Any = TODO()
    fun read(fd: Any?, bytes: ByteArray?, byteOffset: Int, byteCount: Int): Int = TODO()
    fun write(fd: Any?, bytes: ByteArray?, byteOffset: Int, byteCount: Int): Int = TODO()
    fun getpid(): Int = TODO()
    fun getuid(): Int = TODO()
    fun setenv(name: String?, value: String?, overwrite: Boolean) {}
    fun getenv(name: String?): String = TODO()
}
'''

# --------------------------------------------------------------------------
# android.credentials
# --------------------------------------------------------------------------
CREDENTIALS = r'''
open class Credential {
    companion object {
        const val TYPE_PASSWORD_CREDENTIAL = "android.credentials.TYPE_PASSWORD_CREDENTIAL"
    }

    fun getType(): String = TODO()
    fun getData(): android.os.Bundle = TODO()
}

open class CredentialOption {
    companion object {
        const val SUPPORTED_ELEMENT_KEYS = "android.credentials.GetCredentialOption.SUPPORTED_ELEMENT_KEYS"
    }

    open class Builder(type: String?, credentialRetrievalData: android.os.Bundle?, candidateQueryData: android.os.Bundle?) {
        fun setIsSystemProviderRequired(required: Boolean): Builder = TODO()
        fun setAllowedProviders(providers: Any?): Builder = TODO()
        fun build(): CredentialOption = TODO()
    }
}

open class CreateCredentialRequest {
    open class Builder(type: String?, credentialData: android.os.Bundle?, candidateQueryData: android.os.Bundle?) {
        fun setAlwaysSendAppInfoToProvider(value: Boolean): Builder = TODO()
        fun setIsSystemProviderRequired(value: Boolean): Builder = TODO()
        fun setOrigin(origin: String?): Builder = TODO()
        fun build(): CreateCredentialRequest = TODO()
    }

    fun getType(): String = TODO()
    fun getOrigin(): String = TODO()
}

open class CreateCredentialResponse {
    fun getData(): android.os.Bundle = TODO()
}

open class CreateCredentialException : Exception {
    companion object {
        const val TYPE_UNKNOWN = "android.credentials.CreateCredentialException.TYPE_UNKNOWN"
        const val TYPE_NO_CREATE_OPTIONS = "android.credentials.CreateCredentialException.TYPE_NO_CREATE_OPTIONS"
        const val TYPE_INTERRUPTED = "android.credentials.CreateCredentialException.TYPE_INTERRUPTED"
        const val TYPE_USER_CANCELED = "android.credentials.CreateCredentialException.TYPE_USER_CANCELED"
    }

    constructor() : super()
    constructor(type: String?, message: String?) : super(message)

    fun getType(): String = TODO()
}

open class GetCredentialRequest {
    open class Builder(data: android.os.Bundle?) {
        fun addCredentialOption(option: CredentialOption?): Builder = TODO()
        fun setCredentialOptions(options: Any?): Builder = TODO()
        fun setAlwaysSendAppInfoToProvider(value: Boolean): Builder = TODO()
        fun setOrigin(origin: String?): Builder = TODO()
        fun build(): GetCredentialRequest = TODO()
    }

    fun getOrigin(): String = TODO()
    fun getData(): android.os.Bundle = TODO()
}

open class GetCredentialResponse {
    fun getCredential(): Credential = TODO()
}

open class GetCredentialException : Exception {
    companion object {
        const val TYPE_UNKNOWN = "android.credentials.GetCredentialException.TYPE_UNKNOWN"
        const val TYPE_NO_CREDENTIAL = "android.credentials.GetCredentialException.TYPE_NO_CREDENTIAL"
        const val TYPE_INTERRUPTED = "android.credentials.GetCredentialException.TYPE_INTERRUPTED"
        const val TYPE_USER_CANCELED = "android.credentials.GetCredentialException.TYPE_USER_CANCELED"
    }

    constructor() : super()
    constructor(type: String?, message: String?) : super(message)

    fun getType(): String = TODO()
}

open class PrepareGetCredentialResponse {
    class PendingGetCredentialHandle

    fun hasCredentialResults(credentialType: String?): Boolean = TODO()
    fun hasAuthenticationResults(): Boolean = TODO()
    fun hasRemoteResults(): Boolean = TODO()
    fun getPendingGetCredentialHandle(): PendingGetCredentialHandle = TODO()
}

// getSystemService(Context.CREDENTIAL_SERVICE) is cast to this.
open class CredentialManager {
    fun createCredential(
        context: Any?, request: CreateCredentialRequest?, cancellationSignal: Any?,
        executor: Any?, callback: Any?
    ) {}
    fun getCredential(
        context: Any?, request: GetCredentialRequest?, cancellationSignal: Any?,
        executor: Any?, callback: Any?
    ) {}
    fun getCredential(
        context: Any?, pendingHandle: PrepareGetCredentialResponse.PendingGetCredentialHandle?,
        cancellationSignal: Any?, executor: Any?, callback: Any?
    ) {}
    fun prepareGetCredential(
        request: GetCredentialRequest?, cancellationSignal: Any?, executor: Any?, callback: Any?
    ) {}
    fun clearCredentialState(request: Any?, cancellationSignal: Any?, executor: Any?, callback: Any?) {}
}
'''

# --------------------------------------------------------------------------
# android.annotation
# --------------------------------------------------------------------------
ANNOTATION = r'''
private const val ANY_TARGET_NOTE = "@SuppressLint lands on classes, members, params and locals in GeckoView"

@Retention(AnnotationRetention.SOURCE)
@Target(
    AnnotationTarget.CLASS, AnnotationTarget.ANNOTATION_CLASS, AnnotationTarget.TYPE_PARAMETER,
    AnnotationTarget.PROPERTY, AnnotationTarget.FIELD, AnnotationTarget.LOCAL_VARIABLE,
    AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.CONSTRUCTOR, AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER, AnnotationTarget.TYPE,
    AnnotationTarget.EXPRESSION, AnnotationTarget.FILE, AnnotationTarget.TYPEALIAS
)
annotation class SuppressLint(vararg val value: String)

@Retention(AnnotationRetention.SOURCE)
@Target(
    AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY, AnnotationTarget.LOCAL_VARIABLE, AnnotationTarget.TYPE
)
annotation class NonNull

@Retention(AnnotationRetention.SOURCE)
@Target(
    AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY, AnnotationTarget.LOCAL_VARIABLE, AnnotationTarget.TYPE
)
annotation class Nullable

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)
annotation class ColorInt

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)
annotation class DrawableRes

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)
annotation class AttrRes

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)
annotation class Px

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.ANNOTATION_CLASS)
annotation class IntDef(vararg val value: Long, val flag: Boolean = false)

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)
annotation class IntRange(val from: Long = Long.MIN_VALUE, val to: Long = Long.MAX_VALUE)

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)
annotation class FloatRange(val from: Double = -3.4e38, val to: Double = 3.4e38)
'''

# file stem -> (package, body).  media-net.kt is the anchor the brief named.
FILES = [
    ("media-net",                  "android.media",           MEDIA),
    ("media-net-net",              "android.net",             NET),
    ("media-net-net-wifi",         "android.net.wifi",        NET_WIFI),
    ("media-net-app",              "android.app",             APP),
    ("media-net-app-job",          "android.app.job",         APP_JOB),
    ("media-net-hardware",         "android.hardware",        HARDWARE),
    ("media-net-hardware-display", "android.hardware.display", HARDWARE_DISPLAY),
    ("media-net-hardware-input",   "android.hardware.input",  HARDWARE_INPUT),
    ("media-net-location",         "android.location",        LOCATION),
    ("media-net-security",         "android.security",        SECURITY),
    ("media-net-system",           "android.system",          SYSTEM),
    ("media-net-credentials",      "android.credentials",     CREDENTIALS),
    ("media-net-annotation",       "android.annotation",      ANNOTATION),
]

# Placeholders for types owned by the OTHER stub groups (and by whoever ends up
# stubbing java.*).  Only used by --selfcheck so this slice can be compiled on
# its own before the rest of the tree exists.
SELFCHECK_EXTERNALS = r'''// throwaway placeholders for types owned by other groups; --selfcheck only
package android.content
open class Context
open class Intent
'''
SELFCHECK_EXTERNALS2 = r'''package android.content.pm
open class ApplicationInfo
'''
SELFCHECK_EXTERNALS3 = r'''package android.os
open class Bundle
open class Handler
open class Looper
interface IBinder
'''
SELFCHECK_EXTERNALS4 = r'''package android.view
open class Surface
open class Display
open class Window
open class ActionMode
'''
SELFCHECK_EXTERNALS5 = r'''package java.nio
open class ByteBuffer
'''
SELFCHECK_EXTERNALS6 = r'''package java.security
interface PrivateKey
'''
SELFCHECK_EXTERNALS7 = r'''package java.security.cert
open class X509Certificate
'''


def write_stubs():
    os.makedirs(OUT, exist_ok=True)
    written = []
    for stem, pkg, body in FILES:
        path = os.path.join(OUT, stem + ".kt")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HDR)
            fh.write("package %s\n" % pkg)
            fh.write(body)
            if not body.endswith("\n"):
                fh.write("\n")
        written.append(path)
    return written


def write_selfcheck(tmpdir, paths):
    import shutil
    if os.path.isdir(tmpdir):
        shutil.rmtree(tmpdir)
    os.makedirs(tmpdir, exist_ok=True)
    for p in paths:
        shutil.copy(p, tmpdir)
    for i, blob in enumerate([SELFCHECK_EXTERNALS, SELFCHECK_EXTERNALS2,
                              SELFCHECK_EXTERNALS3, SELFCHECK_EXTERNALS4,
                              SELFCHECK_EXTERNALS5, SELFCHECK_EXTERNALS6,
                              SELFCHECK_EXTERNALS7]):
        with open(os.path.join(tmpdir, "ext%d.kt" % i), "w", encoding="utf-8") as fh:
            fh.write(blob)
    return tmpdir


# --------------------------------------------------------------------------
# coverage check: re-scrape the GeckoView sources and report any member that
# the call sites mention but the emitted stubs do not declare.
# --------------------------------------------------------------------------
MY_TYPES = set("""
MediaCodec MediaCodecInfo MediaCodecList MediaFormat MediaCrypto MediaDrm
MediaDrmException MediaCryptoException NotProvisionedException
DeniedByServerException ResourceBusyException UnsupportedSchemeException
AudioManager CodecCapabilities CodecProfileLevel VideoCapabilities BufferInfo
CryptoInfo KeyRequest KeyStatus ProvisionRequest
Uri Network NetworkInfo LinkProperties ConnectivityManager Proxy ProxyInfo
DhcpInfo WifiManager
Activity Application Service ActivityManager UiModeManager PendingIntent
Notification ForegroundServiceStartNotAllowedException ZygotePreload
JobScheduler Dialog MemoryInfo RunningAppProcessInfo
Sensor SensorEvent SensorEventListener SensorManager DisplayManager
InputManager
Criteria Location LocationListener LocationManager
KeyChain KeyChainException
Os OsConstants ErrnoException
Credential CredentialOption CredentialManager CreateCredentialRequest
CreateCredentialResponse CreateCredentialException GetCredentialRequest
GetCredentialResponse GetCredentialException PrepareGetCredentialResponse
SuppressLint
""".split())


def coverage(emitted_text):
    try:
        import javalang
    except ImportError:
        print("javalang not importable -- skipping coverage check", file=sys.stderr)
        return
    hits = collections.defaultdict(set)
    parsefails = []
    for root, _dirs, files in os.walk(SRC):
        for f in files:
            if not f.endswith(".java"):
                continue
            path = os.path.join(root, f)
            src = open(path, encoding="utf-8", errors="replace").read()
            try:
                tree = javalang.parse.parse(src)
            except Exception as e:
                parsefails.append((path, str(e)))
                continue
            env = {}
            for _p, node in tree:
                if isinstance(node, (javalang.tree.LocalVariableDeclaration,
                                     javalang.tree.FieldDeclaration,
                                     javalang.tree.FormalParameter)):
                    tn = getattr(node.type, "name", None)
                    if tn in MY_TYPES:
                        for d in (getattr(node, "declarators", None) or []):
                            env[d.name] = tn
                        if getattr(node, "name", None):
                            env[node.name] = tn
                if isinstance(node, javalang.tree.MethodInvocation):
                    q = node.qualifier
                    if q in MY_TYPES:
                        hits[q].add(node.member)
                    elif q and q.split(".")[0] in MY_TYPES:
                        hits[q.split(".")[0]].add(node.member)
                    elif q and q.split(".")[0] in env:
                        hits[env[q.split(".")[0]]].add(node.member)
                if isinstance(node, javalang.tree.MemberReference):
                    q = node.qualifier
                    if q in MY_TYPES:
                        hits[q].add(node.member)
                    elif q and q.split(".")[0] in MY_TYPES:
                        hits[q.split(".")[0]].add(node.member)
                    elif q and q.split(".")[0] in env:
                        hits[env[q.split(".")[0]]].add(node.member)

    missing = collections.defaultdict(list)
    for t, members in sorted(hits.items()):
        for m in sorted(members):
            if not re.search(r"\b%s\b" % re.escape(m), emitted_text):
                missing[t].append(m)

    total = sum(len(v) for v in hits.values())
    miss = sum(len(v) for v in missing.values())
    print("coverage: %d/%d scraped members present in the emitted stubs"
          % (total - miss, total))
    for t, ms in sorted(missing.items()):
        print("  UNCOVERED %-28s %s" % (t, ", ".join(ms)))
    for p, e in parsefails:
        print("  PARSEFAIL %s: %s" % (p, e))
    print("types recovered from the ATL Java impl: %d" % len(RECOVERED_FROM_ATL))
    print("types with no ATL counterpart (hand-written): %s" % ", ".join(NOT_IN_ATL))


if __name__ == "__main__":
    paths = write_stubs()
    for p in paths:
        print("wrote %s" % p)
    if "--selfcheck" in sys.argv:
        d = write_selfcheck("/tmp/media-net-selfcheck", paths)
        print("selfcheck tree (my stubs + throwaway externals) in %s" % d)
    if "--check" in sys.argv:
        text = "".join(open(p, encoding="utf-8").read() for p in paths)
        coverage(text)
