#!/usr/bin/env python3
"""Generate android.os Kotlin/Native stubs for the transpiled GeckoView.

Two halves:
  1. scrape()  - walks the GeckoView Java with tree-sitter, collects every
                 android.os member GeckoView actually touches (constructors,
                 instance/static calls, field reads, supertypes).
  2. TEMPLATES - hand-written Kotlin per type, signatures taken from ATL's
                 real android.* reimplementation at atlas/src/api-impl/android/os.

The scrape does not write the Kotlin; it audits it. Anything GeckoView uses
that the template does not declare is printed as DRIFT, which is what makes
this re-runnable against a newer mozilla-central.

Run:  python3 stubgen/os.py [--check] [--java-deps /tmp/javadeps.kt]
"""
import argparse, collections, os, sys

GV = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview/src/main/java"
OUT = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview-kn/src/stubs/os.kt"

# Types ATL gave us a real signature for; the rest were derived from call sites only.
FROM_ATL = set("""AsyncTask BatteryManager Binder Build Bundle BaseBundle CancellationSignal Debug
DeadObjectException Environment Handler HandlerThread IBinder IInterface LocaleList Looper MemoryFile
Message MessageQueue OutcomeReceiver Parcel ParcelFileDescriptor ParcelFormatException Parcelable
PersistableBundle PowerManager Process RemoteException SystemClock TransactionTooLargeException
UserHandle UserManager Vibrator""".split())

# ---------------------------------------------------------------- scrape

def scrape(root=GV):
    import tree_sitter_java as tsj
    from tree_sitter import Language, Parser
    P = Parser(Language(tsj.language()))
    known = FROM_ATL | {"Messenger", "ResultReceiver", "StrictMode", "Trace", "ConditionVariable"}
    use = collections.defaultdict(set)

    def txt(n, s): return s[n.start_byte:n.end_byte].decode("utf8", "replace")
    def walk(n):
        yield n
        for c in n.children: yield from walk(c)

    for dp, _, fns in os.walk(root):
        for fn in fns:
            if not fn.endswith(".java"): continue
            src = open(os.path.join(dp, fn), "rb").read()
            root_node = P.parse(src).root_node
            env = {}
            for n in walk(root_node):
                if n.type in ("local_variable_declaration", "field_declaration", "formal_parameter"):
                    t = n.child_by_field_name("type")
                    if t is None: continue
                    base = txt(t, src).split("<")[0].split("[")[0].strip().split(".")[-1]
                    if base not in known: continue
                    nm = n.child_by_field_name("name")
                    if nm is not None:
                        env[txt(nm, src)] = base
                    for d in n.children:
                        if d.type == "variable_declarator":
                            dn = d.child_by_field_name("name")
                            if dn is not None: env[txt(dn, src)] = base
            for n in walk(root_node):
                k = n.type
                if k == "method_invocation":
                    o, nm = n.child_by_field_name("object"), n.child_by_field_name("name")
                    if o is None or nm is None: continue
                    ot = txt(o, src)
                    base = env.get(ot) or (ot.split(".")[-1] if ot.split(".")[-1] in known else None)
                    if base: use[base].add(txt(nm, src))
                elif k == "field_access":
                    o, f = n.child_by_field_name("object"), n.child_by_field_name("field")
                    if o is None or f is None: continue
                    ot = txt(o, src)
                    base = env.get(ot) or (ot.split(".")[-1] if ot.split(".")[-1] in known else None)
                    if base: use[base].add(txt(f, src))
                elif k == "object_creation_expression":
                    t = n.child_by_field_name("type")
                    if t is None: continue
                    base = txt(t, src).split("<")[0].strip().split(".")[-1]
                    if base in known: use[base].add("<init>")
    return use

# ---------------------------------------------------------------- templates

HEADER = """// GENERATED by kn-run/stubgen/os.py -- do not edit by hand.
// android.os stubs for the Kotlin/Native GeckoView port.
// Signatures follow ATL's android.* reimplementation (atlas/src/api-impl/android/os);
// every body is TODO(). There is no JVM here, so nothing is meant to run.
@file:Suppress("UNUSED_PARAMETER", "unused")
"""

# Each entry: (kotlin package, source text).
TEMPLATES = []
def T(src): TEMPLATES.append(src)

T("""
// ---------------------------------------------------------------- Parcel / Parcelable

interface Parcelable {
    fun describeContents(): Int = 0
    fun writeToParcel(dest: Parcel, flags: Int) {}

    interface Creator<T> {
        fun createFromParcel(source: Parcel): T
        fun newArray(size: Int): Array<T>
    }
    interface ClassLoaderCreator<T> : Creator<T>

    companion object {
        const val PARCELABLE_WRITE_RETURN_VALUE: Int = 1
        const val CONTENTS_FILE_DESCRIPTOR: Int = 1
    }
}

open class ParcelFormatException(message: String? = null) : RuntimeException(message)

open class Parcel protected constructor() {
    companion object {
        fun obtain(): Parcel = TODO()
    }
    open fun recycle(): Unit = TODO()
    open fun dataPosition(): Int = TODO()
    open fun setDataPosition(pos: Int): Unit = TODO()
    open fun dataSize(): Int = TODO()
    open fun dataCapacity(): Int = TODO()
    open fun capacity(): Int = TODO()
    open fun isDirect(): Boolean = TODO()

    open fun writeByte(value: Byte): Unit = TODO()
    open fun readByte(): Byte = TODO()
    open fun writeInt(value: Int): Unit = TODO()
    open fun readInt(): Int = TODO()
    open fun writeShort(value: Short): Unit = TODO()
    open fun readShort(): Short = TODO()
    open fun writeLong(value: Long): Unit = TODO()
    open fun readLong(): Long = TODO()
    open fun writeFloat(value: Float): Unit = TODO()
    open fun readFloat(): Float = TODO()
    open fun writeDouble(value: Double): Unit = TODO()
    open fun readDouble(): Double = TODO()
    open fun writeBoolean(value: Boolean): Unit = TODO()
    open fun readBoolean(): Boolean = TODO()
    open fun writeString(value: String?): Unit = TODO()
    open fun readString(): String = TODO()

    open fun writeIntArray(value: IntArray?): Unit = TODO()
    open fun readIntArray(value: IntArray): Unit = TODO()
    open fun createIntArray(): IntArray = TODO()
    open fun writeLongArray(value: LongArray?): Unit = TODO()
    open fun readLongArray(value: LongArray): Unit = TODO()
    open fun createLongArray(): LongArray = TODO()
    open fun writeByteArray(value: ByteArray?): Unit = TODO()
    open fun writeByteArray(value: ByteArray?, offset: Int, length: Int): Unit = TODO()
    open fun readByteArray(value: ByteArray): Unit = TODO()
    open fun createByteArray(): ByteArray = TODO()
    open fun writeCharArray(value: CharArray?): Unit = TODO()
    open fun readCharArray(value: CharArray): Unit = TODO()
    open fun createCharArray(): CharArray = TODO()
    open fun writeBooleanArray(value: BooleanArray?): Unit = TODO()
    open fun readBooleanArray(value: BooleanArray): Unit = TODO()
    open fun createBooleanArray(): BooleanArray = TODO()
    open fun writeFloatArray(value: FloatArray?): Unit = TODO()
    open fun readFloatArray(value: FloatArray): Unit = TODO()
    open fun createFloatArray(): FloatArray = TODO()
    open fun writeDoubleArray(value: DoubleArray?): Unit = TODO()
    open fun readDoubleArray(value: DoubleArray): Unit = TODO()
    open fun createDoubleArray(): DoubleArray = TODO()
    open fun writeStringArray(value: Array<String?>?): Unit = TODO()
    open fun readStringArray(value: Array<String?>): Unit = TODO()
    open fun createStringArray(): Array<String> = TODO()

    open fun writeBundle(value: Bundle?): Unit = TODO()
    open fun readBundle(): Bundle = TODO()
    open fun readBundle(loader: Any?): Bundle = TODO()

    open fun writeParcelable(p: Parcelable?, flags: Int): Unit = TODO()
    open fun <T> readParcelable(loader: Any?): T = TODO()
    open fun writeParcelableArray(array: Array<out Parcelable?>?, flags: Int): Unit = TODO()
    open fun readParcelableArray(loader: Any?): Array<Parcelable> = TODO()
    open fun <T> writeTypedObject(value: T, flags: Int): Unit = TODO()
    open fun <T> readTypedObject(creator: Parcelable.Creator<T>): T = TODO()
    open fun <T> writeTypedArray(array: Array<out T>?, flags: Int): Unit = TODO()
    open fun <T> readTypedArray(array: Array<T>, creator: Parcelable.Creator<T>): Unit = TODO()
    open fun <T> createTypedArray(creator: Parcelable.Creator<T>): Array<T> = TODO()
    open fun <T> writeTypedList(list: List<T>?): Unit = TODO()
    open fun <T> readTypedList(list: MutableList<T>, creator: Parcelable.Creator<T>): Unit = TODO()
    open fun <T> createTypedArrayList(creator: Parcelable.Creator<T>): MutableList<T> = TODO()

    open fun writeStringList(strings: List<String>?): Unit = TODO()
    open fun readStringList(strings: MutableList<String>): Unit = TODO()
    open fun createStringArrayList(): MutableList<String> = TODO()
    open fun writeList(list: List<*>?): Unit = TODO()
    open fun readList(list: MutableList<Any?>, loader: Any?): Unit = TODO()
    open fun readArrayList(loader: Any?): MutableList<Any?> = TODO()
    open fun writeMap(map: Map<String, *>?): Unit = TODO()
    open fun readMap(map: MutableMap<String, Any?>, loader: Any?): Unit = TODO()
    open fun readHashMap(loader: Any?): MutableMap<String, Any?> = TODO()
    open fun writeArray(array: Array<Any?>?): Unit = TODO()
    open fun readArray(loader: Any?): Array<Any?> = TODO()

    open fun writeValue(value: Any?): Unit = TODO()
    open fun readValue(loader: Any?): Any? = TODO()
    open fun writeSerializable(value: Any?): Unit = TODO()
    open fun readSerializable(): Any? = TODO()

    open fun writeInterfaceToken(value: String): Unit = TODO()
    open fun enforceInterface(value: String): Unit = TODO()
    open fun writeException(e: Throwable): Unit = TODO()
    open fun writeNoException(): Unit = TODO()
    open fun readException(): Unit = TODO()

    open fun writeFileDescriptor(fd: java.io.FileDescriptor): Unit = TODO()
    open fun readFileDescriptor(): ParcelFileDescriptor = TODO()
    open fun hasFileDescriptors(): Boolean = TODO()

    open fun writeStrongBinder(binder: IBinder?): Unit = TODO()
    open fun readStrongBinder(): IBinder = TODO()
    open fun writeStrongInterface(binder: IInterface?): Unit = TODO()
    open fun writeBinderArray(array: Array<IBinder?>?): Unit = TODO()
    open fun readBinderArray(array: Array<IBinder?>): Unit = TODO()
    open fun createBinderArray(): Array<IBinder> = TODO()
    open fun writeBinderList(list: List<IBinder>?): Unit = TODO()
    open fun readBinderList(list: MutableList<IBinder>): Unit = TODO()
    open fun createBinderArrayList(): MutableList<IBinder> = TODO()
}
""")

T("""
// ---------------------------------------------------------------- Bundle family

open class BaseBundle {
    open fun isEmpty(): Boolean = TODO()
    open fun size(): Int = TODO()
    open fun keySet(): MutableSet<String> = TODO()
    open fun containsKey(key: String): Boolean = TODO()
    open fun remove(key: String): Unit = TODO()
    open fun get(key: String): Any? = TODO()

    open fun getString(key: String): String? = TODO()
    open fun getString(key: String, defaultValue: String?): String? = TODO()
    open fun putString(key: String, value: String?): Unit = TODO()
    open fun getLong(key: String): Long = TODO()
    open fun getLong(key: String, defaultValue: Long): Long = TODO()
    open fun putLong(key: String, value: Long): Unit = TODO()
    open fun getInt(key: String): Int = TODO()
    open fun getInt(key: String, defaultValue: Int): Int = TODO()
    open fun putInt(key: String, value: Int): Unit = TODO()
    open fun getBoolean(key: String): Boolean = TODO()
    open fun getBoolean(key: String, defaultValue: Boolean): Boolean = TODO()
    open fun putBoolean(key: String, value: Boolean): Unit = TODO()
    open fun getIntArray(key: String): IntArray? = TODO()
    open fun putIntArray(key: String, value: IntArray?): Unit = TODO()
    open fun getLongArray(key: String): LongArray? = TODO()
    open fun putLongArray(key: String, value: LongArray?): Unit = TODO()
    open fun getStringArray(key: String): Array<String>? = TODO()
    open fun putStringArray(key: String, value: Array<String?>?): Unit = TODO()
}

open class PersistableBundle : BaseBundle {
    constructor()
    constructor(capacity: Int)
}

open class Bundle : BaseBundle, Parcelable {
    constructor()
    constructor(capacity: Int)
    constructor(b: Bundle)
    constructor(b: PersistableBundle)

    companion object {
        val EMPTY: Bundle = TODO()
        val CREATOR: Parcelable.Creator<Bundle> = TODO()
        fun forPair(key: String, value: String): Bundle = TODO()
    }

    open fun setClassLoader(loader: Any?): Unit = TODO()
    open fun getClassLoader(): Any? = TODO()
    open fun clone(): Any = TODO()
    open fun clear(): Unit = TODO()
    open fun putAll(map: Bundle): Unit = TODO()
    open fun hasFileDescriptors(): Boolean = TODO()
    open fun setAllowFds(allowFds: Boolean): Boolean = TODO()
    open fun isParcelled(): Boolean = TODO()
    open fun readFromParcel(input: Parcel): Unit = TODO()

    open fun putByte(key: String, value: Byte): Unit = TODO()
    open fun getByte(key: String): Byte = TODO()
    open fun putChar(key: String, value: Char): Unit = TODO()
    open fun getChar(key: String): Char = TODO()
    open fun putShort(key: String, value: Short): Unit = TODO()
    open fun getShort(key: String): Short = TODO()
    open fun putFloat(key: String, value: Float): Unit = TODO()
    open fun getFloat(key: String): Float = TODO()
    open fun putDouble(key: String, value: Double): Unit = TODO()
    open fun getDouble(key: String): Double = TODO()
    open fun putCharSequence(key: String, value: CharSequence?): Unit = TODO()
    open fun getCharSequence(key: String): CharSequence? = TODO()

    open fun putBooleanArray(key: String, value: BooleanArray?): Unit = TODO()
    open fun getBooleanArray(key: String): BooleanArray? = TODO()
    open fun putByteArray(key: String, value: ByteArray?): Unit = TODO()
    open fun getByteArray(key: String): ByteArray? = TODO()
    open fun putShortArray(key: String, value: ShortArray?): Unit = TODO()
    open fun getShortArray(key: String): ShortArray? = TODO()
    open fun putCharArray(key: String, value: CharArray?): Unit = TODO()
    open fun getCharArray(key: String): CharArray? = TODO()
    open fun putFloatArray(key: String, value: FloatArray?): Unit = TODO()
    open fun getFloatArray(key: String): FloatArray? = TODO()
    open fun putDoubleArray(key: String, value: DoubleArray?): Unit = TODO()
    open fun getDoubleArray(key: String): DoubleArray? = TODO()
    open fun putCharSequenceArray(key: String, value: Array<CharSequence?>?): Unit = TODO()
    open fun getCharSequenceArray(key: String): Array<CharSequence>? = TODO()

    open fun putBundle(key: String, value: Bundle?): Unit = TODO()
    open fun getBundle(key: String): Bundle? = TODO()
    open fun putBinder(key: String, value: IBinder?): Unit = TODO()
    open fun getBinder(key: String): IBinder? = TODO()

    open fun putParcelable(key: String, value: Parcelable?): Unit = TODO()
    open fun <T> getParcelable(key: String): T = TODO()
    open fun <T> getParcelable(key: String, clazz: Any?): T = TODO()
    open fun putParcelableArray(key: String, value: Array<out Parcelable?>?): Unit = TODO()
    open fun getParcelableArray(key: String): Array<Parcelable>? = TODO()
    open fun <T> getParcelableArray(key: String, clazz: Any?): Array<T> = TODO()
    open fun <T> putParcelableArrayList(key: String, value: MutableList<T>?): Unit = TODO()
    open fun <T> getParcelableArrayList(key: String): MutableList<T> = TODO()
    open fun <T> getParcelableArrayList(key: String, clazz: Any?): MutableList<T> = TODO()
    open fun putSerializable(key: String, value: Any?): Unit = TODO()
    open fun getSerializable(key: String): Any? = TODO()
    open fun <T> getSerializable(key: String, clazz: Any?): T = TODO()
    open fun putIntegerArrayList(key: String, value: MutableList<Int>?): Unit = TODO()
    open fun getIntegerArrayList(key: String): MutableList<Int>? = TODO()
    open fun putStringArrayList(key: String, value: MutableList<String>?): Unit = TODO()
    open fun getStringArrayList(key: String): MutableList<String>? = TODO()
    open fun putCharSequenceArrayList(key: String, value: MutableList<CharSequence>?): Unit = TODO()
    open fun getCharSequenceArrayList(key: String): MutableList<CharSequence>? = TODO()

    override fun describeContents(): Int = TODO()
    override fun writeToParcel(dest: Parcel, flags: Int): Unit = TODO()
}
""")

T("""
// ---------------------------------------------------------------- binder

interface IInterface {
    fun asBinder(): IBinder?
}

interface IBinder {
    interface DeathRecipient {
        fun binderDied()
    }
    companion object {
        const val FIRST_CALL_TRANSACTION: Int = 0x00000001
        const val LAST_CALL_TRANSACTION: Int = 0x00ffffff
        const val PING_TRANSACTION: Int = ('_'.code shl 24) or ('P'.code shl 16) or ('N'.code shl 8) or 'G'.code
        const val DUMP_TRANSACTION: Int = ('_'.code shl 24) or ('D'.code shl 16) or ('M'.code shl 8) or 'P'.code
        const val SHELL_COMMAND_TRANSACTION: Int = ('_'.code shl 24) or ('C'.code shl 16) or ('M'.code shl 8) or 'D'.code
        const val INTERFACE_TRANSACTION: Int = ('_'.code shl 24) or ('N'.code shl 16) or ('T'.code shl 8) or 'F'.code
        const val FLAG_ONEWAY: Int = 0x00000001
    }
    fun getInterfaceDescriptor(): String?
    fun pingBinder(): Boolean
    fun isBinderAlive(): Boolean
    fun queryLocalInterface(descriptor: String): IInterface?
    fun dump(fd: java.io.FileDescriptor, args: Array<String>?)
    fun dumpAsync(fd: java.io.FileDescriptor, args: Array<String>?)
    fun transact(code: Int, data: Parcel, reply: Parcel?, flags: Int): Boolean
    fun linkToDeath(recipient: DeathRecipient, flags: Int)
    fun unlinkToDeath(recipient: DeathRecipient, flags: Int): Boolean
}

open class Binder : IBinder {
    constructor()
    constructor(descriptor: String?)

    companion object {
        fun flushPendingCommands(): Unit = TODO()
        fun clearCallingIdentity(): Long = TODO()
        fun restoreCallingIdentity(identityToken: Long): Unit = TODO()
        fun getCallingUid(): Int = TODO()
        fun getCallingPid(): Int = TODO()
    }

    open fun attachInterface(owner: IInterface?, descriptor: String?): Unit = TODO()
    override fun getInterfaceDescriptor(): String? = TODO()
    override fun pingBinder(): Boolean = TODO()
    override fun isBinderAlive(): Boolean = TODO()
    override fun queryLocalInterface(descriptor: String): IInterface? = TODO()
    override fun dump(fd: java.io.FileDescriptor, args: Array<String>?): Unit = TODO()
    override fun dumpAsync(fd: java.io.FileDescriptor, args: Array<String>?): Unit = TODO()
    override fun transact(code: Int, data: Parcel, reply: Parcel?, flags: Int): Boolean = TODO()
    protected open fun onTransact(code: Int, data: Parcel, reply: Parcel?, flags: Int): Boolean = TODO()
    override fun linkToDeath(recipient: IBinder.DeathRecipient, flags: Int): Unit = TODO()
    override fun unlinkToDeath(recipient: IBinder.DeathRecipient, flags: Int): Boolean = TODO()
}

open class RemoteException(message: String? = null) : Exception(message)
open class DeadObjectException(message: String? = null) : RemoteException(message)
open class TransactionTooLargeException(message: String? = null) : RemoteException(message)

open class Messenger : Parcelable {
    constructor(target: Handler)
    constructor(target: IBinder)
    open fun send(message: Message): Unit = TODO()
    open fun getBinder(): IBinder = TODO()
    companion object {
        val CREATOR: Parcelable.Creator<Messenger> = TODO()
    }
}
""")

T("""
// ---------------------------------------------------------------- looper / handler / message

open class MessageQueue {
    interface IdleHandler {
        fun queueIdle(): Boolean
    }
    open fun addIdleHandler(handler: IdleHandler): Unit = TODO()
    open fun removeIdleHandler(handler: IdleHandler): Unit = TODO()
    open fun isIdle(): Boolean = TODO()
}

open class Looper {
    companion object {
        fun prepare(): Unit = TODO()
        fun prepareMainLooper(): Unit = TODO()
        fun getMainLooper(): Looper = TODO()
        fun loop(): Unit = TODO()
        fun myLooper(): Looper = TODO()
        fun myQueue(): MessageQueue = TODO()
    }
    open fun isCurrentThread(): Boolean = TODO()
    open fun quit(): Unit = TODO()
    open fun quitSafely(): Unit = TODO()
    open fun getQueue(): MessageQueue = TODO()
    open fun getThread(): Any = TODO()
    open fun isIdling(): Boolean = TODO()
    open fun postSyncBarrier(): Int = TODO()
    open fun removeSyncBarrier(token: Int): Unit = TODO()
}

open class Message {
    var what: Int = 0
    var arg1: Int = 0
    var arg2: Int = 0
    var obj: Any? = null
    var replyTo: Messenger? = null

    companion object {
        fun obtain(): Message = TODO()
        fun obtain(orig: Message): Message = TODO()
        fun obtain(h: Handler?): Message = TODO()
        fun obtain(h: Handler?, callback: Any?): Message = TODO()
        fun obtain(h: Handler?, what: Int): Message = TODO()
        fun obtain(h: Handler?, what: Int, obj: Any?): Message = TODO()
        fun obtain(h: Handler?, what: Int, arg1: Int, arg2: Int): Message = TODO()
        fun obtain(h: Handler?, what: Int, arg1: Int, arg2: Int, obj: Any?): Message = TODO()
    }

    open fun recycle(): Unit = TODO()
    open fun copyFrom(o: Message): Unit = TODO()
    open fun getWhen(): Long = TODO()
    open fun setTarget(target: Handler?): Unit = TODO()
    open fun getTarget(): Handler? = TODO()
    open fun getCallback(): Any? = TODO()
    open fun getData(): Bundle = TODO()
    open fun peekData(): Bundle? = TODO()
    open fun setData(data: Bundle?): Unit = TODO()
    open fun sendToTarget(): Unit = TODO()
    open fun isAsynchronous(): Boolean = TODO()
    open fun setAsynchronous(async: Boolean): Unit = TODO()
    open fun describeContents(): Int = TODO()
}

open class Handler {
    interface Callback {
        fun handleMessage(msg: Message): Boolean
    }

    constructor()
    constructor(callback: Callback?)
    constructor(looper: Looper?)
    constructor(looper: Looper?, callback: Callback?)
    constructor(looper: Looper?, callback: Callback?, async: Boolean)

    companion object {
        fun createAsync(looper: Looper): Handler = TODO()
    }

    open fun handleMessage(msg: Message): Unit = TODO()
    open fun dispatchMessage(msg: Message): Unit = TODO()
    open fun getMessageName(message: Message): String = TODO()

    open fun obtainMessage(): Message = TODO()
    open fun obtainMessage(what: Int): Message = TODO()
    open fun obtainMessage(what: Int, obj: Any?): Message = TODO()
    open fun obtainMessage(what: Int, arg1: Int, arg2: Int): Message = TODO()
    open fun obtainMessage(what: Int, arg1: Int, arg2: Int, obj: Any?): Message = TODO()

    // Runnable is java.lang, which Kotlin/Native does not have. Each of these is
    // declared twice: a lambda overload for `post { ... }`, and an Any? overload
    // so a transpiled `object : Runnable` value also resolves. The lambda form is
    // the more specific one, so it wins for lambda literals.
    open fun post(r: () -> Unit): Boolean = TODO()
    open fun post(r: Any?): Boolean = TODO()
    open fun postAtTime(r: () -> Unit, uptimeMillis: Long): Boolean = TODO()
    open fun postAtTime(r: Any?, uptimeMillis: Long): Boolean = TODO()
    open fun postAtTime(r: () -> Unit, token: Any?, uptimeMillis: Long): Boolean = TODO()
    open fun postDelayed(r: () -> Unit, delayMillis: Long): Boolean = TODO()
    open fun postDelayed(r: Any?, delayMillis: Long): Boolean = TODO()
    open fun postAtFrontOfQueue(r: () -> Unit): Boolean = TODO()
    open fun postAtFrontOfQueue(r: Any?): Boolean = TODO()
    open fun removeCallbacks(r: () -> Unit): Unit = TODO()
    open fun removeCallbacks(r: Any?): Unit = TODO()
    open fun removeCallbacks(r: () -> Unit, token: Any?): Unit = TODO()
    open fun hasCallbacks(r: () -> Unit): Boolean = TODO()
    open fun hasCallbacks(r: Any?): Boolean = TODO()

    open fun sendMessage(msg: Message): Boolean = TODO()
    open fun sendEmptyMessage(what: Int): Boolean = TODO()
    open fun sendEmptyMessageDelayed(what: Int, delayMillis: Long): Boolean = TODO()
    open fun sendEmptyMessageAtTime(what: Int, uptimeMillis: Long): Boolean = TODO()
    open fun sendMessageDelayed(msg: Message, delayMillis: Long): Boolean = TODO()
    open fun sendMessageAtTime(msg: Message, uptimeMillis: Long): Boolean = TODO()
    open fun sendMessageAtFrontOfQueue(msg: Message): Boolean = TODO()
    open fun removeMessages(what: Int): Unit = TODO()
    open fun removeMessages(what: Int, obj: Any?): Unit = TODO()
    open fun removeCallbacksAndMessages(token: Any?): Unit = TODO()
    open fun hasMessages(what: Int): Boolean = TODO()
    open fun hasMessages(what: Int, obj: Any?): Boolean = TODO()
    open fun getLooper(): Looper = TODO()
}

// No java.lang.Thread on Kotlin/Native, so this does not extend it.
// GeckoView only calls start/getLooper/quit/quitSafely.
open class HandlerThread {
    constructor(name: String?)
    constructor(name: String?, priority: Int)
    protected open fun onLooperPrepared(): Unit = TODO()
    open fun run(): Unit = TODO()
    open fun start(): Unit = TODO()
    open fun join(): Unit = TODO()
    open fun interrupt(): Unit = TODO()
    open fun getLooper(): Looper = TODO()
    open fun getThreadId(): Int = TODO()
    open fun quit(): Boolean = TODO()
    open fun quitSafely(): Boolean = TODO()
}
""")

T("""
// ---------------------------------------------------------------- Build

object Build {
    const val UNKNOWN: String = "unknown"
    val ID: String = TODO()
    val DISPLAY: String = TODO()
    val PRODUCT: String = TODO()
    val DEVICE: String = TODO()
    val BOARD: String = TODO()
    val CPU_ABI: String = TODO()
    val CPU_ABI2: String = TODO()
    val MANUFACTURER: String = TODO()
    val BRAND: String = TODO()
    val MODEL: String = TODO()
    val BOOTLOADER: String = TODO()
    val RADIO: String = TODO()
    val HARDWARE: String = TODO()
    val SERIAL: String = TODO()
    val SUPPORTED_ABIS: Array<String> = TODO()
    val TYPE: String = TODO()
    val TAGS: String = TODO()
    val FINGERPRINT: String = TODO()
    val TIME: Long = TODO()
    val USER: String = TODO()
    val HOST: String = TODO()
    const val IS_DEBUGGABLE: Boolean = true
    fun getRadioVersion(): String = TODO()

    object VERSION {
        val INCREMENTAL: String = TODO()
        val RELEASE: String = TODO()
        val SDK: String = TODO()
        val SDK_INT: Int = TODO()
        val RESOURCES_SDK_INT: Int = TODO()
        val CODENAME: String = TODO()
        val SECURITY_PATCH: String = TODO()
    }

    object VERSION_CODES {
        const val CUR_DEVELOPMENT: Int = 10000
        const val BASE: Int = 1
        const val BASE_1_1: Int = 2
        const val CUPCAKE: Int = 3
        const val DONUT: Int = 4
        const val ECLAIR: Int = 5
        const val ECLAIR_0_1: Int = 6
        const val ECLAIR_MR1: Int = 7
        const val FROYO: Int = 8
        const val GINGERBREAD: Int = 9
        const val GINGERBREAD_MR1: Int = 10
        const val HONEYCOMB: Int = 11
        const val HONEYCOMB_MR1: Int = 12
        const val HONEYCOMB_MR2: Int = 13
        const val ICE_CREAM_SANDWICH: Int = 14
        const val ICE_CREAM_SANDWICH_MR1: Int = 15
        const val JELLY_BEAN: Int = 16
        const val JELLY_BEAN_MR1: Int = 17
        const val JELLY_BEAN_MR2: Int = 18
        const val KITKAT: Int = 19
        const val KITKAT_WATCH: Int = 20
        const val L: Int = 21
        const val LOLLIPOP: Int = 21
        const val LOLLIPOP_MR1: Int = 22
        const val M: Int = 23
        const val N: Int = 24
        const val N_MR1: Int = 25
        const val O: Int = 26
        const val O_MR1: Int = 27
        const val P: Int = 28
        const val Q: Int = 29
        const val R: Int = 30
        const val S: Int = 31
        const val S_V2: Int = 32
        const val TIRAMISU: Int = 33
        const val UPSIDE_DOWN_CAKE: Int = 34
        const val VANILLA_ICE_CREAM: Int = 35
    }
}
""")

T("""
// ---------------------------------------------------------------- process / clock / user

object SystemClock {
    fun sleep(ms: Long): Unit = TODO()
    fun setCurrentTimeMillis(millis: Long): Boolean = TODO()
    fun uptimeMillis(): Long = TODO()
    fun elapsedRealtime(): Long = TODO()
    fun elapsedRealtimeNanos(): Long = TODO()
    fun currentThreadTimeMillis(): Long = TODO()
    fun currentThreadTimeMicro(): Long = TODO()
    fun currentTimeMicro(): Long = TODO()
}

open class UserHandle(h: Int) : Parcelable {
    companion object {
        const val PER_USER_RANGE: Int = 100000
        const val USER_ALL: Int = -1
        const val USER_CURRENT: Int = -2
        const val USER_CURRENT_OR_SELF: Int = -3
        const val USER_NULL: Int = -10000
        const val USER_OWNER: Int = 0
        val ALL: UserHandle = TODO()
        val CURRENT: UserHandle = TODO()
        val CURRENT_OR_SELF: UserHandle = TODO()
        val OWNER: UserHandle = TODO()
        val CREATOR: Parcelable.Creator<UserHandle> = TODO()
        fun isSameUser(uid1: Int, uid2: Int): Boolean = TODO()
        fun isSameApp(uid1: Int, uid2: Int): Boolean = TODO()
        fun isIsolated(uid: Int): Boolean = TODO()
        fun isApp(uid: Int): Boolean = TODO()
        fun getUserId(uid: Int): Int = TODO()
        fun getCallingUserId(): Int = TODO()
        fun getUid(userId: Int, appId: Int): Int = TODO()
        fun getAppId(uid: Int): Int = TODO()
        fun getSharedAppGid(id: Int): Int = TODO()
        fun myUserId(): Int = TODO()
    }
    open fun getIdentifier(): Int = TODO()
}

open class UserManager {
    open fun isUserUnlocked(): Boolean = TODO()
    open fun getSerialNumberForUser(user: UserHandle): Long = TODO()
    open fun getUserForSerialNumber(serial: Long): UserHandle? = TODO()
    companion object {
        fun supportsMultipleUsers(): Boolean = TODO()
    }
}

object Process {
    const val SYSTEM_UID: Int = 1000
    const val PHONE_UID: Int = 1001
    const val SHELL_UID: Int = 2000
    const val LOG_UID: Int = 1007
    const val WIFI_UID: Int = 1010
    const val MEDIA_UID: Int = 1013
    const val DRM_UID: Int = 1019
    const val VPN_UID: Int = 1016
    const val NFC_UID: Int = 1027
    const val BLUETOOTH_UID: Int = 1002
    const val FIRST_APPLICATION_UID: Int = 10000
    const val LAST_APPLICATION_UID: Int = 19999
    const val FIRST_ISOLATED_UID: Int = 99000
    const val LAST_ISOLATED_UID: Int = 99999
    const val THREAD_PRIORITY_DEFAULT: Int = 0
    const val THREAD_PRIORITY_LOWEST: Int = 19
    const val THREAD_PRIORITY_BACKGROUND: Int = 10
    const val THREAD_PRIORITY_FOREGROUND: Int = -2
    const val THREAD_PRIORITY_DISPLAY: Int = -4
    const val THREAD_PRIORITY_URGENT_DISPLAY: Int = -8
    const val THREAD_PRIORITY_AUDIO: Int = -16
    const val THREAD_PRIORITY_URGENT_AUDIO: Int = -19
    const val THREAD_PRIORITY_MORE_FAVORABLE: Int = -1
    const val THREAD_PRIORITY_LESS_FAVORABLE: Int = 1
    const val SCHED_OTHER: Int = 0
    const val SCHED_FIFO: Int = 1
    const val SCHED_RR: Int = 2
    const val SCHED_BATCH: Int = 3
    const val SCHED_IDLE: Int = 5

    fun myPid(): Int = TODO()
    fun myTid(): Int = TODO()
    fun myUid(): Int = TODO()
    fun myUserHandle(): UserHandle = TODO()
    fun isIsolated(): Boolean = TODO()
    fun isIsolated(uid: Int): Boolean = TODO()
    fun killProcess(pid: Int): Unit = TODO()
    fun setThreadPriority(priority: Int): Unit = TODO()
    fun setThreadPriority(tid: Int, priority: Int): Unit = TODO()
    fun getThreadPriority(tid: Int): Int = TODO()
    fun getElapsedCpuTime(): Long = TODO()
    fun supportsProcesses(): Boolean = TODO()
}
""")

T("""
// ---------------------------------------------------------------- fd-backed

open class ParcelFileDescriptor : Parcelable {
    constructor(wrapped: ParcelFileDescriptor)
    constructor(fd: java.io.FileDescriptor)
    constructor(fd: java.io.FileDescriptor, commChannel: java.io.FileDescriptor?)

    companion object {
        const val MODE_WORLD_READABLE: Int = 0x00000001
        const val MODE_WORLD_WRITEABLE: Int = 0x00000002
        const val MODE_READ_ONLY: Int = 0x10000000
        const val MODE_WRITE_ONLY: Int = 0x20000000
        const val MODE_READ_WRITE: Int = 0x30000000
        const val MODE_CREATE: Int = 0x08000000
        const val MODE_TRUNCATE: Int = 0x04000000
        const val MODE_APPEND: Int = 0x02000000
        val CREATOR: Parcelable.Creator<ParcelFileDescriptor> = TODO()
        fun open(file: java.io.File, mode: Int): ParcelFileDescriptor = TODO()
        fun dup(orig: java.io.FileDescriptor): ParcelFileDescriptor = TODO()
        fun fromFd(fd: Int): ParcelFileDescriptor = TODO()
        fun adoptFd(fd: Int): ParcelFileDescriptor = TODO()
        fun createPipe(): Array<ParcelFileDescriptor> = TODO()
        fun createReliablePipe(): Array<ParcelFileDescriptor> = TODO()
        fun createSocketPair(): Array<ParcelFileDescriptor> = TODO()
        fun createReliableSocketPair(): Array<ParcelFileDescriptor> = TODO()
        fun fromData(data: ByteArray, name: String?): ParcelFileDescriptor = TODO()
        fun parseMode(mode: String): Int = TODO()
    }

    interface OnCloseListener {
        fun onClose(e: Exception?)
    }
    open class FileDescriptorDetachedException : Exception()

    open fun dup(): ParcelFileDescriptor = TODO()
    open fun getFileDescriptor(): java.io.FileDescriptor = TODO()
    open fun getStatSize(): Long = TODO()
    open fun seekTo(pos: Long): Long = TODO()
    open fun getFd(): Int = TODO()
    open fun detachFd(): Int = TODO()
    open fun close(): Unit = TODO()
    open fun closeWithError(msg: String?): Unit = TODO()
    open fun releaseResources(): Unit = TODO()
    open fun canDetectErrors(): Boolean = TODO()
    open fun checkError(): Unit = TODO()
    override fun describeContents(): Int = TODO()
    override fun writeToParcel(dest: Parcel, flags: Int): Unit = TODO()
}

open class MemoryFile(name: String?, length: Int) {
    open fun close(): Unit = TODO()
    open fun length(): Int = TODO()
    open fun isPurgingAllowed(): Boolean = TODO()
    open fun allowPurging(allowPurging: Boolean): Boolean = TODO()
    open fun readBytes(buffer: ByteArray, srcOffset: Int, destOffset: Int, count: Int): Int = TODO()
    open fun writeBytes(buffer: ByteArray, srcOffset: Int, destOffset: Int, count: Int): Unit = TODO()
    // Hidden on real Android; GeckoView reaches it by reflection.
    open fun getFileDescriptor(): java.io.FileDescriptor = TODO()
    companion object {
        fun getSize(fd: java.io.FileDescriptor): Int = TODO()
    }
}
""")

T("""
// ---------------------------------------------------------------- system services & misc

object Environment {
    const val DIRECTORY_ANDROID: String = "Android"
    const val DIRECTORY_MUSIC: String = "Music"
    const val DIRECTORY_PODCASTS: String = "Podcasts"
    const val DIRECTORY_RINGTONES: String = "Ringtones"
    const val DIRECTORY_ALARMS: String = "Alarms"
    const val DIRECTORY_NOTIFICATIONS: String = "Notifications"
    const val DIRECTORY_PICTURES: String = "Pictures"
    const val DIRECTORY_MOVIES: String = "Movies"
    const val DIRECTORY_DOWNLOADS: String = "Download"
    const val DIRECTORY_DCIM: String = "DCIM"
    const val DIRECTORY_DOCUMENTS: String = "Documents"
    const val MEDIA_UNKNOWN: String = "unknown"
    const val MEDIA_REMOVED: String = "removed"
    const val MEDIA_UNMOUNTED: String = "unmounted"
    const val MEDIA_CHECKING: String = "checking"
    const val MEDIA_MOUNTED: String = "mounted"
    const val MEDIA_MOUNTED_READ_ONLY: String = "mounted_ro"

    fun getRootDirectory(): java.io.File = TODO()
    fun getDataDirectory(): java.io.File = TODO()
    fun getStorageDirectory(): java.io.File = TODO()
    fun getDownloadCacheDirectory(): java.io.File = TODO()
    fun getExternalStorageDirectory(): java.io.File = TODO()
    fun getExternalStoragePublicDirectory(type: String): java.io.File = TODO()
    fun getExternalStorageState(): String = TODO()
    fun isExternalStorageRemovable(): Boolean = TODO()
    fun isExternalStorageRemovable(file: java.io.File): Boolean = TODO()
    fun isExternalStorageEmulated(): Boolean = TODO()
}

open class PowerManager {
    open class WakeLock {
        open fun setReferenceCounted(referenceCounted: Boolean): Unit = TODO()
        open fun acquire(): Unit = TODO()
        open fun acquire(timeout: Long): Unit = TODO()
        open fun release(): Unit = TODO()
        open fun isHeld(): Boolean = TODO()
    }
    companion object {
        const val PARTIAL_WAKE_LOCK: Int = 1
        const val SCREEN_DIM_WAKE_LOCK: Int = 6
        const val SCREEN_BRIGHT_WAKE_LOCK: Int = 10
        const val FULL_WAKE_LOCK: Int = 0x1a
        const val ACQUIRE_CAUSES_WAKEUP: Int = 268435456
        const val ON_AFTER_RELEASE: Int = 536870912
    }
    open fun newWakeLock(levelAndFlags: Int, tag: String): WakeLock = TODO()
    open fun userActivity(who: Long, noChangeLights: Boolean): Unit = TODO()
    open fun isPowerSaveMode(): Boolean = TODO()
    open fun isScreenOn(): Boolean = TODO()
    open fun isInteractive(): Boolean = TODO()
    open fun isIgnoringBatteryOptimizations(packageName: String): Boolean = TODO()
}

open class Vibrator {
    open fun hasVibrator(): Boolean = TODO()
    open fun hasAmplitudeControl(): Boolean = TODO()
    open fun areAllPrimitivesSupported(vararg primitiveIds: Int): Boolean = TODO()
    open fun arePrimitivesSupported(vararg primitiveIds: Int): BooleanArray = TODO()
    open fun vibrate(milliseconds: Long): Unit = TODO()
    open fun vibrate(pattern: LongArray, repeat: Int): Unit = TODO()
    open fun cancel(): Unit = TODO()
}

open class BatteryManager {
    companion object {
        const val EXTRA_LEVEL: String = "level"
        const val EXTRA_PLUGGED: String = "plugged"
        const val EXTRA_PRESENT: String = "present"
        const val EXTRA_SCALE: String = "scale"
        const val EXTRA_STATUS: String = "status"
        const val EXTRA_HEALTH: String = "health"
        const val EXTRA_TEMPERATURE: String = "temperature"
        const val EXTRA_VOLTAGE: String = "voltage"
        const val BATTERY_STATUS_CHARGING: Int = 2
        const val BATTERY_STATUS_DISCHARGING: Int = 3
        const val BATTERY_STATUS_FULL: Int = 5
        const val BATTERY_PLUGGED_AC: Int = 1
        const val BATTERY_PLUGGED_USB: Int = 2
        const val BATTERY_PLUGGED_WIRELESS: Int = 4
    }
}

object Debug {
    open class MemoryInfo {
        var dalvikPss: Int = 0
        var nativePss: Int = 0
        var otherPss: Int = 0
        open fun getTotalPss(): Int = TODO()
        open fun getMemoryStat(name: String): String? = TODO()
    }
    open class InstructionCount

    fun getMemoryInfo(info: MemoryInfo): Unit = TODO()
    fun waitForDebugger(): Unit = TODO()
    fun isDebuggerConnected(): Boolean = TODO()
    fun waitingForDebugger(): Boolean = TODO()
    fun getNativeHeapFreeSize(): Long = TODO()
    fun getNativeHeapAllocatedSize(): Long = TODO()
    fun getNativeHeapSize(): Long = TODO()
    fun threadCpuTimeNanos(): Long = TODO()
    fun dumpHprofData(fileName: String): Unit = TODO()
}

open class LocaleList(vararg list: java.util.Locale) : Parcelable {
    companion object {
        val CREATOR: Parcelable.Creator<LocaleList> = TODO()
        fun getDefault(): LocaleList = TODO()
        fun getAdjustedDefault(): LocaleList = TODO()
        fun getEmptyLocaleList(): LocaleList = TODO()
        fun forLanguageTags(list: String?): LocaleList = TODO()
        fun setDefault(locales: LocaleList): Unit = TODO()
        fun matchesLanguageAndScript(supported: java.util.Locale, desired: java.util.Locale): Boolean = TODO()
    }
    open fun get(index: Int): java.util.Locale = TODO()
    open fun isEmpty(): Boolean = TODO()
    open fun size(): Int = TODO()
    open fun indexOf(locale: java.util.Locale): Int = TODO()
    open fun toLanguageTags(): String = TODO()
    open fun getFirstMatch(supportedLocales: Array<String>): java.util.Locale = TODO()
    override fun describeContents(): Int = TODO()
    override fun writeToParcel(dest: Parcel, flags: Int): Unit = TODO()
}

open class CancellationSignal {
    interface OnCancelListener {
        fun onCancel()
    }
    open fun isCanceled(): Boolean = TODO()
    open fun throwIfCanceled(): Unit = TODO()
    open fun cancel(): Unit = TODO()
    open fun setOnCancelListener(listener: OnCancelListener?): Unit = TODO()
}

interface OutcomeReceiver<R, E : Throwable> {
    fun onResult(result: R)
    fun onError(error: E) {}
}

open class ConditionVariable {
    constructor()
    constructor(state: Boolean)
    open fun open(): Unit = TODO()
    open fun close(): Unit = TODO()
    open fun block(): Unit = TODO()
    open fun block(timeoutMs: Long): Boolean = TODO()
}

abstract class AsyncTask<Params, Progress, Result> {
    enum class Status { PENDING, RUNNING, FINISHED }
    protected abstract fun doInBackground(vararg params: Params): Result
    protected open fun onPreExecute(): Unit = TODO()
    protected open fun onPostExecute(result: Result): Unit = TODO()
    protected open fun onProgressUpdate(vararg values: Progress): Unit = TODO()
    protected open fun onCancelled(result: Result): Unit = TODO()
    protected open fun onCancelled(): Unit = TODO()
    protected open fun publishProgress(vararg values: Progress): Unit = TODO()
    open fun getStatus(): Status = TODO()
    open fun isCancelled(): Boolean = TODO()
    open fun cancel(mayInterruptIfRunning: Boolean): Boolean = TODO()
    open fun get(): Result = TODO()
    open fun execute(vararg params: Params): AsyncTask<Params, Progress, Result> = TODO()
}

object Trace {
    const val TRACE_TAG_NEVER: Long = 0
    const val TRACE_TAG_ALWAYS: Long = 1L
    const val TRACE_TAG_VIEW: Long = 8L
    const val TRACE_TAG_APP: Long = 4096L
    fun beginSection(sectionName: String): Unit = TODO()
    fun endSection(): Unit = TODO()
    fun isEnabled(): Boolean = TODO()
    fun isTagEnabled(traceTag: Long): Boolean = TODO()
    fun traceBegin(traceTag: Long, methodName: String): Unit = TODO()
    fun traceEnd(traceTag: Long): Unit = TODO()
    fun traceCounter(traceTag: Long, counterName: String, counterValue: Int): Unit = TODO()
    fun setCounter(name: String, value: Long): Unit = TODO()
}

object StrictMode {
    class ThreadPolicy {
        class Builder {
            constructor()
            constructor(policy: ThreadPolicy)
            fun detectAll(): Builder = TODO()
            fun permitAll(): Builder = TODO()
            fun permitDiskReads(): Builder = TODO()
            fun permitDiskWrites(): Builder = TODO()
            fun penaltyLog(): Builder = TODO()
            fun penaltyDeath(): Builder = TODO()
            fun build(): ThreadPolicy = TODO()
        }
        companion object { val LAX: ThreadPolicy = TODO() }
    }
    class VmPolicy {
        class Builder {
            constructor()
            constructor(policy: VmPolicy)
            fun detectAll(): Builder = TODO()
            fun penaltyLog(): Builder = TODO()
            fun penaltyDeath(): Builder = TODO()
            fun build(): VmPolicy = TODO()
        }
        companion object { val LAX: VmPolicy = TODO() }
    }
    fun setThreadPolicy(policy: ThreadPolicy): Unit = TODO()
    fun getThreadPolicy(): ThreadPolicy = TODO()
    fun setVmPolicy(policy: VmPolicy): Unit = TODO()
    fun getVmPolicy(): VmPolicy = TODO()
    fun allowThreadDiskWrites(): ThreadPolicy = TODO()
    fun allowThreadDiskReads(): ThreadPolicy = TODO()
    fun noteSlowCall(tag: String): Unit = TODO()
}
""")

# java.* declarations os.kt leans on. Kotlin/Native has no JDK, so somebody has
# to supply these; emitted separately (--java-deps) only so this file can be
# type-checked on its own.
JAVA_DEP_FILES = {
    "javaio.kt": """package java.io

open class File {
    constructor(path: String)
    constructor(parent: String?, child: String)
    open fun getPath(): String = TODO()
    open fun getAbsolutePath(): String = TODO()
}

open class FileDescriptor
""",
    "javautil.kt": """package java.util

open class Locale(language: String) {
    open fun toLanguageTag(): String = TODO()
}
""",
}

def build():
    parts = [HEADER, "\npackage android.os\n"]
    parts.extend(TEMPLATES)
    return "\n".join(parts) + "\n"

def audit(text, use):
    """Print members GeckoView touches that the emitted Kotlin never declares."""
    # java.lang.Object members every Kotlin type already has.
    UNIVERSAL = {"equals", "hashCode", "toString", "wait", "notify", "notifyAll", "getClass"}
    drift = {}
    for ty, members in sorted(use.items()):
        missing = []
        for m in members:
            if m == "<init>" or m in UNIVERSAL:
                continue
            pats = [" %s(" % m, " %s:" % m, "val %s" % m, "var %s" % m,
                    "object %s" % m, "class %s" % m, "interface %s" % m]
            if not any(pt in text for pt in pats):
                missing.append(m)
        if missing: drift[ty] = sorted(missing)
    return drift

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--java-deps", metavar="DIR",
                    help="also write throwaway java.io/java.util decls there (solo type-check only)")
    ap.add_argument("--no-scrape", action="store_true")
    a = ap.parse_args()

    text = build()
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(text)
    print(f"wrote {a.out}  ({len(text.splitlines())} lines)")

    if a.java_deps:
        os.makedirs(a.java_deps, exist_ok=True)
        for name, body in JAVA_DEP_FILES.items():
            with open(os.path.join(a.java_deps, name), "w") as f:
                f.write(body)
        print(f"wrote java.* scratch decls to {a.java_deps}")

    if not a.no_scrape:
        use = scrape()
        print(f"scraped {len(use)} android.os types across GeckoView")
        drift = audit(text, use)
        if drift:
            print("DRIFT -- used by GeckoView, not declared in os.kt:")
            for ty, ms in drift.items():
                print(f"  {ty}: {', '.join(ms)}")
        else:
            print("no drift: every scraped member has a declaration")

if __name__ == "__main__":
    main()
