#!/usr/bin/env python3
"""Generate Kotlin/Native stubs for the android.view / .inputmethod / .accessibility
/ .autofill, android.widget, android.print and android.speech.tts slice of the
android.* surface that GeckoView's Java compiles against.

Re-runnable: point it at a fresh mozilla-central worktree and it re-emits the
stubs and re-reports which call-site members the templates do not cover.

    python3 view.py [--java-root DIR] [--out DIR] [--deps FILE]

Signatures were recovered from GeckoView call sites (see scrape_call_sites) and,
where a call site was ambiguous, from ATL's real android.* reimplementation at
/home/nekit/UT/atlas/src/api-impl/android/.

Note on file count: the task asked for one .kt file. Kotlin allows exactly one
package declaration per file, and this slice spans seven packages, so the
generator emits one file per package. view.kt is the android.view one.
"""

import argparse
import os
import re
import sys
import collections

DEFAULT_JAVA_ROOT = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview/src/main/java"
DEFAULT_OUT = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview-kn/src/stubs"

BANNER = (
    "// GENERATED by kn-run/stubgen/view.py -- do not edit by hand.\n"
    "// Stub surface for %s, derived from GeckoView call sites.\n"
    "// Bodies are TODO(): Kotlin/Native has no Android runtime; nothing here is meant to run.\n"
)

# Packages this generator owns. Anything imported from these in GeckoView's Java
# must resolve against the emitted stubs.
OWNED_PACKAGES = (
    "android.view",
    "android.view.inputmethod",
    "android.view.accessibility",
    "android.view.autofill",
    "android.widget",
    "android.print",
    "android.speech",
)

TEMPLATES = [
    ('android.view', 'view.kt', """\
package android.view

import android.content.ClipData
import android.content.ClipDescription
import android.content.Context
import android.content.ContextWrapper
import android.content.Intent
import android.content.res.Configuration
import android.content.res.TypedArray
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Insets
import android.graphics.Point
import android.graphics.Rect
import android.graphics.Region
import android.graphics.SurfaceTexture
import android.graphics.drawable.Drawable
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Parcel
import android.util.AttributeSet
import android.util.SparseArray
import java.lang.Runnable
import android.view.accessibility.AccessibilityEvent
import android.view.accessibility.AccessibilityNodeInfo
import android.view.accessibility.AccessibilityNodeProvider
import android.view.autofill.AutofillId
import android.view.autofill.AutofillValue
import android.view.inputmethod.EditorInfo
import android.view.inputmethod.InputConnection

// ---------------------------------------------------------------- View

open class View {
    constructor(context: Context?) {}
    constructor(context: Context?, attrs: AttributeSet?) {}
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) {}
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int, defStyleRes: Int) {}

    open class AccessibilityDelegate {
        open fun getAccessibilityNodeProvider(host: View?): AccessibilityNodeProvider? = TODO()
        open fun sendAccessibilityEvent(host: View?, eventType: Int): Unit = TODO()
        open fun onInitializeAccessibilityNodeInfo(host: View?, info: AccessibilityNodeInfo?): Unit = TODO()
        open fun performAccessibilityAction(host: View?, action: Int, args: Bundle?): Boolean = TODO()
    }

    open class DragShadowBuilder {
        constructor() {}
        constructor(view: View?) {}
        open fun onProvideShadowMetrics(outShadowSize: Point?, outShadowTouchPoint: Point?): Unit = TODO()
        open fun onDrawShadow(canvas: Canvas?): Unit = TODO()
        open fun getView(): View? = TODO()
    }

    fun interface OnApplyWindowInsetsListener {
        fun onApplyWindowInsets(v: View?, insets: WindowInsets?): WindowInsets?
    }

    fun interface OnClickListener { fun onClick(v: View?) }
    fun interface OnLongClickListener { fun onLongClick(v: View?): Boolean }
    fun interface OnTouchListener { fun onTouch(v: View?, event: MotionEvent?): Boolean }

    // --- identity / tree
    open fun getId(): Int = TODO()
    open fun setId(id: Int): Unit = TODO()
    open fun getContext(): Context = TODO()
    open fun getResources(): android.content.res.Resources = TODO()
    open fun getRootView(): View = TODO()
    open fun getParent(): ViewParent? = TODO()
    open fun getDisplay(): Display? = TODO()
    open fun getHandler(): Handler? = TODO()
    open fun getWindowToken(): IBinder? = TODO()
    open fun getRootWindowInsets(): WindowInsets? = TODO()
    open fun getLocationOnScreen(outLocation: IntArray?): Unit = TODO()
    open fun getLocationInWindow(outLocation: IntArray?): Unit = TODO()
    open fun getWidth(): Int = TODO()
    open fun getHeight(): Int = TODO()
    open fun getMeasuredWidth(): Int = TODO()
    open fun getMeasuredHeight(): Int = TODO()
    open fun getLayoutParams(): ViewGroup.LayoutParams? = TODO()
    open fun setLayoutParams(params: ViewGroup.LayoutParams?): Unit = TODO()

    // --- posting
    open fun post(action: Runnable?): Boolean = TODO()
    open fun postDelayed(action: Runnable?, delayMillis: Long): Boolean = TODO()
    open fun removeCallbacks(action: Runnable?): Boolean = TODO()

    // --- focus
    open fun requestFocus(): Boolean = TODO()
    open fun requestFocus(direction: Int): Boolean = TODO()
    open fun clearFocus(): Unit = TODO()
    open fun isFocused(): Boolean = TODO()
    open fun hasFocus(): Boolean = TODO()
    open fun findFocus(): View? = TODO()
    open fun hasWindowFocus(): Boolean = TODO()
    open fun setFocusable(focusable: Boolean): Unit = TODO()
    open fun setFocusableInTouchMode(focusable: Boolean): Unit = TODO()
    open fun onFocusChanged(gainFocus: Boolean, direction: Int, previouslyFocusedRect: Rect?): Unit = TODO()
    open fun onWindowFocusChanged(hasWindowFocus: Boolean): Unit = TODO()

    // --- visibility / drawing
    open fun getVisibility(): Int = TODO()
    open fun setVisibility(visibility: Int): Unit = TODO()
    open fun onWindowVisibilityChanged(visibility: Int): Unit = TODO()
    open fun invalidate(): Unit = TODO()
    open fun requestLayout(): Unit = TODO()
    open fun setBackground(background: Drawable?): Unit = TODO()
    open fun setBackgroundColor(color: Int): Unit = TODO()
    open fun setWillNotCacheDrawing(willNotCacheDrawing: Boolean): Unit = TODO()
    open fun onDraw(canvas: Canvas?): Unit = TODO()
    open fun dispatchDraw(canvas: Canvas?): Unit = TODO()
    open fun draw(canvas: Canvas?): Unit = TODO()
    open fun gatherTransparentRegion(region: Region?): Boolean = TODO()
    open fun onAttachedToWindow(): Unit = TODO()
    open fun onDetachedFromWindow(): Unit = TODO()
    open fun onConfigurationChanged(newConfig: Configuration?): Unit = TODO()
    open fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int): Unit = TODO()
    open fun onApplyWindowInsets(insets: WindowInsets?): WindowInsets? = TODO()
    open fun setOnApplyWindowInsetsListener(listener: OnApplyWindowInsetsListener?): Unit = TODO()

    // --- input
    open fun onKeyPreIme(keyCode: Int, event: KeyEvent?): Boolean = TODO()
    open fun onKeyDown(keyCode: Int, event: KeyEvent?): Boolean = TODO()
    open fun onKeyUp(keyCode: Int, event: KeyEvent?): Boolean = TODO()
    open fun onKeyLongPress(keyCode: Int, event: KeyEvent?): Boolean = TODO()
    open fun onKeyMultiple(keyCode: Int, repeatCount: Int, event: KeyEvent?): Boolean = TODO()
    open fun onTouchEvent(event: MotionEvent?): Boolean = TODO()
    open fun onHoverEvent(event: MotionEvent?): Boolean = TODO()
    open fun onGenericMotionEvent(event: MotionEvent?): Boolean = TODO()
    open fun onDragEvent(event: DragEvent?): Boolean = TODO()
    open fun onCreateInputConnection(outAttrs: EditorInfo?): InputConnection? = TODO()
    open fun onCheckIsTextEditor(): Boolean = TODO()
    open fun performHapticFeedback(feedbackConstant: Int): Boolean = TODO()
    open fun performClick(): Boolean = TODO()
    open fun setPointerIcon(pointerIcon: PointerIcon?): Unit = TODO()
    open fun startDragAndDrop(data: ClipData?, shadowBuilder: DragShadowBuilder?, myLocalState: Any?, flags: Int): Boolean = TODO()
    open fun updateDragShadow(shadowBuilder: DragShadowBuilder?): Unit = TODO()

    // --- accessibility
    open fun setAccessibilityDelegate(delegate: AccessibilityDelegate?): Unit = TODO()
    open fun setImportantForAccessibility(mode: Int): Unit = TODO()
    open fun sendAccessibilityEvent(eventType: Int): Unit = TODO()
    open fun onInitializeAccessibilityNodeInfo(info: AccessibilityNodeInfo?): Unit = TODO()
    open fun onInitializeAccessibilityEvent(event: AccessibilityEvent?): Unit = TODO()
    open fun performAccessibilityAction(action: Int, arguments: Bundle?): Boolean = TODO()
    open fun getAccessibilityNodeProvider(): AccessibilityNodeProvider? = TODO()

    // --- autofill
    open fun getAutofillId(): AutofillId? = TODO()
    open fun autofill(values: SparseArray<AutofillValue>?): Unit = TODO()
    open fun onProvideAutofillVirtualStructure(structure: ViewStructure?, flags: Int): Unit = TODO()
    open fun isVisibleToUserForAutofill(virtualId: Int): Boolean = TODO()

    companion object {
        const val NO_ID: Int = -1
        const val VISIBLE: Int = 0
        const val INVISIBLE: Int = 4
        const val GONE: Int = 8
        const val IMPORTANT_FOR_ACCESSIBILITY_AUTO: Int = 0
        const val IMPORTANT_FOR_ACCESSIBILITY_YES: Int = 1
        const val IMPORTANT_FOR_ACCESSIBILITY_NO: Int = 2
        const val AUTOFILL_TYPE_NONE: Int = 0
        const val AUTOFILL_TYPE_TEXT: Int = 1
        const val AUTOFILL_HINT_EMAIL_ADDRESS: String = "emailAddress"
        const val AUTOFILL_HINT_PASSWORD: String = "password"
        const val AUTOFILL_HINT_USERNAME: String = "username"
        const val AUTOFILL_HINT_PHONE: String = "phone"
        const val DRAG_FLAG_GLOBAL: Int = 256
        const val FOCUS_LEFT: Int = 17
        const val FOCUS_UP: Int = 33
        const val FOCUS_RIGHT: Int = 66
        const val FOCUS_DOWN: Int = 130
    }
}

interface ViewParent {
    fun requestLayout()
    fun invalidateChild(child: View?, r: Rect?)
    fun getParent(): ViewParent?
    fun requestSendAccessibilityEvent(child: View?, event: AccessibilityEvent?): Boolean
}

interface ViewManager {
    fun addView(view: View?, params: ViewGroup.LayoutParams?)
    fun updateViewLayout(view: View?, params: ViewGroup.LayoutParams?)
    fun removeView(view: View?)
}

open class ViewGroup : View {
    constructor(context: Context?) : super(context) {}
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs) {}
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {}

    open class LayoutParams {
        var width: Int = 0
        var height: Int = 0
        constructor(width: Int, height: Int) { this.width = width; this.height = height }
        constructor(source: LayoutParams?) {}
        companion object {
            const val MATCH_PARENT: Int = -1
            const val WRAP_CONTENT: Int = -2
            const val FILL_PARENT: Int = -1
        }
    }

    open class MarginLayoutParams : LayoutParams {
        var leftMargin: Int = 0
        var topMargin: Int = 0
        var rightMargin: Int = 0
        var bottomMargin: Int = 0
        constructor(width: Int, height: Int) : super(width, height) {}
        constructor(source: LayoutParams?) : super(source) {}
    }

    open fun addView(child: View?): Unit = TODO()
    open fun addView(child: View?, index: Int): Unit = TODO()
    open fun addView(child: View?, params: LayoutParams?): Unit = TODO()
    open fun addView(child: View?, index: Int, params: LayoutParams?): Unit = TODO()
    open fun removeView(child: View?): Unit = TODO()
    open fun removeAllViews(): Unit = TODO()
    open fun getChildAt(index: Int): View? = TODO()
    open fun getChildCount(): Int = TODO()
    open fun setDescendantFocusability(focusability: Int): Unit = TODO()
    open fun onLayout(changed: Boolean, l: Int, t: Int, r: Int, b: Int): Unit = TODO()

    companion object {
        const val FOCUS_BEFORE_DESCENDANTS: Int = 131072
        const val FOCUS_AFTER_DESCENDANTS: Int = 262144
        const val FOCUS_BLOCK_DESCENDANTS: Int = 393216
    }
}

// ---------------------------------------------------------------- ViewStructure

open class ViewStructure {
    open class HtmlInfo {
        open class Builder {
            open fun addAttribute(name: String?, value: String?): Builder = TODO()
            open fun build(): HtmlInfo = TODO()
        }
        open fun getTag(): String? = TODO()
    }

    open fun newChild(index: Int): ViewStructure = TODO()
    open fun asyncNewChild(index: Int): ViewStructure = TODO()
    open fun newHtmlInfoBuilder(tagName: String?): HtmlInfo.Builder = TODO()
    open fun setId(id: Int, packageName: String?, typeName: String?, entryName: String?): Unit = TODO()
    open fun setAutofillId(parentId: AutofillId?, virtualId: Int): Unit = TODO()
    open fun getAutofillId(): AutofillId? = TODO()
    open fun setAutofillType(type: Int): Unit = TODO()
    open fun setAutofillHints(hints: Array<String?>?): Unit = TODO()
    open fun setAutofillOptions(options: Array<CharSequence?>?): Unit = TODO()
    open fun setAutofillValue(value: AutofillValue?): Unit = TODO()
    open fun setHtmlInfo(htmlInfo: HtmlInfo?): Unit = TODO()
    open fun setChildCount(num: Int): Unit = TODO()
    open fun addChildCount(num: Int): Int = TODO()
    open fun getChildCount(): Int = TODO()
    open fun setClassName(className: String?): Unit = TODO()
    open fun setContentDescription(contentDescription: CharSequence?): Unit = TODO()
    open fun setDimens(left: Int, top: Int, scrollX: Int, scrollY: Int, width: Int, height: Int): Unit = TODO()
    open fun setEnabled(state: Boolean): Unit = TODO()
    open fun setFocusable(state: Boolean): Unit = TODO()
    open fun setFocused(state: Boolean): Unit = TODO()
    open fun setClickable(state: Boolean): Unit = TODO()
    open fun setLongClickable(state: Boolean): Unit = TODO()
    open fun setSelected(state: Boolean): Unit = TODO()
    open fun setChecked(state: Boolean): Unit = TODO()
    open fun setInputType(inputType: Int): Unit = TODO()
    open fun setVisibility(visibility: Int): Unit = TODO()
    open fun setWebDomain(domain: String?): Unit = TODO()
    open fun setText(text: CharSequence?): Unit = TODO()
    open fun setText(text: CharSequence?, selectionStart: Int, selectionEnd: Int): Unit = TODO()
    open fun setHint(hint: CharSequence?): Unit = TODO()
    open fun getExtras(): Bundle = TODO()
    open fun asyncCommit(): Unit = TODO()
}

// ---------------------------------------------------------------- Surface stack

open class Surface {
    constructor() {}
    constructor(surfaceTexture: SurfaceTexture?) {}
    constructor(surfaceControl: SurfaceControl?) {}

    open fun isValid(): Boolean = TODO()
    open fun release(): Unit = TODO()
    open fun lockCanvas(dirty: Rect?): Canvas = TODO()
    open fun unlockCanvasAndPost(canvas: Canvas?): Unit = TODO()
    open fun describeContents(): Int = TODO()
    open fun writeToParcel(dest: Parcel?, flags: Int): Unit = TODO()
    open fun readFromParcel(source: Parcel?): Unit = TODO()

    companion object {
        const val ROTATION_0: Int = 0
        const val ROTATION_90: Int = 1
        const val ROTATION_180: Int = 2
        const val ROTATION_270: Int = 3
        val CREATOR: SurfaceCreator = TODO()
    }
}

interface SurfaceCreator {
    fun createFromParcel(source: Parcel?): Surface
    fun newArray(size: Int): Array<Surface?>
}

open class SurfaceControl {
    open fun isValid(): Boolean = TODO()
    open fun release(): Unit = TODO()

    open class Builder {
        open fun setParent(parent: SurfaceControl?): Builder = TODO()
        open fun setName(name: String?): Builder = TODO()
        open fun setBufferSize(w: Int, h: Int): Builder = TODO()
        open fun build(): SurfaceControl = TODO()
    }

    open class Transaction {
        open fun reparent(sc: SurfaceControl?, newParent: SurfaceControl?): Transaction = TODO()
        open fun setVisibility(sc: SurfaceControl?, visible: Boolean): Transaction = TODO()
        open fun setBufferSize(sc: SurfaceControl?, w: Int, h: Int): Transaction = TODO()
        open fun apply(): Unit = TODO()
        open fun close(): Unit = TODO()
    }

    companion object {
        const val BUFFER_TRANSFORM_IDENTITY: Int = 0
    }
}

interface SurfaceHolder {
    interface Callback {
        fun surfaceCreated(holder: SurfaceHolder?)
        fun surfaceChanged(holder: SurfaceHolder?, format: Int, width: Int, height: Int)
        fun surfaceDestroyed(holder: SurfaceHolder?)
    }
    interface Callback2 : Callback {
        fun surfaceRedrawNeeded(holder: SurfaceHolder?)
    }
    fun addCallback(callback: Callback?)
    fun removeCallback(callback: Callback?)
    fun isCreating(): Boolean
    fun setType(type: Int)
    fun setFixedSize(width: Int, height: Int)
    fun setSizeFromLayout()
    fun setFormat(format: Int)
    fun setKeepScreenOn(screenOn: Boolean)
    fun lockCanvas(): Canvas?
    fun lockCanvas(dirty: Rect?): Canvas?
    fun unlockCanvasAndPost(canvas: Canvas?)
    fun getSurfaceFrame(): Rect
    fun getSurface(): Surface

    companion object {
        const val SURFACE_TYPE_NORMAL: Int = 0
        const val SURFACE_TYPE_HARDWARE: Int = 1
        const val SURFACE_TYPE_GPU: Int = 2
        const val SURFACE_TYPE_PUSH_BUFFERS: Int = 3
    }
}

open class SurfaceView : View {
    constructor(context: Context?) : super(context) {}
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs) {}
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {}

    open fun getHolder(): SurfaceHolder = TODO()
    open fun getSurfaceControl(): SurfaceControl? = TODO()
    open fun setZOrderOnTop(onTop: Boolean): Unit = TODO()
    open fun setZOrderMediaOverlay(isMediaOverlay: Boolean): Unit = TODO()
    open fun setSecure(isSecure: Boolean): Unit = TODO()
}

open class TextureView : View {
    constructor(context: Context?) : super(context) {}
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs) {}

    interface SurfaceTextureListener {
        fun onSurfaceTextureAvailable(surface: SurfaceTexture?, width: Int, height: Int)
        fun onSurfaceTextureSizeChanged(surface: SurfaceTexture?, width: Int, height: Int)
        fun onSurfaceTextureDestroyed(surface: SurfaceTexture?): Boolean
        fun onSurfaceTextureUpdated(surface: SurfaceTexture?)
    }

    open fun getSurfaceTexture(): SurfaceTexture? = TODO()
    open fun setSurfaceTexture(surfaceTexture: SurfaceTexture?): Unit = TODO()
    open fun setSurfaceTextureListener(listener: SurfaceTextureListener?): Unit = TODO()
    open fun getSurfaceTextureListener(): SurfaceTextureListener? = TODO()
    open fun isAvailable(): Boolean = TODO()
    open fun setOpaque(opaque: Boolean): Unit = TODO()
    open fun getBitmap(): Bitmap? = TODO()
}

// ---------------------------------------------------------------- input events

open class InputEvent {
    open fun getDevice(): InputDevice? = TODO()
    open fun getDeviceId(): Int = TODO()
    open fun getSource(): Int = TODO()
    open fun getEventTime(): Long = TODO()
}

open class MotionEvent : InputEvent() {
    open class PointerCoords {
        var x: Float = 0f
        var y: Float = 0f
        var pressure: Float = 0f
        var size: Float = 0f
        var orientation: Float = 0f
        var toolMajor: Float = 0f
        var toolMinor: Float = 0f
        var touchMajor: Float = 0f
        var touchMinor: Float = 0f
        open fun getAxisValue(axis: Int): Float = TODO()
        open fun setAxisValue(axis: Int, value: Float): Unit = TODO()
        open fun clear(): Unit = TODO()
    }

    open class PointerProperties {
        var id: Int = 0
        var toolType: Int = 0
        open fun clear(): Unit = TODO()
    }

    open fun getAction(): Int = TODO()
    open fun getActionMasked(): Int = TODO()
    open fun getActionIndex(): Int = TODO()
    open fun getButtonState(): Int = TODO()
    open fun getMetaState(): Int = TODO()
    open fun getDownTime(): Long = TODO()
    open fun getPointerCount(): Int = TODO()
    open fun getPointerId(index: Int): Int = TODO()
    open fun getToolType(index: Int): Int = TODO()
    open fun getPointerCoords(pointerIndex: Int, outPointerCoords: PointerCoords?): Unit = TODO()
    open fun getPointerProperties(pointerIndex: Int, outPointerProperties: PointerProperties?): Unit = TODO()
    open fun getHistorySize(): Int = TODO()
    open fun getHistoricalEventTime(pos: Int): Long = TODO()
    open fun getHistoricalPointerCoords(pointerIndex: Int, pos: Int, outPointerCoords: PointerCoords?): Unit = TODO()
    open fun getX(): Float = TODO()
    open fun getY(): Float = TODO()
    open fun getX(pointerIndex: Int): Float = TODO()
    open fun getY(pointerIndex: Int): Float = TODO()
    open fun getRawX(): Float = TODO()
    open fun getRawY(): Float = TODO()
    open fun getAxisValue(axis: Int): Float = TODO()
    open fun getAxisValue(axis: Int, pointerIndex: Int): Float = TODO()
    open fun recycle(): Unit = TODO()

    companion object {
        const val ACTION_MASK: Int = 255
        const val ACTION_DOWN: Int = 0
        const val ACTION_UP: Int = 1
        const val ACTION_MOVE: Int = 2
        const val ACTION_CANCEL: Int = 3
        const val ACTION_OUTSIDE: Int = 4
        const val ACTION_POINTER_DOWN: Int = 5
        const val ACTION_POINTER_UP: Int = 6
        const val ACTION_HOVER_MOVE: Int = 7
        const val ACTION_SCROLL: Int = 8
        const val ACTION_HOVER_ENTER: Int = 9
        const val ACTION_HOVER_EXIT: Int = 10
        const val ACTION_POINTER_INDEX_MASK: Int = 65280
        const val ACTION_POINTER_INDEX_SHIFT: Int = 8
        const val AXIS_X: Int = 0
        const val AXIS_Y: Int = 1
        const val AXIS_PRESSURE: Int = 2
        const val AXIS_SIZE: Int = 3
        const val AXIS_VSCROLL: Int = 9
        const val AXIS_HSCROLL: Int = 10
        const val AXIS_Z: Int = 11
        const val AXIS_RZ: Int = 14
        const val AXIS_HAT_X: Int = 15
        const val AXIS_HAT_Y: Int = 16
        const val AXIS_LTRIGGER: Int = 17
        const val AXIS_RTRIGGER: Int = 18
        const val AXIS_TILT: Int = 25
        const val AXIS_GAS: Int = 22
        const val AXIS_BRAKE: Int = 23
        const val TOOL_TYPE_UNKNOWN: Int = 0
        const val TOOL_TYPE_FINGER: Int = 1
        const val TOOL_TYPE_STYLUS: Int = 2
        const val TOOL_TYPE_MOUSE: Int = 3
        const val TOOL_TYPE_ERASER: Int = 4
        const val BUTTON_PRIMARY: Int = 1
        const val BUTTON_SECONDARY: Int = 2
        const val BUTTON_TERTIARY: Int = 4

        fun obtain(other: MotionEvent?): MotionEvent = TODO()
        fun obtain(downTime: Long, eventTime: Long, action: Int, x: Float, y: Float, metaState: Int): MotionEvent = TODO()
        fun obtain(
            downTime: Long,
            eventTime: Long,
            action: Int,
            pointerCount: Int,
            pointerProperties: Array<PointerProperties?>?,
            pointerCoords: Array<PointerCoords?>?,
            metaState: Int,
            buttonState: Int,
            xPrecision: Float,
            yPrecision: Float,
            deviceId: Int,
            edgeFlags: Int,
            source: Int,
            flags: Int
        ): MotionEvent = TODO()
    }
}

open class KeyEvent : InputEvent {
    constructor(action: Int, code: Int) {}
    constructor(downTime: Long, eventTime: Long, action: Int, code: Int, repeat: Int) {}
    constructor(downTime: Long, eventTime: Long, action: Int, code: Int, repeat: Int, metaState: Int) {}
    constructor(origEvent: KeyEvent?, action: Int) {}
    constructor(time: Long, characters: String?, deviceId: Int, flags: Int) {}

    open fun getAction(): Int = TODO()
    open fun getKeyCode(): Int = TODO()
    open fun getRepeatCount(): Int = TODO()
    open fun getMetaState(): Int = TODO()
    open fun getFlags(): Int = TODO()
    open fun getDownTime(): Long = TODO()
    open fun getScanCode(): Int = TODO()
    open fun getUnicodeChar(): Int = TODO()
    open fun getUnicodeChar(metaState: Int): Int = TODO()
    open fun getCharacters(): String? = TODO()
    open fun getNumber(): Char = TODO()
    open fun hasNoModifiers(): Boolean = TODO()
    open fun isShiftPressed(): Boolean = TODO()
    open fun isCtrlPressed(): Boolean = TODO()
    open fun isAltPressed(): Boolean = TODO()
    open fun isSystem(): Boolean = TODO()
    open fun getActionMasked(): Int = TODO()

    companion object {
        fun isModifierKey(keyCode: Int): Boolean = TODO()
        fun getMaxKeyCode(): Int = TODO()
        fun changeAction(event: KeyEvent?, action: Int): KeyEvent = TODO()

        const val ACTION_DOWN: Int = 0
        const val ACTION_UP: Int = 1
        const val ACTION_MULTIPLE: Int = 2
        const val FLAG_EDITOR_ACTION: Int = 16
        const val FLAG_SOFT_KEYBOARD: Int = 2
        const val META_ALT_MASK: Int = 50
        const val META_CTRL_MASK: Int = 28672
        const val META_META_MASK: Int = 458752
        const val META_SHIFT_MASK: Int = 193
        const val KEYCODE_UNKNOWN: Int = 0
        const val KEYCODE_BACK: Int = 4
        const val KEYCODE_MENU: Int = 82
        const val KEYCODE_SEARCH: Int = 84
        const val KEYCODE_TAB: Int = 61
        const val KEYCODE_ENTER: Int = 66
        const val KEYCODE_DEL: Int = 67
        const val KEYCODE_FORWARD_DEL: Int = 112
        const val KEYCODE_FORWARD: Int = 125
        const val KEYCODE_NUMPAD_ENTER: Int = 160
        const val KEYCODE_DPAD_UP: Int = 19
        const val KEYCODE_DPAD_DOWN: Int = 20
        const val KEYCODE_DPAD_LEFT: Int = 21
        const val KEYCODE_DPAD_RIGHT: Int = 22
        const val KEYCODE_DPAD_CENTER: Int = 23
        const val KEYCODE_VOLUME_UP: Int = 24
        const val KEYCODE_VOLUME_DOWN: Int = 25
        const val KEYCODE_VOLUME_MUTE: Int = 164
        const val KEYCODE_MUTE: Int = 91
        const val KEYCODE_HEADSETHOOK: Int = 79
        const val KEYCODE_MEDIA_PLAY: Int = 126
        const val KEYCODE_MEDIA_PAUSE: Int = 127
        const val KEYCODE_MEDIA_PLAY_PAUSE: Int = 85
        const val KEYCODE_MEDIA_STOP: Int = 86
        const val KEYCODE_MEDIA_NEXT: Int = 87
        const val KEYCODE_MEDIA_PREVIOUS: Int = 88
        const val KEYCODE_MEDIA_REWIND: Int = 89
        const val KEYCODE_MEDIA_FAST_FORWARD: Int = 90
        const val KEYCODE_MEDIA_RECORD: Int = 130
        const val KEYCODE_MEDIA_CLOSE: Int = 128
        const val KEYCODE_MEDIA_EJECT: Int = 129
        const val KEYCODE_BUTTON_A: Int = 96
        const val KEYCODE_BUTTON_B: Int = 97
        const val KEYCODE_BUTTON_X: Int = 99
        const val KEYCODE_BUTTON_Y: Int = 100
        const val KEYCODE_BUTTON_L1: Int = 102
        const val KEYCODE_BUTTON_R1: Int = 103
        const val KEYCODE_BUTTON_L2: Int = 104
        const val KEYCODE_BUTTON_R2: Int = 105
        const val KEYCODE_BUTTON_THUMBL: Int = 106
        const val KEYCODE_BUTTON_THUMBR: Int = 107
        const val KEYCODE_BUTTON_START: Int = 108
        const val KEYCODE_BUTTON_SELECT: Int = 109
    }
}

open class InputDevice {
    open class MotionRange {
        open fun getAxis(): Int = TODO()
        open fun getSource(): Int = TODO()
        open fun getMin(): Float = TODO()
        open fun getMax(): Float = TODO()
        open fun getRange(): Float = TODO()
        open fun getFlat(): Float = TODO()
        open fun getFuzz(): Float = TODO()
    }

    open fun getId(): Int = TODO()
    open fun getName(): String? = TODO()
    open fun getSources(): Int = TODO()
    open fun getMotionRange(axis: Int): MotionRange? = TODO()
    open fun getMotionRange(axis: Int, source: Int): MotionRange? = TODO()
    open fun getVendorId(): Int = TODO()
    open fun getProductId(): Int = TODO()
    open fun isVirtual(): Boolean = TODO()

    companion object {
        fun getDevice(id: Int): InputDevice? = TODO()
        fun getDeviceIds(): IntArray = TODO()

        const val SOURCE_CLASS_MASK: Int = 255
        const val SOURCE_CLASS_BUTTON: Int = 1
        const val SOURCE_CLASS_POINTER: Int = 2
        const val SOURCE_CLASS_TRACKBALL: Int = 4
        const val SOURCE_CLASS_POSITION: Int = 8
        const val SOURCE_CLASS_JOYSTICK: Int = 16
        const val SOURCE_KEYBOARD: Int = 257
        const val SOURCE_DPAD: Int = 513
        const val SOURCE_GAMEPAD: Int = 1025
        const val SOURCE_TOUCHSCREEN: Int = 4098
        const val SOURCE_MOUSE: Int = 8194
        const val SOURCE_STYLUS: Int = 16386
        const val SOURCE_BLUETOOTH_STYLUS: Int = 49154
        const val SOURCE_TRACKBALL: Int = 65540
        const val SOURCE_TOUCHPAD: Int = 1048584
        const val SOURCE_JOYSTICK: Int = 16777232
    }
}

open class DragEvent {
    open fun getAction(): Int = TODO()
    open fun getX(): Float = TODO()
    open fun getY(): Float = TODO()
    open fun getClipData(): ClipData? = TODO()
    open fun getClipDescription(): ClipDescription? = TODO()
    open fun getLocalState(): Any? = TODO()
    open fun getResult(): Boolean = TODO()

    companion object {
        const val ACTION_DRAG_STARTED: Int = 1
        const val ACTION_DRAG_LOCATION: Int = 2
        const val ACTION_DROP: Int = 3
        const val ACTION_DRAG_ENDED: Int = 4
        const val ACTION_DRAG_ENTERED: Int = 5
        const val ACTION_DRAG_EXITED: Int = 6
    }
}

// ---------------------------------------------------------------- window / display

open class Window {
    open fun getDecorView(): View = TODO()
    open fun setSoftInputMode(mode: Int): Unit = TODO()
    open fun getAttributes(): WindowManager.LayoutParams? = TODO()
    open fun setAttributes(params: WindowManager.LayoutParams?): Unit = TODO()
}

open class WindowMetrics {
    open fun getBounds(): Rect = TODO()
    open fun getWindowInsets(): WindowInsets = TODO()
}

interface WindowManager : ViewManager {
    open class LayoutParams : ViewGroup.LayoutParams {
        var type: Int = 0
        var flags: Int = 0
        var token: IBinder? = null
        var softInputMode: Int = 0
        constructor() : super(MATCH_PARENT, MATCH_PARENT) {}
        constructor(type: Int) : super(MATCH_PARENT, MATCH_PARENT) {}
        companion object {
            const val TYPE_APPLICATION: Int = 2
            const val TYPE_APPLICATION_PANEL: Int = 1000
            const val FLAG_SECURE: Int = 8192
            const val SOFT_INPUT_STATE_HIDDEN: Int = 2
        }
    }
    fun getDefaultDisplay(): Display
    fun getCurrentWindowMetrics(): WindowMetrics
    fun getMaximumWindowMetrics(): WindowMetrics
}

open class WindowInsets {
    object Type {
        fun ime(): Int = TODO()
        fun statusBars(): Int = TODO()
        fun navigationBars(): Int = TODO()
        fun systemBars(): Int = TODO()
        fun displayCutout(): Int = TODO()
        fun captionBar(): Int = TODO()
    }
    open fun getInsets(typeMask: Int): Insets = TODO()
    open fun getDisplayCutout(): DisplayCutout? = TODO()
    open fun getSystemWindowInsetTop(): Int = TODO()
    open fun getSystemWindowInsetBottom(): Int = TODO()
    open fun getSystemWindowInsetLeft(): Int = TODO()
    open fun getSystemWindowInsetRight(): Int = TODO()
    open fun isVisible(typeMask: Int): Boolean = TODO()
}

open class DisplayCutout {
    open fun getSafeInsetTop(): Int = TODO()
    open fun getSafeInsetBottom(): Int = TODO()
    open fun getSafeInsetLeft(): Int = TODO()
    open fun getSafeInsetRight(): Int = TODO()
}

open class Display {
    open class HdrCapabilities {
        open fun getSupportedHdrTypes(): IntArray = TODO()
        open fun getDesiredMaxLuminance(): Float = TODO()
        open fun getDesiredMinLuminance(): Float = TODO()
        open fun getDesiredMaxAverageLuminance(): Float = TODO()
    }
    open class Mode {
        open fun getPhysicalWidth(): Int = TODO()
        open fun getPhysicalHeight(): Int = TODO()
        open fun getRefreshRate(): Float = TODO()
    }

    open fun getDisplayId(): Int = TODO()
    open fun getName(): String? = TODO()
    open fun getRotation(): Int = TODO()
    open fun getRefreshRate(): Float = TODO()
    open fun getRealSize(outSize: Point?): Unit = TODO()
    open fun getSize(outSize: Point?): Unit = TODO()
    open fun getMetrics(outMetrics: android.util.DisplayMetrics?): Unit = TODO()
    open fun getRealMetrics(outMetrics: android.util.DisplayMetrics?): Unit = TODO()
    open fun isHdr(): Boolean = TODO()
    open fun getHdrCapabilities(): HdrCapabilities? = TODO()
    open fun getHdrSdrRatio(): Float = TODO()
    open fun getMode(): Mode? = TODO()

    companion object {
        const val DEFAULT_DISPLAY: Int = 0
        const val INVALID_DISPLAY: Int = -1
        const val STATE_OFF: Int = 1
        const val STATE_ON: Int = 2
    }
}

// ---------------------------------------------------------------- menus / action mode

interface Menu {
    fun add(title: CharSequence?): MenuItem
    fun add(groupId: Int, itemId: Int, order: Int, title: CharSequence?): MenuItem
    fun addSubMenu(groupId: Int, itemId: Int, order: Int, title: CharSequence?): SubMenu
    fun removeItem(id: Int)
    fun removeGroup(groupId: Int)
    fun clear()
    fun findItem(id: Int): MenuItem?
    fun size(): Int
    fun getItem(index: Int): MenuItem
    fun hasVisibleItems(): Boolean
    fun close()

    companion object {
        const val NONE: Int = 0
        const val FIRST: Int = 1
        const val CATEGORY_CONTAINER: Int = 65536
        const val CATEGORY_SYSTEM: Int = 131072
    }
}

interface SubMenu : Menu {
    fun setHeaderTitle(title: CharSequence?): SubMenu
    fun getItem(): MenuItem
}

interface MenuItem {
    fun getItemId(): Int
    fun getGroupId(): Int
    fun getOrder(): Int
    fun getTitle(): CharSequence?
    fun setTitle(title: CharSequence?): MenuItem
    fun setTitle(title: Int): MenuItem
    fun getIntent(): Intent?
    fun setIntent(intent: Intent?): MenuItem
    fun setEnabled(enabled: Boolean): MenuItem
    fun isEnabled(): Boolean
    fun setVisible(visible: Boolean): MenuItem
    fun isVisible(): Boolean
    fun setIcon(icon: Drawable?): MenuItem
    fun getSubMenu(): SubMenu?
}

abstract class ActionMode {
    interface Callback {
        fun onCreateActionMode(mode: ActionMode?, menu: Menu?): Boolean
        fun onPrepareActionMode(mode: ActionMode?, menu: Menu?): Boolean
        fun onActionItemClicked(mode: ActionMode?, item: MenuItem?): Boolean
        fun onDestroyActionMode(mode: ActionMode?)
    }

    abstract class Callback2 : Callback {
        open fun onGetContentRect(mode: ActionMode?, view: View?, outRect: Rect?): Unit = TODO()
    }

    open fun finish(): Unit = TODO()
    open fun invalidate(): Unit = TODO()
    open fun invalidateContentRect(): Unit = TODO()
    open fun getMenu(): Menu = TODO()
    open fun getTitle(): CharSequence? = TODO()
    open fun setTitle(title: CharSequence?): Unit = TODO()
    open fun setSubtitle(subtitle: CharSequence?): Unit = TODO()
    open fun getTag(): Any? = TODO()
    open fun setTag(tag: Any?): Unit = TODO()

    companion object {
        const val TYPE_PRIMARY: Int = 0
        const val TYPE_FLOATING: Int = 1
    }
}

// ---------------------------------------------------------------- misc

class Choreographer private constructor() {
    fun interface FrameCallback {
        fun doFrame(frameTimeNanos: Long)
    }
    fun postFrameCallback(callback: FrameCallback?): Unit = TODO()
    fun postFrameCallbackDelayed(callback: FrameCallback?, delayMillis: Long): Unit = TODO()
    fun removeFrameCallback(callback: FrameCallback?): Unit = TODO()
    fun postCallback(callbackType: Int, action: Runnable?, token: Any?): Unit = TODO()
    fun removeCallbacks(callbackType: Int, action: Runnable?, token: Any?): Unit = TODO()

    companion object {
        const val CALLBACK_INPUT: Int = 0
        const val CALLBACK_ANIMATION: Int = 1
        const val CALLBACK_TRAVERSAL: Int = 2
        fun getInstance(): Choreographer = TODO()
        fun getFrameDelay(): Long = TODO()
    }
}

open class PointerIcon {
    companion object {
        const val TYPE_NULL: Int = 0
        const val TYPE_ARROW: Int = 1000
        const val TYPE_DEFAULT: Int = 1000
        const val TYPE_TEXT: Int = 1008
        fun create(bitmap: Bitmap?, hotSpotX: Float, hotSpotY: Float): PointerIcon = TODO()
        fun getSystemIcon(context: Context?, type: Int): PointerIcon = TODO()
        fun load(resources: android.content.res.Resources?, resourceId: Int): PointerIcon = TODO()
    }
}

open class KeyCharacterMap {
    class UnavailableException(message: String? = null) : RuntimeException(message)

    open fun getEvents(chars: CharArray?): Array<KeyEvent>? = TODO()
    open fun getDisplayLabel(keyCode: Int): Char = TODO()
    open fun get(keyCode: Int, metaState: Int): Int = TODO()
    open fun getKeyboardType(): Int = TODO()

    companion object {
        const val VIRTUAL_KEYBOARD: Int = -1
        const val BUILT_IN_KEYBOARD: Int = 0
        const val FULL: Int = 4
        fun load(deviceId: Int): KeyCharacterMap = TODO()
        fun deviceHasKey(keyCode: Int): Boolean = TODO()
    }
}

object HapticFeedbackConstants {
    const val LONG_PRESS: Int = 0
    const val VIRTUAL_KEY: Int = 1
    const val KEYBOARD_TAP: Int = 3
    const val CLOCK_TICK: Int = 4
    const val CONTEXT_CLICK: Int = 6
    const val KEYBOARD_PRESS: Int = 3
    const val KEYBOARD_RELEASE: Int = 7
    const val TEXT_HANDLE_MOVE: Int = 9
    const val CONFIRM: Int = 16
    const val REJECT: Int = 17
}

open class ContextThemeWrapper : ContextWrapper {
    constructor(base: Context?, themeResId: Int) : super(base) {}
    constructor(base: Context?, theme: android.content.res.Resources.Theme?) : super(base) {}
    open fun setTheme(resid: Int): Unit = TODO()
    // android.content.Context already declares these; the content slice makes them open.
    override fun obtainStyledAttributes(attrs: IntArray?): TypedArray = TODO()
    override fun obtainStyledAttributes(resid: Int, attrs: IntArray?): TypedArray = TODO()
}

open class LayoutInflater {
    open fun inflate(resource: Int, root: ViewGroup?): View = TODO()
    open fun inflate(resource: Int, root: ViewGroup?, attachToRoot: Boolean): View = TODO()
    companion object {
        fun from(context: Context?): LayoutInflater = TODO()
    }
}
"""),
    ('android.view.inputmethod', 'view_inputmethod.kt', """\
package android.view.inputmethod

import android.graphics.Matrix
import android.graphics.RectF
import android.net.Uri
import android.os.Bundle
import android.os.Handler
import android.text.Editable
import android.text.Spannable
import android.view.KeyEvent
import android.view.View

open class EditorInfo {
    var inputType: Int = 0
    var imeOptions: Int = 0
    var privateImeOptions: String? = null
    var actionLabel: CharSequence? = null
    var actionId: Int = 0
    var initialSelStart: Int = -1
    var initialSelEnd: Int = -1
    var initialCapsMode: Int = 0
    var hintText: CharSequence? = null
    var label: CharSequence? = null
    var packageName: String? = null
    var fieldId: Int = 0
    var fieldName: String? = null
    var extras: Bundle? = null
    var contentMimeTypes: Array<String?>? = null

    open fun setInitialSurroundingText(text: CharSequence?): Unit = TODO()
    open fun setInitialSurroundingSubText(subText: CharSequence?, subTextStart: Int): Unit = TODO()
    open fun getInitialSelectedText(flags: Int): CharSequence? = TODO()
    open fun getInitialTextBeforeCursor(length: Int, flags: Int): CharSequence? = TODO()
    open fun getInitialTextAfterCursor(length: Int, flags: Int): CharSequence? = TODO()
    open fun makeCompatible(targetSdkVersion: Int): Unit = TODO()

    companion object {
        const val IME_ACTION_UNSPECIFIED: Int = 0
        const val IME_ACTION_NONE: Int = 1
        const val IME_ACTION_GO: Int = 2
        const val IME_ACTION_SEARCH: Int = 3
        const val IME_ACTION_SEND: Int = 4
        const val IME_ACTION_NEXT: Int = 5
        const val IME_ACTION_DONE: Int = 6
        const val IME_ACTION_PREVIOUS: Int = 7
        const val IME_MASK_ACTION: Int = 255
        const val IME_FLAG_NO_FULLSCREEN: Int = 33554432
        const val IME_FLAG_NAVIGATE_PREVIOUS: Int = 67108864
        const val IME_FLAG_NAVIGATE_NEXT: Int = 134217728
        const val IME_FLAG_NO_EXTRACT_UI: Int = 268435456
        const val IME_FLAG_NO_ACCESSORY_ACTION: Int = 536870912
        const val IME_FLAG_NO_ENTER_ACTION: Int = 1073741824
        const val IME_FLAG_NO_PERSONALIZED_LEARNING: Int = 16777216
        const val IME_NULL: Int = 0
    }
}

open class ExtractedText {
    var text: CharSequence? = null
    var startOffset: Int = 0
    var partialStartOffset: Int = -1
    var partialEndOffset: Int = -1
    var selectionStart: Int = 0
    var selectionEnd: Int = 0
    var flags: Int = 0

    companion object {
        const val FLAG_SINGLE_LINE: Int = 1
        const val FLAG_SELECTING: Int = 2
    }
}

open class ExtractedTextRequest {
    var token: Int = 0
    var flags: Int = 0
    var hintMaxLines: Int = 0
    var hintMaxChars: Int = 0
}

open class CompletionInfo {
    open fun getId(): Long = TODO()
    open fun getPosition(): Int = TODO()
    open fun getText(): CharSequence? = TODO()
    open fun getLabel(): CharSequence? = TODO()
}

open class CorrectionInfo {
    open fun getOffset(): Int = TODO()
    open fun getOldText(): CharSequence? = TODO()
    open fun getNewText(): CharSequence? = TODO()
}

open class CursorAnchorInfo {
    open class Builder {
        open fun setSelectionRange(newStart: Int, newEnd: Int): Builder = TODO()
        open fun setComposingText(composingTextStart: Int, composingText: CharSequence?): Builder = TODO()
        open fun setInsertionMarkerLocation(
            horizontalPosition: Float,
            lineTop: Float,
            lineBaseline: Float,
            lineBottom: Float,
            flags: Int
        ): Builder = TODO()
        open fun addCharacterBounds(
            index: Int,
            left: Float,
            top: Float,
            right: Float,
            bottom: Float,
            flags: Int
        ): Builder = TODO()
        open fun setMatrix(matrix: Matrix?): Builder = TODO()
        open fun build(): CursorAnchorInfo = TODO()
        open fun reset(): Unit = TODO()
    }

    open fun getSelectionStart(): Int = TODO()
    open fun getSelectionEnd(): Int = TODO()
    open fun getComposingTextStart(): Int = TODO()
    open fun getComposingText(): CharSequence? = TODO()
    open fun getCharacterBounds(index: Int): RectF? = TODO()
    open fun getCharacterBoundsFlags(index: Int): Int = TODO()
    open fun getMatrix(): Matrix? = TODO()

    companion object {
        const val FLAG_HAS_VISIBLE_REGION: Int = 1
        const val FLAG_HAS_INVISIBLE_REGION: Int = 2
        const val FLAG_IS_RTL: Int = 4
    }
}

open class InputContentInfo {
    constructor(contentUri: Uri?, description: android.content.ClipDescription?) {}
    constructor(contentUri: Uri?, description: android.content.ClipDescription?, linkUri: Uri?) {}

    open fun getContentUri(): Uri = TODO()
    open fun getDescription(): android.content.ClipDescription = TODO()
    open fun getLinkUri(): Uri? = TODO()
    open fun requestPermission(): Unit = TODO()
    open fun releasePermission(): Unit = TODO()
}

open class InputMethodSubtype {
    open fun getLanguageTag(): String = TODO()
    open fun getLocale(): String = TODO()
    open fun getMode(): String = TODO()
    open fun getNameResId(): Int = TODO()
}

open class InputMethodInfo {
    open fun getId(): String = TODO()
    open fun getPackageName(): String = TODO()
    open fun getServiceName(): String = TODO()
    open fun getSettingsActivity(): String? = TODO()
    open fun getSubtypeCount(): Int = TODO()
    open fun getSubtypeAt(index: Int): InputMethodSubtype = TODO()
}

interface InputConnection {
    fun getTextBeforeCursor(n: Int, flags: Int): CharSequence?
    fun getTextAfterCursor(n: Int, flags: Int): CharSequence?
    fun getSelectedText(flags: Int): CharSequence?
    fun getCursorCapsMode(reqModes: Int): Int
    fun getExtractedText(request: ExtractedTextRequest?, flags: Int): ExtractedText?
    fun deleteSurroundingText(beforeLength: Int, afterLength: Int): Boolean
    fun deleteSurroundingTextInCodePoints(beforeLength: Int, afterLength: Int): Boolean
    fun setComposingText(text: CharSequence?, newCursorPosition: Int): Boolean
    fun setComposingRegion(start: Int, end: Int): Boolean
    fun finishComposingText(): Boolean
    fun commitText(text: CharSequence?, newCursorPosition: Int): Boolean
    fun commitCompletion(text: CompletionInfo?): Boolean
    fun commitCorrection(correctionInfo: CorrectionInfo?): Boolean
    fun setSelection(start: Int, end: Int): Boolean
    fun performEditorAction(editorAction: Int): Boolean
    fun performContextMenuAction(id: Int): Boolean
    fun beginBatchEdit(): Boolean
    fun endBatchEdit(): Boolean
    fun sendKeyEvent(event: KeyEvent?): Boolean
    fun clearMetaKeyStates(states: Int): Boolean
    fun reportFullscreenMode(enabled: Boolean): Boolean
    fun performPrivateCommand(action: String?, data: Bundle?): Boolean
    fun requestCursorUpdates(cursorUpdateMode: Int): Boolean
    fun getHandler(): Handler?
    fun closeConnection()
    fun commitContent(inputContentInfo: InputContentInfo?, flags: Int, opts: Bundle?): Boolean

    companion object {
        const val GET_TEXT_WITH_STYLES: Int = 1
        const val GET_EXTRACTED_TEXT_MONITOR: Int = 1
        const val CURSOR_UPDATE_IMMEDIATE: Int = 1
        const val CURSOR_UPDATE_MONITOR: Int = 2
        const val INPUT_CONTENT_GRANT_READ_URI_PERMISSION: Int = 1
    }
}

open class BaseInputConnection : InputConnection {
    constructor(targetView: View?, fullEditor: Boolean) {}

    open fun getEditable(): Editable? = TODO()
    open fun getView(): View? = TODO()

    override fun getTextBeforeCursor(n: Int, flags: Int): CharSequence? = TODO()
    override fun getTextAfterCursor(n: Int, flags: Int): CharSequence? = TODO()
    override fun getSelectedText(flags: Int): CharSequence? = TODO()
    override fun getCursorCapsMode(reqModes: Int): Int = TODO()
    override fun getExtractedText(request: ExtractedTextRequest?, flags: Int): ExtractedText? = TODO()
    override fun deleteSurroundingText(beforeLength: Int, afterLength: Int): Boolean = TODO()
    override fun deleteSurroundingTextInCodePoints(beforeLength: Int, afterLength: Int): Boolean = TODO()
    override fun setComposingText(text: CharSequence?, newCursorPosition: Int): Boolean = TODO()
    override fun setComposingRegion(start: Int, end: Int): Boolean = TODO()
    override fun finishComposingText(): Boolean = TODO()
    override fun commitText(text: CharSequence?, newCursorPosition: Int): Boolean = TODO()
    override fun commitCompletion(text: CompletionInfo?): Boolean = TODO()
    override fun commitCorrection(correctionInfo: CorrectionInfo?): Boolean = TODO()
    override fun setSelection(start: Int, end: Int): Boolean = TODO()
    override fun performEditorAction(editorAction: Int): Boolean = TODO()
    override fun performContextMenuAction(id: Int): Boolean = TODO()
    override fun beginBatchEdit(): Boolean = TODO()
    override fun endBatchEdit(): Boolean = TODO()
    override fun sendKeyEvent(event: KeyEvent?): Boolean = TODO()
    override fun clearMetaKeyStates(states: Int): Boolean = TODO()
    override fun reportFullscreenMode(enabled: Boolean): Boolean = TODO()
    override fun performPrivateCommand(action: String?, data: Bundle?): Boolean = TODO()
    override fun requestCursorUpdates(cursorUpdateMode: Int): Boolean = TODO()
    override fun getHandler(): Handler? = TODO()
    override fun closeConnection(): Unit = TODO()
    override fun commitContent(inputContentInfo: InputContentInfo?, flags: Int, opts: Bundle?): Boolean = TODO()

    companion object {
        fun getComposingSpanStart(text: Spannable?): Int = TODO()
        fun getComposingSpanEnd(text: Spannable?): Int = TODO()
        fun removeComposingSpans(text: Spannable?): Unit = TODO()
        fun setComposingSpans(text: Spannable?): Unit = TODO()
    }
}

open class InputMethodManager {
    open fun isActive(): Boolean = TODO()
    open fun isActive(view: View?): Boolean = TODO()
    open fun isFullscreenMode(): Boolean = TODO()
    open fun isAcceptingText(): Boolean = TODO()
    open fun restartInput(view: View?): Unit = TODO()
    open fun showSoftInput(view: View?, flags: Int): Boolean = TODO()
    open fun hideSoftInputFromWindow(windowToken: android.os.IBinder?, flags: Int): Boolean = TODO()
    open fun toggleSoftInput(showFlags: Int, hideFlags: Int): Unit = TODO()
    open fun updateSelection(
        view: View?,
        selStart: Int,
        selEnd: Int,
        candidatesStart: Int,
        candidatesEnd: Int
    ): Unit = TODO()
    open fun updateExtractedText(view: View?, token: Int, text: ExtractedText?): Unit = TODO()
    open fun updateCursorAnchorInfo(view: View?, cursorAnchorInfo: CursorAnchorInfo?): Unit = TODO()
    open fun getEnabledInputMethodList(): MutableList<InputMethodInfo> = TODO()
    open fun getInputMethodList(): MutableList<InputMethodInfo> = TODO()
    open fun getCurrentInputMethodSubtype(): InputMethodSubtype? = TODO()
    open fun getEnabledInputMethodSubtypeList(imi: InputMethodInfo?, allow: Boolean): MutableList<InputMethodSubtype> = TODO()

    companion object {
        const val SHOW_IMPLICIT: Int = 1
        const val SHOW_FORCED: Int = 2
        const val HIDE_IMPLICIT_ONLY: Int = 1
        const val HIDE_NOT_ALWAYS: Int = 2
    }
}
"""),
    ('android.view.accessibility', 'view_accessibility.kt', """\
package android.view.accessibility

import android.graphics.Rect
import android.os.Bundle
import android.view.View

open class AccessibilityRecord {
    open fun setSource(source: View?): Unit = TODO()
    open fun setSource(root: View?, virtualDescendantId: Int): Unit = TODO()
    open fun setClassName(className: CharSequence?): Unit = TODO()
    open fun setContentDescription(contentDescription: CharSequence?): Unit = TODO()
    open fun setEnabled(enabled: Boolean): Unit = TODO()
    open fun setChecked(checked: Boolean): Unit = TODO()
    open fun setPassword(password: Boolean): Unit = TODO()
    open fun setScrollable(scrollable: Boolean): Unit = TODO()
    open fun setBeforeText(beforeText: CharSequence?): Unit = TODO()
    open fun setAddedCount(addedCount: Int): Unit = TODO()
    open fun setRemovedCount(removedCount: Int): Unit = TODO()
    open fun setFromIndex(fromIndex: Int): Unit = TODO()
    open fun setToIndex(toIndex: Int): Unit = TODO()
    open fun setItemCount(itemCount: Int): Unit = TODO()
    open fun setCurrentItemIndex(currentItemIndex: Int): Unit = TODO()
    open fun setScrollX(scrollX: Int): Unit = TODO()
    open fun setScrollY(scrollY: Int): Unit = TODO()
    open fun setMaxScrollX(maxScrollX: Int): Unit = TODO()
    open fun setMaxScrollY(maxScrollY: Int): Unit = TODO()
    open fun getText(): MutableList<CharSequence> = TODO()
    open fun getFromIndex(): Int = TODO()
    open fun getToIndex(): Int = TODO()
    open fun getAddedCount(): Int = TODO()
    open fun getRemovedCount(): Int = TODO()
    open fun getItemCount(): Int = TODO()
    open fun getCurrentItemIndex(): Int = TODO()
}

open class AccessibilityEvent : AccessibilityRecord() {
    open fun getEventType(): Int = TODO()
    open fun setEventType(eventType: Int): Unit = TODO()
    open fun getPackageName(): CharSequence? = TODO()
    open fun setPackageName(packageName: CharSequence?): Unit = TODO()
    open fun getClassName(): CharSequence? = TODO()
    open fun getContentDescription(): CharSequence? = TODO()
    open fun getEventTime(): Long = TODO()
    open fun recycle(): Unit = TODO()

    companion object {
        fun obtain(): AccessibilityEvent = TODO()
        fun obtain(eventType: Int): AccessibilityEvent = TODO()
        fun obtain(event: AccessibilityEvent?): AccessibilityEvent = TODO()

        const val TYPE_VIEW_CLICKED: Int = 1
        const val TYPE_VIEW_LONG_CLICKED: Int = 2
        const val TYPE_VIEW_SELECTED: Int = 4
        const val TYPE_VIEW_FOCUSED: Int = 8
        const val TYPE_VIEW_TEXT_CHANGED: Int = 16
        const val TYPE_WINDOW_STATE_CHANGED: Int = 32
        const val TYPE_VIEW_HOVER_ENTER: Int = 128
        const val TYPE_VIEW_HOVER_EXIT: Int = 256
        const val TYPE_VIEW_SCROLLED: Int = 4096
        const val TYPE_VIEW_TEXT_SELECTION_CHANGED: Int = 8192
        const val TYPE_ANNOUNCEMENT: Int = 16384
        const val TYPE_VIEW_ACCESSIBILITY_FOCUSED: Int = 32768
        const val TYPE_VIEW_ACCESSIBILITY_FOCUS_CLEARED: Int = 65536
        const val TYPE_VIEW_TEXT_TRAVERSED_AT_MOVEMENT_GRANULARITY: Int = 131072
        const val TYPE_WINDOW_CONTENT_CHANGED: Int = 2048
        const val CONTENT_CHANGE_TYPE_SUBTREE: Int = 1
        const val CONTENT_CHANGE_TYPE_TEXT: Int = 2
    }
}

open class AccessibilityNodeInfo {
    open class AccessibilityAction {
        constructor(actionId: Int, label: CharSequence?) {}
        open fun getId(): Int = TODO()
        open fun getLabel(): CharSequence? = TODO()

        companion object {
            val ACTION_CLICK: AccessibilityAction = TODO()
            val ACTION_LONG_CLICK: AccessibilityAction = TODO()
            val ACTION_EXPAND: AccessibilityAction = TODO()
            val ACTION_COLLAPSE: AccessibilityAction = TODO()
            val ACTION_SCROLL_FORWARD: AccessibilityAction = TODO()
            val ACTION_SCROLL_BACKWARD: AccessibilityAction = TODO()
            val ACTION_SET_TEXT: AccessibilityAction = TODO()
            val ACTION_SET_SELECTION: AccessibilityAction = TODO()
            val ACTION_CUT: AccessibilityAction = TODO()
            val ACTION_COPY: AccessibilityAction = TODO()
            val ACTION_PASTE: AccessibilityAction = TODO()
            val ACTION_SELECT: AccessibilityAction = TODO()
            val ACTION_ACCESSIBILITY_FOCUS: AccessibilityAction = TODO()
            val ACTION_CLEAR_ACCESSIBILITY_FOCUS: AccessibilityAction = TODO()
        }
    }

    open class CollectionInfo {
        open fun getRowCount(): Int = TODO()
        open fun getColumnCount(): Int = TODO()
        open fun isHierarchical(): Boolean = TODO()
        open fun getSelectionMode(): Int = TODO()
        companion object {
            const val SELECTION_MODE_NONE: Int = 0
            const val SELECTION_MODE_SINGLE: Int = 1
            const val SELECTION_MODE_MULTIPLE: Int = 2
            fun obtain(rowCount: Int, columnCount: Int, hierarchical: Boolean): CollectionInfo = TODO()
            fun obtain(rowCount: Int, columnCount: Int, hierarchical: Boolean, selectionMode: Int): CollectionInfo = TODO()
        }
    }

    open class CollectionItemInfo {
        open fun getRowIndex(): Int = TODO()
        open fun getRowSpan(): Int = TODO()
        open fun getColumnIndex(): Int = TODO()
        open fun getColumnSpan(): Int = TODO()
        open fun isHeading(): Boolean = TODO()
        companion object {
            fun obtain(rowIndex: Int, rowSpan: Int, columnIndex: Int, columnSpan: Int, heading: Boolean): CollectionItemInfo = TODO()
            fun obtain(rowIndex: Int, rowSpan: Int, columnIndex: Int, columnSpan: Int, heading: Boolean, selected: Boolean): CollectionItemInfo = TODO()
        }
    }

    open class RangeInfo {
        open fun getType(): Int = TODO()
        open fun getMin(): Float = TODO()
        open fun getMax(): Float = TODO()
        open fun getCurrent(): Float = TODO()
        companion object {
            const val RANGE_TYPE_INT: Int = 0
            const val RANGE_TYPE_FLOAT: Int = 1
            const val RANGE_TYPE_PERCENT: Int = 2
            fun obtain(type: Int, min: Float, max: Float, current: Float): RangeInfo = TODO()
        }
    }

    open fun addAction(action: Int): Unit = TODO()
    open fun addAction(action: AccessibilityAction?): Unit = TODO()
    open fun removeAction(action: Int): Unit = TODO()
    open fun removeAction(action: AccessibilityAction?): Boolean = TODO()
    open fun addChild(child: View?): Unit = TODO()
    open fun addChild(root: View?, virtualDescendantId: Int): Unit = TODO()
    open fun setParent(parent: View?): Unit = TODO()
    open fun setParent(root: View?, virtualDescendantId: Int): Unit = TODO()
    open fun getBoundsInParent(outBounds: Rect?): Unit = TODO()
    open fun setBoundsInParent(bounds: Rect?): Unit = TODO()
    open fun getBoundsInScreen(outBounds: Rect?): Unit = TODO()
    open fun setBoundsInScreen(bounds: Rect?): Unit = TODO()
    open fun getExtras(): Bundle = TODO()
    open fun setSource(source: View?): Unit = TODO()
    open fun setSource(root: View?, virtualDescendantId: Int): Unit = TODO()
    open fun setPackageName(packageName: CharSequence?): Unit = TODO()
    open fun setClassName(className: CharSequence?): Unit = TODO()
    open fun getClassName(): CharSequence? = TODO()
    open fun setText(text: CharSequence?): Unit = TODO()
    open fun getText(): CharSequence? = TODO()
    open fun setHintText(hintText: CharSequence?): Unit = TODO()
    open fun setContentDescription(contentDescription: CharSequence?): Unit = TODO()
    open fun setViewIdResourceName(viewIdResName: String?): Unit = TODO()
    open fun setInputType(inputType: Int): Unit = TODO()
    open fun setMovementGranularities(granularities: Int): Unit = TODO()
    open fun setCollectionInfo(collectionInfo: CollectionInfo?): Unit = TODO()
    open fun setCollectionItemInfo(collectionItemInfo: CollectionItemInfo?): Unit = TODO()
    open fun setRangeInfo(rangeInfo: RangeInfo?): Unit = TODO()
    open fun setAccessibilityFocused(focused: Boolean): Unit = TODO()
    open fun setCheckable(checkable: Boolean): Unit = TODO()
    open fun setChecked(checked: Boolean): Unit = TODO()
    open fun setClickable(clickable: Boolean): Unit = TODO()
    open fun setLongClickable(longClickable: Boolean): Unit = TODO()
    open fun setContextClickable(contextClickable: Boolean): Unit = TODO()
    open fun setContentInvalid(contentInvalid: Boolean): Unit = TODO()
    open fun setEditable(editable: Boolean): Unit = TODO()
    open fun setEnabled(enabled: Boolean): Unit = TODO()
    open fun setFocusable(focusable: Boolean): Unit = TODO()
    open fun setFocused(focused: Boolean): Unit = TODO()
    open fun setMultiLine(multiLine: Boolean): Unit = TODO()
    open fun setPassword(password: Boolean): Unit = TODO()
    open fun setScrollable(scrollable: Boolean): Unit = TODO()
    open fun setSelected(selected: Boolean): Unit = TODO()
    open fun setVisibleToUser(visibleToUser: Boolean): Unit = TODO()
    open fun recycle(): Unit = TODO()

    companion object {
        fun obtain(): AccessibilityNodeInfo = TODO()
        fun obtain(source: View?): AccessibilityNodeInfo = TODO()
        fun obtain(root: View?, virtualDescendantId: Int): AccessibilityNodeInfo = TODO()
        fun obtain(info: AccessibilityNodeInfo?): AccessibilityNodeInfo = TODO()

        const val ACTION_FOCUS: Int = 1
        const val ACTION_CLEAR_FOCUS: Int = 2
        const val ACTION_SELECT: Int = 4
        const val ACTION_CLEAR_SELECTION: Int = 8
        const val ACTION_CLICK: Int = 16
        const val ACTION_LONG_CLICK: Int = 32
        const val ACTION_ACCESSIBILITY_FOCUS: Int = 64
        const val ACTION_CLEAR_ACCESSIBILITY_FOCUS: Int = 128
        const val ACTION_NEXT_AT_MOVEMENT_GRANULARITY: Int = 256
        const val ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: Int = 512
        const val ACTION_NEXT_HTML_ELEMENT: Int = 1024
        const val ACTION_PREVIOUS_HTML_ELEMENT: Int = 2048
        const val ACTION_SCROLL_FORWARD: Int = 4096
        const val ACTION_SCROLL_BACKWARD: Int = 8192
        const val ACTION_COPY: Int = 16384
        const val ACTION_PASTE: Int = 32768
        const val ACTION_CUT: Int = 65536
        const val ACTION_SET_SELECTION: Int = 131072
        const val ACTION_EXPAND: Int = 262144
        const val ACTION_COLLAPSE: Int = 524288
        const val ACTION_SET_TEXT: Int = 2097152

        const val ACTION_ARGUMENT_HTML_ELEMENT_STRING: String = "ACTION_ARGUMENT_HTML_ELEMENT_STRING"
        const val ACTION_ARGUMENT_MOVEMENT_GRANULARITY_INT: String = "ACTION_ARGUMENT_MOVEMENT_GRANULARITY_INT"
        const val ACTION_ARGUMENT_EXTEND_SELECTION_BOOLEAN: String = "ACTION_ARGUMENT_EXTEND_SELECTION_BOOLEAN"
        const val ACTION_ARGUMENT_SELECTION_START_INT: String = "ACTION_ARGUMENT_SELECTION_START_INT"
        const val ACTION_ARGUMENT_SELECTION_END_INT: String = "ACTION_ARGUMENT_SELECTION_END_INT"
        const val ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE: String = "ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE"

        const val MOVEMENT_GRANULARITY_CHARACTER: Int = 1
        const val MOVEMENT_GRANULARITY_WORD: Int = 2
        const val MOVEMENT_GRANULARITY_LINE: Int = 4
        const val MOVEMENT_GRANULARITY_PARAGRAPH: Int = 8
        const val MOVEMENT_GRANULARITY_PAGE: Int = 16

        const val FOCUS_INPUT: Int = 1
        const val FOCUS_ACCESSIBILITY: Int = 2
    }
}

open class AccessibilityNodeProvider {
    open fun createAccessibilityNodeInfo(virtualViewId: Int): AccessibilityNodeInfo? = TODO()
    open fun performAction(virtualViewId: Int, action: Int, arguments: Bundle?): Boolean = TODO()
    open fun findAccessibilityNodeInfosByText(text: String?, virtualViewId: Int): MutableList<AccessibilityNodeInfo>? = TODO()
    open fun findFocus(focus: Int): AccessibilityNodeInfo? = TODO()

    companion object {
        const val HOST_VIEW_ID: Int = -1
    }
}

open class AccessibilityManager {
    fun interface AccessibilityStateChangeListener {
        fun onAccessibilityStateChanged(enabled: Boolean)
    }
    fun interface TouchExplorationStateChangeListener {
        fun onTouchExplorationStateChanged(enabled: Boolean)
    }

    open fun isEnabled(): Boolean = TODO()
    open fun isTouchExplorationEnabled(): Boolean = TODO()
    open fun sendAccessibilityEvent(event: AccessibilityEvent?): Unit = TODO()
    open fun addAccessibilityStateChangeListener(listener: AccessibilityStateChangeListener?): Boolean = TODO()
    open fun removeAccessibilityStateChangeListener(listener: AccessibilityStateChangeListener?): Boolean = TODO()
    open fun addTouchExplorationStateChangeListener(listener: TouchExplorationStateChangeListener?): Boolean = TODO()
    open fun removeTouchExplorationStateChangeListener(listener: TouchExplorationStateChangeListener?): Boolean = TODO()
}
"""),
    ('android.view.autofill', 'view_autofill.kt', """\
package android.view.autofill

import android.graphics.Rect
import android.view.View

open class AutofillId {
    open fun getViewId(): Int = TODO()
}

open class AutofillValue {
    open fun isText(): Boolean = TODO()
    open fun isToggle(): Boolean = TODO()
    open fun isList(): Boolean = TODO()
    open fun isDate(): Boolean = TODO()
    open fun getTextValue(): CharSequence = TODO()
    open fun getToggleValue(): Boolean = TODO()
    open fun getListValue(): Int = TODO()
    open fun getDateValue(): Long = TODO()

    companion object {
        fun forText(value: CharSequence?): AutofillValue = TODO()
        fun forToggle(value: Boolean): AutofillValue = TODO()
        fun forList(value: Int): AutofillValue = TODO()
        fun forDate(value: Long): AutofillValue = TODO()
    }
}

open class AutofillManager {
    open fun notifyViewEntered(view: View?): Unit = TODO()
    open fun notifyViewEntered(view: View?, virtualId: Int, absBounds: Rect?): Unit = TODO()
    open fun notifyViewExited(view: View?): Unit = TODO()
    open fun notifyViewExited(view: View?, virtualId: Int): Unit = TODO()
    open fun notifyValueChanged(view: View?): Unit = TODO()
    open fun notifyValueChanged(view: View?, virtualId: Int, value: AutofillValue?): Unit = TODO()
    open fun notifyViewVisibilityChanged(view: View?, virtualId: Int, isVisible: Boolean): Unit = TODO()
    open fun commit(): Unit = TODO()
    open fun cancel(): Unit = TODO()
    open fun isEnabled(): Boolean = TODO()
    open fun requestAutofill(view: View?, virtualId: Int, absBounds: Rect?): Unit = TODO()
}
"""),
    ('android.widget', 'widget.kt', """\
package android.widget

import android.content.Context
import android.graphics.BlendMode
import android.graphics.Bitmap
import android.graphics.Canvas
import android.util.AttributeSet
import android.view.View
import android.view.ViewGroup

open class FrameLayout : ViewGroup {
    constructor(context: Context?) : super(context) {}
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs) {}
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {}

    open class LayoutParams : ViewGroup.MarginLayoutParams {
        var gravity: Int = -1
        constructor(width: Int, height: Int) : super(width, height) {}
        constructor(width: Int, height: Int, gravity: Int) : super(width, height) { this.gravity = gravity }
        constructor(source: ViewGroup.LayoutParams?) : super(source) {}
    }

    open fun setForegroundGravity(foregroundGravity: Int): Unit = TODO()
    open fun setMeasureAllChildren(measureAll: Boolean): Unit = TODO()
}

open class EdgeEffect {
    constructor(context: Context?) {}

    open fun setSize(width: Int, height: Int): Unit = TODO()
    open fun isFinished(): Boolean = TODO()
    open fun finish(): Unit = TODO()
    open fun onPull(deltaDistance: Float): Unit = TODO()
    open fun onPull(deltaDistance: Float, displacement: Float): Unit = TODO()
    open fun onRelease(): Unit = TODO()
    open fun onAbsorb(velocity: Int): Unit = TODO()
    open fun setColor(color: Int): Unit = TODO()
    open fun getColor(): Int = TODO()
    open fun setBlendMode(blendmode: BlendMode?): Unit = TODO()
    open fun draw(canvas: Canvas?): Boolean = TODO()
    open fun getDistance(): Float = TODO()
}

open class Magnifier {
    constructor(view: View?) {}

    open fun show(sourceCenterX: Float, sourceCenterY: Float): Unit = TODO()
    open fun show(sourceCenterX: Float, sourceCenterY: Float, magnifierCenterX: Float, magnifierCenterY: Float): Unit = TODO()
    open fun update(): Unit = TODO()
    open fun dismiss(): Unit = TODO()
    open fun getWidth(): Int = TODO()
    open fun getHeight(): Int = TODO()
    open fun getContent(): Bitmap? = TODO()
}
"""),
    ('android.print', 'print.kt', """\
package android.print

import android.os.Bundle
import android.os.CancellationSignal
import android.os.ParcelFileDescriptor

open class PageRange {
    constructor(start: Int, end: Int) {}
    open fun getStart(): Int = TODO()
    open fun getEnd(): Int = TODO()

    companion object {
        val ALL_PAGES: PageRange = TODO()
    }
}

open class PrintAttributes {
    open class MediaSize {
        companion object {
            val ISO_A4: MediaSize = TODO()
            val NA_LETTER: MediaSize = TODO()
        }
    }
    open class Resolution {
        constructor(id: String?, label: String?, horizontalDpi: Int, verticalDpi: Int) {}
    }
    open class Margins {
        constructor(leftMils: Int, topMils: Int, rightMils: Int, bottomMils: Int) {}
    }
    open class Builder {
        open fun setMediaSize(mediaSize: MediaSize?): Builder = TODO()
        open fun setResolution(resolution: Resolution?): Builder = TODO()
        open fun setMinMargins(margins: Margins?): Builder = TODO()
        open fun setColorMode(colorMode: Int): Builder = TODO()
        open fun build(): PrintAttributes = TODO()
    }

    open fun getMediaSize(): MediaSize? = TODO()
    open fun getResolution(): Resolution? = TODO()
    open fun getMinMargins(): Margins? = TODO()
    open fun getColorMode(): Int = TODO()

    companion object {
        const val COLOR_MODE_MONOCHROME: Int = 1
        const val COLOR_MODE_COLOR: Int = 2
    }
}

open class PrintDocumentInfo {
    open class Builder {
        constructor(name: String?) {}
        open fun setContentType(type: Int): Builder = TODO()
        open fun setPageCount(pageCount: Int): Builder = TODO()
        open fun build(): PrintDocumentInfo = TODO()
    }

    open fun getName(): String? = TODO()
    open fun getPageCount(): Int = TODO()
    open fun getContentType(): Int = TODO()

    companion object {
        const val PAGE_COUNT_UNKNOWN: Int = -1
        const val CONTENT_TYPE_UNKNOWN: Int = -1
        const val CONTENT_TYPE_DOCUMENT: Int = 0
        const val CONTENT_TYPE_PHOTO: Int = 1
    }
}

open class PrintJob {
    open fun getId(): Any? = TODO()
    open fun cancel(): Unit = TODO()
    open fun restart(): Unit = TODO()
    open fun isQueued(): Boolean = TODO()
    open fun isCompleted(): Boolean = TODO()
    open fun isFailed(): Boolean = TODO()
    open fun isCancelled(): Boolean = TODO()
}

abstract class PrintDocumentAdapter {
    abstract class LayoutResultCallback {
        open fun onLayoutFinished(info: PrintDocumentInfo?, changed: Boolean): Unit = TODO()
        open fun onLayoutFailed(error: CharSequence?): Unit = TODO()
        open fun onLayoutCancelled(): Unit = TODO()
    }

    abstract class WriteResultCallback {
        open fun onWriteFinished(pages: Array<PageRange>?): Unit = TODO()
        open fun onWriteFailed(error: CharSequence?): Unit = TODO()
        open fun onWriteCancelled(): Unit = TODO()
    }

    open fun onStart(): Unit = TODO()

    abstract fun onLayout(
        oldAttributes: PrintAttributes?,
        newAttributes: PrintAttributes?,
        cancellationSignal: CancellationSignal?,
        callback: LayoutResultCallback?,
        extras: Bundle?
    )

    abstract fun onWrite(
        pages: Array<PageRange>?,
        destination: ParcelFileDescriptor?,
        cancellationSignal: CancellationSignal?,
        callback: WriteResultCallback?
    )

    open fun onFinish(): Unit = TODO()

    companion object {
        const val EXTRA_PRINT_PREVIEW: String = "EXTRA_PRINT_PREVIEW"
    }
}

open class PrintManager {
    open fun print(printJobName: String?, documentAdapter: PrintDocumentAdapter?, attributes: PrintAttributes?): PrintJob = TODO()
    open fun getPrintJobs(): MutableList<PrintJob> = TODO()
}
"""),
    ('android.speech.tts', 'speech.kt', """\
package android.speech.tts

import android.content.Context
import android.os.Bundle
import java.util.Locale

open class Voice {
    open fun getName(): String? = TODO()
    open fun getLocale(): Locale? = TODO()
    open fun getQuality(): Int = TODO()
    open fun getLatency(): Int = TODO()
    open fun isNetworkConnectionRequired(): Boolean = TODO()
    open fun getFeatures(): MutableSet<String> = TODO()
}

abstract class UtteranceProgressListener {
    abstract fun onStart(utteranceId: String?)
    abstract fun onDone(utteranceId: String?)
    abstract fun onError(utteranceId: String?)
    open fun onError(utteranceId: String?, errorCode: Int): Unit = TODO()
    open fun onStop(utteranceId: String?, interrupted: Boolean): Unit = TODO()
    open fun onBeginSynthesis(utteranceId: String?, sampleRateInHz: Int, audioFormat: Int, channelCount: Int): Unit = TODO()
}

open class TextToSpeech {
    constructor(context: Context?, listener: OnInitListener?) {}
    constructor(context: Context?, listener: OnInitListener?, engine: String?) {}

    fun interface OnInitListener {
        fun onInit(status: Int)
    }

    object Engine {
        const val KEY_PARAM_STREAM: String = "streamType"
        const val KEY_PARAM_VOLUME: String = "volume"
        const val KEY_PARAM_PAN: String = "pan"
        const val KEY_PARAM_UTTERANCE_ID: String = "utteranceId"
        const val KEY_FEATURE_EMBEDDED_SYNTHESIS: String = "embeddedTts"
        const val KEY_FEATURE_NETWORK_SYNTHESIS: String = "networkTts"
        const val INTENT_ACTION_TTS_SERVICE: String = "android.intent.action.TTS_SERVICE"
        const val DEFAULT_STREAM: Int = 3
    }

    open fun speak(text: CharSequence?, queueMode: Int, params: Bundle?, utteranceId: String?): Int = TODO()
    open fun speak(text: String?, queueMode: Int, params: HashMap<String, String>?): Int = TODO()
    open fun stop(): Int = TODO()
    open fun shutdown(): Unit = TODO()
    open fun setLanguage(loc: Locale?): Int = TODO()
    open fun getDefaultLanguage(): Locale? = TODO()
    open fun getLanguage(): Locale? = TODO()
    open fun getAvailableLanguages(): MutableSet<Locale>? = TODO()
    open fun getFeatures(locale: Locale?): MutableSet<String>? = TODO()
    open fun getVoices(): MutableSet<Voice>? = TODO()
    open fun setVoice(voice: Voice?): Int = TODO()
    open fun setPitch(pitch: Float): Int = TODO()
    open fun setSpeechRate(speechRate: Float): Int = TODO()
    open fun isSpeaking(): Boolean = TODO()
    open fun setOnUtteranceProgressListener(listener: UtteranceProgressListener?): Int = TODO()
    open fun isLanguageAvailable(loc: Locale?): Int = TODO()

    companion object {
        const val SUCCESS: Int = 0
        const val ERROR: Int = -1
        const val STOPPED: Int = -2
        const val QUEUE_FLUSH: Int = 0
        const val QUEUE_ADD: Int = 1
        const val LANG_AVAILABLE: Int = 0
        const val LANG_MISSING_DATA: Int = -1
        const val LANG_NOT_SUPPORTED: Int = -2
    }
}
"""),
    ("java.lang", "java_lang_runnable.kt", """\
package java.lang

// Kotlin/Native has no java.lang. GeckoView passes `new Runnable(){...}` to
// View.post and Choreographer.postCallback, so something has to declare it.
// Delete this file if the os/util slice claims java.lang.
fun interface Runnable {
    fun run()
}
"""),
    ("java.util", "java_util_locale.kt", """\
package java.util

open class Locale {
    constructor(language: String?) {}
    constructor(language: String?, country: String?) {}
    open fun getLanguage(): String = TODO()
    open fun getCountry(): String = TODO()
    open fun getVariant(): String = TODO()
    open fun getISO3Language(): String = TODO()
    open fun getDisplayName(): String = TODO()
    open fun toLanguageTag(): String = TODO()
    companion object {
        val US: Locale = TODO()
        val ROOT: Locale = TODO()
        fun getDefault(): Locale = TODO()
        fun forLanguageTag(tag: String?): Locale = TODO()
    }
}
"""),
]

# --------------------------------------------------------------------------
# call-site scraping (coverage check, not code generation)
# --------------------------------------------------------------------------

IMPORT_RE = re.compile(r"^import\s+(static\s+)?([\w.]+)\s*;", re.M)
# "Type varName" in a declaration/parameter position
DECL_RE = re.compile(r"\b([A-Z][A-Za-z0-9_]*)(?:<[^<>;=)]*>)?\s+(m?[a-zA-Z][A-Za-z0-9_]*)\s*(?=[,;=):])")


def owned_type_names(java_root):
    """Simple names of every type GeckoView imports out of our packages."""
    names = collections.defaultdict(set)  # simple name -> set of fqns
    for path in java_files(java_root):
        for _, fqn in IMPORT_RE.findall(read(path)):
            pkg = fqn.rsplit(".", 1)[0]
            # android.view.Display.HdrCapabilities imports a nested type
            if pkg in OWNED_PACKAGES or pkg.rsplit(".", 1)[0] in OWNED_PACKAGES:
                if fqn.startswith(OWNED_PACKAGES):
                    names[fqn.rsplit(".", 1)[1]].add(fqn)
    return names


def java_files(java_root):
    for root, _dirs, files in os.walk(java_root):
        for f in files:
            if f.endswith(".java"):
                yield os.path.join(root, f)


COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)
STRING_RE = re.compile(r'"(?:\\.|[^"\\\n])*"')


def read(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        return fh.read()


def read_code(path):
    """Source with comments, string literals and import lines removed.

    All three are pure noise for call-site scraping: javadoc says
    {@link android.view.View}, strings say "AccessibilityNodeInfo.hint", and an
    import line is not a use.
    """
    src = COMMENT_RE.sub(" ", read(path))
    src = STRING_RE.sub('""', src)
    return IMPORT_RE.sub("", src)


def declared_java_types(java_root):
    """Simple names of types GeckoView declares itself.

    GeckoView has its own inner `Display`, so `mDisplay.capturePixels()` is not a
    gap in the android.view.Display stub. Names that collide are reported apart.
    """
    names = set()
    for path in java_files(java_root):
        names.update(re.findall(r"\b(?:class|interface|enum)\s+([A-Z]\w*)", read_code(path)))
    return names


def scrape_call_sites(java_root):
    """Every member name GeckoView touches on one of our types.

    Two sources: `Type.MEMBER` (statics, constants, nested types) and
    `var.member` where `var` was declared with one of our types.
    """
    owned = owned_type_names(java_root)
    hits = collections.defaultdict(set)  # simple type name -> {member}
    static_re = re.compile(
        r"\b(" + "|".join(sorted(map(re.escape, owned))) + r")\.([A-Za-z_]\w*)"
    ) if owned else None

    for path in java_files(java_root):
        src = read_code(path)
        if static_re:
            for t, m in static_re.findall(src):
                hits[t].add(m)
        # instance members, via declared types
        varmap = {}
        for t, v in DECL_RE.findall(src):
            if t in owned:
                varmap.setdefault(v, t)
        for v, t in varmap.items():
            for m in re.findall(r"(?<![\w.])" + re.escape(v) + r"\.([a-zA-Z_]\w*)", src):
                hits[t].add(m)
    return owned, hits


DECL_NAME_RE = re.compile(
    r"^\s*(?:@JvmField\s+)?"
    r"(?:open\s+|abstract\s+|override\s+|const\s+|private\s+|internal\s+)*"
    r"(?:fun|val|var|class|object|interface)\s+([A-Za-z_]\w*)",
    re.M,
)


def declared_names(kotlin_sources):
    names = set()
    for src in kotlin_sources:
        names.update(DECL_NAME_RE.findall(src))
        # `fun interface Foo`, `open class Foo : Bar`
        names.update(re.findall(r"\b(?:fun\s+interface|open\s+class|abstract\s+class)\s+(\w+)", src))
        names.update(re.findall(r"\bconstructor\b", src) and [] or [])
    return names


# Members that legitimately have no stub: java.lang.Object / reflection / Kotlin
# builtins reached through one of our types, and Java-side names the regex
# mis-attributes to an owned type.
IGNORED_MEMBERS = frozenset(
    """class this super toString equals hashCode getClass getStackTrace name
    length values valueOf ordinal wait notify notifyAll clone finalize
    """.split()
)


def report(owned, hits, names, shadowed=frozenset(), stream=sys.stderr):
    missing, ambiguous = {}, {}
    for t in sorted(hits):
        gaps = sorted(m for m in hits[t] if m not in names and m not in IGNORED_MEMBERS)
        if not gaps:
            continue
        (ambiguous if t in shadowed else missing)[t] = gaps
    total_members = sum(len(v) for v in hits.values())
    covered = total_members - sum(len(v) for v in missing.values()) - sum(len(v) for v in ambiguous.values())
    stream.write("stubgen/view.py coverage\n")
    stream.write("  types imported by GeckoView from our packages: %d\n" % len(owned))
    stream.write("  distinct members seen at call sites:           %d\n" % total_members)
    stream.write("  members with a matching declaration:           %d\n" % covered)
    if missing:
        stream.write("  NOT covered (name never declared in the stubs):\n")
        for t, gaps in sorted(missing.items()):
            stream.write("    %-28s %s\n" % (t, " ".join(gaps)))
    if ambiguous:
        stream.write("  ignored -- GeckoView declares its own type of the same name:\n")
        for t, gaps in sorted(ambiguous.items()):
            stream.write("    %-28s %s\n" % (t, " ".join(gaps)))
    return missing


# --------------------------------------------------------------------------
# a throwaway set of the OTHER groups' types, so this slice can be compiled
# standalone before the rest of the stub surface lands. Never written into the
# geckoview-kn tree.
# --------------------------------------------------------------------------

DEPS_PARTS = [
    ("android.content", """
open class Context {
    open fun getSystemService(name: String?): Any? = TODO()
    open fun obtainStyledAttributes(attrs: IntArray?): android.content.res.TypedArray = TODO()
    open fun obtainStyledAttributes(resid: Int, attrs: IntArray?): android.content.res.TypedArray = TODO()
}
open class ContextWrapper(base: Context?) : Context()
open class Intent
open class ClipData
open class ClipDescription
"""),
    ("android.content.res", """
open class Resources { open class Theme }
open class TypedArray
open class Configuration
"""),
    ("android.graphics", """
open class Bitmap
open class Canvas
open class Insets { var top: Int = 0; var bottom: Int = 0; var left: Int = 0; var right: Int = 0 }
open class Matrix
open class Point { var x: Int = 0; var y: Int = 0 }
open class Rect { var left: Int = 0; var top: Int = 0; var right: Int = 0; var bottom: Int = 0 }
open class RectF
open class Region
open class SurfaceTexture
open class BlendMode
"""),
    ("android.graphics.drawable", """
open class Drawable
"""),
    ("android.os", """
open class Bundle
open class Handler
interface IBinder
open class Parcel
interface Parcelable { fun describeContents(): Int; fun writeToParcel(dest: Parcel?, flags: Int); interface Creator<T> { fun createFromParcel(source: Parcel?): T } }
open class CancellationSignal
open class ParcelFileDescriptor
"""),
    ("android.text", """
interface Spannable
interface Editable : Spannable
"""),
    ("android.util", """
open class AttributeSet
open class SparseArray<E>
open class DisplayMetrics
"""),
    ("android.net", """
open class Uri
"""),
]


def write_deps(path):
    chunks = []
    for i, (pkg, body) in enumerate(DEPS_PARTS):
        chunks.append("// deps placeholder -- not part of the stub surface\npackage %s\n%s" % (pkg, body))
    # one package per file, so emit a directory
    os.makedirs(path, exist_ok=True)
    for pkg, body in DEPS_PARTS:
        with open(os.path.join(path, pkg.replace(".", "_") + ".kt"), "w") as fh:
            fh.write("// deps placeholder -- not part of the stub surface\npackage %s\n%s" % (pkg, body))
    return path


# --------------------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--java-root", default=DEFAULT_JAVA_ROOT)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--deps", default=None,
                    help="also write throwaway stubs for other groups' packages into this dir")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    sources = []
    for pkg, fname, body in TEMPLATES:
        text = (BANNER % pkg) + body
        with open(os.path.join(args.out, fname), "w") as fh:
            fh.write(text)
        sources.append(body)
        print("wrote %s (%s, %d lines)" % (os.path.join(args.out, fname), pkg, body.count("\n")))

    if args.deps:
        write_deps(args.deps)
        print("wrote deps placeholders into %s" % args.deps)

    owned, hits = scrape_call_sites(args.java_root)
    shadowed = declared_java_types(args.java_root) & set(owned)
    missing = report(owned, hits, declared_names(sources), shadowed)
    return 0


if __name__ == "__main__":
    sys.exit(main())
