"""Types no .java file declares because the Android build generates them.

Bucket "buildgen-and-aidl-stubs".  Five generators sit between the GeckoView
sources and javac, and Kotlin/Native has none of them:

  * aidl(1)          - 12 of the 18 `.aidl` files declare an interface, and the
                       tool emits `interface X extends IInterface` plus a
                       `X.Stub` binder base class and `X.Stub.asInterface`.
  * AGP BuildConfig  - `org.mozilla.geckoview.BuildConfig`, whose fields are
                       spelled out as `buildConfigField` in build.gradle.
  * aapt2 R          - `org.mozilla.geckoview.R` and the framework's
                       `android.R`.
  * gen_from_jinja   - `XPCOMError` and `GeckoChildProcessServices`, whose
                       `.jinja` templates are in the tree.
  * a crash-annotation generator outside mobile/android - `CrashReport`, whose
                       yaml is not in this worktree at all.

Everything here is derived, never hand-listed:

  * the AIDL interfaces are parsed out of `src/main/aidl/**.aidl`;
  * BuildConfig's fields and their Java types come from `buildConfigField`
    lines in `geckoview/build.gradle`;
  * XPCOMError's four helper methods are read off its `.jinja`, and its
    constants - which live inside `{% for %}` loops the template alone cannot
    resolve - are scraped from use sites, `NS_ERROR_MODULE_*` as Int and the
    rest as Long, matching the template;
  * `GeckoChildProcessServices.MAX_NUM_ISOLATED_CONTENT_SERVICES` likewise
    comes from its `.jinja`;
  * `R` and `CrashReport.Annotation` are scraped from use sites the way
    stubgen/os.py scrapes android.os.

Two shape decisions matter, both forced by what j2k already emitted:

  * Every interface method gets a `= TODO()` body, so nothing is abstract.
    Classes like `object : IMediaManager.Stub` implement three of a dozen
    members; with abstract members they would each become a "does not
    implement" error, trading one bucket for another.
  * Parameter types are emitted nullable for every reference type and non-null
    for primitives, because that is exactly what j2k emits at the override
    sites, and Kotlin matches override parameters exactly.  Return types are
    nullable too: an override may narrow a return type, so `SampleBuffer?` in
    the interface accepts j2k's `SampleBuffer`.

The only text edit is `object : X.Stub` -> `object : X.Stub()`.  j2k decides
that paren from its corpus index, which never saw `Stub`, so it guessed
interface.  A class *declaration* needs no such fix: `class C : X.Stub` with a
secondary constructor delegates to `super()` implicitly, and both spellings
appear in the output.
"""
import os
import re
from collections import OrderedDict

ORDER = 55
NAME = "buildgen-and-aidl-stubs"
DESCRIPTION = "AIDL interfaces, BuildConfig, R, XPCOMError, GeckoChildProcessServices, CrashReport"

GV = "/home/nekit/UT/firefox-src-kn/mobile/android/geckoview"
AIDL_ROOT = os.path.join(GV, "src", "main", "aidl")
GRADLE = os.path.join(GV, "build.gradle")
XPCOM_JINJA = os.path.join(GV, "src/main/java/org/mozilla/gecko/util/XPCOMError.jinja")
SERVICES_JINJA = os.path.join(
    GV, "src/main/java/org/mozilla/gecko/process/GeckoChildProcessServices.jinja")

BANNER = ("// GENERATED by kn-run/rules/buildgen-and-aidl-stubs.py -- do not edit by hand.\n"
          "// %s\n"
          "// The Android build generates this type; Kotlin/Native has no such step.\n"
          "@file:Suppress(\"unused\", \"UNUSED_PARAMETER\", \"ClassName\", \"EnumEntryName\",\n"
          "               \"PropertyName\", \"ObjectPropertyName\", \"ConstPropertyName\")\n")

# Types an .aidl names without importing (the AIDL compiler has them built in).
IMPLICIT = {
    "IBinder": "android.os.IBinder",
    "Bundle": "android.os.Bundle",
    "ParcelFileDescriptor": "android.os.ParcelFileDescriptor",
    "PersistableBundle": "android.os.PersistableBundle",
    "KeyEvent": "android.view.KeyEvent",
    "Surface": "android.view.Surface",
    "SurfaceTexture": "android.graphics.SurfaceTexture",
    "RectF": "android.graphics.RectF",
    "Rect": "android.graphics.Rect",
    "Intent": "android.content.Intent",
}
PRIMITIVE = {"void": "Unit", "boolean": "Boolean", "byte": "Byte", "char": "Char",
             "short": "Short", "int": "Int", "long": "Long", "float": "Float",
             "double": "Double"}
PRIM_ARRAY = {"boolean": "BooleanArray", "byte": "ByteArray", "char": "CharArray",
              "short": "ShortArray", "int": "IntArray", "long": "LongArray",
              "float": "FloatArray", "double": "DoubleArray"}
BUILTIN = {"String": "String", "CharSequence": "CharSequence", "Object": "Any",
           "List": "MutableList<Any?>", "Map": "MutableMap<Any?, Any?>"}

_COMMENT = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)
_JAVA_ID = r"[A-Za-z_$][\w$]*"


# ------------------------------------------------------------------ aidl

def _strip_comments(text):
    return _COMMENT.sub(" ", text)


def _aidl_files():
    out = []
    for d, _, fs in os.walk(AIDL_ROOT):
        for f in sorted(fs):
            if f.endswith(".aidl"):
                out.append(os.path.join(d, f))
    return out


def _aidl_packages(files):
    """simple name -> package, for every .aidl (parcelables included)."""
    pkgs = {}
    for p in files:
        text = _strip_comments(open(p).read())
        m = re.search(r"\bpackage\s+([\w.]+)\s*;", text)
        if m:
            pkgs[os.path.basename(p)[:-len(".aidl")]] = m.group(1)
    return pkgs


def _split_params(s):
    depth, cur, out = 0, "", []
    for ch in s:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [x.strip() for x in out if x.strip()]


def _ktype(jtype, resolve, nullable=True):
    """AIDL type -> Kotlin.  Reference types nullable, primitives never."""
    t = jtype.strip()
    arr = False
    while t.endswith("[]"):
        arr, t = True, t[:-2].strip()
    t = t.split("<")[0].strip()
    if arr and t in PRIM_ARRAY:
        return PRIM_ARRAY[t] + ("?" if nullable else "")
    if not arr and t in PRIMITIVE:
        return PRIMITIVE[t]
    base = BUILTIN.get(t) or resolve.get(t) or IMPLICIT.get(t) or t
    if arr:
        base = "Array<%s>" % base
    return base + ("?" if nullable else "")


def parse_aidl(path, pkgs):
    """-> (package, name, [(ret, name, [ptype...])], [(constname, kotlin type, value)]) or None."""
    text = _strip_comments(open(path).read())
    pkg = re.search(r"\bpackage\s+([\w.]+)\s*;", text)
    iface = re.search(r"\binterface\s+(%s)\s*\{" % _JAVA_ID, text)
    if not pkg or not iface:
        return None                      # `parcelable X;` - a real .java exists
    resolve = dict(pkgs and {k: "%s.%s" % (v, k) for k, v in pkgs.items()})
    for m in re.finditer(r"\bimport\s+([\w.]+)\s*;", text):
        resolve[m.group(1).rsplit(".", 1)[-1]] = m.group(1)
    body = text[iface.end():text.rindex("}")]

    methods, consts = [], []
    for stmt in body.split(";"):
        stmt = " ".join(stmt.split())
        if not stmt:
            continue
        c = re.match(r"const\s+(\w+)\s+(%s)\s*=\s*(.+)$" % _JAVA_ID, stmt)
        if c:
            consts.append((c.group(2), _ktype(c.group(1), resolve), c.group(3).strip()))
            continue
        m = re.match(r"(?:oneway\s+)?([\w.\[\]<>, ]+?)\s+(%s)\s*\((.*)\)$" % _JAVA_ID, stmt)
        if not m:
            continue
        params = []
        for i, p in enumerate(_split_params(m.group(3))):
            p = re.sub(r"^(?:in|out|inout)\s+", "", p.strip())
            bits = p.rsplit(" ", 1)
            ptype = bits[0] if len(bits) == 2 else p
            pname = bits[1] if len(bits) == 2 else "p%d" % i
            params.append((re.sub(r"[^\w$]", "", pname) or "p%d" % i,
                           _ktype(ptype, resolve)))
        methods.append((m.group(2), params, _ktype(m.group(1), resolve)))
    return pkg.group(1), iface.group(1), methods, consts


def render_aidl(pkg, name, methods, consts):
    L = [BANNER % ("aidl(1) generates this from %s.aidl." % name),
         "package %s\n" % pkg,
         "interface %s : android.os.IInterface {" % name]
    for mname, params, ret in methods:
        args = ", ".join("%s: %s" % (n, t) for n, t in params)
        L.append("    fun %s(%s): %s = TODO(\"aidl\")" % (mname, args, ret))
    L.append("")
    L.append("    abstract class Stub : android.os.Binder(), %s {" % name)
    L.append("        override fun asBinder(): android.os.IBinder = TODO(\"aidl\")")
    L.append("        companion object {")
    L.append("            fun asInterface(binder: android.os.IBinder?): %s = TODO(\"aidl\")"
             % name)
    L.append("        }")
    L.append("    }")
    if consts:
        L.append("")
        L.append("    companion object {")
        for cname, ctype, cval in consts:
            L.append("        const val %s: %s = %s" % (cname, ctype, cval))
        L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


# ------------------------------------------------------------- scraping

def _java_texts(src_root, cache={}):
    if src_root not in cache:
        blobs = []
        for d, _, fs in os.walk(src_root):
            for f in sorted(fs):
                if f.endswith(".java"):
                    blobs.append(open(os.path.join(d, f), errors="replace").read())
        cache[src_root] = "\n".join(blobs)
    return cache[src_root]


def scrape(src_root, pattern):
    return sorted(set(re.findall(pattern, _java_texts(src_root))))


# ---------------------------------------------------------- buildconfig

_BCF = re.compile(r"buildConfigField\s+['\"](\w+)['\"]\s*,\s*['\"](\w+)['\"]")
_DEFAULTS = {"String": '""', "boolean": "false", "int": "0", "long": "0L",
             "float": "0.0f", "double": "0.0"}
_BCTYPE = {"String": "String", "boolean": "Boolean", "int": "Int", "long": "Long",
           "float": "Float", "double": "Double"}


def render_buildconfig(src_root, notes):
    fields = OrderedDict()
    if os.path.exists(GRADLE):
        for jtype, fname in _BCF.findall(open(GRADLE, errors="replace").read()):
            fields[fname] = jtype
    used = scrape(src_root, r"\bBuildConfig\.(\w+)")
    missing = [u for u in used if u not in fields]
    for u in missing:
        fields[u] = "String"
    if missing:
        notes.append("BuildConfig fields not in build.gradle, guessed String: %s"
                     % ", ".join(missing))
    L = [BANNER % "AGP generates this from buildConfigField lines in build.gradle.",
         "package org.mozilla.geckoview\n",
         "object BuildConfig {"]
    for fname, jtype in fields.items():
        L.append("    val %s: %s = %s" % (fname, _BCTYPE.get(jtype, "String"),
                                          _DEFAULTS.get(jtype, '""')))
    L.append("}")
    return "\n".join(L) + "\n"


# -------------------------------------------------------------------- R

def _render_r(pkg, entries, what):
    L = [BANNER % what, "package %s\n" % pkg, "object R {"]
    for cat in sorted(entries):
        L.append("    object %s {" % cat)
        for nm in sorted(entries[cat]):
            L.append("        val %s: %s = 0" % (nm, "Int"))
        L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


def render_r(src_root):
    own, framework = {}, {}
    for cat, nm in re.findall(r"(?<![\w.])R\.(\w+)\.(\w+)", _java_texts(src_root)):
        own.setdefault(cat, set()).add(nm)
    for cat, nm in re.findall(r"\bandroid\.R\.(\w+)\.(\w+)", _java_texts(src_root)):
        framework.setdefault(cat, set()).add(nm)
    return (_render_r("org.mozilla.geckoview", own, "aapt2 generates this from res/."),
            _render_r("android", framework, "The framework's own aapt2-generated R."))


# ------------------------------------------------------------ the jinjas

def render_xpcomerror(src_root, notes):
    methods = []
    if os.path.exists(XPCOM_JINJA):
        tpl = _strip_comments(open(XPCOM_JINJA, errors="replace").read())
        for m in re.finditer(r"public\s+static\s+(\w+)\s+(%s)\s*\(([^)]*)\)"
                             % _JAVA_ID, tpl):
            params = []
            for i, p in enumerate(_split_params(m.group(3))):
                p = re.sub(r"^final\s+", "", p.strip())
                bits = p.rsplit(" ", 1)
                params.append((bits[1] if len(bits) == 2 else "p%d" % i,
                               _ktype(bits[0] if len(bits) == 2 else "Object", {})))
            methods.append((m.group(2), params, _ktype(m.group(1), {})))
    if not methods:
        notes.append("XPCOMError.jinja not found; helper methods omitted")
    method_names = {m[0] for m in methods}
    consts = [c for c in scrape(src_root, r"\bXPCOMError\.(\w+)")
              if c not in method_names]
    L = [BANNER % "gen_from_jinja.py renders this from XPCOMError.jinja.",
         "package org.mozilla.gecko.util\n",
         "object XPCOMError {"]
    for mname, params, ret in methods:
        args = ", ".join("%s: %s" % (n, t) for n, t in params)
        L.append("    fun %s(%s): %s = TODO(\"buildgen\")" % (mname, args, ret))
    for c in consts:
        # matches the template: the module ids are int, the error codes long.
        if c.startswith("NS_ERROR_MODULE_"):
            L.append("    const val %s: Int = 0" % c)
        else:
            L.append("    const val %s: Long = 0L" % c)
    L.append("}")
    return "\n".join(L) + "\n"


def render_child_process_services(src_root):
    consts = []
    if os.path.exists(SERVICES_JINJA):
        tpl = open(SERVICES_JINJA, errors="replace").read()
        for m in re.finditer(r"static\s+final\s+int\s+(\w+)\s*=", tpl):
            consts.append(m.group(1))
    # anything the corpus reads that the template did not spell out
    for u in scrape(src_root, r"\bGeckoChildProcessServices\.(\w+)"):
        if u not in consts and u.isupper():
            consts.append(u)
    L = [BANNER % "gen_from_jinja.py renders this from GeckoChildProcessServices.jinja.",
         "package org.mozilla.gecko.process\n",
         "// The per-content-process service classes the template also emits are",
         "// referenced only from AndroidManifest.xml, so they are left out.",
         "open class GeckoChildProcessServices {",
         "    companion object {"]
    for c in consts:
        L.append("        const val %s: Int = 0" % c)
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


# --------------------------------------------------------- crash report

_ENUM_NOISE = {"values", "valueOf", "name", "ordinal", "toString", "class", "entries"}


def render_crash_report(src_root):
    names = [n for n in scrape(src_root, r"\bCrashReport\.Annotation\.(\w+)")
             if n not in _ENUM_NOISE]
    L = [BANNER % "Generated from CrashAnnotations.yaml, which lives outside mobile/android.",
         "package org.mozilla.geckoview\n",
         "class CrashReport {",
         "    enum class Annotation {"]
    L.append("        " + ",\n        ".join(names) if names else "        Unused")
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


# ------------------------------------------------------------ emit + fix

def _write(out_root, rel, text, stats, index, decl_name):
    """Write a generated source, unless a real .java already declares the type."""
    if index is not None and decl_name in getattr(index, "kinds", {}):
        stats["buildgen-skipped-declared"] += 1
        return None
    path = os.path.join(out_root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)
    stats["buildgen-files"] += 1
    return rel


def emit(ctx, notes):
    out_root, src_root = ctx["out_root"], ctx["src_root"]
    index, stats = ctx.get("index"), ctx["stats"]
    ifaces = {}

    files = _aidl_files()
    pkgs = _aidl_packages(files)
    for p in files:
        got = parse_aidl(p, pkgs)
        if not got:
            continue
        pkg, name, methods, consts = got
        ifaces[name] = {m[0] for m in methods}
        _write(out_root, os.path.join(*pkg.split(".")) + "/%s.kt" % name,
               render_aidl(pkg, name, methods, consts), stats, index, name)
        stats["aidl-interfaces"] += 1

    _write(out_root, "org/mozilla/geckoview/BuildConfig.kt",
           render_buildconfig(src_root, notes), stats, index, "BuildConfig")
    own_r, framework_r = render_r(src_root)
    _write(out_root, "org/mozilla/geckoview/R.kt", own_r, stats, index, "R")
    _write(out_root, "android/R.kt", framework_r, stats, index, "__android_R__")
    _write(out_root, "org/mozilla/gecko/util/XPCOMError.kt",
           render_xpcomerror(src_root, notes), stats, index, "XPCOMError")
    _write(out_root, "org/mozilla/gecko/process/GeckoChildProcessServices.kt",
           render_child_process_services(src_root), stats, index,
           "GeckoChildProcessServices")
    _write(out_root, "org/mozilla/geckoview/CrashReport.kt",
           render_crash_report(src_root), stats, index, "CrashReport")
    return ifaces


def transform(unit, ctx):
    if "_buildgen_ifaces" not in ctx:
        notes = []
        ctx["_buildgen_ifaces"] = emit(ctx, notes)
        ctx["_buildgen_notes"] = notes
    for n in ctx.get("_buildgen_notes", ()):
        if n not in unit.notes:
            unit.notes.append(n)
    ctx["_buildgen_notes"] = []

    ifaces = ctx["_buildgen_ifaces"]
    if not ifaces:
        return
    # `object : X.Stub {` -> `object : X.Stub() {`.  j2k guessed "interface"
    # because Stub is not in its corpus index; a class declaration needs no fix.
    pat = re.compile(r"(object\s*:\s*(?:[\w.]+\.)?(?:%s)\.Stub)(?!\s*\()"
                     % "|".join(sorted(ifaces)))
    new, n = pat.subn(r"\1()", unit.kotlin)
    if n:
        unit.kotlin = new
        ctx["stats"]["stub-object-parens"] += n
