"""Qualify what Java inherits into scope and Kotlin does not: static constants and nested types.

Java resolves a simple name against the *inherited* scope of every enclosing
class: an implementor of `GeckoSession.SelectionActionDelegate` writes bare
`ACTION_COPY` and bare `Selection`, and javac walks up the supertype chain to
find the interface constant and the nested class.  Kotlin inherits neither.
A companion object is not inherited, and neither are nested classifiers, so
every one of those names is an `unresolved reference`.

Three shapes land in this bucket, all fixed the same way - by rewriting the
bare name to a fully qualified one:

  * inherited static constants      ACTION_CUT, HIDE_REASON_*, IME_STATE_DISABLED
  * inherited nested classifiers    Selection, Callbacks, TrackType, DemuxerError
  * `import static a.b.C.NAME`      Kotlin needs `C.Companion.NAME`, and j2k
                                    either drops the import or emits a path
                                    that skips `Companion`

The qualified spelling is always the *fully qualified* one
(`org.mozilla.geckoview.GeckoSession.SelectionActionDelegate.ACTION_CUT`)
rather than the shortest one that would work.  It needs no import, it cannot
collide with a wildcard import, and - the case that decided it - it beats a
single-type import of the same simple name.  `BasicSelectionActionDelegate`
imports `android.text.Selection` and means
`GeckoSession.SelectionActionDelegate.Selection`; Java's inherited scope wins
over an import there, and only a fully qualified name reproduces that.

Cost of getting it wrong is why the two indexes are separate:

  * the Java corpus is parsed with tree-sitter, so nesting, `static`, and the
    implicit `static final` on interface fields are real facts, not guesses.
  * the stub tree (`geckoview-kn/src/**` files not generated by j2k) is scanned
    line-wise for the same facts.  It is needed because a supertype chain
    leaves the corpus: `GeckoInputConnection` -> `BaseInputConnection` ->
    `android.view.inputmethod.InputConnection`, which is where
    `GET_TEXT_WITH_STYLES` lives.

A name is left alone if it is declared anywhere in the file being rewritten.
That is coarser than real scoping - a constant inherited by one class and
shadowed by a local `val` in another would be skipped - but it is the cheap
direction to be wrong in, and it is what keeps the pass from touching a name
that already resolves.  The exception is a name that came from an
`import static`: the import is proof of where the name comes from, so those
are rewritten even when the same file also declares them (`ExperimentDelegate`
static-imports a constant out of its own nested `ExperimentException`).
Declaration sites themselves are always skipped, as are comments, strings,
`import`/`package` lines, and anything already qualified.

One extra, same shape: a `when` branch that is a bare enum constant of a *stub*
enum.  j2k qualifies `case CONST:` from its corpus enum index, which does not
cover `java.net.Proxy.Type`, so `HTTP ->` and `SOCKS ->` in `GeckoAppShell`
stay unresolved.  Qualified only where the constant name is unique across the
whole stub tree.

Two things this rule deliberately does *not* qualify:

  * a nested type that is not static.  Kotlin does carry a superclass's nested
    classifiers into scope - it is the ones inherited through an *interface*
    that go missing - and a non-static nested class is `inner` in Kotlin, whose
    constructor cannot be reached through a type name at all.  Writing
    `RuntimeSettings.Pref(...)` where bare `Pref(...)` already worked cost 109
    new errors before this exclusion existed.
  * a `when` branch that looks like an enum constant but sits in an `enum
    class` body.  Matching a trailing comma as well as `->` rewrote four enum
    declarations into syntax errors.

The one thing here that is not a qualification: `recv.new Inner()`.  Java's
qualified inner-class creation loses its receiver in conversion, so
`ServiceAllocator` calls `DefaultBindDelegate()` / `IsolatedBindDelegate()`
bare.  Qualifying those would only trade one error for another, so they become
`with(recv!!) { Inner() }` - the one spelling Kotlin accepts - driven off the
Java AST, and confined to the block of the class the Java site was in, because
a `this.new Inner()` elsewhere in the same file converts to the same bare text
and is already correct.

Measured by ablation on the round-4 tree, whole corpus, klib: the same tree
generated with every other rule and this one switched off has 92 errors in this
bucket - 54 of them in BasicSelectionActionDelegate, where the unresolved
nested `Selection` also costs 14 `smart cast to TypeVariable(K)` and every
member read off it - against 0 with the rule on.  Corpus total in that ablation
was 106; the rest belongs to other buckets (SessionState's Kotlin-builtin
overrides, `Short.or` in GeckoScreenOrientation, WebResponse.Builder.mBody).
"""
import os
import re

from tree_sitter import Language, Parser
import tree_sitter_java

ORDER = 75                 # after the stub generators (50-65) and java-declaration-forms (70):
                           # they key off simple names, so qualify only once they are done
NAME = "inherited-statics-and-nested-types"
DESCRIPTION = ("qualify inherited constants / nested types and static imports - "
               "Kotlin inherits neither companions nor nested classifiers")

_JAVA = Language(tree_sitter_java.language())

_TYPE_DECLS = ("class_declaration", "interface_declaration",
               "enum_declaration", "annotation_type_declaration",
               "record_declaration")

_KIND = {"class_declaration": "class", "interface_declaration": "interface",
         "enum_declaration": "enum", "annotation_type_declaration": "annotation",
         "record_declaration": "class"}

# Members of these are static whether or not anybody wrote `static`.
_IMPLICIT_STATIC = ("interface", "annotation")

_DECL_KEYWORDS = {"val", "var", "fun", "class", "interface", "object",
                  "typealias", "enum", "annotation", "constructor"}


# --------------------------------------------------------------------------
# masking: blank out comments and string literals so a token scan sees code only

def _mask(text):
    """Same-length copy of `text` with comments and strings replaced by spaces."""
    out = list(text)
    i, n = 0, len(text)
    depth = 0                       # /* */ nesting (Kotlin nests them)
    while i < n:
        c = text[i]
        if depth:
            if text.startswith("/*", i):
                depth += 1
                out[i] = out[i + 1] = " "
                i += 2
                continue
            if text.startswith("*/", i):
                depth -= 1
                out[i] = out[i + 1] = " "
                i += 2
                continue
            if c != "\n":
                out[i] = " "
            i += 1
            continue
        if text.startswith("/*", i):
            depth = 1
            out[i] = out[i + 1] = " "
            i += 2
            continue
        if text.startswith("//", i):
            while i < n and text[i] != "\n":
                out[i] = " "
                i += 1
            continue
        if text.startswith('"""', i):
            out[i] = out[i + 1] = out[i + 2] = " "
            i += 3
            while i < n and not text.startswith('"""', i):
                if text[i] != "\n":
                    out[i] = " "
                i += 1
            for k in range(i, min(i + 3, n)):
                out[k] = " "
            i += 3
            continue
        if c in ('"', "'"):
            quote = c
            out[i] = " "
            i += 1
            while i < n and text[i] != quote:
                if text[i] == "\\":
                    out[i] = " "
                    i += 1
                    if i < n and text[i] != "\n":
                        out[i] = " "
                        i += 1
                    continue
                if text[i] == "\n":         # unterminated; bail out of the literal
                    break
                out[i] = " "
                i += 1
            if i < n and text[i] == quote:
                out[i] = " "
                i += 1
            continue
        i += 1
    return "".join(out)


# --------------------------------------------------------------------------
# index: the Java corpus

def _txt(src, node):
    if node is None:
        return ""
    return src[node.start_byte:node.end_byte].decode("utf-8", "replace")


def _modifier_words(src, node):
    for c in node.children:
        if c.type == "modifiers":
            return set(_txt(src, c).split())
    return set()


def _declarator_names(src, node):
    """Field names out of a field_declaration / constant_declaration."""
    names = []
    for c in node.named_children:
        if c.type == "variable_declarator":
            nm = c.child_by_field_name("name")
            if nm is not None:
                names.append(_txt(src, nm))
    return names


def _new_type(fqn, kind, pkg, static):
    return {"fqn": fqn, "kind": kind, "pkg": pkg, "static": static,
            "supers": [], "consts": set(), "nested": {}, "enum_consts": set()}


def _index_java(idx, path, src, tree):
    pkg = ""
    for c in tree.root_node.named_children:
        if c.type == "package_declaration":
            pkg = re.sub(r"^package\s+|;\s*$", "", _txt(src, c).strip()).strip()
            break

    statics = idx["static_imports"].setdefault(path, {})
    for c in tree.root_node.named_children:
        if c.type == "import_declaration" and "static" in _txt(src, c):
            body = re.sub(r"^import\s+static\s+|;\s*$", "", _txt(src, c).strip()).strip()
            if body.endswith("*") or "." not in body:
                continue
            owner, _, member = body.rpartition(".")
            statics[member] = owner

    def walk(node, prefix, container):
        for child in node.named_children:
            t = child.type
            if t not in _TYPE_DECLS:
                walk(child, prefix, container)
                continue
            nm = _txt(src, child.child_by_field_name("name"))
            if not nm:
                continue
            path_parts = prefix + [nm]
            fqn = (pkg + "." if pkg else "") + ".".join(path_parts)
            kind = _KIND[t]
            mods = _modifier_words(src, child)
            # "static" in the Kotlin sense: a nested type that needs no outer
            # instance.  Java writes it explicitly only some of the time -
            # interfaces, annotations, enums and records always are, and
            # anything declared inside an interface is too.
            is_static = (not prefix
                         or "static" in mods
                         or kind in ("interface", "annotation", "enum")
                         or t == "record_declaration"
                         or (container is not None
                             and container["kind"] in _IMPLICIT_STATIC))
            rec = _new_type(fqn, kind, pkg, is_static)
            idx["types"][fqn] = rec
            idx["by_simple"].setdefault(nm, []).append(fqn)
            idx["by_file"].setdefault(path, []).append(fqn)
            if container is not None:
                container["nested"][nm] = fqn

            for sc in child.named_children:
                if sc.type == "superclass":
                    for k in sc.named_children:
                        rec["supers"].append(_txt(src, k).split("<")[0].strip())
                elif sc.type in ("super_interfaces", "extends_interfaces"):
                    for tl in sc.named_children:
                        kids = tl.named_children if tl.type == "type_list" else [tl]
                        for k in kids:
                            rec["supers"].append(_txt(src, k).split("<")[0].strip())

            body = child.child_by_field_name("body")
            if body is None:
                continue
            implicit = kind in _IMPLICIT_STATIC

            def members(container_node):
                for m in container_node.named_children:
                    if m.type in ("field_declaration", "constant_declaration"):
                        if implicit or "static" in _modifier_words(src, m):
                            rec["consts"].update(_declarator_names(src, m))
                    elif m.type == "enum_constant":
                        rec["enum_consts"].add(
                            _txt(src, m.child_by_field_name("name")))
                    elif m.type == "enum_body_declarations":
                        members(m)

            members(body)
            walk(body, path_parts, rec)

    walk(tree.root_node, [], None)


# --------------------------------------------------------------------------
# index: the Kotlin stub tree (everything under out_root that j2k did not write)

_KT_TYPE = re.compile(
    r"^\s*(?:(?:public|internal|private|protected|open|abstract|sealed|final|"
    r"inner|external|expect|actual|annotation|data|value|enum|fun)\s+)*"
    r"(?P<kw>class|interface|object)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)")
_KT_COMPANION = re.compile(r"^\s*companion\s+object\b")
_KT_VAL = re.compile(r"^\s*(?:(?:public|internal|private|protected|const|"
                     r"lateinit|override|open|final|external|actual)\s+)*"
                     r"(?:val|var)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)")
_KT_IDENTS = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*\s*[,;]?$")


def _kt_supers(line):
    """Supertype simple names out of a Kotlin declaration header."""
    head = line.split("{")[0]
    if ":" not in head:
        return []
    tail = head.split(":", 1)[1]
    tail = re.sub(r"\([^()]*\)", "", tail)
    out = []
    for part in tail.split(","):
        part = part.split("<")[0].strip()
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.]*", part or ""):
            out.append(part)
    return out


def _index_kotlin_stub(idx, text):
    pkg = ""
    m = re.search(r"^package\s+([\w.]+)", text, re.M)
    if m:
        pkg = m.group(1)

    stack = []          # [(rec_or_None, depth_at_open, is_companion)]
    depth = 0
    pending = None      # (rec, is_companion) waiting for its `{`
    in_enum_head = None

    for raw in _mask(text).split("\n"):
        line = raw.rstrip()
        stripped = line.strip()

        if in_enum_head is not None and stripped and _KT_IDENTS.match(stripped):
            for nm in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", stripped):
                in_enum_head["enum_consts"].add(nm)
                idx["stub_enum_consts"].setdefault(nm, set()).add(in_enum_head["fqn"])

        owner = None
        for rec, _d, is_comp in reversed(stack):
            if rec is not None:
                owner = rec
                break

        mt = _KT_TYPE.match(line)
        if mt and pending is None:
            nm = mt.group("name")
            parent = owner
            parts = ([parent["fqn"]] if parent else ([pkg] if pkg else []))
            fqn = ".".join([p for p in parts if p] + [nm])
            kind = "object" if mt.group("kw") == "object" else mt.group("kw")
            if re.search(r"\benum\s+class\b", line):
                kind = "enum"
            rec = _new_type(fqn, kind, pkg, True)
            rec["supers"] = _kt_supers(line)
            idx["types"].setdefault(fqn, rec)
            rec = idx["types"][fqn]
            idx["by_simple"].setdefault(nm, []).append(fqn)
            if parent is not None:
                parent["nested"][nm] = fqn
            if kind in ("interface", "object", "enum"):
                pending = (rec, False)
            else:
                pending = (rec, False)
            # single-line `enum class T { A, B, C }`
            if kind == "enum" and "{" in line and "}" in line:
                inner = line[line.index("{") + 1:line.rindex("}")]
                for nm2 in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", inner.split(";")[0]):
                    rec["enum_consts"].add(nm2)
                    idx["stub_enum_consts"].setdefault(nm2, set()).add(fqn)
        elif _KT_COMPANION.match(line) and pending is None:
            pending = (None, True)
        else:
            mv = _KT_VAL.match(line)
            if mv is not None and owner is not None:
                in_static = False
                for rec2, _d, is_comp in reversed(stack):
                    if is_comp:
                        in_static = True
                        break
                    if rec2 is not None:
                        in_static = rec2["kind"] in ("object", "interface", "annotation")
                        break
                if in_static:
                    owner["consts"].add(mv.group("name"))

        for ch in line:
            if ch == "{":
                depth += 1
                if pending is not None:
                    stack.append((pending[0], depth, pending[1]))
                    if pending[0] is not None and pending[0]["kind"] == "enum":
                        in_enum_head = pending[0]
                    pending = None
            elif ch == "}":
                if stack and stack[-1][1] == depth:
                    if in_enum_head is not None and stack[-1][0] is in_enum_head:
                        in_enum_head = None
                    stack.pop()
                depth -= 1
        if in_enum_head is not None and ";" in line:
            in_enum_head = None


# --------------------------------------------------------------------------

def _build_index(ctx):
    idx = ctx.get("_inh_idx")
    if idx is not None:
        return idx
    idx = {"types": {}, "by_simple": {}, "by_file": {},
           "static_imports": {}, "stub_enum_consts": {}, "qualified_new": {}}

    parser = Parser(_JAVA)
    src_root = ctx["src_root"]
    for d, _dirs, fs in os.walk(src_root):
        for f in sorted(fs):
            if not f.endswith(".java"):
                continue
            p = os.path.join(d, f)
            try:
                src = open(p, "rb").read()
                tree = parser.parse(src)
                if tree.root_node.has_error:
                    continue
                _index_java(idx, p, src, tree)
                _index_qualified_new(idx, p, src, tree)
            except Exception:                                # noqa: BLE001
                continue

    out_root = ctx.get("out_root")
    if out_root and os.path.isdir(out_root):
        for d, _dirs, fs in os.walk(out_root):
            for f in sorted(fs):
                if not f.endswith(".kt"):
                    continue
                p = os.path.join(d, f)
                try:
                    text = open(p, encoding="utf-8", errors="replace").read()
                except Exception:                            # noqa: BLE001
                    continue
                if "Generated by kn-run/j2k.py" in text[:400]:
                    continue                                  # j2k output; the Java index has it
                try:
                    _index_kotlin_stub(idx, text)
                except Exception:                            # noqa: BLE001
                    continue

    ctx["_inh_idx"] = idx
    return idx


def _index_qualified_new(idx, path, src, tree):
    """`recv.new Inner(args)` sites - Kotlin has no spelling, j2k drops `recv.`.

    The enclosing type is recorded with each site so the rewrite can be
    confined to that class's block: `this.new Inner()` elsewhere in the same
    file converts to the same bare `Inner()` and is already correct Kotlin.
    """
    sites = []

    def walk(node, enclosing):
        if node.type in _TYPE_DECLS:
            nm = node.child_by_field_name("name")
            if nm is not None:
                enclosing = _txt(src, nm)
        if node.type == "object_creation_expression":
            head = src[node.start_byte:node.end_byte].decode("utf-8", "replace")
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_.]*)\s*\.\s*new\s+"
                         r"([A-Za-z_][A-Za-z0-9_]*)\s*\(", head)
            if m and m.group(1) != "this":
                sites.append((enclosing, m.group(1), m.group(2)))
        for c in node.children:
            walk(c, enclosing)

    walk(tree.root_node, None)
    if sites:
        idx["qualified_new"][path] = sites


# --------------------------------------------------------------------------
# resolution

def _resolve(idx, raw, from_fqn):
    """A supertype name, as written, against the corpus + stub index."""
    raw = raw.split("<")[0].strip()
    if not raw:
        return None
    if raw in idx["types"]:
        return raw
    # enclosing scopes of the referring type, innermost first
    parts = from_fqn.split(".")
    for i in range(len(parts), 0, -1):
        cand = ".".join(parts[:i]) + "." + raw
        if cand in idx["types"]:
            return cand
    pkg = idx["types"].get(from_fqn, {}).get("pkg", "")
    if pkg and (pkg + "." + raw) in idx["types"]:
        return pkg + "." + raw
    simple = raw.split(".")[-1]
    hits = [f for f in idx["by_simple"].get(simple, [])
            if f == raw or f.endswith("." + raw)]
    if len(hits) == 1:
        return hits[0]
    hits = idx["by_simple"].get(simple, [])
    if len(hits) == 1:
        return hits[0]
    return None


def _closure(idx, fqn, seen):
    """Strict supertype closure of `fqn`, as fqns."""
    out = []
    stack = list(idx["types"].get(fqn, {}).get("supers", []))
    local = set()
    while stack:
        raw = stack.pop()
        got = _resolve(idx, raw, fqn)
        if got is None or got in local or got == fqn:
            continue
        local.add(got)
        out.append(got)
        stack.extend(idx["types"].get(got, {}).get("supers", []))
    return out


# --------------------------------------------------------------------------

_TOKEN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def _line_bounds(text, pos):
    start = text.rfind("\n", 0, pos) + 1
    end = text.find("\n", pos)
    return start, (len(text) if end < 0 else end)


def _apply(unit, subs, forced, declared):
    """Rewrite bare `name` -> `subs[name].name`.  Returns the number of edits."""
    text = unit.kotlin
    masked = _mask(text)
    pieces = []
    last = 0
    edits = 0

    for m in _TOKEN.finditer(masked):
        name = m.group(0)
        owner = subs.get(name)
        if owner is None:
            continue
        if name in declared and name not in forced:
            continue
        s, e = m.start(), m.end()
        ls, le = _line_bounds(masked, s)
        head = masked[ls:s]
        if head.lstrip().startswith(("import ", "package ", "@")):
            continue
        prev = head.rstrip()
        if prev.endswith((".", "@", "`", "?", "::")):
            continue
        if masked[e:e + 1] == "`":
            continue
        words = re.findall(r"[A-Za-z_][A-Za-z0-9_]*", prev)
        if words and words[-1] in _DECL_KEYWORDS:
            continue
        pieces.append(text[last:s])
        pieces.append(owner + "." + name)
        last = e
        edits += 1

    if edits:
        pieces.append(text[last:])
        unit.kotlin = "".join(pieces)
    return edits


def _apply_when_enums(unit, enum_subs, declared):
    """`HTTP ->` inside a `when`, where HTTP is a constant of a stub enum.

    The match is anchored on a whole branch line ending in `->`, which is the
    one shape an enum *entry* can never have: an earlier version matched a
    trailing comma too and happily rewrote `NONE,` inside four `enum class`
    bodies into a fully qualified name, which is a syntax error.
    """
    if not enum_subs:
        return 0
    text = unit.kotlin
    masked = _mask(text)
    pieces = []
    last = 0
    edits = 0
    branch = re.compile(r"(?m)^[ \t]*([A-Za-z_][A-Za-z0-9_]*"
                        r"(?:[ \t]*,[ \t]*[A-Za-z_][A-Za-z0-9_]*)*)[ \t]*->")
    label = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
    for m in branch.finditer(masked):
        for lm in label.finditer(masked, m.start(1), m.end(1)):
            name = lm.group(0)
            owner = enum_subs.get(name)
            if owner is None or name in declared:
                continue
            pieces.append(text[last:lm.start()])
            pieces.append(owner + "." + name)
            last = lm.end()
            edits += 1
    if edits:
        pieces.append(text[last:])
        unit.kotlin = "".join(pieces)
    return edits


def _kt_class_block(text, simple):
    """(start, end) of the `class <simple>` block in the generated Kotlin, by indent."""
    m = re.search(r"(?m)^(\s*)(?:[\w]+\s+)*(?:class|object|interface)\s+"
                  + re.escape(simple) + r"\b", text)
    if m is None:
        return None
    indent = len(m.group(1))
    start = m.start()
    nl = text.find("\n", m.end())
    if nl < 0:
        return start, len(text)
    for line_m in re.finditer(r"(?m)^([ \t]*)\S", text[nl + 1:]):
        if len(line_m.group(1)) <= indent:
            return start, nl + 1 + line_m.start()
    return start, len(text)


def _apply_qualified_new(unit, sites):
    """`recv.new Inner(a)` came out as `Inner(a)`; Kotlin spells it `with(recv) { Inner(a) }`."""
    text = unit.kotlin
    edits = 0
    for enclosing, recv, inner in sites:
        span = _kt_class_block(text, enclosing) if enclosing else (0, len(text))
        if span is None:
            continue
        lo, hi = span
        pat = re.compile(r"(?<![\w.])" + re.escape(inner) + r"\(\s*\)")
        chunk, n = pat.subn("with(%s!!) { %s() }" % (recv, inner), text[lo:hi])
        if n:
            text = text[:lo] + chunk + text[hi:]
            edits += n
    if edits:
        unit.kotlin = text
    return edits


_DECLARED = re.compile(
    r"\b(?:val|var|fun|class|interface|object|typealias|annotation\s+class|"
    r"enum\s+class)\s+(?:<[^>\n]*>\s*)?([A-Za-z_][A-Za-z0-9_]*)")


def transform(unit, ctx):
    idx = _build_index(ctx)

    own = idx["by_file"].get(unit.java_path, [])
    if not own and unit.java_path not in idx["static_imports"]:
        return

    declared = set(_DECLARED.findall(_mask(unit.kotlin)))
    own_set = set(own)

    subs = {}
    for fqn in own:
        for anc in _closure(idx, fqn, None):
            if anc in own_set:
                continue                       # nested in this very file; already in scope
            rec = idx["types"].get(anc)
            if rec is None:
                continue
            for c in rec["consts"]:
                subs.setdefault(c, anc)
            for nm, nested_fqn in rec["nested"].items():
                nested = idx["types"].get(nested_fqn)
                if nested is None or not nested["static"]:
                    # A non-static nested class is `inner` in Kotlin, and an
                    # inner constructor cannot be reached through a type name
                    # at all - `RuntimeSettings.Pref(...)` is an error where
                    # bare `Pref(...)` inside a subclass is not.  Kotlin does
                    # carry a superclass's nested classifiers into scope; it is
                    # the ones inherited through an *interface* that go
                    # missing, and those are always static.
                    continue
                subs.setdefault(nm, anc)

    forced = {}
    for member, owner in idx["static_imports"].get(unit.java_path, {}).items():
        if owner.startswith(("java.lang.annotation", "androidx.", "android.")):
            continue
        subs[member] = owner
        forced[member] = owner

    n = _apply(unit, subs, forced, declared)

    # The `import static` line itself: j2k copies it through as
    # `import a.b.C.NAME`, which Kotlin reads as a member of the *class* C and
    # cannot find, because j2k put NAME in C's companion.  Every use site is
    # qualified above, so the import has no work left to do - drop it rather
    # than respell it `a.b.C.Companion.NAME`, which would be wrong the moment
    # a constant lands somewhere other than a companion.
    if forced:
        kept = []
        for line in unit.kotlin.split("\n"):
            stripped = line.strip()
            if stripped.startswith("import "):
                path = stripped[len("import "):].strip()
                member = path.rsplit(".", 1)[-1]
                if member in forced and path == forced[member] + "." + member:
                    n += 1
                    continue
            kept.append(line)
        unit.kotlin = "\n".join(kept)

    # Stub enum constants, for `when` branches j2k could not qualify: it only
    # knows the enums in the Java corpus, so `java.net.Proxy.Type` is invisible
    # to it.  Ambiguous names are skipped, and so is anything the corpus index
    # already claims as an enum constant - that one belongs to j2k.
    corpus_enums = getattr(ctx.get("index"), "enum_consts", {})
    enum_subs = {}
    for nm, owners in idx["stub_enum_consts"].items():
        if len(owners) == 1 and nm not in declared and nm not in corpus_enums:
            enum_subs[nm] = next(iter(owners))
    n += _apply_when_enums(unit, enum_subs, declared)

    sites = idx["qualified_new"].get(unit.java_path, [])
    if sites:
        k = _apply_qualified_new(unit, sites)
        n += k
        if k:
            unit.notes.append(
                "%s: rewrote %d qualified inner-class creation(s) `recv.new T()` "
                "as `with(recv) { T() }`" % (NAME, k))

    if n:
        ctx["stats"][NAME] += n
