"""Java's stdlib spelling, where the Kotlin type already exists.

Bucket "java-stdlib-idioms": Java calls a member that Kotlin spells as a
property (`arr.length`, `s.length()`, `list.size()`, `e.ordinal()`), calls
`java.lang.Object`/`Throwable` methods Kotlin renamed (`getClass`,
`getMessage`), or mutates a collection whose Java type (`java.util.List`,
`Map`, `Set`) maps onto Kotlin's *read-only* `List`/`Map`/`Set`, so `add`/
`put`/`clear` do not resolve.

Two mechanisms, and the choice between them is the whole point of the rule:

* Almost everything is fixed by a generated shim file of *extensions*, not by
  rewriting call sites.  A post-pass has no type information, and text like
  `.size()` is not safe to rewrite: this corpus really does declare
  `fun size()` (MultiMap, GeckoBundle) and `fun length()` (GeckoEditable), and
  the stubs declare more.  An extension only takes effect where the member is
  absent - exactly where the compiler is erroring - so a member always wins and
  nothing that compiles today can break.  `x.size()` where `size` is a property
  is fixed the same way: `operator fun Int.invoke()` only ever applies to the
  "expression 'size' of type 'Int' cannot be invoked" case.  Dirty, and
  deliberately so: nobody runs this code.

* Only two things must be text, because a member beats an extension there:
  `.toArray(...)` (protected in kotlin.collections.ArrayList) and
  `.toLowerCase(Locale)` / `.toUpperCase(Locale)` ("too many arguments").

The deprecated-with-ERROR stdlib calls (`String(chars)`, `remove(index)`,
`toLowerCase()`) are not rewritten at all - `DEPRECATION_ERROR` is added to the
file-level @file:Suppress, which is why this rule runs after r90_suppress.

The shim lives in one generated file, `knshim/JavaStdlibShim.kt`, and every
converted file gets `import org.mozilla.gecko.knshim.*`.  It is generated, not
hand-written: it is erased and rewritten on every run like the rest of the
output tree.

It also stays out of the stub lane's way.  `out/stubs` is scanned for what it
declares: if a real `java.lang.Class` is there, `getClass()` is left to it, and
a `java.util` type it declares keeps its import.  So the rule is correct both
with and without a stub lane, which matters because the two are being built at
the same time.
"""
import os
import re

ORDER = 95           # after r90_suppress: this rule edits the @file:Suppress it wrote
NAME = "java-stdlib-idioms"
DESCRIPTION = "Java collection/Object API spelling vs the Kotlin stdlib"

SHIM_PKG = "photoncam.knshim"
SHIM_REL = os.path.join("photoncam", "knshim", "JavaStdlibShim.kt")
SHIM_IMPORT = "import %s.*" % SHIM_PKG

PRIM_ARRAYS = ("ByteArray", "ShortArray", "IntArray", "LongArray", "CharArray",
               "FloatArray", "DoubleArray", "BooleanArray")

# java.util names that ARE a Kotlin stdlib type.  Where nothing declares
# java.util.List, the import resolves to nothing and dropping it lets the
# default kotlin.collections import supply the type - which is what the body
# type-checked against anyway.  Dropped only if the stub lane has not declared
# that type itself (see _stub_types): java.util.Iterator has a `remove()` that
# kotlin.collections.Iterator does not, so taking their stub away costs errors.
# Anything without an exact Kotlin equivalent (Arrays, Collections, Objects,
# UUID, Deque, Queue, ...) was never ours.
JAVA_UTIL_KOTLIN = {
    "List", "Map", "Set", "Collection", "Iterator", "Iterable", "Comparator",
    "ArrayList", "HashMap", "HashSet", "LinkedHashMap", "LinkedHashSet",
    "RandomAccess", "NoSuchElementException", "ConcurrentModificationException",
}
_JU_IMPORT = re.compile(r"^import java\.util\.(\w+)$")

_SUPPRESS_HEAD = re.compile(r"@file:Suppress\(")


def _shim(with_get_class):
    b = []
    w = b.append
    w("// GENERATED by kn-run/rules/java-stdlib-idioms.py -- do not edit by hand.")
    w("// Extensions that give Java's stdlib spelling something to resolve to on")
    w("// Kotlin/Native.  An extension never shadows a member, so this file can only")
    w("// affect call sites that do not compile today.  Bodies are not meant to run.")
    w('@file:Suppress("UNCHECKED_CAST", "NOTHING_TO_INLINE", "unused", "EXTENSION_SHADOWED_BY_MEMBER")')
    w("package %s" % SHIM_PKG)
    w("")
    w("// --- arr.length (176 sites): a property in Kotlin, a field in Java.")
    w("val <T> Array<out T>.length: Int get() = size")
    for a in PRIM_ARRAYS:
        w("val %s.length: Int get() = size" % a)
    w("")
    w("// --- x.size() / s.length() / e.ordinal() / e.name() / map.values():")
    w("// Kotlin properties invoked as Java methods.  These only ever fire on")
    w('// "expression of type T cannot be invoked as a function"; a real member')
    w("// function of the same name still wins.")
    w("operator fun Int.invoke(): Int = this")
    w("operator fun Long.invoke(): Long = this")
    w("operator fun Boolean.invoke(): Boolean = this")
    w("operator fun Char.invoke(): Char = this")
    w("operator fun Float.invoke(): Float = this")
    w("operator fun Double.invoke(): Double = this")
    w("operator fun String.invoke(): String = this")
    w("operator fun <T> Collection<T>.invoke(): Collection<T> = this")
    w("operator fun <K, V> Map<K, V>.invoke(): Map<K, V> = this")
    w("")
    w("// --- mutation through a read-only view: java.util.List/Map/Set map onto")
    w("// kotlin.collections.List/Map/Set, which have no add/put/clear.")
    w("fun List<*>.add(e: Any?): Boolean = (this as MutableList<Any?>).add(e)")
    w("fun List<*>.add(i: Int, e: Any?) { (this as MutableList<Any?>).add(i, e) }")
    w("fun List<*>.remove(e: Any?): Boolean = (this as MutableList<Any?>).remove(e)")
    w("fun List<*>.removeAt(i: Int): Any? = (this as MutableList<Any?>).removeAt(i)")
    w("// Java's list.remove(int).  Kotlin/Native has no remove(index) at all, so")
    w("// without these the call binds to remove(element) and removes nothing.")
    w("fun <T> MutableList<T>.remove(index: Int): T = removeAt(index)")
    w("fun List<*>.remove(index: Int): Any? = (this as MutableList<Any?>).removeAt(index)")
    w("fun List<*>.clear() { (this as MutableList<Any?>).clear() }")
    w("fun List<*>.addAll(c: Collection<Any?>): Boolean = (this as MutableList<Any?>).addAll(c)")
    w("fun List<*>.addAll(i: Int, c: Collection<Any?>): Boolean = (this as MutableList<Any?>).addAll(i, c)")
    w("fun List<*>.removeAll(c: Collection<Any?>): Boolean = (this as MutableList<Any?>).removeAll(c)")
    w("fun List<*>.retainAll(c: Collection<Any?>): Boolean = (this as MutableList<Any?>).retainAll(c)")
    w("fun List<*>.set(i: Int, e: Any?): Any? = (this as MutableList<Any?>).set(i, e)")
    w("fun Set<*>.add(e: Any?): Boolean = (this as MutableSet<Any?>).add(e)")
    w("fun Set<*>.remove(e: Any?): Boolean = (this as MutableSet<Any?>).remove(e)")
    w("fun Set<*>.clear() { (this as MutableSet<Any?>).clear() }")
    w("fun Set<*>.addAll(c: Collection<Any?>): Boolean = (this as MutableSet<Any?>).addAll(c)")
    w("fun Set<*>.removeAll(c: Collection<Any?>): Boolean = (this as MutableSet<Any?>).removeAll(c)")
    w("fun Collection<*>.add(e: Any?): Boolean = (this as MutableCollection<Any?>).add(e)")
    w("fun Collection<*>.remove(e: Any?): Boolean = (this as MutableCollection<Any?>).remove(e)")
    w("fun Collection<*>.clear() { (this as MutableCollection<Any?>).clear() }")
    w("fun Collection<*>.addAll(c: Collection<Any?>): Boolean = (this as MutableCollection<Any?>).addAll(c)")
    w("fun Collection<*>.removeAll(c: Collection<Any?>): Boolean = (this as MutableCollection<Any?>).removeAll(c)")
    w("fun Map<*, *>.put(k: Any?, v: Any?): Any? = (this as MutableMap<Any?, Any?>).put(k, v)")
    w("fun Map<*, *>.remove(k: Any?): Any? = (this as MutableMap<Any?, Any?>).remove(k)")
    w("fun Map<*, *>.clear() { (this as MutableMap<Any?, Any?>).clear() }")
    w("fun Map<*, *>.putAll(m: Map<*, *>) { (this as MutableMap<Any?, Any?>).putAll(m) }")
    w("fun Map<*, *>.putIfAbsent(k: Any?, v: Any?): Any? = (this as MutableMap<Any?, Any?>).put(k, v)")
    w("")
    w("// --- java.util.Queue/Deque spelling, where the receiver landed on a List.")
    w("fun List<*>.offer(e: Any?): Boolean = (this as MutableList<Any?>).add(e)")
    w("fun List<*>.poll(): Any? = (this as MutableList<Any?>).removeFirstOrNull()")
    w("fun List<*>.peek(): Any? = firstOrNull()")
    w("fun List<*>.push(e: Any?) { (this as MutableList<Any?>).add(0, e) }")
    w("fun List<*>.pop(): Any? = (this as MutableList<Any?>).removeFirstOrNull()")
    w("fun List<*>.addFirst(e: Any?) { (this as MutableList<Any?>).add(0, e) }")
    w("fun List<*>.addLast(e: Any?) { (this as MutableList<Any?>).add(e) }")
    w("")
    w("// --- Map.Entry and keySet/entrySet: Kotlin renamed them to properties.")
    w("fun <K, V> Map<K, V>.keySet(): Set<K> = keys")
    w("fun <K, V> Map<K, V>.entrySet(): Set<Map.Entry<K, V>> = entries")
    w("fun <K, V> Map.Entry<K, V>.getKey(): K = key")
    w("fun <K, V> Map.Entry<K, V>.getValue(): V = value")
    w("")
    w("// --- java.lang.Object / Throwable / String / boxed-number methods.")
    w("fun Throwable.getMessage(): String? = message")
    w("fun Throwable.getLocalizedMessage(): String? = message")
    w("fun Throwable.getCause(): Throwable? = cause")
    w("fun String.equalsIgnoreCase(other: String?): Boolean = this.equals(other, ignoreCase = true)")
    w("fun CharSequence.charAt(i: Int): Char = this[i]")
    w("fun String.getBytes(vararg charset: Any?): ByteArray = encodeToByteArray()")
    w("fun String.Companion.valueOf(v: Any?): String = v.toString()")
    w("fun String.Companion.format(fmt: String?, vararg args: Any?): String = fmt ?: \"\"")
    w("fun String.Companion.join(sep: CharSequence, parts: Iterable<CharSequence>): String = parts.joinToString(sep)")
    w("fun Boolean.Companion.valueOf(v: Any?): Boolean = v == true")
    w("fun Float.Companion.valueOf(v: Any?): Float = 0.0f")
    w("fun Double.Companion.valueOf(v: Any?): Double = 0.0")
    w("fun Number.intValue(): Int = toInt()")
    w("fun Number.longValue(): Long = toLong()")
    w("fun Number.shortValue(): Short = toShort()")
    w("fun Number.byteValue(): Byte = toByte()")
    w("fun Number.floatValue(): Float = toFloat()")
    w("fun Number.doubleValue(): Double = toDouble()")
    w("fun Boolean.booleanValue(): Boolean = this")
    if with_get_class:
        w("")
        w("// --- x.getClass().  Kotlin/Native has no java.lang.Class and no JVM")
        w("// reflection; this is a name carrier so the call sites type-check.")
        w("// Skipped entirely if the stub lane ever declares a real `Class`.")
        w("class JavaClass(val simple: String?) {")
        w("    fun getName(): String? = simple")
        w("    fun getSimpleName(): String? = simple")
        w("    fun getCanonicalName(): String? = simple")
        w("    fun isArray(): Boolean = false")
        w("    fun getComponentType(): JavaClass? = null")
        w("    fun getClassLoader(): Any? = null")
        w("    fun getDeclaredMethod(name: String?, vararg types: Any?): Any? = null")
        w("    fun getMethod(name: String?, vararg types: Any?): Any? = null")
        w("    fun getField(name: String?): Any? = null")
        w("    fun isInstance(o: Any?): Boolean = false")
        w("}")
        w("fun Any.getClass(): JavaClass = JavaClass(this::class.simpleName)")
    w("")
    return "\n".join(b)


_DECL = re.compile(
    r"^\s*(?:public |internal |open |abstract |sealed |data |value |external )*"
    r"(?:class|interface|object|enum class|fun interface|annotation class|typealias)\s+(\w+)", re.M)
_PKG = re.compile(r"^package\s+([\w.]+)", re.M)


def _stub_types(ctx):
    """package -> {type names} declared by the stub lane, cached on ctx.

    The stub lane generates java.* stubs into out/stubs on the same run, so this
    is read fresh: what it owns, this rule leaves alone.
    """
    if "_stdlib_stub_types" in ctx:
        return ctx["_stdlib_stub_types"]
    types = {}
    stubs = os.path.join(ctx["out_root"], "stubs")
    for d, _, fs in os.walk(stubs) if os.path.isdir(stubs) else ():
        for f in fs:
            if not f.endswith(".kt"):
                continue
            try:
                text = open(os.path.join(d, f)).read()
            except OSError:
                continue
            m = _PKG.search(text)
            pkg = m.group(1) if m else ""
            types.setdefault(pkg, set()).update(_DECL.findall(text))
    ctx["_stdlib_stub_types"] = types
    return types


def _write_shim(ctx):
    dest = os.path.join(ctx["out_root"], SHIM_REL)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    have_class = "Class" in _stub_types(ctx).get("java.lang", ())
    with open(dest, "w") as fh:
        fh.write(_shim(not have_class))
    ctx["stats"]["stdlib-shim-file"] += 1


def _drop_call_args(text, marker, replacement):
    """`recv.marker(<balanced args>)` -> `recv.replacement()`.  Used where a
    member beats an extension, so the shim cannot help."""
    out, i, n = [], 0, 0
    while True:
        j = text.find(marker, i)
        if j < 0:
            out.append(text[i:])
            break
        k, depth = j + len(marker), 1
        while k < len(text) and depth:
            c = text[k]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
            elif c == '"':                      # skip a string literal
                k += 1
                while k < len(text) and text[k] != '"':
                    k += 2 if text[k] == "\\" else 1
            k += 1
        if depth:                               # unbalanced: leave it alone
            out.append(text[i:j + len(marker)])
            i = j + len(marker)
            continue
        out.append(text[i:j])
        out.append(replacement)
        i = k
        n += 1
    return "".join(out), n


def transform(unit, ctx):
    if unit.meta.get("stdlib_idioms"):
        return
    unit.meta["stdlib_idioms"] = True
    if not ctx.get("_stdlib_shim_written"):
        ctx["_stdlib_shim_written"] = True
        _write_shim(ctx)

    src = unit.kotlin

    # 1. toArray(...) is protected on kotlin.collections.ArrayList, so a member
    #    is found and an extension can never win.  Must be text.
    for marker in (".toArray(",):
        src, n = _drop_call_args(src, marker, ".toTypedArray()")
        if n:
            ctx["stats"]["toArray->toTypedArray"] += n
    # 2. toLowerCase(Locale) / toUpperCase(Locale): "too many arguments", not a
    #    deprecation, so suppression does not cover it.
    for marker, repl in ((".toLowerCase(", ".lowercase()"),
                         (".toUpperCase(", ".uppercase()")):
        src, n = _drop_call_args(src, marker, repl)
        if n:
            ctx["stats"]["case-conversion"] += n

    # 3. imports of java.util types that are Kotlin stdlib types and that the
    #    stub lane has not declared: they resolve to nothing, and the body
    #    already type-checks against kotlin.collections.
    stub_util = _stub_types(ctx).get("java.util", ())
    kept, dropped = [], 0
    for line in src.split("\n"):
        m = _JU_IMPORT.match(line.strip())
        if m and m.group(1) in JAVA_UTIL_KOTLIN and m.group(1) not in stub_util:
            dropped += 1
            continue
        kept.append(line)
    if dropped:
        src = "\n".join(kept)
        ctx["stats"]["java.util-import-dropped"] += dropped

    # 4. the shim import, right after the package declaration.
    if SHIM_IMPORT not in src and unit.package != SHIM_PKG:
        lines = src.split("\n")
        for i, l in enumerate(lines):
            if l.startswith("package "):
                lines.insert(i + 1, SHIM_IMPORT)
                break
        else:
            lines.insert(0, SHIM_IMPORT)
        src = "\n".join(lines)
        ctx["stats"]["stdlib-shim-import"] += 1

    # 5. String(chars), list.remove(index), s.toLowerCase() and friends are
    #    deprecated at ERROR level.  Suppressing beats rewriting: it needs no
    #    type information and cannot mis-target.
    if _SUPPRESS_HEAD.search(src):
        if "DEPRECATION_ERROR" not in src:
            src = _SUPPRESS_HEAD.sub('@file:Suppress("DEPRECATION_ERROR", ', src, count=1)
            ctx["stats"]["deprecation-error-suppressed"] += 1
    else:
        src = '@file:Suppress("DEPRECATION_ERROR")\n' + src
        ctx["stats"]["deprecation-error-suppressed"] += 1

    unit.kotlin = src
    unit.imports = [l for l in src.split("\n") if l.startswith("import ")]
