"""Give the port a java.*/javax.*/dalvik.* surface, and import it.

Kotlin/Native has no JDK.  Nothing under `java.` resolves, which costs twice:
once for every `import java....` line, and again for every use site plus every
member invoked on a receiver whose type never resolved.  It was the single
largest root cause in the round-1 log (~2000 of 5902 errors).

Two halves, the same shape as `stubgen/os.py`:

  1. A klib-local stub package per JDK package we touch, emitted once per run
     into `<out>/stubs/jdk_*.kt`.  Every body is TODO(); nothing here runs.
     Names another stub file already declares (`java.lang.Runnable`,
     `java.util.Locale` from `stubgen/view.py`) are skipped, so the two lanes
     can coexist and this stays re-runnable.

  2. A per-file import pass.  `java.lang` is implicit in Java and explicit in
     Kotlin, so `Math`, `Thread`, `Integer`, `Class`, `Runnable` and friends
     need an import line the Java never had.

Three things the JDK does that Kotlin spells differently are handled by
rewriting rather than stubbing:

  * `java.util.List/Map/Set/...` are typealiases onto Kotlin's *mutable*
    collections.  Java code calls `add`/`put` on them, and a stub hierarchy of
    our own would not interoperate with the collections the android.* stubs
    already hand back.
  * `java.lang.reflect.Array` would shadow `kotlin.Array` in any file that
    imports it, so its import is dropped and its call sites are qualified.
  * `Map.Entry` becomes `MutableMap.MutableEntry`, with getKey()/getValue()
    as extensions.

Statics on types Kotlin already owns (`Long.parseLong`, `String.format`) cannot
be stubbed - importing a `java.lang.Long` of our own would shadow `kotlin.Long`
for the whole file.  They are extensions on the Kotlin companion instead, and
the import pass pulls them in by call site.
"""
import os
import re

ORDER = 50
NAME = "jdk-stubs"
DESCRIPTION = "emit java.*/javax.*/dalvik.* stubs and import them at use sites"

BANNER = (
    "// GENERATED by kn-run/rules/jdk-stubs.py -- do not edit by hand.\n"
    "// %s stubs for the Kotlin/Native GeckoView port, derived from the\n"
    "// call sites in mobile/android/geckoview.  Every body is TODO():\n"
    "// there is no JVM here and nothing in this file is meant to run.\n"
    '@file:Suppress("UNUSED_PARAMETER", "unused", "UNCHECKED_CAST",\n'
    '               "EXTENSION_SHADOWED_BY_MEMBER", "NOTHING_TO_INLINE")\n'
)

# --------------------------------------------------------------------------
# the stub surface.  file -> (package, [(declared name, kotlin), ...])
# A name is skipped if some other stubs/*.kt already declares it in that
# package; that is what keeps this from colliding with the os/view lanes.

S = {}

S["jdk_lang"] = ("java.lang", [
("Runnable", """
fun interface Runnable {
    fun run()
}
"""),
("Math", """
object Math {
    const val PI: Double = 3.141592653589793
    const val E: Double = 2.718281828459045
    fun abs(a: Int): Int = TODO()
    fun abs(a: Long): Long = TODO()
    fun abs(a: Float): Float = TODO()
    fun abs(a: Double): Double = TODO()
    fun max(a: Int, b: Int): Int = TODO()
    fun max(a: Long, b: Long): Long = TODO()
    fun max(a: Float, b: Float): Float = TODO()
    fun max(a: Double, b: Double): Double = TODO()
    fun min(a: Int, b: Int): Int = TODO()
    fun min(a: Long, b: Long): Long = TODO()
    fun min(a: Float, b: Float): Float = TODO()
    fun min(a: Double, b: Double): Double = TODO()
    fun round(a: Float): Int = TODO()
    fun round(a: Double): Long = TODO()
    fun ceil(a: Double): Double = TODO()
    fun floor(a: Double): Double = TODO()
    fun sqrt(a: Double): Double = TODO()
    fun cbrt(a: Double): Double = TODO()
    // Java widens the argument implicitly; these are the same functions
    // with the narrower primitives spelled out.
    fun sqrt(a: Int): Double = TODO()
    fun sqrt(a: Long): Double = TODO()
    fun sqrt(a: Float): Double = TODO()
    fun cbrt(a: Int): Double = TODO()
    fun cbrt(a: Long): Double = TODO()
    fun cbrt(a: Float): Double = TODO()
    fun ceil(a: Int): Double = TODO()
    fun ceil(a: Long): Double = TODO()
    fun ceil(a: Float): Double = TODO()
    fun floor(a: Int): Double = TODO()
    fun floor(a: Long): Double = TODO()
    fun floor(a: Float): Double = TODO()
    fun log(a: Int): Double = TODO()
    fun log(a: Long): Double = TODO()
    fun log(a: Float): Double = TODO()
    fun log10(a: Int): Double = TODO()
    fun log10(a: Long): Double = TODO()
    fun log10(a: Float): Double = TODO()
    fun exp(a: Int): Double = TODO()
    fun exp(a: Long): Double = TODO()
    fun exp(a: Float): Double = TODO()
    fun sin(a: Int): Double = TODO()
    fun sin(a: Long): Double = TODO()
    fun sin(a: Float): Double = TODO()
    fun cos(a: Int): Double = TODO()
    fun cos(a: Long): Double = TODO()
    fun cos(a: Float): Double = TODO()
    fun tan(a: Int): Double = TODO()
    fun tan(a: Long): Double = TODO()
    fun tan(a: Float): Double = TODO()
    fun atan(a: Int): Double = TODO()
    fun atan(a: Long): Double = TODO()
    fun atan(a: Float): Double = TODO()
    fun toDegrees(a: Int): Double = TODO()
    fun toDegrees(a: Long): Double = TODO()
    fun toDegrees(a: Float): Double = TODO()
    fun toRadians(a: Int): Double = TODO()
    fun toRadians(a: Long): Double = TODO()
    fun toRadians(a: Float): Double = TODO()
    fun signum(a: Int): Float = TODO()
    fun signum(a: Long): Float = TODO()
    fun pow(a: Double, b: Double): Double = TODO()
    fun hypot(a: Double, b: Double): Double = TODO()
    fun log(a: Double): Double = TODO()
    fun log10(a: Double): Double = TODO()
    fun exp(a: Double): Double = TODO()
    fun sin(a: Double): Double = TODO()
    fun cos(a: Double): Double = TODO()
    fun tan(a: Double): Double = TODO()
    fun atan(a: Double): Double = TODO()
    fun atan2(a: Double, b: Double): Double = TODO()
    fun asin(a: Double): Double = TODO()
    fun acos(a: Double): Double = TODO()
    fun signum(a: Float): Float = TODO()
    fun signum(a: Double): Double = TODO()
    fun toDegrees(a: Double): Double = TODO()
    fun toRadians(a: Double): Double = TODO()
    fun random(): Double = TODO()
    fun floorDiv(a: Int, b: Int): Int = TODO()
    fun floorMod(a: Int, b: Int): Int = TODO()
}
"""),
("Thread", """
open class Thread() : Runnable {
    constructor(target: Runnable?) : this()
    constructor(target: Runnable?, name: String?) : this()
    constructor(name: String?) : this()
    constructor(group: Any?, target: Runnable?, name: String?) : this()
    constructor(group: Any?, target: Runnable?, name: String?, stackSize: Long) : this()
    constructor(group: Any?, target: Runnable?, name: String?, stackSize: Int) : this()

    interface UncaughtExceptionHandler {
        fun uncaughtException(t: Thread, e: Throwable)
    }
    enum class State { NEW, RUNNABLE, BLOCKED, WAITING, TIMED_WAITING, TERMINATED }

    override fun run() {}
    open fun start(): Unit = TODO()
    open fun join(): Unit = TODO()
    open fun join(millis: Long): Unit = TODO()
    open fun interrupt(): Unit = TODO()
    open fun isInterrupted(): Boolean = TODO()
    open fun isAlive(): Boolean = TODO()
    open fun isDaemon(): Boolean = TODO()
    open fun setDaemon(on: Boolean): Unit = TODO()
    open fun getId(): Long = TODO()
    open fun getName(): String = TODO()
    open fun setName(name: String?): Unit = TODO()
    open fun getPriority(): Int = TODO()
    open fun setPriority(p: Int): Unit = TODO()
    open fun getState(): State = TODO()
    open fun getStackTrace(): Array<StackTraceElement> = TODO()
    open fun getThreadGroup(): ThreadGroup = TODO()
    open fun getContextClassLoader(): ClassLoader = TODO()
    open fun setContextClassLoader(cl: ClassLoader?): Unit = TODO()
    open fun getUncaughtExceptionHandler(): UncaughtExceptionHandler = TODO()
    open fun setUncaughtExceptionHandler(h: UncaughtExceptionHandler?): Unit = TODO()

    companion object {
        const val MIN_PRIORITY: Int = 1
        const val NORM_PRIORITY: Int = 5
        const val MAX_PRIORITY: Int = 10
        fun currentThread(): Thread = TODO()
        fun sleep(millis: Long): Unit = TODO()
        fun sleep(millis: Long, nanos: Int): Unit = TODO()
        fun yield(): Unit = TODO()
        fun getDefaultUncaughtExceptionHandler(): UncaughtExceptionHandler = TODO()
        fun setDefaultUncaughtExceptionHandler(h: UncaughtExceptionHandler?): Unit = TODO()
    }
}
"""),
("ThreadGroup", """
open class ThreadGroup(name: String?) {
    open fun getName(): String = TODO()
    open fun activeCount(): Int = TODO()
    open fun getParent(): ThreadGroup = TODO()
    open fun enumerate(list: Array<Thread?>?): Int = TODO()
}
"""),
("StackTraceElement", """
open class StackTraceElement {
    open fun getClassName(): String = TODO()
    open fun getMethodName(): String = TODO()
    open fun getFileName(): String = TODO()
    open fun getLineNumber(): Int = TODO()
}
"""),
("Integer", """
object Integer {
    const val MAX_VALUE: Int = 2147483647
    const val MIN_VALUE: Int = -2147483648
    const val SIZE: Int = 32
    val TYPE: Class<Int> get() = TODO()
    fun parseInt(s: String?): Int = TODO()
    fun parseInt(s: String?, radix: Int): Int = TODO()
    fun valueOf(s: String?): Int = TODO()
    fun valueOf(s: String?, radix: Int): Int = TODO()
    fun valueOf(v: Int): Int = TODO()
    fun toString(v: Int): String = TODO()
    fun toString(v: Int, radix: Int): String = TODO()
    fun toHexString(v: Int): String = TODO()
    fun toBinaryString(v: Int): String = TODO()
    fun toOctalString(v: Int): String = TODO()
    fun compare(a: Int, b: Int): Int = TODO()
    fun decode(s: String?): Int = TODO()
    fun bitCount(v: Int): Int = TODO()
    fun highestOneBit(v: Int): Int = TODO()
    fun numberOfTrailingZeros(v: Int): Int = TODO()
    fun numberOfLeadingZeros(v: Int): Int = TODO()
    fun signum(v: Int): Int = TODO()
    fun reverseBytes(v: Int): Int = TODO()
}
"""),
("Character", """
object Character {
    const val MIN_VALUE: Char = '\\u0000'
    const val MAX_VALUE: Char = '\\uffff'
    val TYPE: Class<Char> get() = TODO()
    fun isDigit(c: Char): Boolean = TODO()
    fun isLetter(c: Char): Boolean = TODO()
    fun isLetterOrDigit(c: Char): Boolean = TODO()
    fun isWhitespace(c: Char): Boolean = TODO()
    fun isSpaceChar(c: Char): Boolean = TODO()
    fun isUpperCase(c: Char): Boolean = TODO()
    fun isLowerCase(c: Char): Boolean = TODO()
    fun isAlphabetic(c: Int): Boolean = TODO()
    fun toUpperCase(c: Char): Char = TODO()
    fun toLowerCase(c: Char): Char = TODO()
    fun toString(c: Char): String = TODO()
    fun valueOf(c: Char): Char = TODO()
    fun digit(c: Char, radix: Int): Int = TODO()
    fun isHighSurrogate(c: Char): Boolean = TODO()
    fun isLowSurrogate(c: Char): Boolean = TODO()
    fun isSurrogatePair(a: Char, b: Char): Boolean = TODO()
    fun charCount(cp: Int): Int = TODO()
    fun codePointAt(s: CharSequence?, i: Int): Int = TODO()
}
"""),
("System", """
object System {
    val out: java.io.PrintStream = TODO()
    val err: java.io.PrintStream = TODO()
    val `in`: java.io.InputStream = TODO()
    fun currentTimeMillis(): Long = TODO()
    fun nanoTime(): Long = TODO()
    fun arraycopy(src: Any?, srcPos: Int, dst: Any?, dstPos: Int, len: Int): Unit = TODO()
    fun exit(code: Int): Unit = TODO()
    fun gc(): Unit = TODO()
    fun identityHashCode(o: Any?): Int = TODO()
    fun lineSeparator(): String = TODO()
    fun getProperty(key: String?): String = TODO()
    fun getProperty(key: String?, def: String?): String = TODO()
    fun setProperty(key: String?, value: String?): String = TODO()
    fun getenv(name: String?): String = TODO()
    fun load(path: String?): Unit = TODO()
    fun loadLibrary(name: String?): Unit = TODO()
    fun mapLibraryName(name: String?): String = TODO()
}
"""),
("Class", """
open class Class<T> {
    open fun getName(): String = TODO()
    open fun getSimpleName(): String = TODO()
    open fun getCanonicalName(): String = TODO()
    open fun isArray(): Boolean = TODO()
    open fun isPrimitive(): Boolean = TODO()
    open fun isInterface(): Boolean = TODO()
    open fun isInstance(o: Any?): Boolean = TODO()
    open fun isAssignableFrom(c: Class<*>?): Boolean = TODO()
    open fun isEnum(): Boolean = TODO()
    open fun newInstance(): T = TODO()
    open fun cast(o: Any?): T = TODO()
    open fun getComponentType(): Class<Any> = TODO()
    open fun getSuperclass(): Class<Any> = TODO()
    open fun getInterfaces(): Array<Class<Any>> = TODO()
    open fun getClassLoader(): ClassLoader = TODO()
    open fun getEnumConstants(): Array<T> = TODO()
    open fun getDeclaredFields(): Array<java.lang.reflect.Field> = TODO()
    open fun getFields(): Array<java.lang.reflect.Field> = TODO()
    open fun getDeclaredField(name: String?): java.lang.reflect.Field = TODO()
    open fun getField(name: String?): java.lang.reflect.Field = TODO()
    open fun getDeclaredMethods(): Array<java.lang.reflect.Method> = TODO()
    open fun getMethods(): Array<java.lang.reflect.Method> = TODO()
    open fun getDeclaredMethod(name: String?, vararg types: Class<*>?): java.lang.reflect.Method = TODO()
    open fun getMethod(name: String?, vararg types: Class<*>?): java.lang.reflect.Method = TODO()
    open fun getDeclaredConstructor(vararg types: Class<*>?): Any = TODO()
    companion object {
        fun forName(name: String?): Class<Any> = TODO()
        fun forName(name: String?, init: Boolean, cl: ClassLoader?): Class<Any> = TODO()
    }
}
"""),
("ClassLoader", """
open class ClassLoader {
    open fun loadClass(name: String?): Class<Any> = TODO()
    open fun getResource(name: String?): java.net.URL = TODO()
    open fun getResourceAsStream(name: String?): java.io.InputStream = TODO()
    companion object {
        fun getSystemClassLoader(): ClassLoader = TODO()
    }
}
"""),
("Void", """
class Void private constructor() {
    companion object { val TYPE: Class<Void> get() = TODO() }
}
"""),
("StringBuffer", """
open class StringBuffer() {
    constructor(capacity: Int) : this()
    constructor(s: String?) : this()
    open fun append(v: Any?): StringBuffer = TODO()
    open fun insert(i: Int, v: Any?): StringBuffer = TODO()
    open fun setLength(n: Int): Unit = TODO()
    open fun length(): Int = TODO()
    open fun charAt(i: Int): Char = TODO()
    open fun substring(a: Int, b: Int): String = TODO()
    open fun deleteCharAt(i: Int): StringBuffer = TODO()
}
"""),
("Runtime", """
open class Runtime {
    open fun exec(cmd: Array<String>?): Process = TODO()
    open fun availableProcessors(): Int = TODO()
    open fun maxMemory(): Long = TODO()
    open fun totalMemory(): Long = TODO()
    open fun freeMemory(): Long = TODO()
    open fun gc(): Unit = TODO()
    companion object { fun getRuntime(): Runtime = TODO() }
}
open class Process {
    open fun waitFor(): Int = TODO()
    open fun destroy(): Unit = TODO()
    open fun exitValue(): Int = TODO()
    open fun getInputStream(): java.io.InputStream = TODO()
    open fun getOutputStream(): java.io.OutputStream = TODO()
    open fun getErrorStream(): java.io.InputStream = TODO()
}
"""),
("ThreadLocal", """
open class ThreadLocal<T>() {
    open fun get(): T = TODO()
    open fun set(v: T): Unit = TODO()
    open fun remove(): Unit = TODO()
}
"""),
("AutoCloseable", """
interface AutoCloseable {
    fun close()
}
"""),
("SecurityException", """
open class SecurityException(message: String? = null, cause: Throwable? = null)
    : RuntimeException(message, cause)
open class InterruptedException(message: String? = null) : Exception(message)
open class ClassNotFoundException(message: String? = null) : Exception(message)
open class NoSuchMethodException(message: String? = null) : Exception(message)
open class NoSuchFieldException(message: String? = null) : Exception(message)
open class IllegalAccessException(message: String? = null) : Exception(message)
open class InstantiationException(message: String? = null) : Exception(message)
open class CloneNotSupportedException(message: String? = null) : Exception(message)
open class ArrayIndexOutOfBoundsException(message: String? = null) : IndexOutOfBoundsException(message)
open class StringIndexOutOfBoundsException(message: String? = null) : IndexOutOfBoundsException(message)
open class OutOfMemoryError(message: String? = null) : Error(message)
open class StackOverflowError(message: String? = null) : Error(message)
open class UnsatisfiedLinkError(message: String? = null) : Error(message)
open class NoClassDefFoundError(message: String? = null) : Error(message)
"""),
("wait", """
// JVM monitors.  j2k drops `synchronized`, but Object.wait/notify survive as
// bare calls with no receiver type to hang them on.
fun Any.wait(): Unit = TODO()
fun Any.wait(timeout: Long): Unit = TODO()
fun Any.notify(): Unit = TODO()
fun Any.notifyAll(): Unit = TODO()
fun Any.clone(): Any = TODO()
fun Any.finalize(): Unit = TODO()
"""),
("TYPE", """
// Integer.TYPE and friends: the primitive Class object, reached through the
// Kotlin companion because a java.lang.Boolean of ours would shadow kotlin.Boolean.
val Boolean.Companion.TYPE: Class<Boolean> get() = TODO()
val Byte.Companion.TYPE: Class<Byte> get() = TODO()
val Char.Companion.TYPE: Class<Char> get() = TODO()
val Short.Companion.TYPE: Class<Short> get() = TODO()
val Int.Companion.TYPE: Class<Int> get() = TODO()
val Long.Companion.TYPE: Class<Long> get() = TODO()
val Float.Companion.TYPE: Class<Float> get() = TODO()
val Double.Companion.TYPE: Class<Double> get() = TODO()
"""),
# statics on types Kotlin already owns; they cannot be classes of ours without
# shadowing kotlin.Long / kotlin.String for the whole importing file.
("parseLong", """
fun Long.Companion.parseLong(s: String?): Long = TODO()
fun Long.Companion.parseLong(s: String?, radix: Int): Long = TODO()
"""),
("parseFloat", """
fun Float.Companion.parseFloat(s: String?): Float = TODO()
"""),
("parseDouble", """
fun Double.Companion.parseDouble(s: String?): Double = TODO()
"""),
("parseBoolean", """
fun Boolean.Companion.parseBoolean(s: String?): Boolean = TODO()
"""),
("valueOf", """
fun Long.Companion.valueOf(s: String?): Long = TODO()
fun Long.Companion.valueOf(v: Long): Long = TODO()
fun Float.Companion.valueOf(s: String?): Float = TODO()
fun Float.Companion.valueOf(v: Float): Float = TODO()
fun Double.Companion.valueOf(s: String?): Double = TODO()
fun Double.Companion.valueOf(v: Double): Double = TODO()
fun Boolean.Companion.valueOf(s: String?): Boolean = TODO()
fun Boolean.Companion.valueOf(v: Boolean): Boolean = TODO()
fun String.Companion.valueOf(v: Any?): String = TODO()
fun Char.Companion.valueOf(v: Char): Char = TODO()
"""),
("format", """
fun String.Companion.format(fmt: String?, vararg args: Any?): String = TODO()
fun String.Companion.format(locale: java.util.Locale?, fmt: String?, vararg args: Any?): String = TODO()
"""),
("getClass", """
fun Any.getClass(): Class<Any> = TODO()
"""),
("getName", """
// j2k renders Java's `Foo.class` as `Foo::class`, a KClass.  The JDK's Class
// API is reached on it through these rather than by reifying a java.lang.Class.
fun kotlin.reflect.KClass<*>.getName(): String = TODO()
fun kotlin.reflect.KClass<*>.getSimpleName(): String = TODO()
fun kotlin.reflect.KClass<*>.getCanonicalName(): String = TODO()
fun kotlin.reflect.KClass<*>.isInstance(o: Any?): Boolean = TODO()
fun kotlin.reflect.KClass<*>.isAssignableFrom(c: Any?): Boolean = TODO()
fun kotlin.reflect.KClass<*>.newInstance(): Any = TODO()
fun kotlin.reflect.KClass<*>.getDeclaredMethod(name: String?, vararg types: Any?): java.lang.reflect.Method = TODO()
fun kotlin.reflect.KClass<*>.getMethod(name: String?, vararg types: Any?): java.lang.reflect.Method = TODO()
fun kotlin.reflect.KClass<*>.getDeclaredFields(): Array<java.lang.reflect.Field> = TODO()
fun kotlin.reflect.KClass<*>.getDeclaredField(name: String?): java.lang.reflect.Field = TODO()
"""),
])

S["jdk_lang_ref"] = ("java.lang.ref", [
("WeakReference", """
open class WeakReference<T>(referent: T?) {
    open fun get(): T = TODO()
    open fun clear(): Unit = TODO()
}
open class SoftReference<T>(referent: T?) {
    open fun get(): T = TODO()
    open fun clear(): Unit = TODO()
}
"""),
])

S["jdk_lang_reflect"] = ("java.lang.reflect", [
("Method", """
open class Method {
    open fun getName(): String = TODO()
    open fun getModifiers(): Int = TODO()
    open fun getReturnType(): java.lang.Class<Any> = TODO()
    open fun getParameterTypes(): Array<java.lang.Class<Any>> = TODO()
    open fun getDeclaringClass(): java.lang.Class<Any> = TODO()
    open fun setAccessible(flag: Boolean): Unit = TODO()
    open fun invoke(receiver: Any?, vararg args: Any?): Any = TODO()
}
"""),
("Field", """
open class Field {
    open fun getName(): String = TODO()
    open fun getModifiers(): Int = TODO()
    open fun getType(): java.lang.Class<Any> = TODO()
    open fun getDeclaringClass(): java.lang.Class<Any> = TODO()
    open fun setAccessible(flag: Boolean): Unit = TODO()
    open fun get(receiver: Any?): Any = TODO()
    open fun set(receiver: Any?, v: Any?): Unit = TODO()
    open fun getInt(receiver: Any?): Int = TODO()
    open fun getBoolean(receiver: Any?): Boolean = TODO()
}
"""),
("Modifier", """
object Modifier {
    const val PUBLIC: Int = 1
    const val PRIVATE: Int = 2
    const val PROTECTED: Int = 4
    const val STATIC: Int = 8
    const val FINAL: Int = 16
    const val NATIVE: Int = 256
    fun isPublic(m: Int): Boolean = TODO()
    fun isStatic(m: Int): Boolean = TODO()
    fun isFinal(m: Int): Boolean = TODO()
    fun isNative(m: Int): Boolean = TODO()
    fun isAbstract(m: Int): Boolean = TODO()
}
"""),
# java.lang.reflect.Array would shadow kotlin.Array in any importing file.
# jdk-stubs.py drops that import and qualifies the call sites onto this.
("ArrayReflect", """
object ArrayReflect {
    fun getLength(a: Any?): Int = TODO()
    fun get(a: Any?, i: Int): Any = TODO()
    fun set(a: Any?, i: Int, v: Any?): Unit = TODO()
    fun newInstance(component: java.lang.Class<*>?, len: Int): Any = TODO()
}
"""),
("InvocationHandler", """
fun interface InvocationHandler {
    fun invoke(proxy: Any?, method: Method?, args: Array<Any?>?): Any?
}
"""),
("Proxy", """
open class Proxy {
    companion object {
        fun newProxyInstance(cl: java.lang.ClassLoader?, ifaces: Array<java.lang.Class<*>?>?,
                             h: InvocationHandler?): Any = TODO()
        fun getInvocationHandler(proxy: Any?): InvocationHandler = TODO()
        fun isProxyClass(c: java.lang.Class<*>?): Boolean = TODO()
    }
}
"""),
("InvocationTargetException", """
open class InvocationTargetException(cause: Throwable? = null) : Exception(cause) {
    open fun getTargetException(): Throwable = TODO()
}
"""),
])

S["jdk_lang_annotation"] = ("java.lang.annotation", [
("RetentionPolicy", """
enum class RetentionPolicy { SOURCE, CLASS, RUNTIME }
"""),
("ElementType", """
enum class ElementType {
    TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE, ANNOTATION_TYPE,
    PACKAGE, TYPE_PARAMETER, TYPE_USE
}
"""),
("Retention", """
annotation class Retention(val value: RetentionPolicy)
"""),
("Target", """
annotation class Target(vararg val value: ElementType)
"""),
("Documented", """
annotation class Documented
annotation class Inherited
"""),
])

S["jdk_io"] = ("java.io", [
("IOException", """
open class IOException(message: String? = null, cause: Throwable? = null) : Exception(message, cause) {
    // Java's IOException(Throwable).  The defaulted String? primary would
    // otherwise swallow the one-argument form.
    constructor(cause: Throwable?) : this(cause?.toString(), cause)
}
open class FileNotFoundException(message: String? = null) : IOException(message)
open class InterruptedIOException(message: String? = null) : IOException(message)
open class UnsupportedEncodingException(message: String? = null) : IOException(message)
open class EOFException(message: String? = null) : IOException(message)
"""),
("Closeable", """
interface Closeable {
    fun close()
}
interface Flushable {
    fun flush()
}
interface Serializable
"""),
("InputStream", """
open class InputStream : Closeable {
    override fun close(): Unit = TODO()
    open fun read(): Int = TODO()
    open fun read(b: ByteArray?): Int = TODO()
    open fun read(b: ByteArray?, off: Int, len: Int): Int = TODO()
    open fun available(): Int = TODO()
    open fun skip(n: Long): Long = TODO()
    open fun mark(limit: Int): Unit = TODO()
    open fun reset(): Unit = TODO()
    open fun markSupported(): Boolean = TODO()
}
"""),
("OutputStream", """
open class OutputStream : Closeable, Flushable {
    override fun close(): Unit = TODO()
    override fun flush(): Unit = TODO()
    open fun write(b: Int): Unit = TODO()
    open fun write(b: ByteArray?): Unit = TODO()
    open fun write(b: ByteArray?, off: Int, len: Int): Unit = TODO()
}
"""),
("ByteArrayInputStream", """
open class ByteArrayInputStream(buf: ByteArray?) : InputStream() {
    constructor(buf: ByteArray?, off: Int, len: Int) : this(buf)
}
"""),
("ByteArrayOutputStream", """
open class ByteArrayOutputStream() : OutputStream() {
    constructor(size: Int) : this()
    open fun toByteArray(): ByteArray = TODO()
    open fun size(): Int = TODO()
    open fun reset(): Unit = TODO()
    open fun writeTo(out: OutputStream?): Unit = TODO()
}
"""),
("BufferedInputStream", """
open class BufferedInputStream(s: InputStream?) : InputStream()
open class BufferedOutputStream(s: OutputStream?) : OutputStream()
open class DataInputStream(s: InputStream?) : InputStream() {
    open fun readInt(): Int = TODO()
    open fun readLong(): Long = TODO()
    open fun readFully(b: ByteArray?): Unit = TODO()
}
open class DataOutputStream(s: OutputStream?) : OutputStream() {
    open fun writeInt(v: Int): Unit = TODO()
    open fun writeLong(v: Long): Unit = TODO()
}
"""),
("FileDescriptor", """
open class FileDescriptor {
    open fun valid(): Boolean = TODO()
    open fun sync(): Unit = TODO()
    companion object {
        val `in`: FileDescriptor = TODO()
        val out: FileDescriptor = TODO()
        val err: FileDescriptor = TODO()
    }
}
"""),
("File", """
open class File(path: String?) {
    constructor(parent: String?, child: String?) : this(child)
    constructor(parent: File?, child: String?) : this(child)
    open fun getName(): String = TODO()
    open fun getPath(): String = TODO()
    open fun getAbsolutePath(): String = TODO()
    open fun getCanonicalPath(): String = TODO()
    open fun getParent(): String = TODO()
    open fun getParentFile(): File = TODO()
    open fun exists(): Boolean = TODO()
    open fun isDirectory(): Boolean = TODO()
    open fun isFile(): Boolean = TODO()
    open fun canRead(): Boolean = TODO()
    open fun canWrite(): Boolean = TODO()
    open fun canExecute(): Boolean = TODO()
    open fun delete(): Boolean = TODO()
    open fun deleteOnExit(): Unit = TODO()
    open fun mkdir(): Boolean = TODO()
    open fun mkdirs(): Boolean = TODO()
    open fun createNewFile(): Boolean = TODO()
    open fun renameTo(dest: File?): Boolean = TODO()
    open fun length(): Long = TODO()
    open fun lastModified(): Long = TODO()
    open fun setLastModified(t: Long): Boolean = TODO()
    open fun setReadable(r: Boolean, ownerOnly: Boolean): Boolean = TODO()
    open fun setWritable(w: Boolean, ownerOnly: Boolean): Boolean = TODO()
    open fun setExecutable(x: Boolean, ownerOnly: Boolean): Boolean = TODO()
    open fun listFiles(): Array<File> = TODO()
    open fun list(): Array<String> = TODO()
    open fun getFreeSpace(): Long = TODO()
    open fun getUsableSpace(): Long = TODO()
    open fun toURI(): java.net.URI = TODO()
    companion object {
        val separator: String = "/"
        val separatorChar: Char = '/'
        val pathSeparator: String = ":"
        fun createTempFile(prefix: String?, suffix: String?): File = TODO()
        fun createTempFile(prefix: String?, suffix: String?, dir: File?): File = TODO()
    }
}
"""),
("FileInputStream", """
open class FileInputStream(f: File?) : InputStream() {
    constructor(path: String?) : this(null as File?)
    constructor(fd: FileDescriptor?) : this(null as File?)
    open fun getFD(): FileDescriptor = TODO()
    open fun getChannel(): java.nio.channels.FileChannel = TODO()
}
open class FileOutputStream(f: File?) : OutputStream() {
    constructor(path: String?) : this(null as File?)
    constructor(path: String?, append: Boolean) : this(null as File?)
    constructor(f: File?, append: Boolean) : this(f)
    constructor(fd: FileDescriptor?) : this(null as File?)
    open fun getFD(): FileDescriptor = TODO()
    open fun getChannel(): java.nio.channels.FileChannel = TODO()
}
"""),
("Reader", """
open class Reader : Closeable {
    override fun close(): Unit = TODO()
    open fun read(): Int = TODO()
    open fun read(b: CharArray?): Int = TODO()
    open fun read(b: CharArray?, off: Int, len: Int): Int = TODO()
    open fun ready(): Boolean = TODO()
}
open class Writer : Closeable, Flushable {
    override fun close(): Unit = TODO()
    override fun flush(): Unit = TODO()
    open fun write(s: String?): Unit = TODO()
    open fun write(c: Int): Unit = TODO()
    open fun write(b: CharArray?, off: Int, len: Int): Unit = TODO()
    open fun append(c: Char): Writer = TODO()
}
"""),
("InputStreamReader", """
open class InputStreamReader(s: InputStream?) : Reader() {
    constructor(s: InputStream?, charset: java.nio.charset.Charset?) : this(s)
    constructor(s: InputStream?, charset: String?) : this(s)
}
open class OutputStreamWriter(s: OutputStream?) : Writer() {
    constructor(s: OutputStream?, charset: java.nio.charset.Charset?) : this(s)
    constructor(s: OutputStream?, charset: String?) : this(s)
}
"""),
("BufferedReader", """
open class BufferedReader(r: Reader?) : Reader() {
    constructor(r: Reader?, size: Int) : this(r)
    open fun readLine(): String = TODO()
}
open class BufferedWriter(w: Writer?) : Writer() {
    constructor(w: Writer?, size: Int) : this(w)
    open fun newLine(): Unit = TODO()
}
"""),
("FileReader", """
open class FileReader(f: File?) : Reader() {
    constructor(path: String?) : this(null as File?)
}
open class FileWriter(f: File?) : Writer() {
    constructor(path: String?) : this(null as File?)
    constructor(f: File?, append: Boolean) : this(f)
}
"""),
("StringWriter", """
open class StringWriter() : Writer() {
    open fun getBuffer(): java.lang.StringBuffer = TODO()
}
open class PrintWriter(w: Writer?) : Writer() {
    constructor(s: OutputStream?) : this(null as Writer?)
    constructor(f: File?) : this(null as Writer?)
    open fun println(v: Any?): Unit = TODO()
    open fun print(v: Any?): Unit = TODO()
    open fun printf(fmt: String?, vararg args: Any?): PrintWriter = TODO()
}
open class PrintStream(s: OutputStream?) : OutputStream() {
    open fun println(v: Any?): Unit = TODO()
    open fun println(): Unit = TODO()
    open fun print(v: Any?): Unit = TODO()
    open fun printf(fmt: String?, vararg args: Any?): PrintStream = TODO()
}
"""),
("RandomAccessFile", """
open class RandomAccessFile(f: File?, mode: String?) : Closeable {
    constructor(path: String?, mode: String?) : this(null as File?, mode)
    override fun close(): Unit = TODO()
    open fun length(): Long = TODO()
    open fun seek(pos: Long): Unit = TODO()
    open fun read(b: ByteArray?): Int = TODO()
    open fun write(b: ByteArray?): Unit = TODO()
    open fun getFD(): FileDescriptor = TODO()
    open fun getChannel(): java.nio.channels.FileChannel = TODO()
}
"""),
])

S["jdk_nio"] = ("java.nio", [
("Buffer", """
open class Buffer {
    open fun capacity(): Int = TODO()
    open fun position(): Int = TODO()
    open fun position(p: Int): Buffer = TODO()
    open fun limit(): Int = TODO()
    open fun limit(l: Int): Buffer = TODO()
    open fun remaining(): Int = TODO()
    open fun hasRemaining(): Boolean = TODO()
    open fun clear(): Buffer = TODO()
    open fun flip(): Buffer = TODO()
    open fun rewind(): Buffer = TODO()
    open fun mark(): Buffer = TODO()
    open fun reset(): Buffer = TODO()
    open fun isDirect(): Boolean = TODO()
    open fun hasArray(): Boolean = TODO()
    open fun isReadOnly(): Boolean = TODO()
}
"""),
("ByteOrder", """
open class ByteOrder {
    companion object {
        val BIG_ENDIAN: ByteOrder = TODO()
        val LITTLE_ENDIAN: ByteOrder = TODO()
        fun nativeOrder(): ByteOrder = TODO()
    }
}
"""),
("ByteBuffer", """
open class ByteBuffer : Buffer() {
    open fun array(): ByteArray = TODO()
    open fun arrayOffset(): Int = TODO()
    open fun get(): Byte = TODO()
    open fun get(i: Int): Byte = TODO()
    open fun get(dst: ByteArray?): ByteBuffer = TODO()
    open fun get(dst: ByteArray?, off: Int, len: Int): ByteBuffer = TODO()
    open fun put(b: Byte): ByteBuffer = TODO()
    open fun put(i: Int, b: Byte): ByteBuffer = TODO()
    open fun put(src: ByteArray?): ByteBuffer = TODO()
    open fun put(src: ByteArray?, off: Int, len: Int): ByteBuffer = TODO()
    open fun put(src: ByteBuffer?): ByteBuffer = TODO()
    open fun getInt(): Int = TODO()
    open fun getInt(i: Int): Int = TODO()
    open fun putInt(v: Int): ByteBuffer = TODO()
    open fun getLong(): Long = TODO()
    open fun putLong(v: Long): ByteBuffer = TODO()
    open fun getShort(): Short = TODO()
    open fun putShort(v: Short): ByteBuffer = TODO()
    open fun getFloat(): Float = TODO()
    open fun putFloat(v: Float): ByteBuffer = TODO()
    open fun getDouble(): Double = TODO()
    open fun putDouble(v: Double): ByteBuffer = TODO()
    open fun getChar(): Char = TODO()
    open fun order(): ByteOrder = TODO()
    open fun order(o: ByteOrder?): ByteBuffer = TODO()
    open fun slice(): ByteBuffer = TODO()
    open fun duplicate(): ByteBuffer = TODO()
    open fun asReadOnlyBuffer(): ByteBuffer = TODO()
    open fun asIntBuffer(): IntBuffer = TODO()
    open fun asCharBuffer(): CharBuffer = TODO()
    open fun compact(): ByteBuffer = TODO()
    companion object {
        fun allocate(cap: Int): ByteBuffer = TODO()
        fun allocateDirect(cap: Int): ByteBuffer = TODO()
        fun wrap(a: ByteArray?): ByteBuffer = TODO()
        fun wrap(a: ByteArray?, off: Int, len: Int): ByteBuffer = TODO()
    }
}
"""),
("CharBuffer", """
open class CharBuffer : Buffer() {
    open fun array(): CharArray = TODO()
    open fun get(): Char = TODO()
    open fun get(i: Int): Char = TODO()
    open fun put(c: Char): CharBuffer = TODO()
    override fun toString(): String = TODO()
    companion object {
        fun allocate(cap: Int): CharBuffer = TODO()
        fun wrap(s: CharSequence?): CharBuffer = TODO()
        fun wrap(a: CharArray?): CharBuffer = TODO()
    }
}
open class IntBuffer : Buffer() {
    open fun array(): IntArray = TODO()
    open fun get(): Int = TODO()
    open fun get(i: Int): Int = TODO()
    open fun put(v: Int): IntBuffer = TODO()
    companion object {
        fun allocate(cap: Int): IntBuffer = TODO()
        fun wrap(a: IntArray?): IntBuffer = TODO()
    }
}
open class FloatBuffer : Buffer() {
    open fun array(): FloatArray = TODO()
    open fun get(i: Int): Float = TODO()
    open fun put(v: Float): FloatBuffer = TODO()
    companion object { fun allocate(cap: Int): FloatBuffer = TODO() }
}
"""),
])

S["jdk_nio_charset"] = ("java.nio.charset", [
("Charset", """
open class Charset {
    open fun name(): String = TODO()
    open fun displayName(): String = TODO()
    open fun decode(b: java.nio.ByteBuffer?): java.nio.CharBuffer = TODO()
    open fun encode(s: String?): java.nio.ByteBuffer = TODO()
    companion object {
        fun forName(name: String?): Charset = TODO()
        fun defaultCharset(): Charset = TODO()
        fun isSupported(name: String?): Boolean = TODO()
    }
}
"""),
("StandardCharsets", """
object StandardCharsets {
    val UTF_8: Charset = TODO()
    val US_ASCII: Charset = TODO()
    val ISO_8859_1: Charset = TODO()
    val UTF_16: Charset = TODO()
    val UTF_16BE: Charset = TODO()
    val UTF_16LE: Charset = TODO()
}
"""),
("UnsupportedCharsetException", """
open class UnsupportedCharsetException(name: String? = null) : IllegalArgumentException(name)
open class CharacterCodingException : java.io.IOException()
"""),
])

S["jdk_nio_channels"] = ("java.nio.channels", [
("Channel", """
interface Channel : java.io.Closeable {
    fun isOpen(): Boolean
}
interface ReadableByteChannel : Channel {
    fun read(dst: java.nio.ByteBuffer?): Int
}
interface WritableByteChannel : Channel {
    fun write(src: java.nio.ByteBuffer?): Int
}
"""),
("FileChannel", """
open class FileChannel : ReadableByteChannel, WritableByteChannel {
    override fun isOpen(): Boolean = TODO()
    override fun close(): Unit = TODO()
    override fun read(dst: java.nio.ByteBuffer?): Int = TODO()
    override fun write(src: java.nio.ByteBuffer?): Int = TODO()
    open fun size(): Long = TODO()
    open fun position(): Long = TODO()
    open fun position(p: Long): FileChannel = TODO()
    open fun truncate(n: Long): FileChannel = TODO()
    open fun force(meta: Boolean): Unit = TODO()
    open fun transferTo(pos: Long, count: Long, target: WritableByteChannel?): Long = TODO()
    open fun transferFrom(src: ReadableByteChannel?, pos: Long, count: Long): Long = TODO()
    open fun map(mode: Any?, pos: Long, size: Long): java.nio.ByteBuffer = TODO()
}
"""),
("Channels", """
object Channels {
    fun newChannel(s: java.io.InputStream?): ReadableByteChannel = TODO()
    fun newChannel(s: java.io.OutputStream?): WritableByteChannel = TODO()
    fun newInputStream(c: ReadableByteChannel?): java.io.InputStream = TODO()
    fun newOutputStream(c: WritableByteChannel?): java.io.OutputStream = TODO()
}
"""),
])

S["jdk_math"] = ("java.math", [
("BigInteger", """
open class BigInteger(s: String?) {
    constructor(s: String?, radix: Int) : this(s)
    constructor(signum: Int, magnitude: ByteArray?) : this(null as String?)
    open fun toByteArray(): ByteArray = TODO()
    open fun intValue(): Int = TODO()
    open fun longValue(): Long = TODO()
    open fun signum(): Int = TODO()
    open fun add(o: BigInteger?): BigInteger = TODO()
    open fun compareTo(o: BigInteger?): Int = TODO()
    companion object {
        val ZERO: BigInteger = TODO()
        val ONE: BigInteger = TODO()
        fun valueOf(v: Long): BigInteger = TODO()
    }
}
open class BigDecimal(s: String?) {
    open fun doubleValue(): Double = TODO()
    open fun toPlainString(): String = TODO()
}
"""),
])

S["jdk_util"] = ("java.util", [
# Kotlin's mutable collections, under their JDK names.  Java code calls
# add/put/remove on these, and the android.* stub lanes already speak
# kotlin.collections, so aliasing beats a parallel hierarchy of our own.
("List", """
typealias List<E> = MutableList<E>
typealias Collection<E> = MutableCollection<E>
typealias Set<E> = MutableSet<E>
typealias Map<K, V> = MutableMap<K, V>
typealias Iterator<E> = MutableIterator<E>
typealias ListIterator<E> = MutableListIterator<E>
typealias Iterable<E> = kotlin.collections.Iterable<E>
typealias ArrayList<E> = kotlin.collections.ArrayList<E>
typealias HashMap<K, V> = kotlin.collections.HashMap<K, V>
typealias LinkedHashMap<K, V> = kotlin.collections.LinkedHashMap<K, V>
typealias HashSet<E> = kotlin.collections.HashSet<E>
typealias LinkedHashSet<E> = kotlin.collections.LinkedHashSet<E>
typealias Comparator<T> = kotlin.Comparator<T>
typealias NoSuchElementException = kotlin.NoSuchElementException
typealias ConcurrentModificationException = kotlin.ConcurrentModificationException
typealias RandomAccess = kotlin.collections.RandomAccess
"""),
("getKey", """
// Map.Entry is rewritten to MutableMap.MutableEntry; Java asks for its halves
// with getters Kotlin spells as properties.
fun <K, V> kotlin.collections.Map.Entry<K, V>.getKey(): K = key
fun <K, V> kotlin.collections.Map.Entry<K, V>.getValue(): V = value

// Map methods Kotlin has only on the JVM.
fun <K, V> MutableMap<K, V>.computeIfAbsent(k: K, f: (K) -> V): V = TODO()
fun <K, V> MutableMap<K, V>.putIfAbsent(k: K, v: V): V = TODO()
fun <K, V> MutableMap<K, V>.getOrDefault(k: K, def: V): V = TODO()
"""),
("Queue", """
interface Queue<E> : MutableList<E> {
    fun offer(e: E): Boolean
    fun poll(): E
    fun peek(): E
    fun element(): E
    fun remove(): E
}
interface Deque<E> : Queue<E> {
    fun addFirst(e: E)
    fun addLast(e: E)
    fun offerFirst(e: E): Boolean
    fun offerLast(e: E): Boolean
    fun removeFirst(): E
    fun removeLast(): E
    fun pollFirst(): E
    fun pollLast(): E
    fun peekFirst(): E
    fun peekLast(): E
    fun getFirst(): E
    fun getLast(): E
    fun push(e: E)
    fun pop(): E
    fun descendingIterator(): MutableIterator<E>
}
"""),
("AbstractQueue", """
// One delegating base: Kotlin has no open ArrayList to extend, but `by` gives
// every MutableList member for free and leaves only the deque half to stub.
abstract class AbstractDeque<E> : Deque<E>, MutableList<E> by kotlin.collections.ArrayList<E>() {
    override fun offer(e: E): Boolean = TODO()
    override fun poll(): E = TODO()
    override fun peek(): E = TODO()
    override fun element(): E = TODO()
    override fun remove(): E = TODO()
    override fun addFirst(e: E): Unit = TODO()
    override fun addLast(e: E): Unit = TODO()
    override fun offerFirst(e: E): Boolean = TODO()
    override fun offerLast(e: E): Boolean = TODO()
    override fun removeFirst(): E = TODO()
    override fun removeLast(): E = TODO()
    override fun pollFirst(): E = TODO()
    override fun pollLast(): E = TODO()
    override fun peekFirst(): E = TODO()
    override fun peekLast(): E = TODO()
    override fun getFirst(): E = TODO()
    override fun getLast(): E = TODO()
    override fun push(e: E): Unit = TODO()
    override fun pop(): E = TODO()
    override fun descendingIterator(): MutableIterator<E> = TODO()
}
"""),
("LinkedList", """
open class LinkedList<E>() : AbstractDeque<E>() {
    constructor(c: kotlin.collections.Collection<E>?) : this()
}
open class ArrayDeque<E>() : AbstractDeque<E>() {
    constructor(capacity: Int) : this()
    constructor(c: kotlin.collections.Collection<E>?) : this()
}
open class Stack<E>() : AbstractDeque<E>() {
    open fun empty(): Boolean = TODO()
    open fun search(o: Any?): Int = TODO()
}
open class Vector<E>() : AbstractDeque<E>() {
    constructor(capacity: Int) : this()
}
"""),
("TreeMap", """
open class TreeMap<K, V>() : MutableMap<K, V> by kotlin.collections.HashMap<K, V>() {
    constructor(c: kotlin.Comparator<in K>?) : this()
    constructor(m: kotlin.collections.Map<K, V>?) : this()
    open fun firstKey(): K = TODO()
    open fun lastKey(): K = TODO()
    open fun headMap(k: K): MutableMap<K, V> = TODO()
    open fun tailMap(k: K): MutableMap<K, V> = TODO()
}
open class WeakHashMap<K, V>() : MutableMap<K, V> by kotlin.collections.HashMap<K, V>() {
    constructor(capacity: Int) : this()
}
open class EnumMap<K, V>(type: java.lang.Class<K>?) : MutableMap<K, V> by kotlin.collections.HashMap<K, V>() {
    open fun clone(): EnumMap<K, V> = TODO()
}
open class TreeSet<E>() : MutableSet<E> by kotlin.collections.HashSet<E>() {
    constructor(c: kotlin.Comparator<in E>?) : this()
}
"""),
("Arrays", """
object Arrays {
    fun <T> asList(a: Array<out T>): MutableList<T> = TODO()
    fun <T> asList(vararg a: T): MutableList<T> = TODO()
    fun <T> copyOf(a: Array<out T>, n: Int): Array<T> = TODO()
    fun <T> copyOf(a: Array<out T>, n: Int, cls: java.lang.Class<*>?): Array<T> = TODO()
    fun copyOf(a: ByteArray, n: Int): ByteArray = TODO()
    fun copyOf(a: IntArray, n: Int): IntArray = TODO()
    fun copyOf(a: LongArray, n: Int): LongArray = TODO()
    fun copyOf(a: FloatArray, n: Int): FloatArray = TODO()
    fun copyOf(a: DoubleArray, n: Int): DoubleArray = TODO()
    fun copyOf(a: BooleanArray, n: Int): BooleanArray = TODO()
    fun <T> copyOfRange(a: Array<T>, from: Int, to: Int): Array<T> = TODO()
    fun copyOfRange(a: ByteArray, from: Int, to: Int): ByteArray = TODO()
    fun copyOfRange(a: IntArray, from: Int, to: Int): IntArray = TODO()
    fun equals(a: Any?, b: Any?): Boolean = TODO()
    fun hashCode(a: Any?): Int = TODO()
    fun deepHashCode(a: Any?): Int = TODO()
    fun toString(a: Any?): String = TODO()
    fun deepToString(a: Any?): String = TODO()
    fun <T> fill(a: Array<T>, v: T): Unit = TODO()
    fun fill(a: ByteArray, v: Byte): Unit = TODO()
    fun fill(a: IntArray, v: Int): Unit = TODO()
    fun fill(a: BooleanArray, v: Boolean): Unit = TODO()
    fun <T> sort(a: Array<T>): Unit = TODO()
    fun <T> sort(a: Array<T>, c: kotlin.Comparator<in T>?): Unit = TODO()
    fun sort(a: IntArray): Unit = TODO()
    fun <T> binarySearch(a: Array<T>, key: T): Int = TODO()
    fun binarySearch(a: IntArray, key: Int): Int = TODO()
    fun <T> stream(a: Array<T>): kotlin.sequences.Sequence<T> = TODO()
}
"""),
("Collections", """
object Collections {
    fun <E> emptyList(): MutableList<E> = TODO()
    fun <K, V> emptyMap(): MutableMap<K, V> = TODO()
    fun <E> emptySet(): MutableSet<E> = TODO()
    fun <E> singletonList(e: E): MutableList<E> = TODO()
    fun <E> singleton(e: E): MutableSet<E> = TODO()
    fun <K, V> singletonMap(k: K, v: V): MutableMap<K, V> = TODO()
    fun <E> unmodifiableList(l: kotlin.collections.List<E>?): MutableList<E> = TODO()
    fun <E> unmodifiableCollection(c: kotlin.collections.Collection<E>?): MutableCollection<E> = TODO()
    fun <E> unmodifiableSet(s: kotlin.collections.Set<E>?): MutableSet<E> = TODO()
    fun <K, V> unmodifiableMap(m: kotlin.collections.Map<K, V>?): MutableMap<K, V> = TODO()
    fun <E> synchronizedList(l: MutableList<E>?): MutableList<E> = TODO()
    fun <K, V> synchronizedMap(m: MutableMap<K, V>?): MutableMap<K, V> = TODO()
    fun <E> synchronizedSet(s: MutableSet<E>?): MutableSet<E> = TODO()
    fun <E> nCopies(n: Int, e: E): MutableList<E> = TODO()
    fun <E> addAll(c: MutableCollection<E>?, vararg e: E): Boolean = TODO()
    fun <E> addAll(c: MutableCollection<E>?, e: Array<out E>?): Boolean = TODO()
    fun <E> sort(l: MutableList<E>?): Unit = TODO()
    fun <E> sort(l: MutableList<E>?, c: kotlin.Comparator<in E>?): Unit = TODO()
    fun <E> reverse(l: MutableList<E>?): Unit = TODO()
    fun <E> shuffle(l: MutableList<E>?): Unit = TODO()
    fun <E> max(c: kotlin.collections.Collection<E>?): E = TODO()
    fun <E> min(c: kotlin.collections.Collection<E>?): E = TODO()
    fun <K, V> newSetFromMap(m: MutableMap<K, Boolean>?): MutableSet<K> = TODO()
}
"""),
("Objects", """
object Objects {
    fun equals(a: Any?, b: Any?): Boolean = TODO()
    fun deepEquals(a: Any?, b: Any?): Boolean = TODO()
    fun hash(vararg a: Any?): Int = TODO()
    fun hashCode(a: Any?): Int = TODO()
    fun <T> requireNonNull(o: T): T = TODO()
    fun <T> requireNonNull(o: T, message: String?): T = TODO()
    fun toString(o: Any?): String = TODO()
    fun toString(o: Any?, def: String?): String = TODO()
    fun isNull(o: Any?): Boolean = TODO()
    fun nonNull(o: Any?): Boolean = TODO()
}
"""),
("UUID", """
open class UUID(most: Long, least: Long) {
    open fun getMostSignificantBits(): Long = TODO()
    open fun getLeastSignificantBits(): Long = TODO()
    companion object {
        fun randomUUID(): UUID = TODO()
        fun fromString(s: String?): UUID = TODO()
        fun nameUUIDFromBytes(b: ByteArray?): UUID = TODO()
    }
}
"""),
("Optional", """
open class Optional<T> {
    open fun get(): T = TODO()
    open fun isPresent(): Boolean = TODO()
    open fun isEmpty(): Boolean = TODO()
    open fun orElse(other: T): T = TODO()
    companion object {
        fun <T> of(v: T): Optional<T> = TODO()
        fun <T> ofNullable(v: T?): Optional<T> = TODO()
        fun <T> empty(): Optional<T> = TODO()
    }
}
"""),
("Enumeration", """
interface Enumeration<E> {
    fun hasMoreElements(): Boolean
    fun nextElement(): E
}
"""),
("StringTokenizer", """
open class StringTokenizer(s: String?) : Enumeration<Any> {
    constructor(s: String?, delim: String?) : this(s)
    constructor(s: String?, delim: String?, returnDelims: Boolean) : this(s)
    override fun hasMoreElements(): Boolean = TODO()
    override fun nextElement(): Any = TODO()
    open fun hasMoreTokens(): Boolean = TODO()
    open fun nextToken(): String = TODO()
    open fun countTokens(): Int = TODO()
}
"""),
("BitSet", """
open class BitSet() {
    constructor(nbits: Int) : this()
    open fun get(i: Int): Boolean = TODO()
    open fun set(i: Int): Unit = TODO()
    open fun set(i: Int, v: Boolean): Unit = TODO()
    open fun clear(i: Int): Unit = TODO()
    open fun clear(): Unit = TODO()
    open fun cardinality(): Int = TODO()
    open fun nextSetBit(from: Int): Int = TODO()
    open fun nextClearBit(from: Int): Int = TODO()
    open fun isEmpty(): Boolean = TODO()
    open fun size(): Int = TODO()
    open fun length(): Int = TODO()
}
"""),
("Timer", """
open class Timer() {
    constructor(name: String?) : this()
    constructor(isDaemon: Boolean) : this()
    open fun schedule(task: TimerTask?, delay: Long): Unit = TODO()
    open fun schedule(task: TimerTask?, delay: Long, period: Long): Unit = TODO()
    open fun scheduleAtFixedRate(task: TimerTask?, delay: Long, period: Long): Unit = TODO()
    open fun cancel(): Unit = TODO()
    open fun purge(): Int = TODO()
}
abstract class TimerTask : java.lang.Runnable {
    open fun cancel(): Boolean = TODO()
    open fun scheduledExecutionTime(): Long = TODO()
}
"""),
("Random", """
open class Random() {
    constructor(seed: Long) : this()
    open fun nextInt(): Int = TODO()
    open fun nextInt(bound: Int): Int = TODO()
    open fun nextLong(): Long = TODO()
    open fun nextBoolean(): Boolean = TODO()
    open fun nextDouble(): Double = TODO()
    open fun nextFloat(): Float = TODO()
    open fun nextBytes(b: ByteArray?): Unit = TODO()
    open fun setSeed(seed: Long): Unit = TODO()
}
"""),
("AbstractSequentialList", """
abstract class AbstractSequentialList<E> : MutableList<E> by kotlin.collections.ArrayList<E>()
abstract class AbstractList<E> : MutableList<E> by kotlin.collections.ArrayList<E>()
abstract class AbstractMap<K, V> : MutableMap<K, V> by kotlin.collections.HashMap<K, V>()
"""),
])

S["jdk_util_concurrent"] = ("java.util.concurrent", [
("TimeUnit", """
enum class TimeUnit {
    NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS;
    fun sleep(t: Long): Unit = TODO()
    fun toMillis(t: Long): Long = TODO()
    fun toNanos(t: Long): Long = TODO()
    fun toSeconds(t: Long): Long = TODO()
    fun convert(t: Long, u: TimeUnit): Long = TODO()
}
"""),
("TimeoutException", """
open class TimeoutException(message: String? = null) : Exception(message)
open class CancellationException(message: String? = null) : IllegalStateException(message)
open class ExecutionException(cause: Throwable? = null) : Exception(cause)
open class RejectedExecutionException(message: String? = null) : RuntimeException(message)
"""),
("Callable", """
fun interface Callable<V> {
    fun call(): V
}
"""),
("Future", """
interface Future<V> {
    fun get(): V
    fun get(timeout: Long, unit: TimeUnit?): V
    fun cancel(mayInterrupt: Boolean): Boolean
    fun isDone(): Boolean
    fun isCancelled(): Boolean
}
interface ScheduledFuture<V> : Future<V>
"""),
("FutureTask", """
open class FutureTask<V>(c: Callable<V>?) : Future<V>, java.lang.Runnable {
    constructor(r: java.lang.Runnable?, result: V) : this(null as Callable<V>?)
    override fun run(): Unit = TODO()
    override fun get(): V = TODO()
    override fun get(timeout: Long, unit: TimeUnit?): V = TODO()
    override fun cancel(mayInterrupt: Boolean): Boolean = TODO()
    override fun isDone(): Boolean = TODO()
    override fun isCancelled(): Boolean = TODO()
}
"""),
("Executor", """
interface Executor {
    fun execute(command: java.lang.Runnable?)
}
interface ExecutorService : Executor {
    fun shutdown()
    fun shutdownNow(): MutableList<java.lang.Runnable>
    fun isShutdown(): Boolean
    fun isTerminated(): Boolean
    fun awaitTermination(timeout: Long, unit: TimeUnit?): Boolean
    fun <T> submit(task: Callable<T>?): Future<T>
    fun submit(task: java.lang.Runnable?): Future<Any>
}
interface ScheduledExecutorService : ExecutorService {
    fun schedule(command: java.lang.Runnable?, delay: Long, unit: TimeUnit?): ScheduledFuture<Any>
    fun scheduleAtFixedRate(command: java.lang.Runnable?, initialDelay: Long,
                            period: Long, unit: TimeUnit?): ScheduledFuture<Any>
    fun scheduleWithFixedDelay(command: java.lang.Runnable?, initialDelay: Long,
                               delay: Long, unit: TimeUnit?): ScheduledFuture<Any>
}
"""),
("Executors", """
object Executors {
    fun newSingleThreadExecutor(): ExecutorService = TODO()
    fun newSingleThreadScheduledExecutor(): ScheduledExecutorService = TODO()
    fun newFixedThreadPool(n: Int): ExecutorService = TODO()
    fun newCachedThreadPool(): ExecutorService = TODO()
    fun newScheduledThreadPool(n: Int): ScheduledExecutorService = TODO()
}
"""),
("ConcurrentLinkedQueue", """
open class ConcurrentLinkedQueue<E>() : java.util.AbstractDeque<E>() {
    constructor(c: kotlin.collections.Collection<E>?) : this()
}
open class LinkedBlockingQueue<E>() : java.util.AbstractDeque<E>() {
    constructor(capacity: Int) : this()
    open fun take(): E = TODO()
    open fun put(e: E): Unit = TODO()
    open fun drainTo(c: MutableCollection<E>?): Int = TODO()
}
open class ConcurrentLinkedDeque<E>() : java.util.AbstractDeque<E>()
open class CopyOnWriteArrayList<E>() : java.util.AbstractDeque<E>()
"""),
("ConcurrentHashMap", """
open class ConcurrentHashMap<K, V>() : MutableMap<K, V> by kotlin.collections.HashMap<K, V>() {
    constructor(capacity: Int) : this()
    open fun putIfAbsent(k: K, v: V): V = TODO()
}
interface ConcurrentMap<K, V> : MutableMap<K, V>
"""),
("CountDownLatch", """
open class CountDownLatch(count: Int) {
    open fun countDown(): Unit = TODO()
    open fun await(): Unit = TODO()
    open fun await(timeout: Long, unit: TimeUnit?): Boolean = TODO()
    open fun getCount(): Long = TODO()
}
open class Semaphore(permits: Int) {
    open fun acquire(): Unit = TODO()
    open fun release(): Unit = TODO()
    open fun tryAcquire(): Boolean = TODO()
}
"""),
])

S["jdk_util_atomic"] = ("java.util.concurrent.atomic", [
("AtomicInteger", """
open class AtomicInteger() {
    constructor(initial: Int) : this()
    open fun get(): Int = TODO()
    open fun set(v: Int): Unit = TODO()
    open fun lazySet(v: Int): Unit = TODO()
    open fun getAndSet(v: Int): Int = TODO()
    open fun getAndIncrement(): Int = TODO()
    open fun getAndDecrement(): Int = TODO()
    open fun getAndAdd(d: Int): Int = TODO()
    open fun incrementAndGet(): Int = TODO()
    open fun decrementAndGet(): Int = TODO()
    open fun addAndGet(d: Int): Int = TODO()
    open fun compareAndSet(expect: Int, update: Int): Boolean = TODO()
}
open class AtomicLong() {
    constructor(initial: Long) : this()
    open fun get(): Long = TODO()
    open fun set(v: Long): Unit = TODO()
    open fun getAndSet(v: Long): Long = TODO()
    open fun getAndIncrement(): Long = TODO()
    open fun incrementAndGet(): Long = TODO()
    open fun decrementAndGet(): Long = TODO()
    open fun addAndGet(d: Long): Long = TODO()
    open fun compareAndSet(expect: Long, update: Long): Boolean = TODO()
}
open class AtomicBoolean() {
    constructor(initial: Boolean) : this()
    open fun get(): Boolean = TODO()
    open fun set(v: Boolean): Unit = TODO()
    open fun getAndSet(v: Boolean): Boolean = TODO()
    open fun compareAndSet(expect: Boolean, update: Boolean): Boolean = TODO()
}
open class AtomicReference<T>() {
    constructor(initial: T) : this()
    open fun get(): T = TODO()
    open fun set(v: T): Unit = TODO()
    open fun lazySet(v: T): Unit = TODO()
    open fun getAndSet(v: T): T = TODO()
    open fun compareAndSet(expect: T, update: T): Boolean = TODO()
}
"""),
])

S["jdk_util_function"] = ("java.util.function", [
("Consumer", """
fun interface Consumer<T> {
    fun accept(t: T)
}
fun interface Supplier<T> {
    fun get(): T
}
fun interface Function<T, R> {
    fun apply(t: T): R
}
fun interface BiFunction<T, U, R> {
    fun apply(t: T, u: U): R
}
fun interface Predicate<T> {
    fun test(t: T): Boolean
}
fun interface BiConsumer<T, U> {
    fun accept(t: T, u: U)
}
"""),
])

S["jdk_util_zip"] = ("java.util.zip", [
("ZipEntry", """
open class ZipEntry(name: String?) {
    open fun getName(): String = TODO()
    open fun getSize(): Long = TODO()
    open fun getCompressedSize(): Long = TODO()
    open fun getCrc(): Long = TODO()
    open fun getTime(): Long = TODO()
    open fun getMethod(): Int = TODO()
    open fun isDirectory(): Boolean = TODO()
    companion object {
        const val STORED: Int = 0
        const val DEFLATED: Int = 8
    }
}
"""),
("ZipFile", """
open class ZipFile(f: java.io.File?) : java.io.Closeable {
    constructor(path: String?) : this(null as java.io.File?)
    override fun close(): Unit = TODO()
    open fun getEntry(name: String?): ZipEntry = TODO()
    open fun getInputStream(e: ZipEntry?): java.io.InputStream = TODO()
    open fun entries(): java.util.Enumeration<ZipEntry> = TODO()
    open fun size(): Int = TODO()
    open fun getName(): String = TODO()
}
open class ZipInputStream(s: java.io.InputStream?) : java.io.InputStream() {
    open fun getNextEntry(): ZipEntry = TODO()
    open fun closeEntry(): Unit = TODO()
}
open class GZIPOutputStream(s: java.io.OutputStream?) : java.io.OutputStream() {
    open fun finish(): Unit = TODO()
}
open class GZIPInputStream(s: java.io.InputStream?) : java.io.InputStream()
open class ZipException(message: String? = null) : java.io.IOException(message)
"""),
])

S["jdk_net"] = ("java.net", [
("URISyntaxException", """
open class URISyntaxException(input: String? = null, reason: String? = null) : Exception(reason)
open class MalformedURLException(message: String? = null) : java.io.IOException(message)
open class UnknownHostException(message: String? = null) : java.io.IOException(message)
open class SocketException(message: String? = null) : java.io.IOException(message)
open class SocketTimeoutException(message: String? = null) : java.io.IOException(message)
open class ConnectException(message: String? = null) : java.io.IOException(message)
open class ProtocolException(message: String? = null) : java.io.IOException(message)
"""),
("URI", """
open class URI(s: String?) {
    constructor(scheme: String?, userInfo: String?, host: String?, port: Int,
                path: String?, query: String?, fragment: String?) : this(null as String?)
    constructor(scheme: String?, host: String?, path: String?, fragment: String?) : this(null as String?)
    open fun getScheme(): String = TODO()
    open fun getHost(): String = TODO()
    open fun getPort(): Int = TODO()
    open fun getPath(): String = TODO()
    open fun getQuery(): String = TODO()
    open fun getFragment(): String = TODO()
    open fun getUserInfo(): String = TODO()
    open fun getAuthority(): String = TODO()
    open fun getSchemeSpecificPart(): String = TODO()
    open fun isAbsolute(): Boolean = TODO()
    open fun normalize(): URI = TODO()
    open fun resolve(s: String?): URI = TODO()
    open fun toURL(): URL = TODO()
    open fun toASCIIString(): String = TODO()
    companion object { fun create(s: String?): URI = TODO() }
}
"""),
("URL", """
open class URL(s: String?) {
    constructor(protocol: String?, host: String?, file: String?) : this(null as String?)
    constructor(context: URL?, spec: String?) : this(null as String?)
    open fun getProtocol(): String = TODO()
    open fun getHost(): String = TODO()
    open fun getPort(): Int = TODO()
    open fun getDefaultPort(): Int = TODO()
    open fun getPath(): String = TODO()
    open fun getFile(): String = TODO()
    open fun getQuery(): String = TODO()
    open fun getRef(): String = TODO()
    open fun getUserInfo(): String = TODO()
    open fun getAuthority(): String = TODO()
    open fun openConnection(): URLConnection = TODO()
    open fun openStream(): java.io.InputStream = TODO()
    open fun toURI(): URI = TODO()
    open fun toExternalForm(): String = TODO()
}
"""),
("URLConnection", """
open class URLConnection {
    open fun connect(): Unit = TODO()
    open fun getInputStream(): java.io.InputStream = TODO()
    open fun getOutputStream(): java.io.OutputStream = TODO()
    open fun getContentType(): String = TODO()
    open fun getContentLength(): Int = TODO()
    open fun getContentEncoding(): String = TODO()
    open fun getHeaderField(name: String?): String = TODO()
    open fun setRequestProperty(key: String?, value: String?): Unit = TODO()
    open fun getRequestProperty(key: String?): String = TODO()
    open fun setDoInput(v: Boolean): Unit = TODO()
    open fun setDoOutput(v: Boolean): Unit = TODO()
    open fun setUseCaches(v: Boolean): Unit = TODO()
    open fun setConnectTimeout(ms: Int): Unit = TODO()
    open fun setReadTimeout(ms: Int): Unit = TODO()
    open fun setInstanceFollowRedirects(v: Boolean): Unit = TODO()
    open fun getURL(): URL = TODO()
}
open class HttpURLConnection : URLConnection() {
    open fun getResponseCode(): Int = TODO()
    open fun getResponseMessage(): String = TODO()
    open fun getErrorStream(): java.io.InputStream = TODO()
    open fun setRequestMethod(method: String?): Unit = TODO()
    open fun getRequestMethod(): String = TODO()
    open fun setFixedLengthStreamingMode(len: Int): Unit = TODO()
    open fun setChunkedStreamingMode(len: Int): Unit = TODO()
    open fun disconnect(): Unit = TODO()
    companion object {
        const val HTTP_OK: Int = 200
        const val HTTP_MOVED_PERM: Int = 301
        const val HTTP_MOVED_TEMP: Int = 302
        const val HTTP_NOT_FOUND: Int = 404
        const val HTTP_INTERNAL_ERROR: Int = 500
    }
}
"""),
("URLEncoder", """
object URLEncoder {
    fun encode(s: String?): String = TODO()
    fun encode(s: String?, enc: String?): String = TODO()
}
object URLDecoder {
    fun decode(s: String?): String = TODO()
    fun decode(s: String?, enc: String?): String = TODO()
}
"""),
("InetAddress", """
open class InetAddress {
    open fun getHostAddress(): String = TODO()
    open fun getHostName(): String = TODO()
    open fun getAddress(): ByteArray = TODO()
    open fun isLoopbackAddress(): Boolean = TODO()
    companion object {
        fun getByName(host: String?): InetAddress = TODO()
        fun getAllByName(host: String?): Array<InetAddress> = TODO()
        fun getLocalHost(): InetAddress = TODO()
        fun getByAddress(a: ByteArray?): InetAddress = TODO()
    }
}
open class Inet4Address : InetAddress()
open class Inet6Address : InetAddress()
open class SocketAddress
open class InetSocketAddress(host: String?, port: Int) : SocketAddress() {
    constructor(addr: InetAddress?, port: Int) : this(null as String?, port)
    constructor(port: Int) : this(null as String?, port)
    open fun getHostString(): String = TODO()
    open fun getHostName(): String = TODO()
    open fun getPort(): Int = TODO()
    open fun getAddress(): InetAddress = TODO()
    companion object {
        fun createUnresolved(host: String?, port: Int): InetSocketAddress = TODO()
    }
}
"""),
("Proxy", """
open class Proxy(type: Type?, sa: SocketAddress?) {
    enum class Type { DIRECT, HTTP, SOCKS }
    open fun type(): Type = TODO()
    open fun address(): SocketAddress = TODO()
    companion object { val NO_PROXY: Proxy = TODO() }
}
open class ProxySelector {
    companion object { fun getDefault(): ProxySelector = TODO() }
}
"""),
])

S["jdk_security"] = ("java.security", [
("GeneralSecurityException", """
open class GeneralSecurityException(message: String? = null, cause: Throwable? = null)
    : Exception(message, cause)
open class NoSuchAlgorithmException(message: String? = null) : GeneralSecurityException(message)
open class NoSuchProviderException(message: String? = null) : GeneralSecurityException(message)
open class InvalidKeyException(message: String? = null) : GeneralSecurityException(message)
open class InvalidAlgorithmParameterException(message: String? = null) : GeneralSecurityException(message)
open class SignatureException(message: String? = null) : GeneralSecurityException(message)
open class KeyStoreException(message: String? = null) : GeneralSecurityException(message)
open class UnrecoverableKeyException(message: String? = null) : GeneralSecurityException(message)
open class KeyManagementException(message: String? = null) : GeneralSecurityException(message)
"""),
("Key", """
interface Principal {
    fun getName(): String
}
interface Key {
    fun getAlgorithm(): String
    fun getFormat(): String
    fun getEncoded(): ByteArray
}
interface PublicKey : Key
interface PrivateKey : Key
open class KeyPair(pub: PublicKey?, priv: PrivateKey?) {
    open fun getPublic(): PublicKey = TODO()
    open fun getPrivate(): PrivateKey = TODO()
}
"""),
("MessageDigest", """
open class MessageDigest {
    open fun update(b: ByteArray?): Unit = TODO()
    open fun update(b: ByteArray?, off: Int, len: Int): Unit = TODO()
    open fun digest(): ByteArray = TODO()
    open fun digest(b: ByteArray?): ByteArray = TODO()
    open fun reset(): Unit = TODO()
    open fun getAlgorithm(): String = TODO()
    companion object {
        fun getInstance(algorithm: String?): MessageDigest = TODO()
        fun isEqual(a: ByteArray?, b: ByteArray?): Boolean = TODO()
    }
}
"""),
("SecureRandom", """
open class SecureRandom() : java.util.Random() {
    constructor(seed: ByteArray?) : this()
    open fun generateSeed(n: Int): ByteArray = TODO()
    companion object { fun getInstance(algorithm: String?): SecureRandom = TODO() }
}
"""),
("Signature", """
open class Signature {
    open fun initSign(key: PrivateKey?): Unit = TODO()
    open fun initVerify(key: PublicKey?): Unit = TODO()
    open fun update(b: ByteArray?): Unit = TODO()
    open fun update(b: ByteArray?, off: Int, len: Int): Unit = TODO()
    open fun sign(): ByteArray = TODO()
    open fun verify(sig: ByteArray?): Boolean = TODO()
    companion object { fun getInstance(algorithm: String?): Signature = TODO() }
}
"""),
("KeyStore", """
open class KeyStore {
    open fun load(s: java.io.InputStream?): Unit = TODO()
    open fun load(s: java.io.InputStream?, password: CharArray?): Unit = TODO()
    open fun aliases(): java.util.Enumeration<String> = TODO()
    open fun containsAlias(alias: String?): Boolean = TODO()
    open fun isCertificateEntry(alias: String?): Boolean = TODO()
    open fun isKeyEntry(alias: String?): Boolean = TODO()
    open fun getCertificate(alias: String?): java.security.cert.Certificate = TODO()
    open fun getCertificateChain(alias: String?): Array<java.security.cert.Certificate> = TODO()
    open fun getKey(alias: String?, password: CharArray?): Key = TODO()
    companion object {
        fun getInstance(type: String?): KeyStore = TODO()
        fun getDefaultType(): String = TODO()
    }
}
open class KeyFactory {
    companion object { fun getInstance(algorithm: String?): KeyFactory = TODO() }
}
open class Provider {
    open fun getName(): String = TODO()
}
"""),
])

S["jdk_security_cert"] = ("java.security.cert", [
("CertificateException", """
open class CertificateException(message: String? = null, cause: Throwable? = null)
    : java.security.GeneralSecurityException(message, cause)
open class CertificateEncodingException(message: String? = null) : CertificateException(message)
open class CertificateParsingException(message: String? = null) : CertificateException(message)
open class CertificateExpiredException(message: String? = null) : CertificateException(message)
open class CertificateNotYetValidException(message: String? = null) : CertificateException(message)
"""),
("Certificate", """
open class Certificate {
    open fun getEncoded(): ByteArray = TODO()
    open fun getPublicKey(): java.security.PublicKey = TODO()
    open fun getType(): String = TODO()
    open fun verify(key: java.security.PublicKey?): Unit = TODO()
}
open class X509Certificate : Certificate() {
    open fun getSubjectDN(): java.security.Principal = TODO()
    open fun getIssuerDN(): java.security.Principal = TODO()
    open fun getSubjectX500Principal(): javax.security.auth.x500.X500Principal = TODO()
    open fun getIssuerX500Principal(): javax.security.auth.x500.X500Principal = TODO()
    open fun getSerialNumber(): java.math.BigInteger = TODO()
    open fun getNotBefore(): Any = TODO()
    open fun getNotAfter(): Any = TODO()
    open fun getKeyUsage(): BooleanArray = TODO()
    open fun getBasicConstraints(): Int = TODO()
    open fun getSigAlgName(): String = TODO()
    open fun checkValidity(): Unit = TODO()
}
open class CertificateFactory {
    open fun generateCertificate(s: java.io.InputStream?): Certificate = TODO()
    open fun generateCertificates(s: java.io.InputStream?): MutableCollection<Certificate> = TODO()
    companion object { fun getInstance(type: String?): CertificateFactory = TODO() }
}
"""),
])

S["jdk_security_interfaces"] = ("java.security.interfaces", [
("RSAPublicKey", """
interface RSAPublicKey : java.security.PublicKey {
    fun getModulus(): java.math.BigInteger
    fun getPublicExponent(): java.math.BigInteger
}
interface ECPublicKey : java.security.PublicKey {
    fun getParams(): Any
}
"""),
])

S["jdk_javax_crypto"] = ("javax.crypto", [
("Cipher", """
open class Cipher {
    open fun init(opmode: Int, key: java.security.Key?): Unit = TODO()
    open fun doFinal(input: ByteArray?): ByteArray = TODO()
    open fun doFinal(): ByteArray = TODO()
    open fun update(input: ByteArray?): ByteArray = TODO()
    open fun getBlockSize(): Int = TODO()
    companion object {
        const val ENCRYPT_MODE: Int = 1
        const val DECRYPT_MODE: Int = 2
        fun getInstance(transformation: String?): Cipher = TODO()
    }
}
interface SecretKey : java.security.Key
open class NoSuchPaddingException(message: String? = null)
    : java.security.GeneralSecurityException(message)
open class IllegalBlockSizeException(message: String? = null)
    : java.security.GeneralSecurityException(message)
open class BadPaddingException(message: String? = null)
    : java.security.GeneralSecurityException(message)
"""),
])

S["jdk_javax_x500"] = ("javax.security.auth.x500", [
("X500Principal", """
open class X500Principal(name: String?) : java.security.Principal {
    constructor(encoded: ByteArray?) : this(null as String?)
    override fun getName(): String = TODO()
    open fun getName(format: String?): String = TODO()
    open fun getEncoded(): ByteArray = TODO()
}
"""),
])

S["jdk_dalvik"] = ("dalvik.system", [
("BaseDexClassLoader", """
open class BaseDexClassLoader(dexPath: String?, optimizedDirectory: java.io.File?,
                              librarySearchPath: String?, parent: java.lang.ClassLoader?)
    : java.lang.ClassLoader() {
    open fun findLibrary(name: String?): String = TODO()
    open fun addDexPath(path: String?): Unit = TODO()
}
open class PathClassLoader(dexPath: String?, parent: java.lang.ClassLoader?)
    : BaseDexClassLoader(dexPath, null, null, parent)
open class DexClassLoader(dexPath: String?, optimizedDirectory: String?,
                          librarySearchPath: String?, parent: java.lang.ClassLoader?)
    : BaseDexClassLoader(dexPath, null, librarySearchPath, parent)
"""),
])

# --------------------------------------------------------------------------
# import injection

# java.lang is implicit in Java and explicit in Kotlin.  Simple name -> import.
LANG_TYPES = {
    "Math": "java.lang.Math",
    "Thread": "java.lang.Thread",
    "Integer": "java.lang.Integer",
    "Character": "java.lang.Character",
    "System": "java.lang.System",
    "Class": "java.lang.Class",
    "ClassLoader": "java.lang.ClassLoader",
    "Void": "java.lang.Void",
    "Runnable": "java.lang.Runnable",
    "StringBuffer": "java.lang.StringBuffer",
    "StackTraceElement": "java.lang.StackTraceElement",
    "Runtime": "java.lang.Runtime",
    "ThreadLocal": "java.lang.ThreadLocal",
    "AutoCloseable": "java.lang.AutoCloseable",
    "ThreadGroup": "java.lang.ThreadGroup",
    "SecurityException": "java.lang.SecurityException",
    "InterruptedException": "java.lang.InterruptedException",
    "ClassNotFoundException": "java.lang.ClassNotFoundException",
    "NoSuchMethodException": "java.lang.NoSuchMethodException",
    "NoSuchFieldException": "java.lang.NoSuchFieldException",
    "IllegalAccessException": "java.lang.IllegalAccessException",
    "InstantiationException": "java.lang.InstantiationException",
    "CloneNotSupportedException": "java.lang.CloneNotSupportedException",
    "ArrayIndexOutOfBoundsException": "java.lang.ArrayIndexOutOfBoundsException",
    "OutOfMemoryError": "java.lang.OutOfMemoryError",
    "StackOverflowError": "java.lang.StackOverflowError",
    "UnsatisfiedLinkError": "java.lang.UnsatisfiedLinkError",
}

# Statics on types Kotlin owns; extensions on the companion, imported by name.
EXT_TRIGGERS = [
    (re.compile(r"\bLong\.parseLong\b"), "java.lang.parseLong"),
    (re.compile(r"\bFloat\.parseFloat\b"), "java.lang.parseFloat"),
    (re.compile(r"\bDouble\.parseDouble\b"), "java.lang.parseDouble"),
    (re.compile(r"\bBoolean\.parseBoolean\b"), "java.lang.parseBoolean"),
    (re.compile(r"\b(?:Long|Float|Double|Boolean|String|Char)\.valueOf\b"), "java.lang.valueOf"),
    (re.compile(r"\bString\.format\b"), "java.lang.format"),
    (re.compile(r"(?<![\w.])getClass\(\)|\.getClass\(\)"), "java.lang.getClass"),
    (re.compile(r"\.getKey\(\)"), "java.util.getKey"),
    (re.compile(r"\.getValue\(\)"), "java.util.getValue"),
    (re.compile(r"(?<![\w.])wait\(|\.wait\("), "java.lang.wait"),
    (re.compile(r"(?<![\w.])notify\(|\.notify\("), "java.lang.notify"),
    (re.compile(r"(?<![\w.])notifyAll\(|\.notifyAll\("), "java.lang.notifyAll"),
    (re.compile(r"\.clone\(\)"), "java.lang.clone"),
    (re.compile(r"\.finalize\(\)"), "java.lang.finalize"),
] + [
    (re.compile(r"::class\.%s\(" % _n), "java.lang." + _n) for _n in (
        "getName", "getSimpleName", "getCanonicalName", "isInstance",
        "isAssignableFrom", "newInstance", "getDeclaredMethod", "getMethod",
        "getDeclaredFields", "getDeclaredField")
] + [
    (re.compile(r"\.computeIfAbsent\("), "java.util.computeIfAbsent"),
    (re.compile(r"\.putIfAbsent\("), "java.util.putIfAbsent"),
    (re.compile(r"\.getOrDefault\("), "java.util.getOrDefault"),
    (re.compile(r"(?<![\w.])(?:Boolean|Byte|Char|Short|Int|Long|Float|Double)\.TYPE\b"), "java.lang.TYPE"),
]

# List.of / Set.of: the collections are typealiases onto Kotlin's, and a
# typealias carries no companion to hang a factory on.
_FACTORY = re.compile(r"(?<![\w.])(List|Set)\.of\(")

_ARRAY_IMPORT = re.compile(r"^import java\.lang\.reflect\.Array\s*$", re.M)
_ARRAY_CALL = re.compile(r"(?<![\w.])Array\.(getLength|newInstance|get|set)\(")
_MAP_ENTRY = re.compile(r"(?<![\w.])Map\.Entry\b")

_DECL = re.compile(
    r"^(?:@\w+\s+)*(?:public |internal |private |open |abstract |sealed |value |data |inline )*"
    r"(?:fun interface|annotation class|enum class|class|interface|object|typealias|fun)\s+"
    r"(?:<[^>]*>\s+)?"
    r"(?:[\w.<>,?\s]+\.)?(\w+)", re.M)


def _existing_stub_names(stub_dir):
    """(package, name) already declared by another stub lane's file."""
    taken = set()
    if not os.path.isdir(stub_dir):
        return taken
    for f in sorted(os.listdir(stub_dir)):
        if not f.endswith(".kt") or f.startswith("jdk_"):
            continue
        text = open(os.path.join(stub_dir, f)).read()
        m = re.search(r"^package\s+([\w.]+)", text, re.M)
        if not m or m.group(1).split(".")[0] not in ("java", "javax", "dalvik"):
            continue
        pkg = m.group(1)
        for d in _DECL.finditer(text):
            taken.add((pkg, d.group(1)))
    return taken


def emit_stubs(out_root, stats):
    stub_dir = os.path.join(out_root, "stubs")
    os.makedirs(stub_dir, exist_ok=True)
    taken = _existing_stub_names(stub_dir)
    for fname, (pkg, decls) in sorted(S.items()):
        body, skipped = [], []
        for name, code in decls:
            if (pkg, name) in taken:
                skipped.append(name)
                continue
            body.append(code.strip() + "\n")
        path = os.path.join(stub_dir, fname + ".kt")
        with open(path, "w") as fh:
            fh.write(BANNER % pkg)
            if skipped:
                fh.write("// deferred to another stub lane: %s\n" % ", ".join(skipped))
            fh.write("\npackage %s\n\n" % pkg)
            fh.write("\n".join(body))
        stats["jdk-stubs:files"] += 1


# --------------------------------------------------------------------------

def transform(unit, ctx):
    if not ctx.get("_jdk_stubs_emitted"):
        ctx["_jdk_stubs_emitted"] = True
        emit_stubs(ctx["out_root"], ctx["stats"])

    text = unit.kotlin

    # java.lang.reflect.Array shadows kotlin.Array for the whole file.
    if _ARRAY_IMPORT.search(text):
        text = _ARRAY_IMPORT.sub("import java.lang.reflect.ArrayReflect", text)
        text = _ARRAY_CALL.sub(r"ArrayReflect.\1(", text)
        ctx["stats"]["jdk-stubs:reflect-array"] += 1

    n = len(_FACTORY.findall(text))
    if n:
        text = _FACTORY.sub(lambda m: "mutable%sOf(" % m.group(1), text)
        ctx["stats"]["jdk-stubs:list-of"] += n

    # Map.Entry -> MutableMap.MutableEntry
    n = len(_MAP_ENTRY.findall(text))
    if n:
        text = _MAP_ENTRY.sub("MutableMap.MutableEntry", text)
        ctx["stats"]["jdk-stubs:map-entry"] += n

    lines = text.split("\n")
    body = "\n".join(l for l in lines if not l.startswith("import "))
    have = set()
    for l in lines:
        if l.startswith("import "):
            have.add(l[len("import "):].strip())
    have_simple = {i.rsplit(".", 1)[-1] for i in have}

    add = []
    for simple, fqn in sorted(LANG_TYPES.items()):
        if fqn in have or simple in have_simple:
            continue
        if re.search(r"(?<![\w.])%s\b" % simple, body):
            add.append(fqn)
    for rx, fqn in EXT_TRIGGERS:
        if fqn not in have and rx.search(body):
            add.append(fqn)

    if add:
        out, done = [], False
        for l in lines:
            if not done and (l.startswith("import ") or l.startswith("package ")):
                # after the package line, before the first import
                if l.startswith("package "):
                    out.append(l)
                    continue
                out.extend("import " + a for a in add)
                done = True
            out.append(l)
        if not done:                       # no imports at all: append after package
            out = []
            for l in lines:
                out.append(l)
                if l.startswith("package ") and not done:
                    out.append("")
                    out.extend("import " + a for a in add)
                    done = True
        lines = out
        ctx["stats"]["jdk-stubs:imports"] += len(add)

    unit.kotlin = "\n".join(lines)
    unit.imports = [l for l in lines if l.startswith("import ")]
