"""Stub the third-party packages nothing in the tree declares at all.

Round 3's biggest single error bucket was not a bad conversion: it was four
whole package families GeckoView imports that no stub lane had scraped, so
every reference in the importing file cascaded off one unresolved package root.

  * `android.text`, `.style`, `.method`, `.format` - Editable/Spanned/Spannable
    and the span API, TextUtils, Selection, InputType, TextPaint.  GeckoEditable
    *implements* `Editable`, so these are not free-form: the interface members
    have to match, signature for signature, the `override fun`s the converter
    already emitted (`fun length()`, not `val length`; `Class<T>?`, not KClass).
    `SpannableString`/`SpannableStringBuilder` additionally implement
    kotlin.CharSequence, because corpus code assigns them to `CharSequence`
    fields; a class can carry both `fun length()` and `override val length`.
  * `com.google.android.gms.fido.*` + `com.google.android.gms.tasks.Task` -
    the whole WebAuthn Fido2 builder surface.  Dead weight for the port; it is
    stubbed only so WebAuthnTokenManager.kt stops cascading.
  * `com.google.common.net.HttpHeaders` / `com.google.common.base.Predicate`.
  * `org.yaml.snakeyaml` - Raptor's debug-config reader.

Plus three small things that live in the same files:

  1. `java.util.stream` - three `.stream()` call sites.  A `Stream<T>` stub and
     an `Iterable<T>.stream()` extension.
  2. Java resolves `X.class` where Kotlin has `X::class`, so the `Class<T>?`
     members of `Spanned` are unreachable from the call sites.  KClass-taking
     *extensions* of `getSpans`/`nextSpanTransition` sit beside them; an
     extension is only picked when no member applies, so this cannot change a
     call site that already compiles.
  3. `RequestProperties` and `HttpDataSourceException` ARE declared (the media3
     stub lane has them, top-level) but the corpus refers to them unqualified,
     because in Java they are nested in the `HttpDataSource` interface that
     HttpChannelDataSource implements.  Kotlin does not inherit nested types:
     the fix is an import line, so one is added.

Every body is TODO().  None of it is meant to run.
"""
import os
import re

ORDER = 65                       # after stub-surface-completion (60)
NAME = "missing-third-party-packages"
DESCRIPTION = "stub android.text, gms.fido, guava and snakeyaml wholesale"

EXT_PKG = "org.mozilla.gecko.knthird"
EXT_IMPORT = "import %s.*" % EXT_PKG
MY_PREFIX = "thirdparty_"

BANNER = (
    "// GENERATED by kn-run/rules/missing-third-party-packages.py -- do not edit by hand.\n"
    "// Stub surface for %s, derived from the GeckoView call sites.\n"
    "// Every body is TODO(): there is no JVM, no Android runtime, no Play\n"
    "// Services and no snakeyaml on Kotlin/Native.\n"
    '@file:Suppress("UNUSED_PARAMETER", "unused", "UNCHECKED_CAST",\n'
    '               "EXTENSION_SHADOWED_BY_MEMBER", "NOTHING_TO_INLINE",\n'
    '               "PARAMETER_NAME_CHANGED_ON_OVERRIDE", "OVERRIDE_DEPRECATION")\n'
)

# --------------------------------------------------------------------------
# 1.  the stub packages.  file -> (package, [(declared name, kotlin source)])

S = {}

# --- android.text ----------------------------------------------------------
# Member shapes are dictated by GeckoEditable's emitted `override fun`s.

S["thirdparty_android_text"] = ("android.text", [
("NoCopySpan", """
interface NoCopySpan
"""),
("GetChars", """
interface GetChars {
    fun getChars(start: Int, end: Int, dest: CharArray?, destoff: Int)
}
"""),
("InputFilter", """
interface InputFilter {
    fun filter(source: CharSequence?, start: Int, end: Int,
               dest: Spanned?, dstart: Int, dend: Int): CharSequence? = TODO()
}
"""),
("Spanned", """
// Extends kotlin.CharSequence because corpus code passes a Spanned/Editable
// straight into a CharSequence parameter, as Java lets it.  The three
// kotlin.CharSequence members carry default bodies so that GeckoEditable --
// which implements only the Java-shaped `fun length()` / `fun charAt()` the
// converter emitted -- is not left abstract.
interface Spanned : CharSequence {
    override val length: Int get() = TODO()
    override fun get(index: Int): Char = TODO()
    override fun subSequence(startIndex: Int, endIndex: Int): CharSequence = TODO()

    fun getSpanStart(tag: Any?): Int
    fun getSpanEnd(tag: Any?): Int
    fun getSpanFlags(tag: Any?): Int
    fun <T> getSpans(start: Int, end: Int, type: java.lang.Class<T>?): Array<T>?
    fun nextSpanTransition(start: Int, limit: Int, type: java.lang.Class<*>?): Int
    fun length(): Int
    fun charAt(index: Int): Char

    companion object {
        const val SPAN_POINT_MARK_MASK = 0x33
        const val SPAN_MARK_MARK = 0x11
        const val SPAN_MARK_POINT = 0x12
        const val SPAN_POINT_MARK = 0x21
        const val SPAN_POINT_POINT = 0x22
        const val SPAN_PARAGRAPH = 0x33
        const val SPAN_INCLUSIVE_EXCLUSIVE = SPAN_MARK_MARK
        const val SPAN_INCLUSIVE_INCLUSIVE = SPAN_MARK_POINT
        const val SPAN_EXCLUSIVE_EXCLUSIVE = SPAN_POINT_MARK
        const val SPAN_EXCLUSIVE_INCLUSIVE = SPAN_POINT_POINT
        const val SPAN_COMPOSING = 0x100
        const val SPAN_INTERMEDIATE = 0x200
        const val SPAN_USER_SHIFT = 24
        const val SPAN_USER = -0x1000000
        const val SPAN_PRIORITY_SHIFT = 16
        const val SPAN_PRIORITY = 0x00FF0000
    }
}
"""),
("Spannable", """
interface Spannable : Spanned {
    fun setSpan(what: Any?, start: Int, end: Int, flags: Int)
    fun removeSpan(what: Any?)
}
"""),
("Editable", """
interface Editable : Spannable, GetChars {
    fun replace(st: Int, en: Int, source: CharSequence?, start: Int, end: Int): Editable?
    fun replace(st: Int, en: Int, text: CharSequence?): Editable?
    fun insert(where: Int, text: CharSequence?, start: Int, end: Int): Editable?
    fun insert(where: Int, text: CharSequence?): Editable?
    fun delete(st: Int, en: Int): Editable?
    fun append(text: CharSequence?): Editable?
    fun append(text: CharSequence?, start: Int, end: Int): Editable?
    fun append(text: Char): Editable?
    fun clear()
    fun clearSpans()
    fun setFilters(filters: Array<InputFilter>?)
    fun getFilters(): Array<InputFilter>?
}
"""),
("SpannableString", """
// Implements kotlin.CharSequence as well: GeckoInputConnection assigns one to
// ExtractedText.text, which is a CharSequence.
open class SpannableString(source: Any? = null) : Spannable {
    override val length: Int get() = TODO()
    override fun get(index: Int): Char = TODO()
    override fun subSequence(start: Int, end: Int): CharSequence = TODO()
    override fun length(): Int = TODO()
    override fun charAt(index: Int): Char = TODO()
    override fun getSpanStart(tag: Any?): Int = TODO()
    override fun getSpanEnd(tag: Any?): Int = TODO()
    override fun getSpanFlags(tag: Any?): Int = TODO()
    override fun <T> getSpans(start: Int, end: Int, type: java.lang.Class<T>?): Array<T>? = TODO()
    override fun nextSpanTransition(start: Int, limit: Int, type: java.lang.Class<*>?): Int = TODO()
    override fun setSpan(what: Any?, start: Int, end: Int, flags: Int): Unit = TODO()
    override fun removeSpan(what: Any?): Unit = TODO()
    companion object {
        fun valueOf(source: Any?): SpannableString = TODO()
    }
}
"""),
("SpannableStringBuilder", """
open class SpannableStringBuilder(source: Any? = null) : Editable {
    override val length: Int get() = TODO()
    override fun get(index: Int): Char = TODO()
    override fun subSequence(start: Int, end: Int): CharSequence = TODO()
    override fun length(): Int = TODO()
    override fun charAt(index: Int): Char = TODO()
    override fun getSpanStart(tag: Any?): Int = TODO()
    override fun getSpanEnd(tag: Any?): Int = TODO()
    override fun getSpanFlags(tag: Any?): Int = TODO()
    override fun <T> getSpans(start: Int, end: Int, type: java.lang.Class<T>?): Array<T>? = TODO()
    override fun nextSpanTransition(start: Int, limit: Int, type: java.lang.Class<*>?): Int = TODO()
    override fun setSpan(what: Any?, start: Int, end: Int, flags: Int): Unit = TODO()
    override fun removeSpan(what: Any?): Unit = TODO()
    override fun getChars(start: Int, end: Int, dest: CharArray?, destoff: Int): Unit = TODO()
    override fun replace(st: Int, en: Int, source: CharSequence?, start: Int, end: Int): Editable? = TODO()
    override fun replace(st: Int, en: Int, text: CharSequence?): Editable? = TODO()
    override fun insert(where: Int, text: CharSequence?, start: Int, end: Int): Editable? = TODO()
    override fun insert(where: Int, text: CharSequence?): Editable? = TODO()
    override fun delete(st: Int, en: Int): Editable? = TODO()
    override fun append(text: CharSequence?): Editable? = TODO()
    override fun append(text: CharSequence?, start: Int, end: Int): Editable? = TODO()
    override fun append(text: Char): Editable? = TODO()
    override fun clear(): Unit = TODO()
    override fun clearSpans(): Unit = TODO()
    override fun setFilters(filters: Array<InputFilter>?): Unit = TODO()
    override fun getFilters(): Array<InputFilter>? = TODO()
}
"""),
("Selection", """
object Selection {
    val SELECTION_START: Any = TODO()
    val SELECTION_END: Any = TODO()
    fun getSelectionStart(text: Any?): Int = TODO()
    fun getSelectionEnd(text: Any?): Int = TODO()
    fun setSelection(text: Any?, index: Int): Unit = TODO()
    fun setSelection(text: Any?, start: Int, stop: Int): Unit = TODO()
    fun selectAll(text: Any?): Unit = TODO()
    fun removeSelection(text: Any?): Unit = TODO()
}
"""),
("TextUtils", """
object TextUtils {
    fun isEmpty(str: Any?): Boolean = TODO()
    fun equals(a: Any?, b: Any?): Boolean = TODO()
    fun join(delimiter: Any?, tokens: Any?): String = TODO()
    fun substring(source: Any?, start: Int, end: Int): String = TODO()
    fun indexOf(source: Any?, needle: Any?): Int = TODO()
    fun indexOf(source: Any?, needle: Any?, start: Int): Int = TODO()
    fun indexOf(source: Any?, needle: Any?, start: Int, end: Int): Int = TODO()
    fun lastIndexOf(source: Any?, needle: Any?): Int = TODO()
    fun regionMatches(one: Any?, toffset: Int, two: Any?, ooffset: Int, len: Int): Boolean = TODO()
    fun getChars(s: Any?, start: Int, end: Int, dest: CharArray?, destoff: Int): Unit = TODO()
    fun split(text: String?, expression: String?): Array<String> = TODO()
    fun htmlEncode(s: String?): String = TODO()
    fun concat(vararg text: Any?): CharSequence = TODO()
}
"""),
("InputType", """
object InputType {
    const val TYPE_MASK_CLASS = 0x0000000f
    const val TYPE_MASK_VARIATION = 0x00000ff0
    const val TYPE_MASK_FLAGS = 0x00fff000
    const val TYPE_NULL = 0x00000000
    const val TYPE_CLASS_TEXT = 0x00000001
    const val TYPE_TEXT_FLAG_CAP_CHARACTERS = 0x00001000
    const val TYPE_TEXT_FLAG_CAP_WORDS = 0x00002000
    const val TYPE_TEXT_FLAG_CAP_SENTENCES = 0x00004000
    const val TYPE_TEXT_FLAG_AUTO_CORRECT = 0x00008000
    const val TYPE_TEXT_FLAG_AUTO_COMPLETE = 0x00010000
    const val TYPE_TEXT_FLAG_MULTI_LINE = 0x00020000
    const val TYPE_TEXT_FLAG_IME_MULTI_LINE = 0x00040000
    const val TYPE_TEXT_FLAG_NO_SUGGESTIONS = 0x00080000
    const val TYPE_TEXT_VARIATION_NORMAL = 0x00000000
    const val TYPE_TEXT_VARIATION_URI = 0x00000010
    const val TYPE_TEXT_VARIATION_EMAIL_ADDRESS = 0x00000020
    const val TYPE_TEXT_VARIATION_EMAIL_SUBJECT = 0x00000030
    const val TYPE_TEXT_VARIATION_SHORT_MESSAGE = 0x00000040
    const val TYPE_TEXT_VARIATION_LONG_MESSAGE = 0x00000050
    const val TYPE_TEXT_VARIATION_PERSON_NAME = 0x00000060
    const val TYPE_TEXT_VARIATION_POSTAL_ADDRESS = 0x00000070
    const val TYPE_TEXT_VARIATION_PASSWORD = 0x00000080
    const val TYPE_TEXT_VARIATION_VISIBLE_PASSWORD = 0x00000090
    const val TYPE_TEXT_VARIATION_WEB_EDIT_TEXT = 0x000000a0
    const val TYPE_TEXT_VARIATION_FILTER = 0x000000b0
    const val TYPE_TEXT_VARIATION_PHONETIC = 0x000000c0
    const val TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS = 0x000000d0
    const val TYPE_TEXT_VARIATION_WEB_PASSWORD = 0x000000e0
    const val TYPE_CLASS_NUMBER = 0x00000002
    const val TYPE_NUMBER_FLAG_SIGNED = 0x00001000
    const val TYPE_NUMBER_FLAG_DECIMAL = 0x00002000
    const val TYPE_NUMBER_VARIATION_NORMAL = 0x00000000
    const val TYPE_NUMBER_VARIATION_PASSWORD = 0x00000010
    const val TYPE_CLASS_PHONE = 0x00000003
    const val TYPE_CLASS_DATETIME = 0x00000004
    const val TYPE_DATETIME_VARIATION_NORMAL = 0x00000000
    const val TYPE_DATETIME_VARIATION_DATE = 0x00000010
    const val TYPE_DATETIME_VARIATION_TIME = 0x00000020
}
"""),
("TextPaint", """
open class TextPaint {
    var bgColor: Int = 0
    var baselineShift: Int = 0
    var linkColor: Int = 0
    var drawableState: IntArray? = null
    var density: Float = 1.0f
    var underlineColor: Int = 0
    var underlineThickness: Float = 0.0f
    open fun set(other: TextPaint?): Unit = TODO()
    open fun setColor(color: Int): Unit = TODO()
    open fun getColor(): Int = TODO()
    open fun setUnderlineText(on: Boolean): Unit = TODO()
    open fun isUnderlineText(): Boolean = TODO()
    open fun setTextSize(size: Float): Unit = TODO()
    open fun getTextSize(): Float = TODO()
}
"""),
("TextWatcher", """
interface TextWatcher {
    fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int)
    fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int)
    fun afterTextChanged(s: Editable?)
}
"""),
])

S["thirdparty_android_text_style"] = ("android.text.style", [
("CharacterStyle", """
import android.text.TextPaint

open class CharacterStyle {
    open fun updateDrawState(tp: TextPaint?): Unit = TODO()
    open fun getUnderlying(): CharacterStyle = TODO()
}
"""),
("UnderlineSpan", """
open class UnderlineSpan : CharacterStyle()
"""),
("BackgroundColorSpan", """
open class BackgroundColorSpan(color: Int) : CharacterStyle()
"""),
("ForegroundColorSpan", """
open class ForegroundColorSpan(color: Int) : CharacterStyle()
"""),
])

S["thirdparty_android_text_method"] = ("android.text.method", [
("KeyListener", """
import android.text.Editable
import android.view.KeyEvent
import android.view.View

interface KeyListener {
    fun getInputType(): Int = TODO()
    fun onKeyDown(view: View?, text: Editable?, keyCode: Int, event: KeyEvent?): Boolean = TODO()
    fun onKeyUp(view: View?, text: Editable?, keyCode: Int, event: KeyEvent?): Boolean = TODO()
    fun onKeyOther(view: View?, text: Editable?, event: KeyEvent?): Boolean = TODO()
    fun clearMetaKeyState(view: View?, content: Editable?, states: Int): Unit = TODO()
}
"""),
("MetaKeyKeyListener", """
open class MetaKeyKeyListener {
    companion object {
        const val META_SHIFT_ON = 1
        const val META_ALT_ON = 2
        const val META_SYM_ON = 4
        fun getMetaState(text: Any?): Int = TODO()
        fun getMetaState(text: Any?, meta: Int): Int = TODO()
        fun resetMetaState(text: Any?): Unit = TODO()
        fun adjustMetaAfterKeypress(content: Any?): Unit = TODO()
    }
}
"""),
("TextKeyListener", """
open class TextKeyListener : MetaKeyKeyListener() {
    companion object {
        fun getInstance(): KeyListener = TODO()
        fun getMetaState(text: Any?): Int = TODO()
        fun getMetaState(text: Any?, meta: Int): Int = TODO()
        fun adjustMetaAfterKeypress(content: Any?): Unit = TODO()
        fun clear(e: Any?): Unit = TODO()
    }
}
"""),
])

S["thirdparty_android_text_format"] = ("android.text.format", [
("DateFormat", """
import android.content.Context

object DateFormat {
    fun is24HourFormat(context: Context?): Boolean = TODO()
    fun getDateFormat(context: Context?): Any = TODO()
    fun getTimeFormat(context: Context?): Any = TODO()
}
"""),
])

# --- com.google.android.gms.fido -------------------------------------------
# Only reachable from WebAuthnTokenManager/WebAuthnUtils.  Nothing here is
# load-bearing for the port; it exists so one absent package stops costing 206
# errors.  Builders return themselves so the fluent chains type-check.

S["thirdparty_gms_tasks"] = ("com.google.android.gms.tasks", [
("Task", """
open class Task<T> {
    open fun addOnSuccessListener(listener: (T?) -> Unit): Task<T> = TODO()
    open fun addOnFailureListener(listener: (Exception?) -> Unit): Task<T> = TODO()
    open fun addOnCompleteListener(listener: (Task<T>?) -> Unit): Task<T> = TODO()
    open fun isComplete(): Boolean = TODO()
    open fun isSuccessful(): Boolean = TODO()
    open fun getResult(): T? = TODO()
    open fun getException(): Exception? = TODO()
}
"""),
])

S["thirdparty_gms_fido_common"] = ("com.google.android.gms.fido.common", [
("Transport", """
enum class Transport {
    BLUETOOTH_CLASSIC, BLUETOOTH_LOW_ENERGY, NFC, USB, INTERNAL, HYBRID;
    fun toJsonString(): String = TODO()
}
"""),
])

_FIDO_API = "com.google.android.gms.fido.fido2.api.common"

S["thirdparty_gms_fido_api"] = (_FIDO_API, [
("Algorithm", """
interface Algorithm {
    fun getAlgoValue(): Int = TODO()
}
"""),
("EC2Algorithm", """
enum class EC2Algorithm : Algorithm {
    ES256, ES384, ES512, ED256, ED512;
    override fun getAlgoValue(): Int = TODO()
}
"""),
("RSAAlgorithm", """
enum class RSAAlgorithm : Algorithm {
    PS256, PS384, PS512, RS256, RS384, RS512, RS1;
    override fun getAlgoValue(): Int = TODO()
}
"""),
("Attachment", """
enum class Attachment {
    PLATFORM, CROSS_PLATFORM;
    fun toString2(): String = TODO()
}
"""),
("AttestationConveyancePreference", """
enum class AttestationConveyancePreference {
    NONE, INDIRECT, DIRECT, ENTERPRISE
}
"""),
("ResidentKeyRequirement", """
enum class ResidentKeyRequirement {
    RESIDENT_KEY_DISCOURAGED, RESIDENT_KEY_PREFERRED, RESIDENT_KEY_REQUIRED
}
"""),
("PublicKeyCredentialType", """
enum class PublicKeyCredentialType {
    PUBLIC_KEY
}
"""),
("ErrorCode", """
enum class ErrorCode {
    NOT_SUPPORTED_ERR, INVALID_STATE_ERR, SECURITY_ERR, NETWORK_ERR,
    ABORT_ERR, TIMEOUT_ERR, ENCODING_ERR, UNKNOWN_ERR, CONSTRAINT_ERR,
    DATA_ERR, NOT_ALLOWED_ERR, ATTESTATION_NOT_PRIVATE_ERR
}
"""),
("FidoAppIdExtension", """
open class FidoAppIdExtension(appId: String?)
"""),
("FidoCredentialDetails", """
open class FidoCredentialDetails {
    open fun getIsDiscoverable(): Boolean = TODO()
    open fun getCredentialId(): ByteArray? = TODO()
    open fun getUserName(): String? = TODO()
    open fun getUserDisplayName(): String? = TODO()
}
"""),
("AuthenticationExtensionsCredPropsOutputs", """
open class AuthenticationExtensionsCredPropsOutputs {
    open fun getIsDiscoverableCredential(): Boolean = TODO()
}
"""),
("AuthenticationExtensionsClientOutputs", """
open class AuthenticationExtensionsClientOutputs {
    open fun getCredProps(): AuthenticationExtensionsCredPropsOutputs? = TODO()
}
"""),
("AuthenticationExtensions", """
open class AuthenticationExtensions {
    open class Builder {
        open fun setFido2Extension(ext: FidoAppIdExtension?): Builder = TODO()
        open fun build(): AuthenticationExtensions = TODO()
    }
}
"""),
("AuthenticatorSelectionCriteria", """
open class AuthenticatorSelectionCriteria {
    open class Builder {
        open fun setAttachment(attachment: Attachment?): Builder = TODO()
        open fun setRequireResidentKey(require: Boolean?): Builder = TODO()
        open fun setResidentKeyRequirement(req: ResidentKeyRequirement?): Builder = TODO()
        open fun build(): AuthenticatorSelectionCriteria = TODO()
    }
}
"""),
("AuthenticatorResponse", """
open class AuthenticatorResponse {
    open fun getClientDataJSON(): ByteArray? = TODO()
    open fun serializeToBytes(): ByteArray? = TODO()
}
"""),
("AuthenticatorErrorResponse", """
open class AuthenticatorErrorResponse : AuthenticatorResponse() {
    open fun getErrorCode(): ErrorCode? = TODO()
    open fun getErrorMessage(): String? = TODO()
}
"""),
("AuthenticatorAttestationResponse", """
open class AuthenticatorAttestationResponse : AuthenticatorResponse() {
    open fun getAttestationObject(): ByteArray? = TODO()
    open fun getKeyHandle(): ByteArray? = TODO()
    open fun getTransports(): Array<String>? = TODO()
}
"""),
("AuthenticatorAssertionResponse", """
open class AuthenticatorAssertionResponse : AuthenticatorResponse() {
    open fun getAuthenticatorData(): ByteArray? = TODO()
    open fun getSignature(): ByteArray? = TODO()
    open fun getUserHandle(): ByteArray? = TODO()
    open fun getKeyHandle(): ByteArray? = TODO()
}
"""),
("PublicKeyCredential", """
open class PublicKeyCredential {
    open fun getRawId(): ByteArray? = TODO()
    open fun getId(): String? = TODO()
    open fun getResponse(): AuthenticatorResponse? = TODO()
    open fun getAuthenticatorAttachment(): String? = TODO()
    open fun getClientExtensionResults(): AuthenticationExtensionsClientOutputs? = TODO()
    companion object {
        fun deserializeFromBytes(bytes: ByteArray?): PublicKeyCredential = TODO()
    }
}
"""),
("PublicKeyCredentialParameters", """
open class PublicKeyCredentialParameters(type: String?, algorithm: Int)
"""),
("PublicKeyCredentialDescriptor", """
open class PublicKeyCredentialDescriptor(
    type: String?,
    id: ByteArray?,
    transports: Any? = null,
)
"""),
("PublicKeyCredentialRpEntity", """
open class PublicKeyCredentialRpEntity(id: String?, name: String?, icon: String?)
"""),
("PublicKeyCredentialUserEntity", """
open class PublicKeyCredentialUserEntity(
    id: ByteArray?,
    name: String?,
    icon: String?,
    displayName: String?,
)
"""),
("PublicKeyCredentialCreationOptions", """
open class PublicKeyCredentialCreationOptions {
    open class Builder {
        open fun setRp(rp: PublicKeyCredentialRpEntity?): Builder = TODO()
        open fun setUser(user: PublicKeyCredentialUserEntity?): Builder = TODO()
        open fun setChallenge(challenge: ByteArray?): Builder = TODO()
        open fun setParameters(parameters: Any?): Builder = TODO()
        open fun setTimeoutSeconds(timeout: Double?): Builder = TODO()
        open fun setExcludeList(excludeList: Any?): Builder = TODO()
        open fun setAuthenticatorSelection(sel: AuthenticatorSelectionCriteria?): Builder = TODO()
        open fun setAttestationConveyancePreference(pref: AttestationConveyancePreference?): Builder = TODO()
        open fun setAuthenticationExtensions(ext: AuthenticationExtensions?): Builder = TODO()
        open fun build(): PublicKeyCredentialCreationOptions = TODO()
    }
}
"""),
("PublicKeyCredentialRequestOptions", """
open class PublicKeyCredentialRequestOptions {
    open class Builder {
        open fun setChallenge(challenge: ByteArray?): Builder = TODO()
        open fun setAllowList(allowList: Any?): Builder = TODO()
        open fun setTimeoutSeconds(timeout: Double?): Builder = TODO()
        open fun setRpId(rpId: String?): Builder = TODO()
        open fun setAuthenticationExtensions(ext: AuthenticationExtensions?): Builder = TODO()
        open fun build(): PublicKeyCredentialRequestOptions = TODO()
    }
}
"""),
("BrowserPublicKeyCredentialCreationOptions", """
open class BrowserPublicKeyCredentialCreationOptions {
    open class Builder {
        open fun setPublicKeyCredentialCreationOptions(
            options: PublicKeyCredentialCreationOptions?): Builder = TODO()
        open fun setOrigin(origin: android.net.Uri?): Builder = TODO()
        open fun setClientDataHash(hash: ByteArray?): Builder = TODO()
        open fun build(): BrowserPublicKeyCredentialCreationOptions = TODO()
    }
}
"""),
("BrowserPublicKeyCredentialRequestOptions", """
open class BrowserPublicKeyCredentialRequestOptions {
    open class Builder {
        open fun setPublicKeyCredentialRequestOptions(
            options: PublicKeyCredentialRequestOptions?): Builder = TODO()
        open fun setOrigin(origin: android.net.Uri?): Builder = TODO()
        open fun setClientDataHash(hash: ByteArray?): Builder = TODO()
        open fun build(): BrowserPublicKeyCredentialRequestOptions = TODO()
    }
}
"""),
])

S["thirdparty_gms_fido2"] = ("com.google.android.gms.fido.fido2", [
("Fido2ApiClient", """
import android.app.PendingIntent
import com.google.android.gms.fido.fido2.api.common.FidoCredentialDetails
import com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialCreationOptions
import com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialRequestOptions
import com.google.android.gms.tasks.Task

open class Fido2ApiClient {
    open fun getRegisterPendingIntent(
        options: PublicKeyCredentialCreationOptions?): Task<PendingIntent> = TODO()
    open fun getSignPendingIntent(
        options: PublicKeyCredentialRequestOptions?): Task<PendingIntent> = TODO()
    open fun isUserVerifyingPlatformAuthenticatorAvailable(): Task<Boolean> = TODO()
    open fun getCredentialList(rpId: String?): Task<MutableList<FidoCredentialDetails>> = TODO()
}
"""),
("Fido2PrivilegedApiClient", """
import android.app.PendingIntent
import com.google.android.gms.fido.fido2.api.common.BrowserPublicKeyCredentialCreationOptions
import com.google.android.gms.fido.fido2.api.common.BrowserPublicKeyCredentialRequestOptions
import com.google.android.gms.fido.fido2.api.common.FidoCredentialDetails
import com.google.android.gms.tasks.Task

open class Fido2PrivilegedApiClient {
    open fun getRegisterPendingIntent(
        options: BrowserPublicKeyCredentialCreationOptions?): Task<PendingIntent> = TODO()
    open fun getSignPendingIntent(
        options: BrowserPublicKeyCredentialRequestOptions?): Task<PendingIntent> = TODO()
    open fun isUserVerifyingPlatformAuthenticatorAvailable(): Task<Boolean> = TODO()
    open fun getCredentialList(rpId: String?): Task<MutableList<FidoCredentialDetails>> = TODO()
}
"""),
])

S["thirdparty_gms_fido"] = ("com.google.android.gms.fido", [
("Fido", """
import android.content.Context
import com.google.android.gms.fido.fido2.Fido2ApiClient
import com.google.android.gms.fido.fido2.Fido2PrivilegedApiClient

object Fido {
    const val FIDO2_KEY_CREDENTIAL_EXTRA = "FIDO2_CREDENTIAL_EXTRA"
    const val FIDO2_KEY_RESPONSE_EXTRA = "FIDO2_RESPONSE_EXTRA"
    const val FIDO2_KEY_ERROR_EXTRA = "FIDO2_ERROR_EXTRA"
    fun getFido2ApiClient(context: Context?): Fido2ApiClient = TODO()
    fun getFido2PrivilegedApiClient(context: Context?): Fido2PrivilegedApiClient = TODO()
}
"""),
])

# --- guava -----------------------------------------------------------------

S["thirdparty_guava_base"] = ("com.google.common.base", [
("Predicate", """
interface Predicate<T> {
    fun apply(input: T): Boolean = TODO()
}
"""),
])

S["thirdparty_guava_net"] = ("com.google.common.net", [
("HttpHeaders", """
object HttpHeaders {
    const val ACCEPT = "Accept"
    const val ACCEPT_CHARSET = "Accept-Charset"
    const val ACCEPT_ENCODING = "Accept-Encoding"
    const val ACCEPT_LANGUAGE = "Accept-Language"
    const val AUTHORIZATION = "Authorization"
    const val CACHE_CONTROL = "Cache-Control"
    const val CONNECTION = "Connection"
    const val CONTENT_DISPOSITION = "Content-Disposition"
    const val CONTENT_ENCODING = "Content-Encoding"
    const val CONTENT_LENGTH = "Content-Length"
    const val CONTENT_RANGE = "Content-Range"
    const val CONTENT_TYPE = "Content-Type"
    const val COOKIE = "Cookie"
    const val ETAG = "ETag"
    const val HOST = "Host"
    const val IF_MODIFIED_SINCE = "If-Modified-Since"
    const val LAST_MODIFIED = "Last-Modified"
    const val LOCATION = "Location"
    const val RANGE = "Range"
    const val REFERER = "Referer"
    const val SET_COOKIE = "Set-Cookie"
    const val TRANSFER_ENCODING = "Transfer-Encoding"
    const val USER_AGENT = "User-Agent"
}
"""),
])

# --- snakeyaml -------------------------------------------------------------

S["thirdparty_snakeyaml"] = ("org.yaml.snakeyaml", [
("LoaderOptions", """
open class LoaderOptions {
    open fun setAllowDuplicateKeys(allow: Boolean): Unit = TODO()
    open fun setMaxAliasesForCollections(max: Int): Unit = TODO()
}
"""),
("TypeDescription", """
open class TypeDescription(clazz: Any? = null, tag: Any? = null) {
    open fun putMapPropertyType(property: String?, key: Any?, value: Any?): Unit = TODO()
    open fun putListPropertyType(property: String?, type: Any?): Unit = TODO()
    open fun setPropertyUtils(utils: Any?): Unit = TODO()
}
"""),
("Yaml", """
open class Yaml(constructor: Any? = null) {
    open fun addTypeDescription(td: TypeDescription?): TypeDescription? = TODO()
    open fun <T> load(input: Any?): T = TODO()
    open fun <T> loadAs(input: Any?, type: Any?): T = TODO()
    open fun dump(data: Any?): String = TODO()
}
"""),
])

S["thirdparty_snakeyaml_constructor"] = ("org.yaml.snakeyaml.constructor", [
("Constructor", """
open class Constructor(theRoot: Any? = null, loadingConfig: Any? = null)
"""),
("SafeConstructor", """
open class SafeConstructor(loadingConfig: Any? = null)
"""),
])

S["thirdparty_snakeyaml_error"] = ("org.yaml.snakeyaml.error", [
("YAMLException", """
open class YAMLException : RuntimeException {
    constructor(message: String?) : super(message)
    constructor(cause: Throwable?) : super(cause)
    constructor(message: String?, cause: Throwable?) : super(message, cause)
}
"""),
])

# --- java.util.stream ------------------------------------------------------

S["thirdparty_java_util_stream"] = ("java.util.stream", [
("Stream", """
open class Stream<T> {
    open fun filter(predicate: (T) -> Boolean): Stream<T> = TODO()
    open fun <R> map(mapper: (T) -> R): Stream<R> = TODO()
    open fun anyMatch(predicate: (T) -> Boolean): Boolean = TODO()
    open fun allMatch(predicate: (T) -> Boolean): Boolean = TODO()
    open fun noneMatch(predicate: (T) -> Boolean): Boolean = TODO()
    open fun findFirst(): java.util.Optional<T> = TODO()
    open fun findAny(): java.util.Optional<T> = TODO()
    open fun count(): Long = TODO()
    open fun sorted(): Stream<T> = TODO()
    open fun distinct(): Stream<T> = TODO()
    open fun limit(n: Long): Stream<T> = TODO()
    open fun forEach(action: (T) -> Unit): Unit = TODO()
    open fun toList(): List<T> = TODO()
    open fun toTypedArray(): Array<T> = TODO()
    open fun toArray(): Array<Any?> = TODO()
}
"""),
("Collectors", """
object Collectors {
    fun <T> toList(): Any = TODO()
    fun <T> toSet(): Any = TODO()
    fun joining(sep: CharSequence? = null): Any = TODO()
}
"""),
])

# --------------------------------------------------------------------------
# 2.  the extension file: things that cannot live on the stub type itself.

EXT_FILE = "thirdparty_knthird"
EXT_BODY = """
import android.text.Spanned
import java.util.stream.Stream
import kotlin.reflect.KClass

// Java's `Foo.class` is Kotlin's `Foo::class`, a KClass, so the `Class<T>`
// members of Spanned/Editable are unreachable from the converted call sites.
// These extensions are only picked when no member applies.
fun <T : Any> Spanned.getSpans(start: Int, end: Int, type: KClass<T>?): Array<T> = TODO()
fun Spanned.nextSpanTransition(start: Int, limit: Int, type: KClass<*>?): Int = TODO()

// `list.stream()` is a Java 8 default method on Collection.
fun <T> Iterable<T>.stream(): Stream<T> = TODO()
fun <T> Collection<T>.stream(): Stream<T> = TODO()
"""

EXT_TRIGGERS = [re.compile(rx) for rx in (
    r"\.getSpans\(",
    r"\.nextSpanTransition\(",
    r"\.stream\(\)",
)]

# --------------------------------------------------------------------------
# 3.  per-file import surgery.
#
# Java nested types that Kotlin will not inherit.  The declaration exists (the
# media3 stub lane emits it, top-level in the same package); the corpus just
# names it unqualified because in Java it is nested in an implemented
# interface.  Add the import when the file uses the name and imports the owner.

NESTED_IMPORTS = {
    "RequestProperties": ("androidx.media3.datasource.HttpDataSource",
                          "androidx.media3.datasource.RequestProperties"),
    "HttpDataSourceException": ("androidx.media3.datasource.HttpDataSource",
                                "androidx.media3.datasource.HttpDataSourceException"),
    "InvalidResponseCodeException": ("androidx.media3.datasource.HttpDataSource",
                                     "androidx.media3.datasource.InvalidResponseCodeException"),
    "InvalidContentTypeException": ("androidx.media3.datasource.HttpDataSource",
                                    "androidx.media3.datasource.InvalidContentTypeException"),
}

# `Spanned.nextSpanTransition(int, int, Class)` is raw in the Android SDK, so
# GeckoEditable's override is raw too and Kotlin wants an argument.
_RAW_CLASS_PARAM = re.compile(r"(fun nextSpanTransition\([^)]*?type: )Class(\??)\)")

# Java's CharSequence.subSequence is non-null; the converter emitted `CharSequence?`
# for it, which does not override kotlin.CharSequence's member.  The one body this
# hits throws, so tightening the return type cannot change behaviour.
_SUBSEQUENCE_RET = re.compile(
    r"(override fun subSequence\(\w+: Int, \w+: Int\): CharSequence)\?")

_DECL = re.compile(
    r"^(?:@\w+\s*)*(?:public\s+|open\s+|abstract\s+|sealed\s+|final\s+|data\s+|value\s+|enum\s+|annotation\s+|fun\s+)*"
    r"(?:class|interface|object|typealias)\s+(\w+)", re.M)


def _existing_stub_names(stub_dir):
    """(package, name) some other stub lane already declares."""
    taken = set()
    if not os.path.isdir(stub_dir):
        return taken
    for f in sorted(os.listdir(stub_dir)):
        if not f.endswith(".kt") or f.startswith(MY_PREFIX):
            continue
        text = open(os.path.join(stub_dir, f)).read()
        m = re.search(r"^package\s+([\w.]+)", text, re.M)
        if not m:
            continue
        pkg = m.group(1)
        for d in _DECL.finditer(text):
            taken.add((pkg, d.group(1)))
    return taken


def emit_stubs(out_root, stats, notes):
    stub_dir = os.path.join(out_root, "stubs")
    os.makedirs(stub_dir, exist_ok=True)
    for f in os.listdir(stub_dir):
        if f.startswith(MY_PREFIX) and f.endswith(".kt"):
            os.remove(os.path.join(stub_dir, f))
    taken = _existing_stub_names(stub_dir)

    for fname, (pkg, decls) in sorted(S.items()):
        body, skipped, heads = [], [], []
        for name, code in decls:
            if (pkg, name) in taken:
                skipped.append(name)
                continue
            # imports are written next to the declaration that needs them;
            # Kotlin wants them all at the top of the file.
            keep = []
            for line in code.strip().split("\n"):
                if line.startswith("import "):
                    if line not in heads:
                        heads.append(line)
                else:
                    keep.append(line)
            body.append("\n".join(keep).strip() + "\n")
        if not body:
            notes.append("third-party: %s entirely covered by another lane" % pkg)
            continue
        if skipped:
            # A partial overlap is worse than none: the members we do not
            # declare are the ones another lane was missing.  Say so.
            notes.append("third-party: %s deferred to another lane: %s"
                         % (pkg, ", ".join(skipped)))
        with open(os.path.join(stub_dir, fname + ".kt"), "w") as fh:
            fh.write(BANNER % pkg)
            fh.write("\npackage %s\n\n" % pkg)
            if heads:
                fh.write("\n".join(heads) + "\n\n")
            fh.write("\n".join(body))
        stats["third-party:files"] += 1
        stats["third-party:decls"] += len(body)

    with open(os.path.join(stub_dir, EXT_FILE + ".kt"), "w") as fh:
        fh.write(BANNER % "call-site extensions")
        fh.write("\npackage %s\n" % EXT_PKG)
        fh.write(EXT_BODY)
    stats["third-party:files"] += 1


# --------------------------------------------------------------------------

def transform(unit, ctx):
    if not ctx.get("_thirdparty_emitted"):
        ctx["_thirdparty_emitted"] = True
        emit_stubs(ctx["out_root"], ctx["stats"], unit.notes)

    if unit.package == EXT_PKG:
        return

    text = unit.kotlin

    n = len(_RAW_CLASS_PARAM.findall(text))
    if n:
        text = _RAW_CLASS_PARAM.sub(r"\1Class<*>\2)", text)
        ctx["stats"]["third-party:raw-class-param"] += n

    if "import android.text.Editable" in text:
        n = len(_SUBSEQUENCE_RET.findall(text))
        if n:
            text = _SUBSEQUENCE_RET.sub(r"\1", text)
            ctx["stats"]["third-party:subsequence-return"] += n

    lines = text.split("\n")
    imports = set(l.strip() for l in lines if l.startswith("import "))
    body = "\n".join(l for l in lines if not l.startswith("import "))

    add = []
    for name, (owner, imp) in sorted(NESTED_IMPORTS.items()):
        if ("import " + owner) not in imports:
            continue
        if ("import " + imp) in imports:
            continue
        if re.search(r"\b%s\b" % re.escape(name), body):
            add.append("import " + imp)
    if any(rx.search(body) for rx in EXT_TRIGGERS) and EXT_IMPORT not in imports:
        add.append(EXT_IMPORT)

    if add:
        out, done = [], False
        for l in lines:
            out.append(l)
            if not done and l.startswith("package "):
                out.extend(add)
                done = True
        if done:
            lines = out
            ctx["stats"]["third-party:imports"] += len(add)

    unit.kotlin = "\n".join(lines)
    unit.imports = [l for l in lines if l.startswith("import ")]
