"""Finish the android.*/java.* stub surface: the packages and members round 1 missed.

The stub lane (`stubgen/*.py`, `rules/jdk-stubs.py`) scraped the types GeckoView
*imports*.  Two holes are left, and this rule fills both:

  1. A package nobody stubbed at all.  `org.json` is the big one - GeckoBundle,
     WebExtension, CrashReporter and the WebAuthn code all speak JSON - plus
     `android.webkit.MimeTypeMap`, `android.telephony.TelephonyManager` and
     `android.Manifest`.  Emitted here as ordinary stub files.

  2. A type that IS stubbed but is missing the member GeckoView calls:
     `Context.createWindowContext`/`getDisplay`, `Display.getPixelFormat`,
     `Locale.getAvailableLocales`/`TRADITIONAL_CHINESE`/`setDefault`,
     `Thread.getId`, `Charset.newEncoder`, `KClass.getClassLoader`,
     `ProxySelector.select`.  Those cannot go in the file that declares the
     type - that file belongs to another lane and is regenerated - so they are
     *extensions* in a package of our own, `org.mozilla.gecko.knstub`, pulled
     in by call site.  An extension never shadows a member, so this can only
     affect call sites that do not compile today.

Two Java scoping rules leak in here as well, because both land on stub types:

  * A class implementing `Parcelable` refers to the nested `Creator` and to the
    inherited constant `CONTENTS_FILE_DESCRIPTOR` unqualified.  Kotlin inherits
    neither nested types nor companions, so `knstub` carries a
    `typealias Creator<T> = Parcelable.Creator<T>` and the constants.
  * `import android.content.res.Configuration.ORIENTATION_LANDSCAPE` is a Java
     static import of what is now a companion member; the import line is
     rewritten to go through `.Companion.`.

Everything emitted is TODO(); none of it is meant to run.
"""
import os
import re

ORDER = 60                       # after jdk-stubs (50): its files must exist
NAME = "stub-surface-completion"
DESCRIPTION = "stub the packages and members the round-1 scrape missed"

EXT_PKG = "org.mozilla.gecko.knstub"
EXT_IMPORT = "import %s.*" % EXT_PKG
MY_PREFIX = "stubsurf_"

BANNER = (
    "// GENERATED by kn-run/rules/stub-surface-completion.py -- do not edit by hand.\n"
    "// %s stubs for the Kotlin/Native GeckoView port, derived from the\n"
    "// call sites in mobile/android/geckoview.  Every body is TODO():\n"
    "// there is no JVM and no Android runtime here.\n"
    '@file:Suppress("UNUSED_PARAMETER", "unused", "UNCHECKED_CAST",\n'
    '               "EXTENSION_SHADOWED_BY_MEMBER", "NOTHING_TO_INLINE")\n'
)

# --------------------------------------------------------------------------
# 1. packages nobody stubbed.  file -> (package, [(declared name, kotlin)])

S = {}

S["stubsurf_org_json"] = ("org.json", [
("JSONException", """
open class JSONException : Exception {
    constructor() : super()
    constructor(message: String?) : super(message)
    constructor(message: String?, cause: Throwable?) : super(message, cause)
    constructor(cause: Throwable?) : super(cause)
}
"""),
("JSONTokener", """
open class JSONTokener(input: String?) {
    open fun nextValue(): Any = TODO()
    open fun more(): Boolean = TODO()
    open fun next(): Char = TODO()
    open fun skipTo(c: Char): Char = TODO()
}
"""),
("JSONObject", """
open class JSONObject {
    constructor()
    constructor(json: String?)
    constructor(copyFrom: JSONObject?, names: Array<String?>?)
    constructor(readFrom: JSONTokener?)
    constructor(copyFrom: MutableMap<*, *>?)

    open fun length(): Int = TODO()
    open fun has(name: String?): Boolean = TODO()
    open fun isNull(name: String?): Boolean = TODO()
    open fun keys(): MutableIterator<String> = TODO()
    open fun names(): JSONArray? = TODO()
    open fun remove(name: String?): Any? = TODO()
    open fun toJSONArray(names: JSONArray?): JSONArray? = TODO()

    open fun put(name: String?, value: Boolean): JSONObject = TODO()
    open fun put(name: String?, value: Int): JSONObject = TODO()
    open fun put(name: String?, value: Long): JSONObject = TODO()
    open fun put(name: String?, value: Double): JSONObject = TODO()
    open fun put(name: String?, value: Any?): JSONObject = TODO()
    open fun putOpt(name: String?, value: Any?): JSONObject = TODO()
    open fun accumulate(name: String?, value: Any?): JSONObject = TODO()

    open fun get(name: String?): Any = TODO()
    open fun opt(name: String?): Any? = TODO()
    open fun getBoolean(name: String?): Boolean = TODO()
    open fun optBoolean(name: String?): Boolean = TODO()
    open fun optBoolean(name: String?, fallback: Boolean): Boolean = TODO()
    open fun getDouble(name: String?): Double = TODO()
    open fun optDouble(name: String?): Double = TODO()
    open fun optDouble(name: String?, fallback: Double): Double = TODO()
    open fun getInt(name: String?): Int = TODO()
    open fun optInt(name: String?): Int = TODO()
    open fun optInt(name: String?, fallback: Int): Int = TODO()
    open fun getLong(name: String?): Long = TODO()
    open fun optLong(name: String?): Long = TODO()
    open fun optLong(name: String?, fallback: Long): Long = TODO()
    open fun getString(name: String?): String = TODO()
    open fun optString(name: String?): String = TODO()
    open fun optString(name: String?, fallback: String?): String = TODO()
    open fun getJSONArray(name: String?): JSONArray = TODO()
    open fun optJSONArray(name: String?): JSONArray? = TODO()
    open fun getJSONObject(name: String?): JSONObject = TODO()
    open fun optJSONObject(name: String?): JSONObject? = TODO()

    override fun toString(): String = TODO()
    open fun toString(indentSpaces: Int): String = TODO()

    companion object {
        val NULL: Any = TODO()
        fun quote(data: String?): String = TODO()
        fun wrap(o: Any?): Any? = TODO()
        fun numberToString(number: Number?): String = TODO()
    }
}
"""),
("JSONArray", """
open class JSONArray {
    constructor()
    constructor(json: String?)
    constructor(copyFrom: MutableCollection<*>?)
    constructor(readFrom: JSONTokener?)
    constructor(array: Any?)

    open fun length(): Int = TODO()
    open fun isNull(index: Int): Boolean = TODO()
    open fun remove(index: Int): Any? = TODO()

    open fun put(value: Boolean): JSONArray = TODO()
    open fun put(value: Int): JSONArray = TODO()
    open fun put(value: Long): JSONArray = TODO()
    open fun put(value: Double): JSONArray = TODO()
    open fun put(value: Any?): JSONArray = TODO()
    open fun put(index: Int, value: Boolean): JSONArray = TODO()
    open fun put(index: Int, value: Int): JSONArray = TODO()
    open fun put(index: Int, value: Long): JSONArray = TODO()
    open fun put(index: Int, value: Double): JSONArray = TODO()
    open fun put(index: Int, value: Any?): JSONArray = TODO()

    open fun get(index: Int): Any = TODO()
    open fun opt(index: Int): Any? = TODO()
    open fun getBoolean(index: Int): Boolean = TODO()
    open fun optBoolean(index: Int): Boolean = TODO()
    open fun optBoolean(index: Int, fallback: Boolean): Boolean = TODO()
    open fun getDouble(index: Int): Double = TODO()
    open fun optDouble(index: Int): Double = TODO()
    open fun optDouble(index: Int, fallback: Double): Double = TODO()
    open fun getInt(index: Int): Int = TODO()
    open fun optInt(index: Int): Int = TODO()
    open fun optInt(index: Int, fallback: Int): Int = TODO()
    open fun getLong(index: Int): Long = TODO()
    open fun optLong(index: Int): Long = TODO()
    open fun optLong(index: Int, fallback: Long): Long = TODO()
    open fun getString(index: Int): String = TODO()
    open fun optString(index: Int): String = TODO()
    open fun optString(index: Int, fallback: String?): String = TODO()
    open fun getJSONArray(index: Int): JSONArray = TODO()
    open fun optJSONArray(index: Int): JSONArray? = TODO()
    open fun getJSONObject(index: Int): JSONObject = TODO()
    open fun optJSONObject(index: Int): JSONObject? = TODO()

    open fun toJSONObject(names: JSONArray?): JSONObject? = TODO()
    open fun join(separator: String?): String = TODO()
    override fun toString(): String = TODO()
    open fun toString(indentSpaces: Int): String = TODO()
}
"""),
("JSONStringer", """
open class JSONStringer {
    open fun array(): JSONStringer = TODO()
    open fun endArray(): JSONStringer = TODO()
    open fun `object`(): JSONStringer = TODO()
    open fun endObject(): JSONStringer = TODO()
    open fun key(name: String?): JSONStringer = TODO()
    open fun value(value: Any?): JSONStringer = TODO()
    override fun toString(): String = TODO()
}
"""),
])

S["stubsurf_android_webkit"] = ("android.webkit", [
("MimeTypeMap", """
open class MimeTypeMap {
    open fun hasMimeType(mimeType: String?): Boolean = TODO()
    open fun getMimeTypeFromExtension(extension: String?): String? = TODO()
    open fun hasExtension(extension: String?): Boolean = TODO()
    open fun getExtensionFromMimeType(mimeType: String?): String? = TODO()
    companion object {
        fun getSingleton(): MimeTypeMap = TODO()
        fun getFileExtensionFromUrl(url: String?): String = TODO()
    }
}
"""),
])

# NETWORK_TYPE_* are the constants NetworkUtils switches on; the rest of the
# surface is what a scrape of android.telephony call sites in geckoview finds.
S["stubsurf_android_telephony"] = ("android.telephony", [
("TelephonyManager", """
open class TelephonyManager {
    open fun getNetworkType(): Int = TODO()
    open fun getDataNetworkType(): Int = TODO()
    open fun getPhoneType(): Int = TODO()
    open fun getNetworkOperator(): String? = TODO()
    open fun getNetworkOperatorName(): String? = TODO()
    open fun getNetworkCountryIso(): String? = TODO()
    open fun getSimOperator(): String? = TODO()
    open fun getSimCountryIso(): String? = TODO()
    open fun getSimState(): Int = TODO()
    companion object {
        const val NETWORK_TYPE_UNKNOWN = 0
        const val NETWORK_TYPE_GPRS = 1
        const val NETWORK_TYPE_EDGE = 2
        const val NETWORK_TYPE_UMTS = 3
        const val NETWORK_TYPE_CDMA = 4
        const val NETWORK_TYPE_EVDO_0 = 5
        const val NETWORK_TYPE_EVDO_A = 6
        const val NETWORK_TYPE_1xRTT = 7
        const val NETWORK_TYPE_HSDPA = 8
        const val NETWORK_TYPE_HSUPA = 9
        const val NETWORK_TYPE_HSPA = 10
        const val NETWORK_TYPE_IDEN = 11
        const val NETWORK_TYPE_EVDO_B = 12
        const val NETWORK_TYPE_LTE = 13
        const val NETWORK_TYPE_EHRPD = 14
        const val NETWORK_TYPE_HSPAP = 15
        const val NETWORK_TYPE_GSM = 16
        const val NETWORK_TYPE_TD_SCDMA = 17
        const val NETWORK_TYPE_IWLAN = 18
        const val NETWORK_TYPE_NR = 20
        const val PHONE_TYPE_NONE = 0
        const val PHONE_TYPE_GSM = 1
        const val PHONE_TYPE_CDMA = 2
        const val PHONE_TYPE_SIP = 3
        const val SIM_STATE_UNKNOWN = 0
        const val SIM_STATE_READY = 5
    }
}
"""),
])

# android.Manifest.permission.* - a bare `object`, since Kotlin has no statics.
S["stubsurf_android_manifest"] = ("android", [
("Manifest", """
object Manifest {
    object permission {
        const val ACCESS_COARSE_LOCATION = "android.permission.ACCESS_COARSE_LOCATION"
        const val ACCESS_FINE_LOCATION = "android.permission.ACCESS_FINE_LOCATION"
        const val ACCESS_LOCAL_NETWORK = "android.permission.ACCESS_LOCAL_NETWORK"
        const val ACCESS_NETWORK_STATE = "android.permission.ACCESS_NETWORK_STATE"
        const val ACCESS_WIFI_STATE = "android.permission.ACCESS_WIFI_STATE"
        const val CAMERA = "android.permission.CAMERA"
        const val INTERNET = "android.permission.INTERNET"
        const val READ_EXTERNAL_STORAGE = "android.permission.READ_EXTERNAL_STORAGE"
        const val RECORD_AUDIO = "android.permission.RECORD_AUDIO"
        const val VIBRATE = "android.permission.VIBRATE"
        const val WAKE_LOCK = "android.permission.WAKE_LOCK"
        const val WRITE_EXTERNAL_STORAGE = "android.permission.WRITE_EXTERNAL_STORAGE"
    }
    object permission_group
}
"""),
])

# java.lang types the round-1 scrape did not see, because they only ever appear
# in a `catch` or a `throw` and never in an import.
S["stubsurf_java_lang"] = ("java.lang", [
("IllegalThreadStateException", """
open class IllegalThreadStateException(message: String? = null) : IllegalArgumentException(message)
"""),
("LinkageError", """
open class LinkageError(message: String? = null) : Error(message)
"""),
("NoSuchFieldError", """
open class NoSuchFieldError(message: String? = null) : LinkageError(message)
"""),
("NoSuchMethodError", """
open class NoSuchMethodError(message: String? = null) : LinkageError(message)
"""),
("UnknownError", """
open class UnknownError(message: String? = null) : Error(message)
"""),
("ProcessBuilder", """
open class ProcessBuilder() {
    open fun command(vararg cmd: String?): ProcessBuilder = TODO()
    open fun command(cmd: MutableList<String?>?): ProcessBuilder = TODO()
    open fun command(): MutableList<String> = TODO()
    open fun environment(): MutableMap<String, String> = TODO()
    open fun directory(dir: java.io.File?): ProcessBuilder = TODO()
    open fun redirectErrorStream(v: Boolean): ProcessBuilder = TODO()
    open fun start(): Process = TODO()
}
"""),
# `catch (e: java.lang.Exception)` - the converter keeps the Java spelling
# qualified, so the name has to exist in this package too.
("Exception", "typealias Exception = kotlin.Exception\n"),
("RuntimeException", "typealias RuntimeException = kotlin.RuntimeException\n"),
("IllegalStateException", "typealias IllegalStateException = kotlin.IllegalStateException\n"),
("IllegalArgumentException", "typealias IllegalArgumentException = kotlin.IllegalArgumentException\n"),
("NullPointerException", "typealias NullPointerException = kotlin.NullPointerException\n"),
("UnsupportedOperationException", "typealias UnsupportedOperationException = kotlin.UnsupportedOperationException\n"),
("IndexOutOfBoundsException", "typealias IndexOutOfBoundsException = kotlin.IndexOutOfBoundsException\n"),
("NumberFormatException", "typealias NumberFormatException = kotlin.NumberFormatException\n"),
("Throwable", "typealias Throwable = kotlin.Throwable\n"),
("Error", "typealias Error = kotlin.Error\n"),
("Object", "typealias Object = Any\n"),
("String", "typealias String = kotlin.String\n"),
])

# java.nio.charset.Charset.newEncoder()'s return type never got stubbed.
S["stubsurf_java_nio_charset"] = ("java.nio.charset", [
("CoderResult", """
open class CoderResult {
    open fun isError(): Boolean = TODO()
    open fun isOverflow(): Boolean = TODO()
    open fun isUnderflow(): Boolean = TODO()
    open fun isMalformed(): Boolean = TODO()
    open fun isUnmappable(): Boolean = TODO()
    open fun length(): Int = TODO()
    open fun throwException(): Unit = TODO()
    companion object {
        val OVERFLOW: CoderResult = TODO()
        val UNDERFLOW: CoderResult = TODO()
    }
}
"""),
("CodingErrorAction", """
open class CodingErrorAction {
    companion object {
        val IGNORE: CodingErrorAction = TODO()
        val REPLACE: CodingErrorAction = TODO()
        val REPORT: CodingErrorAction = TODO()
    }
}
"""),
("CharsetEncoder", """
open class CharsetEncoder {
    open fun charset(): Charset = TODO()
    open fun averageBytesPerChar(): Float = TODO()
    open fun maxBytesPerChar(): Float = TODO()
    open fun canEncode(c: Char): Boolean = TODO()
    open fun canEncode(cs: CharSequence?): Boolean = TODO()
    open fun encode(input: java.nio.CharBuffer?): java.nio.ByteBuffer = TODO()
    open fun encode(input: java.nio.CharBuffer?, out: java.nio.ByteBuffer?, endOfInput: Boolean): CoderResult = TODO()
    open fun flush(out: java.nio.ByteBuffer?): CoderResult = TODO()
    open fun reset(): CharsetEncoder = TODO()
    open fun onMalformedInput(action: CodingErrorAction?): CharsetEncoder = TODO()
    open fun onUnmappableCharacter(action: CodingErrorAction?): CharsetEncoder = TODO()
    open fun replaceWith(replacement: ByteArray?): CharsetEncoder = TODO()
}
"""),
("CharsetDecoder", """
open class CharsetDecoder {
    open fun charset(): Charset = TODO()
    open fun decode(input: java.nio.ByteBuffer?): java.nio.CharBuffer = TODO()
    open fun decode(input: java.nio.ByteBuffer?, out: java.nio.CharBuffer?, endOfInput: Boolean): CoderResult = TODO()
    open fun reset(): CharsetDecoder = TODO()
    open fun onMalformedInput(action: CodingErrorAction?): CharsetDecoder = TODO()
    open fun onUnmappableCharacter(action: CodingErrorAction?): CharsetDecoder = TODO()
}
"""),
])

# --------------------------------------------------------------------------
# 2. members missing from a type that is already stubbed.  Extensions, in a
# package of our own, imported by call site.  An extension never shadows a
# member, so nothing here can break a call site that already compiles.

EXT_FILE = "stubsurf_knstub"

EXT_BODY = """
import android.content.Context
import android.os.Bundle
import android.os.Parcelable
import android.view.Display
import java.nio.charset.Charset
import java.nio.charset.CharsetDecoder
import java.nio.charset.CharsetEncoder
import java.util.Locale

// --- android.os.Parcelable: Java inherits the nested Creator and the
// interface constants into an implementor's scope.  Kotlin inherits neither.
typealias Creator<T> = Parcelable.Creator<T>
typealias ClassLoaderCreator<T> = Parcelable.ClassLoaderCreator<T>
const val CONTENTS_FILE_DESCRIPTOR: Int = 1
const val PARCELABLE_WRITE_RETURN_VALUE: Int = 1

// --- java.lang types that only ever appear unqualified, in a catch or a throw.
typealias IllegalThreadStateException = java.lang.IllegalThreadStateException
typealias LinkageError = java.lang.LinkageError
typealias NoSuchFieldError = java.lang.NoSuchFieldError
typealias NoSuchMethodError = java.lang.NoSuchMethodError
typealias UnknownError = java.lang.UnknownError
typealias ProcessBuilder = java.lang.ProcessBuilder

// --- android.content.Context
fun Context.createWindowContext(type: Int, options: Bundle?): Context = TODO()
fun Context.createWindowContext(display: Display?, type: Int, options: Bundle?): Context = TODO()
fun Context.getDisplay(): Display = TODO()

// --- android.view.Display
fun Display.getPixelFormat(): Int = TODO()

// --- java.util.Locale
fun Locale.Companion.getAvailableLocales(): Array<Locale> = TODO()
fun Locale.Companion.setDefault(locale: Locale?): Unit = TODO()
val Locale.Companion.TRADITIONAL_CHINESE: Locale get() = TODO()
val Locale.Companion.SIMPLIFIED_CHINESE: Locale get() = TODO()
val Locale.Companion.CHINESE: Locale get() = TODO()
val Locale.Companion.ENGLISH: Locale get() = TODO()
val Locale.Companion.UK: Locale get() = TODO()
val Locale.Companion.CANADA: Locale get() = TODO()

// --- java.lang.Thread
fun java.lang.Thread.getId(): Long = TODO()

// --- java.nio.charset.Charset
fun Charset.newEncoder(): CharsetEncoder = TODO()
fun Charset.newDecoder(): CharsetDecoder = TODO()

// --- java.lang.Class.  Java's `Foo.class` is emitted as `Foo::class.java`,
// which needs the `.java` bridge the JVM stdlib would give us; `Foo[].class`
// cannot be a class literal at all (Kotlin forbids the type argument), so it
// goes through knArrayClass instead.
val <T : Any> kotlin.reflect.KClass<T>.java: java.lang.Class<T> get() = TODO()
fun <T : Any> knArrayClass(): java.lang.Class<T> = TODO()

// --- java.lang.String: the JDK constructors and the regex methods Kotlin
// spells differently.  A top-level function named String is a constructor as
// far as the call sites are concerned.
fun String(bytes: ByteArray?): String = TODO()
fun String(bytes: ByteArray?, charsetName: String?): String = TODO()
fun String(bytes: ByteArray?, charset: java.nio.charset.Charset?): String = TODO()
fun String(bytes: ByteArray?, offset: Int, length: Int): String = TODO()
fun String.replaceAll(regex: String?, replacement: String?): String = TODO()
fun String.matches(regex: String?): Boolean = TODO()
fun String.split(regex: String?, limit: Int): Array<String> = TODO()

// --- java.net.ProxySelector
fun java.net.ProxySelector.select(uri: java.net.URI?): MutableList<java.net.Proxy> = TODO()
fun java.net.ProxySelector.connectFailed(uri: java.net.URI?, sa: java.net.SocketAddress?, e: java.io.IOException?): Unit = TODO()
"""

# A file gets `import org.mozilla.gecko.knstub.*` only when one of these fires,
# so the star import lands on ~a dozen files rather than all 168.
EXT_TRIGGERS = [re.compile(p) for p in (
    r"(?<![\w.])Creator\s*<",
    r"(?<![\w.])ClassLoaderCreator\s*<",
    r"(?<![\w.])CONTENTS_FILE_DESCRIPTOR\b",
    r"(?<![\w.])PARCELABLE_WRITE_RETURN_VALUE\b",
    r"(?<![\w.])IllegalThreadStateException\b",
    r"(?<![\w.])LinkageError\b",
    r"(?<![\w.])NoSuchFieldError\b",
    r"(?<![\w.])NoSuchMethodError\b",
    r"(?<![\w.])UnknownError\b",
    r"(?<![\w.])ProcessBuilder\b",
    r"\.createWindowContext\(",
    r"\.getDisplay\(\)",
    r"\.getPixelFormat\(",
    r"\bLocale\.(?:getAvailableLocales|setDefault|TRADITIONAL_CHINESE|SIMPLIFIED_CHINESE|CHINESE|ENGLISH|UK|CANADA)\b",
    r"\.getId\(\)",
    r"\.newEncoder\(|\.newDecoder\(",
    r"::class\.java\b",
    r"(?<![\w.])String\s*\(",
    r"\.replaceAll\(|\.matches\(",
    r"(?<![\w.])knArrayClass\s*<",
    r"\.select\(|\.connectFailed\(",
)]

# --------------------------------------------------------------------------
# 3. `import a.b.C.CONSTANT` - a Java static import of what is a companion
# member in Kotlin.  Only rewritten for the stub packages; the corpus's own
# static imports belong to whoever owns that bucket.
_STUB_ROOTS = ("android.", "java.", "javax.", "dalvik.", "org.json.")
_STATIC_IMPORT = re.compile(
    r"^import ((?:[a-z][\w]*\.)+(?:[A-Z]\w*\.)*[A-Z]\w*)\.([A-Z][A-Z0-9_]*)$", re.M)

# The converter drops the type argument off `new Creator<T>() {...}` when the
# supertype is an interface.  Bare `Creator` was merely unresolved before this
# rule; against the typealias it is a "one type argument expected".  Put the
# argument back from the declared type on the same line.
_RAW_CREATOR = re.compile(
    r"(:\s*(?:Parcelable\.)?Creator<([\w.]+)>\??\s*=\s*object\s*:\s*(?:Parcelable\.)?Creator)(\s*\{)")


_DECL = re.compile(
    r"^(?:@\w+\s*)*(?:public\s+|open\s+|abstract\s+|sealed\s+|final\s+|data\s+|value\s+|enum\s+|annotation\s+|fun\s+)*"
    r"(?:class|interface|object|typealias)\s+(\w+)", re.M)


def _existing_stub_names(stub_dir):
    """(package, name) already declared by some other stub lane's file."""
    taken = set()
    if not os.path.isdir(stub_dir):
        return taken
    for f in sorted(os.listdir(stub_dir)):
        if not f.endswith(".kt") or f.startswith(MY_PREFIX):
            continue
        text = open(os.path.join(stub_dir, f)).read()
        m = re.search(r"^package\s+([\w.]+)", text, re.M)
        if not m:
            continue
        pkg = m.group(1)
        for d in _DECL.finditer(text):
            taken.add((pkg, d.group(1)))
    return taken


def emit_stubs(out_root, stats, notes):
    stub_dir = os.path.join(out_root, "stubs")
    os.makedirs(stub_dir, exist_ok=True)
    # drop our own output first, so the scan below never defers to a stale
    # copy of ourselves.
    for f in os.listdir(stub_dir):
        if f.startswith(MY_PREFIX) and f.endswith(".kt"):
            os.remove(os.path.join(stub_dir, f))
    taken = _existing_stub_names(stub_dir)

    for fname, (pkg, decls) in sorted(S.items()):
        body, skipped = [], []
        for name, code in decls:
            if (pkg, name) in taken:
                skipped.append(name)
                continue
            body.append(code.strip() + "\n")
        if not body:
            notes.append("stub-surface: %s entirely covered by another lane" % pkg)
            continue
        with open(os.path.join(stub_dir, fname + ".kt"), "w") as fh:
            fh.write(BANNER % pkg)
            if skipped:
                fh.write("// deferred to another stub lane: %s\n" % ", ".join(skipped))
            fh.write("\npackage %s\n\n" % pkg)
            fh.write("\n".join(body))
        stats["stub-surface:files"] += 1
        stats["stub-surface:decls"] += len(body)

    with open(os.path.join(stub_dir, EXT_FILE + ".kt"), "w") as fh:
        fh.write(BANNER % "missing-member")
        fh.write("\npackage %s\n" % EXT_PKG)
        fh.write(EXT_BODY)
    stats["stub-surface:files"] += 1


# --------------------------------------------------------------------------

def transform(unit, ctx):
    if not ctx.get("_stub_surface_emitted"):
        ctx["_stub_surface_emitted"] = True
        emit_stubs(ctx["out_root"], ctx["stats"], unit.notes)

    if unit.package == EXT_PKG:
        return

    text = unit.kotlin

    # static import of a companion constant on a stub type
    def _companion(m):
        owner, const = m.group(1), m.group(2)
        if not owner.startswith(_STUB_ROOTS):
            return m.group(0)
        ctx["stats"]["stub-surface:companion-import"] += 1
        return "import %s.Companion.%s" % (owner, const)

    text = _STATIC_IMPORT.sub(_companion, text)

    n = len(_RAW_CREATOR.findall(text))
    if n:
        text = _RAW_CREATOR.sub(r"\1<\2>\3", text)
        ctx["stats"]["stub-surface:raw-creator"] += n

    lines = text.split("\n")
    body = "\n".join(l for l in lines if not l.startswith("import "))
    if EXT_IMPORT not in text and any(rx.search(body) for rx in EXT_TRIGGERS):
        out, done = [], False
        for l in lines:
            out.append(l)
            if not done and l.startswith("package "):
                out.append(EXT_IMPORT)
                done = True
        if done:
            lines = out
            ctx["stats"]["stub-surface:ext-import"] += 1

    unit.kotlin = "\n".join(lines)
    unit.imports = [l for l in lines if l.startswith("import ")]
